### ISSUE TITLE
App Designer - Numeric Concept Low absolute value not shown properly after save

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-webapp#1000]
**Describe the bug**
In the web app the if numeric value we enter 0(zero) it show after saving N.A
Because of this suppose I set the low absolute value 0 , then I am able to enter the  negative value also.

**To Reproduce**
1. Create one Numeric concept  
2. Set low absolute value 0
3. save
4. After saving this it convert in to NA
**Expected behavior**

**Screenshots**

https://github.com/avniproject/avni-webapp/assets/104890488/b5570d51-03fc-481d-b90d-377ce803ef07

This will affect the 
https://github.com/avniproject/avni-client/issues/1049

**Comment by 1t5j0y** [comment]
This was a display only issue. The actual low absolute (and other attribute) values were getting saved correctly.

**Comment by AchalaBelokar** [comment]
- [ ] need to change value here also
- 

![Image](https://github.com/avniproject/avni-webapp/assets/104890488/59f1bd5d-0302-43c2-ad7c-cb83e2a0c7e4)

**Comment by vinayvenu** [comment]
@AchalaBelokar @1t5j0y lets discuss in person today. This needs to be fixed in a patch only if it is causing trouble in data. My understanding is that negative values are being allowed even with a 0 absolute value.

**Comment by 1t5j0y** [comment]
Fixed display issue on inline concept display as well.
Moved code to master since this was moved to release 4.0.0.
