### ISSUE TITLE
Not able to edit concept on staging

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-webapp#1001]
**Describe the bug**
Not able to edit concept on staging

**To Reproduce**

1. Go to 'any organisation '
2. Click on 'App designer '
3. Click on 'Concept'
4. Click on 'Any Concepts'
5. Click on 'edit Concept '
6. save the concept
7. See error

**Expected behavior**
User is able to save the concept

**Test Data**
Any admin user
Or org admin user 
**Screenshots**

**Desktop (please complete the following information):**

https://github.com/avniproject/avni-webapp/assets/104890488/08e59f89-6cf2-4e03-a0c8-8b69417bc892

**Comment by vinayvenu** [comment]
These are core concepts that cannot be edited or deleted through the app designer.
