### ISSUE TITLE
Subject Type name not shown in UserGroup Privilege assignment screen

### ISSUE THREAD

**Issue by himeshr** [avniproject/avni-webapp#1004]
**Describe the bug**
Subject Type name not shown in UserGroup Privilege assignment screen

**To Reproduce**

1. Go to 'Admin' app in Avni-webapp
2. Click on 'UserGroups' in left-side tab
3. Click on any user group
4. Click on "Privileges" tab
5. See that SubjectTypes info is missing

**Expected behavior**
Subject Type info should be shown in UserGroup Privilege assignment screen

**Screenshots**
![Image](https://github.com/avniproject/avni-webapp/assets/72493481/069ea566-7b11-4b0c-99a6-a1df8d6e54e0)

**Comment by himeshr** [comment]
Screenshot after the change:


![Image](https://github.com/avniproject/avni-webapp/assets/72493481/ecbb408e-fdb6-4a04-a812-6c51ef7fa783)

**Comment by petmongrels** [comment]
the data managed by saga is meant to be used in multiple places. hence instead of modifying the store data we should pull the data and modify it according to the needs of the view where it is actually used.

**Comment by himeshr** [comment]
@petmongrels, made the code changes as suggested..
