### ISSUE TITLE
User should able to see the data in data entry app from super admin

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-webapp#1005]
**Describe the bug**
User should able to see the data in data entry app from super admin

**To Reproduce**
1.Login as super admin
2.Click on  data entry app
3.See error

**Expected behavior**
See the data in data entry app

**Screenshots**
https://github.com/avniproject/avni-webapp/assets/104890488/fba62847-3df5-47d5-8d8b-a2f9eeefe0d5

**Comment by vinayvenu** [comment]
Superadmin will not be able to see transactional data anymore. Closing this card.
