### ISSUE TITLE
Download sample file is broken in web app

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-webapp#1007]
**Describe the bug**
Download sample file is broken in web app
when User is not able to download file
when I am clicking on download sample file app is not working.

**To Reproduce**

1. Go to admin tab
2. Click on upload 
3. Click on download sample file
5. See error

**Expected behavior**
we can see the downloaded file

**Screenshots**

https://github.com/avniproject/avni-webapp/assets/104890488/68b0ec62-8c57-45a3-9302-dc6cf6ff959b

**Comment by vinayvenu** [comment]
This might have already been fixed. @petmongrels ?

**Comment by petmongrels** [comment]
Yes
