### ISSUE TITLE
Voided user group entries show up on the assignment screen in the User's name

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-webapp#1008]
**Describe the bug**
Under assignment screen, we show up user group name of the user during assignment, so right now it shows the voided user group entries as well. Voided user groups as in, the  user was earlier part of some user group and now has been removed from the group, and that group still shows along with his name. 

**To Reproduce**

1. Go to LAHI (Lend A Hand India) organisation.
2. GO to assignment screen, select Assigned to as Alim in the filter
3. See that user group names are coming along with his name which he is not part of now.
4. See error in the attached screenshot.

**Expected behavior**
Ideally the user groups from which the user has been removed should not have come on the assignment screen

**Test Data**
Query to see his user group assignment details-- 

set role lahi;
select * from user_group where user_id in (select id from users where username = 'alims@lahi');

**Screenshots**

![Image](https://github.com/avniproject/avni-webapp/assets/37863085/c4110c70-de66-45a9-8a15-ca071b190273)

**Developer Checklist**(Developer fixing the bug should fill this checklist)
- Does the fix require extensive regression testing?
  - [ ] Yes
  - [x] No
- Are you mentioning the required scenarios that could be affected?
  - [x] Yes
  - [ ] No

**Comment by himeshr** [comment]
Code changes will only affect list of userGroups for Users. Its mostly a safe code change, as we are only filtering out voided userGroups from the users response.

![Image](https://github.com/avniproject/avni-webapp/assets/72493481/e11b3161-c224-4ec5-8f63-a786c8e597c9)

**Comment by ashusvnath** [comment]
Verified using himeshr@power on staging.

Voided groups are no longer shown for assigned users in Subject assignment screen.
