### ISSUE TITLE
After 1st time login as admin, user admin should see the organisations list currently it is not happening 

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-webapp#1010]
**Describe the bug**
After 1st time login as admin user admin should see the organisations list currently it is not happening .

it is showing me error cannot read properties of undefined (reading 'origin')

**To Reproduce**

1. Login with admin user 
2. Click on  Admins
4. Click on Organisations 
5. See error

**Expected behavior**
user should able to see the org list

**Screenshots**

https://github.com/avniproject/avni-webapp/assets/104890488/4a26cf40-0fff-470c-9b40-aec8c5d351b9

**Comment by vinayvenu** [comment]
Low priority. 

Screen works when you refresh
This is an internal screen
