### ISSUE TITLE
ETL table is showing empty value even though there is data available 

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-webapp#1019]
**Describe the bug**
"Tried setting up ETL on Lend A Hand India. The table studen_lahi_a_lahi_alumni_profile_employment_details_g is empty even though there is data in the public schema 

select observations->>'a284be97-2fb7-44e7-9891-b90f166aa532' from public.program_encounter
where observations->>'a284be97-2fb7-44e7-9891-b90f166aa532' is not null;"

**Comment by petmongrels** [comment]
media viewer not supported repeatable question groups.

**Comment by vinayvenu** [comment]
avniproject/avni-etl#63

**Comment by himeshr** [comment]
In prerelease env, ETL process completed for LAHI after clearing up old ETL schema data.
Table 'lahi.studen_lahi_a_lahi_alumni_profile_employment_details_g' now contains the required data, corresponding to data present in observations->>'a284be97-2fb7-44e7-9891-b90f166aa532' from public.program_encounter where et.id = 1833.
