### ISSUE TITLE
After creating the user in calcutta kids. User is created with suffix @null 

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-webapp#1020]
**Describe the bug**
when I am try to create user for calcutta kids after it is not showing the @Calcutta_kids on prerelease 
Generally while creating the user suffix came automatically but same is not happening with this org 
after creating the user it is showing null suffix

**To Reproduce*
1. Login with admin
2. create a user
3.user is created with @null vaule

**Expected behavior**
User should create with normal suffix value not null

**Screenshots**

https://github.com/avniproject/avni-webapp/assets/104890488/738558e6-1c13-462e-8b5b-1f14907e57ad

**Comment by AchalaBelokar** [comment]
I uploaded latest server and web app still it is not workin

**Comment by Dinesh2019** [comment]
Still, the bug is reproducible attached the video for the reference 
org : Calcutta kids
env : pre-release 


https://github.com/avniproject/avni-webapp/assets/127730126/3483b197-1e29-40b4-8747-3405a0be62ee

**Comment by petmongrels** [comment]
wrong build was deployed on prerelease. pls test again.
