### ISSUE TITLE
Form edit page - Mention that form is readonly

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#1021]
It will be useful to have a message on the Form Designer page so that users know that the page is view only. 

Message: "This is a read-only form. Changes will not be saved"

**Comment by 1t5j0y** [comment]
Isn't "This is a read-only form" misleading? The logged in user does not have access to make changes to the form so it should be something like "You do not have access to edit this form. Changes will not be saved."

**Comment by vinayvenu** [comment]
@1t5j0y yes, your message is clearer.
