### ISSUE TITLE
Voided flag of dashboard section card_mapping ignored when bundle import

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-webapp#1027]
### Need:
Same issue multiple times. Need to save on debugging and manual fixing time.

### Steps to reproduce:
- Consider 2 orgs with similar metadata setup
- Delete(void at db level) a report card from a dashboard section from one of the org
- Export the bundle
- Import the bundle in the second org. The deleted report card continues to show under the dashboard section in the second org.

### Analysis:
We are not exporting the voided entries of dashboard_section_card_mapping table.

### Acceptance criteria:
The voided entries should reflect in the exported bundle.

### Related issues - duplicate report cards:
1. Use an implementation which has offline dashboard which has multiple cards in it
2. Voiding a Dashboard Section to ReportCard mapping in UAT org and recreate the new mapping for the same card in the same Dashboard section.Since we ignore the voided flag while creating bundle entries for Dashboards, Sections and report-cards, we get this error.
3. Now upload such a bundle to its respective UAT or Prod org and see
4. The uploaded bundle has added same cards multiple times to the same dashboard

**Developer Checklist**(Developer fixing the bug should fill this checklist)
- Does the fix require extensive regression testing?
  - [ ] Yes
  - [x] No
- Are you mentioning the required scenarios that could be affected?
  - [x] Yes
  - [ ] No

**Comment by vinayvenu** [comment]
@nupoorkhandelwal 

Can't seem to reproduce this issue. I just created a new organisation, and uploaded a bundle file multiple times. It doesn't seem to create multiple cards. 

Can you try doing this on a non-prod environment and confirm if this is an issue?

**Comment by himeshr** [comment]
> @nupoorkhandelwal
> 
> Can't seem to reproduce this issue. I just created a new organisation, and uploaded a bundle file multiple times. It doesn't seem to create multiple cards.
> 
> Can you try doing this on a non-prod environment and confirm if this is an issue?

This issue can be easily reproduced by voiding a Dashboard Section to ReportCard mapping in UAT org and recreating a new mapping for the same card in the same Dashboard section.

Since we ignore the voided flag while creating bundle entries for Dashboards, Sections and report-cards, we get this error.

@adamsanadi6 this is the issue you are facing currently.

@mahalakshme implementation team faces this issue repeatedly, and this is a fix we should be able to do quickly.

**Comment by AchalaBelokar** [comment]
- [ ] created a one org which is having the  copy of Achala Test which is having a offline dashboard created new dashboard .
- [ ]

**Comment by mahalakshme** [comment]
@AchalaBelokar did you check by deleting a report card?

**Comment by mahalakshme** [comment]
achala mentioned the above is tested
