### ISSUE TITLE
Users getting Oops error screen while trying to access Subject on DEA

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-webapp#1031]
**Describe the bug**
Users getting Oops error screen while trying to access Subject on DEA. The root cause of the issue is the user is non org admin and is only part of Everyone group. Ideally, a proper permission denied message should show up in such scenarios so that it saves users and support team's effort to debug such issues.

**To Reproduce**

1. Go to Saahas org
2. Create a non admin user only part of Everyone group
3. Login with this user and Go to DEA
4. Click on any one subject and see the error

**Expected behavior**
A clear message should come that user does not have relevant permission.

Relevant ticket - https://avni.freshdesk.com/a/tickets/2985

**Screenshots**

![Image](https://github.com/avniproject/avni-webapp/assets/37863085/859e4344-22fa-45ae-be61-7e77ddffcc46)

**Developer Checklist**(Developer fixing the bug should fill this checklist)
- Does the fix require extensive regression testing?
  - [ ] Yes
  - [ ] No
- Are you mentioning the required scenarios that could be affected?
  - [ ] Yes
  - [ ] No

**Comment by vinayvenu** [comment]
### Solution
- Temp fix: Find all network calls, and add a generic popup on the screen that mentions if it is a privilege issue.
