### ISSUE TITLE
Ability to show DEA on demand (privileges)

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#1036]
Acceptance criteria:

- Add new Subject/Entity Type in Permissions page saying 'Transaction data on Data Entry App', Entity Type will also be 'Transaction data on Data Entry App', Privilege should be 'View/edit entities on Data Entry App'.
- When the permissions is toggled on, 'Data Entry App' box will display, else should not display.
- So when the permissions is toggled on, we should be able to view/edit subjects, view/edit encounters, etc. as usual.
- @mahalakshme for all existing UserGroups, i have set the default privilege "allow" value to **true** for TransactionDataOnDataEntryApp. Would that be okay, or should we set them to **false**.?

Out of scope:
- Permissions for viewing/editing specific entities within data entry app

**Comment by himeshr** [comment]
User Group Privileges screenshot for the new 'Transaction data on Data Entry App' privilege.
<img width="1840" alt="Screenshot 2023-10-19 at 12 54 23 PM" src="https://github.com/avniproject/avni-webapp/assets/72493481/6486f10b-c464-4532-964b-dcd89ad8805d">

**Comment by mahalakshme** [comment]
@himeshr true is fine. But I feel in Subject/EntityType we can just have as "DataEntryApp" instead of "TransactionDataOnDataEntryApp" since Data entry app deals with only transactional data.

**Comment by ashusvnath** [comment]
@himeshr , @vinayvenu : What happens if users directly browsers to <web-app-base-url>/#app ?

**Comment by himeshr** [comment]
> @himeshr true is fine. But I feel in Subject/EntityType we can just have as "DataEntryApp" instead of "TransactionDataOnDataEntryApp" since Data entry app deals with only transactional data.

Renamed "TransactionDataOnDataEntryApp"  to "DataEntryApp"

**Comment by AchalaBelokar** [comment]
<img width="722" alt="permission" src="https://github.com/avniproject/avni-webapp/assets/104890488/89f32dd3-c320-43b5-97a3-1d240c602ad3">
not able to see the toggle
