### ISSUE TITLE
In app designer edit and delete symbol is changed it is showing wrong symbol 

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-webapp#1037]
**Describe the bug**
In app designer edit and delete symbol is changed it is showing wrong symbol 
this is happen with staging
**To Reproduce**

1. login as org admin
3. Click on app designer
4. click on subject type see the edit and delete subject type
5. it is happening with program edit and delete and same with concept and encounter, programs
6. See error

**Expected behavior**
edit and delete show as 
![edit](https://github.com/avniproject/avni-webapp/assets/104890488/ecc88641-496a-49e3-a89a-0c9a39fef96c)

**Screenshots**

https://github.com/avniproject/avni-webapp/assets/104890488/da7712de-cecd-4d88-a162-b703b82ff0c3

**Comment by ashusvnath** [comment]
QA Observation:

* * Missing Icons are visible everywhere
