### ISSUE TITLE
Save button text wrong/wierd

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-webapp#1038]
<img width="1728" alt="image" src="https://github.com/avniproject/avni-webapp/assets/105867/6cef9e25-417a-47f0-adae-bba2abd26b22">

**Comment by ashusvnath** [comment]
QA Observation:
The save icon is now restored:


![Image](https://github.com/avniproject/avni-webapp/assets/568925/3a789642-f438-435c-b413-6e510618139c)
