### ISSUE TITLE
App shows blank page if closed within expiry time and opened later in the day (Keycloak only)

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#1041]
### To reproduce
In an environment with only Keycloak, open the app and login
Close the tab
Open after token expiry time (20 minutes)
Expected - App should take user to login page
Actual - Blank page with error below

```
GET
https://app.security.lfe.avniproject.org/web/userInfo
[HTTP/2 401 Unauthorized 55ms]

Unauthorized [httpClient.js:106:14](https://app.security.lfe.avniproject.org/static/js/common/utils/httpClient.js)
Error: Unauthorized
    t HttpError.js:50
    s fetch.js:64
    promise callback*s fetch.js:51
    e httpClient.js:105
    _ runtime.js:63
    _invoke runtime.js:282
    t runtime.js:116
    Babel 6
    value httpClient.js:112
    fetchUserInfo saga.js:19
```

### Analysis
- httpClient.js looks for TokenExpiredException. However, the exception was moved from an http 500 to http 401 recently, so this piece of code does not work.

**Comment by AchalaBelokar** [comment]
- [ ] After expiry timeout  I click on refresh screen get blank and after that I need to clear out data

**Comment by vinayvenu** [comment]
@AchalaBelokar when I click on refresh, the app goes to the login screen. I do not have to clear data. Can you recheck?

**Comment by mahalakshme** [comment]
@vinayvenu @AchalaBelokar I dont know if it makes a difference. I kept the previously logged in tabs open. After around 30 minutes, in a new tab, type app.security.lfe.avniproject.org - blank page shows up - consistently happens

**Comment by vinayvenu** [comment]
This happens only on Chrome where error.message does not exist. Check moved to error.code === 401 instead of error.message === "Unauthorized"

**Comment by 1t5j0y** [comment]
Pending deployment to LFE security env to test.

**Comment by ashusvnath** [comment]
Deployed latest 5.0 webapp to LFE security environment.

**Comment by ashusvnath** [comment]
QA Observation:
* Scenario 1:  
  * User behaviour: User logs in and leaves tab/window unattended for 20 minutes. 
  * App behaviour : User is logged out from app after configured time (20 minutes) and redirected to the login screen. Refresh also takes user to the login screen.
* Scenario 2: 
  * User behaviour: User logs in to app and closes the tab. Browses back to the app page after 20 minutes.
  * App behaviour : User is logged out from app after 20 minutes. The user is presented with a login screen. If older version of app is present locally, a white page is seen initially. On refreshing the page, user is taken to login screen.
