### ISSUE TITLE
Remove rules in webapp

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1047]
Currently the server is under more load than it can handle. Call to program Summary rule takes up 8%.
So we can get rid of programSummaryRule from DEA since DEA's purpose is data entry.

**Comment by vinayvenu** [comment]
@arjunk do watch this card. The programSummaryRule and encounterEligibilityRule are currently bringing down production.

**Comment by mahalakshme** [comment]
@vinayvenu looks like we cant remove eligiblePrograms and eligibleProgramEncounters calls since it is based on them we are displaying the programs and encounter options that an Data entry person can click on to enter. We can remove programSummaryRule though since mostly its data will be available in program enrolment or in encounters.

@arjunk what will be the impact on ground if we remove the programSummaryRule from DEA. We discussed that since the purpose of DEA is to facilitate data entry, we can remove the summary rule. We can think of removing subjectSummary as well. Or is the naming 'Data Entry App' incorrect and its been used for other purposes also? Based on that we can decide on if we want to make the removal permanent or temporary until the other performance fixes come in.

**Comment by mahalakshme** [comment]
closing since duplicate: https://github.com/avniproject/avni-webapp/issues/1042
