### ISSUE TITLE
Ability to clone a form

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-webapp#105]
This is required because sometimes we want to copy an existing form an make some modifications to it. 

### Acceptance Criteria:
- There should be an option to clone a form on forms listing page. 
- Clicking on clone button should open a popup asking for the name of new form and mapping(similar to new form popup). All the fields in popup should be empty by default. 
- Giving same name as an existing form should give an error saying form already exist.

### Implementation:
- Open the new form popup. After user clicks Add button we call POST /web/forms. It will return uuid of new form. We will get old form data by calling GET /forms/export?formUUID={oldFormUUID}. We will send this data with uuids changed to POST /forms api. Then we will redirect user to new form page with cloned content.

##### Test Cases - 
Ayu Implementation - 
1. Cloning a form (Birth Registration) with the same name in the same Program (Mission Titlee) and for the same Subject Type.
I should not be able to create/clone that form. - **PASS**

2. Cloning a form (Birth Registration) with the same name in the different Program (Mission Titlee) and for the different Subject Type.
I should be able to create/clone that form. - **Failed** 
**Dev notes**: Moving this requirement to different story avni-product#1094

3.

**Comment by swapnil106111** [comment]
@hithacker Pushed clone form code in cloneForm branch.

**Comment by hithacker** [comment]
@garimadosar5 Moving the requirement of not able to assign duplicate mapping to another story openchs-product#1092

**Comment by hithacker** [comment]
@garimadosar5 moving the requirement of being able to create a form with same name but different subject type or program to another story as it's common usecase in create, edit, and clone form. https://app.zenhub.com/workspaces/avni-5cf8e458bf08585333fd64ac/issues/avniproject/avni-product/1094
