### ISSUE TITLE
Unable to access offline report cards under App designer

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-webapp#1054]
**Describe the bug**
As an org admin user, i am currently unable to access the offline report card though i can edit it!

**To Reproduce**

1. Go to Pre release - APF
2. Click on App designer
3. Scroll down to "Offline report cards"
4. Click on any one of them and see the error

**Screenshots**

![Image](https://github.com/avniproject/avni-webapp/assets/37863085/c8f6e4d0-0ae0-489a-827a-49a6518e16fb)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Analysis details**
- This happens when report card is clicked and Icon is not added for the report card and it returns 500.
<img width="943" alt="Screenshot 2023-10-03 at 5 24 49 PM" src="https://github.com/avniproject/avni-webapp/assets/10369963/a844039a-2ec7-4389-8348-95a384dcfaab">
- The above issue is happening in prod as well like in the above image but it doesn't block the user from using the webapp. Currently in prerelease it blocks the user from using the app, since we have added the check for hostname as part of security fixes.

**Acceptance criteria**
- Call to fetch the icon need not happen unless there is an icon url returned from the report card url.
- Test by adding icon.

**Developer Checklist**(Developer fixing the bug should fill this checklist)
- Does the fix require extensive regression testing?
  - [ ] Yes
  - [ ] No
- Are you mentioning the required scenarios that could be affected?
  - [ ] Yes
  - [ ] No

**Comment by 1t5j0y** [comment]
QA Notes:
1. Works as expected. Report card screen loads fine if icon is an empty string.
2. Super admin users access to report cards is blocked if icon is a valid s3 uri. (The GET /media/signedUrl call fails with a 500 "Access is denied" error and the page errors out) - this probably needs a different card.  If there is no icon set for the report card, it loads fine. FYI @vinayvenu @mahalakshme

**Comment by mahalakshme** [comment]
@1t5j0y yes, that can be moved to a separate card. can you create a card for it. I think few other things also dont work for super admin as expected. We can add them as and when we find out.
