### ISSUE TITLE
Not loading extension script because of CSP

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1055]
Env: prerelease, login details: nupoork@jscs, 

** Steps to reproduce **
- Go to DataEntryApp
- Click on "Print SS Card"
- We can see the below issue because of our CSP policy.

![Image](https://github.com/avniproject/avni-webapp/assets/10369963/02076ddd-33e1-4620-a543-6152103c95d9)

**Comment by 1t5j0y** [comment]
Added config to have CSP enabled/disabled and turned it off in prerelease.
