### ISSUE TITLE
New longitudinal fails for program encounter with no cancellation form

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-webapp#1056]
**Describe the bug**
Currently, the new longitudinal export fails when a program encounter in the request is not mapped to a Cancel form.

**To Reproduce**

1. Go to "Yenepoya" org >> Reports >> New Longitudinal Export
2. Request json - With comments - https://github.com/avniproject/yenepoya/blob/master/New%20longitudinal%20request.json
3. Remove comments and see the request fails and there is no downloadable error file
4. Now remove the "Delivery" encounter under Pregnancy program >> The request will run and give results
5. Basically, the Delivery encounter do not have Cancellation form.

**Expected behavior**
So, even if the cancel form is not mapped, the new longitudinal export should work fine

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Developer Checklist**(Developer fixing the bug should fill this checklist)
- Does the fix require extensive regression testing?
  - [ ] Yes
  - [ ] No
- Are you mentioning the required scenarios that could be affected?
  - [ ] Yes
  - [ ] No

**Comment by mahalakshme** [comment]
@nupoorkhandelwal you are right, its because the encounter type doesn't have cancellation form. would like to know why is that some encounter types need not have cancellation form.

**Comment by nupoorkhandelwal** [comment]
@mahalakshme It is possible to remove the cancel form mapping under Forms, and since this is Delivery encounter, as part of requirement it must have been removed by implementor at some piont.
