### ISSUE TITLE
Unable to add new concept in coded concept

### ISSUE THREAD

**Issue by vedfordev** [avniproject/avni-webapp#1058]
**Describe the bug**
Unable to add new concept in existing concept

**To Reproduce**
Steps to reproduce the behaviour:

**Org**
lahiint

1. Go to concept **Trade/Sector**
2. Try to added new concept in ite.
3. See error
<img width="1381" alt="Screenshot 2023-10-09 at 11 12 43 AM" src="https://github.com/avniproject/avni-webapp/assets/106894932/e5277809-8ddd-429c-b907-b0a65a19d405">

#### Analysis:
- 1st issue. The above is because when an existing concept answer of the concept has '&' symbol then no new concept is able to be added. Eg: say when a existing concept has a concept answer 'a&b', then click on Edit and add any new concept answer, the response returns with "400" status, and saying  "concept a&b exists with different uuid"
- 2nd issue. Click on Edit of the concept - delete the concept answer with '&' -> click Save. The concept answer with '&' will still appear as part of the concept.

#### Acceptance criteria:
- for the 1st issue, new concept answers should be able to be added even when a concept already has a concept answer with '&'
- for the second issue, should be able to delete.
- check the above behavior for concept answers with other special characters like %, &, /, etc.,

**Comment by ashusvnath** [comment]
Changes only needed on avniproject/avni-server

**Comment by himeshr** [comment]
@vinayvenu  and @mahalakshme , for this card, the code fix done in sufficient.
But there might be a root-cause analysis and fix needed, to ensure that encoding behaviour on request params has not broken after security code changes.

**Comment by mahalakshme** [comment]
@ashusvnath can you also identify the rootcause for this issue. This will help us in figuring out similar issues and preventing future errrors.

**Comment by ashusvnath** [comment]
@mahalakshme , @himeshr , @vinayvenu : The problem does not occur on the 4.0 branch of avni-server and only occurs on the 5.0 branch. The code at org/avni/server/framework/sync/MutableRequestFilter.java:80 seems to be the root cause of the issue. where `&` is coverted to `&amp;`.

**Comment by AchalaBelokar** [comment]
According to security env we are not allowed & on coded concept but this is allow us to add coded concept
