### ISSUE TITLE
Unable to close Rule Failure issue

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/avni-webapp#1059]
**Describe the bug**
1. The "Open", "Closed" and "All" buttons get doubled on selecting something.
2. Not able to close errors. 

**To Reproduce**
Have an obvious JS rule error( I found out when I was trying out a visitSchedueLogic in the client and synced my device to see if I was getting any errors)
![Image](https://github.com/avniproject/avni-webapp/assets/94247708/1b22d84f-8431-4e6a-9427-3ed06f7a7b23)

**Acceptance criteria**
- For the 1st issue above, buttons should not be doubled on selection.
- For the 2nd issue, add Update dropdown on the top like that of below image - Options should be Open and Closed. And the placeholder text should be "UPDATE" 
![Image](https://github.com/avniproject/avni-webapp/assets/10369963/020f8f62-80c3-440d-813a-0a514a855fc2)

**Comment by mahalakshme** [comment]
@ashusvnath can you add a screenshot of current UI now here?

**Comment by ashusvnath** [comment]
@AchalaBelokar , @mahalakshme : i've fixed the Issue closed date time bug as part of this card
