### ISSUE TITLE
Screen to download flattened data for a visit

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-webapp#106]
- User should be able to submit job by selecting appropriate subjectType, program, encounter types and date range.
- User should be able to track the status of job.
- User should be able to download the generated file once job is complete.

#### Feedback Comments
1. New row should appear when new job is triggered.
2. State of the options should not get reset after submitting the job.
3. There should be two separate sections one for options and other for job status.
4. Display duration in ISO format.
5. For any subject type where  program is not present, it shows visit date filter.
6. Change generate Report label to generate Export.
7. If media directory is not present for any organisation then job should not start.

##### Test Cases - 
- Click on Report Type and based on the selection get the report.
- Status Table gets updated automatically.
- Status of Report generation is shown in the table.
- Date Range should show the two dates when data is generated. - Date Range is not showing for Registration data.
- The status table should get updated with the subject type user has chosen for report generation.

**Comment by garimadosar5** [comment]
QA Notes - 

1. It gives the date range options only for Program encounter. The user might need date range in registration or Program enrolment also.

2. What if User wants to download only enrolment data. There is no option for that.

3. Put * sign for whatever is mandatory.

4. Cannot download the file-
![Screen Shot 2019-12-03 at 3.20.16 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/a0ef7f6d-c0ea-436f-b52e-f920a50f5a19)
