### ISSUE TITLE
Duplicate concept answers breaks concepts page

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1060]
#### Need:
Some coded concepts have more than 15 answers and all are added at the same time. Hence the user sometimes by mistake adds the same concept answer twice. When it doesn't show a valid error, it is raised as a ticket.

#### Current scenario:

env: staging, prod
-  Go to any organisation in webapp
- Go to a coded concept
- Add the same concept answer twice
- Results in 500 error
Video to understand the issue: 
https://github.com/avniproject/avni-webapp/assets/10369963/674a69cf-aa27-4c4f-8e5c-39f8cd4db465

### Expected:
- Show error 'Duplicate answer specified' on-clicking "Save" button and Oops error page should not display.
- Also handle the above when creating concepts directly in form. (InlineConcept)
- Removal of duplicate answer of previously existing answer concept should not result in voiding of earlier answer
- All duplicates except the first original answer should have duplicate error msg shown
- All different duplicates should be shown as errors at once

#### Expected:
- Whenever duplicate concept answers are added show valid error message stating 'Duplicate answer present. Remove them to proceed.' like in the mockup below, below the last duplicate instead of showing Oops error page. 

![Image](https://github.com/user-attachments/assets/4ff277b5-3316-4e40-9009-ef77267b9750)

**Comment by vinayvenu** [comment]
@mahalakshme 
Where does the app break? Is this in the form designer, concept page or the data entry app? If it is form designer, then why prioritize to 5.1.0? Is bad data getting inserted? 

Acceptance criteria needs to be specific enough for devs and testers to know which area to test.

**Comment by mahalakshme** [comment]
concept page breaks. Added it to 5.1.0 since was raised by Vedant once, came as ticket and multiple discussions. To reduce the ticket add it to 5.1.0.

**Comment by arjunk** [comment]
I see in the database we have concepts with '&' and various other special characters also. 

check using the following queries
select * from concept where name ~* '[^a-z0-9 ]' order by created_date_time desc;   (last created till July)
select * from concept where name like '%&%'

What special characters are currently being supported/not supported? What is the basis of this? This change seems to have been in last few releases but couldn't find any relevant issue except this https://github.com/avniproject/avni-server/issues/449. (Haven't checked code)
For the concepts where such names with special characters are already there, what problem is it or will it be causing? Do we need to migrate them?
Apart from giving an informative error message to the user, we need to document this.

**Comment by vinayvenu** [comment]
@mahalakshme I think I read the acceptance criteria wrong. Is there a need to remove these characters from concept answers?

**Comment by mahalakshme** [comment]
@vinayvenu @arjunk I think as part of security fixes, this change might have occured. But special characters are not allowed even after turning off enhanced validations in prod. We will need to check what has caused this change.

**Comment by mahalakshme** [comment]
moved the character issue to separate card: https://github.com/avniproject/avni-webapp/issues/1058

**Comment by vinayvenu** [comment]
Mockups - we can show the duplicates if possible?

**Comment by himeshr** [comment]
## Sample Duplicate answer screenshots

<img width="901" alt="Screenshot 2024-08-28 at 1 11 07 PM" src="https://github.com/user-attachments/assets/a63f8858-3d5e-4930-9d8b-46b2b8526403">

<img width="1172" alt="Screenshot 2024-08-28 at 1 16 42 PM" src="https://github.com/user-attachments/assets/354115b3-ae06-47c7-84ca-afb680027f8c">

**Comment by himeshr** [comment]
> @himeshr I created a concept with ASH and ash it is accepting the value not showing the error. is it valid or not.?

@AchalaBelokar, In Avni, Concept names are case-sensitive, we allow users to create concepts with same name but with different case, which are used in different forms.. this is pretty common.

Now for Concept Answers, the only usecase i can think of, where concept answers with same name but different case might be needed, is when there is an external integration system, which accepts different case answers in different conditions.

So i would say that in principle, we should not error in-case there is more than 1 concept-answer with same name but different case.

**Comment by mahalakshme** [comment]
@himeshr I will think and update

**Comment by mahalakshme** [comment]
@AchalaBelokar it does make sense to make the concepts to be considered duplicate independent of the case, but considering we have allowed it so far, it is now complex to correct the existing data. So we need not fix it as part of 10.1.0, will add it to a different release.

**Comment by himeshr** [comment]
Handled additional test-cases:
- Recreation of previously saved voided concept answer
- Handling removal of duplicate non-voided answers when previously saved non-voided concept answer

**Comment by petmongrels** [comment]
We don't have any check on server for duplicate concepts. we should add a database constraint.

**Comment by himeshr** [comment]
<img width="1840" alt="Screenshot 2024-11-05 at 2 47 16 PM" src="https://github.com/user-attachments/assets/0cdbb9c1-39e3-4f9b-87c0-aafb529bcfce">


> We don't have any check on server for duplicate concepts. we should add a database constraint.

We do have it, checked in code as well as on local and prod openchs Databases for Concept table.

**Comment by himeshr** [comment]
Constraint also exists on DB for concept_answer..
<img width="1840" alt="Screenshot 2024-11-05 at 2 52 06 PM" src="https://github.com/user-attachments/assets/71980b2c-da76-4996-8c89-24d0e1f86863">

**Comment by dinesh2096** [comment]
QA Reference : 

[Click here to watch video](https://drive.google.com/file/d/1A-iypE7psDIvdSJWoaR0aKZgmWCYjtm9/view?usp=drive_link)
