### ISSUE TITLE
Unable to select colour in Offline report card.

### ISSUE THREAD

**Issue by vedfordev** [avniproject/avni-webapp#1061]
**Describe the bug**
For new offline report card, unable to select colour. So, It gives error **Colour cannot be empty** and to save card we have to go with default colour which is red.

**To Reproduce**

**Org**
happens in all orgs

1. Go to Offline Report card.
2. Fill mandatory details
3. Try to change colour

**Expected behaviour**
User should able to select colour. 

https://github.com/avniproject/avni-webapp/assets/106894932/e9f1b6e4-9521-47fb-8882-c9c7bc07723c

**Comment by himeshr** [comment]
Issue was caused due to recent switch from ColorPicker to PopOverColorPicker done in recent release.
Minor code change, code-review not needed.
Verified that all other code-pickers are also working fine.
