### ISSUE TITLE
Not able to go next page on concept screen next button is not working on staging env

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-webapp#1075]
**Describe the bug**
Not able to go next page on concept screen next button is not working on staging env

**To Reproduce**
1. Login with any user
2. Click on app designer
3. click on concepts
4. click on next button
5. unable to next page
6. 
**Expected behavior**
User is able to go to next page
https://github.com/avniproject/avni-webapp/assets/104890488/04261d46-879d-45f0-b8a4-c027d2090928

**Comment by mahalakshme** [comment]
just to add this issue is not occuring in prerelease

**Comment by himeshr** [comment]
Not undoing the switch from onChangePage to onPageChange in JobStatus and Status files, as Next page functionality is working there.
