### ISSUE TITLE
Translations not uploaded for webapp via circle-ci

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1081]

**Comment by 1t5j0y** [comment]
Lot of trial and error commits.
Actual [diff](https://github.com/avniproject/avni-webapp/compare/0d6b5ed8dd71638b2ca835a06cb07b0a6561e30e...f871cfbf8c0740296b35a455dfc1946502b7aedf)

**Comment by himeshr** [comment]
Verified that the env variables are added to circleCI job.
And also that the deploy was successful, with platform translations applied for the target environment.
