### ISSUE TITLE
SScard & diagnostic card printing not working for jscs

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-webapp#1082]
**Describe the bug**
SScard & diagnostic card printing not working for jscs

**To Reproduce**

1.login with dineshsh@jscs
2. Click on data entry app
3. click on search 
4. select the subject 
5. click on print 
6. see the error
**Expected behavior**
User is able to print the report

**Screenshots**

https://github.com/avniproject/avni-webapp/assets/104890488/43cf269d-d943-44dd-9614-a6ca31585bbc

-

**Comment by mahalakshme** [comment]
@AchalaBelokar try after uploading the extensions it should work. This is because s3 looks like was cleared.,

**Comment by mahalakshme** [comment]
after uploading the extensions to s3 it is working. @AchalaBelokar so closing this card
