### ISSUE TITLE
Configure glific messaging on user creation

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1098]
### Motivation:
- As a user, I would like to receive my Avni username in whatsapp so that I can use it to login in Avni. 
- We receive complaints that users didn't receive their username - now by doing this, the organisation can keep track of the messages delivered via Glific.
- Messages app is clogged with notifications and delivering via Whatsapp will help the user to easily identify the messages.
- Can do more things in glific like setting up of flow which when a org sets up will help the users to better understand, and will add up to the advantage of doing this in addition to SNS.

### Acceptance criteria:
![Image](https://github.com/avniproject/avni-webapp/assets/10369963/d0ba88b1-0eb7-4568-a41f-7129495655b4)
Note the URL change and the documentation to the right. And Receiver Type need not get displayed since here the receiver type by default is User.
- The dropdown should display a list of glific templates and user should be able to select one. 
- On re-clicking the Menu item the already selected template and message rule should appear
- On edit scenario, the saved entries should get updated
- Should be able to add more than one message rule
- The default message rule should return the username as parameter and the default schedule rule should mean sending the message immediately on save.
- Add documentation on readme for "user-messaging-config"

- Regarding error handling logic, any existing logic that exists for other message rules like in Subject Type can be retained and no need to handle anything new.

### Technical preliminary analysis:
- On saving of configuration, insert a entry into message_rule table
- Entity type will be User
- There is no entity_type_id - since here it need not be made/configurable at user group level as well
- On edit scenario, update the entry in the message_rule table
- Feel free to change the technical implementation if there is a better way

### Regression testing
 - Ensure old SubjectType / Encounter / Program MessageRules config works correctly for both User / Subject

### Out of scope:
- Handling of permissions regarding who can do this

**Comment by mahalakshme** [comment]
@vinayvenu didn't move this to broadcast tab/menu since configuration for automatic sending of messages is currently placed in the respective entities UI. So if we move this to Broadcast tab, implementors/self implementing orgs will raise questions like configuration for automatic sending of messages to subjects is missing in broadcast tab. Also no one is using broadcast tab as of now. Let me know if u think otherwise.

**Comment by vinayvenu** [comment]
@mahalakshme what permissions are required to activate this feature?

**Comment by mahalakshme** [comment]
@vinayvenu there is a separate card to handle permissions. I feel the placement is fine, since Messaging doesn't necessarily come under App designer and it is more of a association function. Let me know if u think otherwise

**Comment by mahalakshme** [comment]
concluded after discussion that cant place in Admin tab since its not Admin action, and App designing action.

**Comment by himeshr** [comment]
UserMessagingConfig sample screenshot
<img width="1728" alt="Screenshot 2023-12-27 at 4 40 38 PM" src="https://github.com/avniproject/avni-webapp/assets/72493481/0ff4bad1-fa23-4397-afb4-cf34dce116eb">

**Comment by AchalaBelokar** [comment]
I created the work order with using the subject rule But did not get any msg

**Comment by himeshr** [comment]
The common_otp template expects 3 params in the message_rule, you have specified only 2.
