### ISSUE TITLE
Send glific message on user save

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1099]
### Motivation:
- As a user, I would like to receive my Avni username in whatsapp so that I can use it to login in Avni.
- We receive complaints that users didn't receive their username - now by doing this, the organisation can keep track of the messages delivered via Glific.
- Messages app is clogged with notifications and delivering via Whatsapp will help the user to easily identify the messages.
- Can do more things in glific like setting up of flow which when a org sets up will help the users to better understand, and will add up to the advantage of doing this in addition to SMS.

### Acceptance criteria:
- [x] On user create, message(created using the glific template configured in the user settings) should be sent to user phone number 
- [x] Should work for users created via CSV as well,
- [x] Dont send message for user update. 
- [x] Also on CSV upload, if user already exists, no need to send message.
- [x] Like in other cases, create glific contact if it doesnt exist and figure out the parameters
- [x] Add documentation on sending Glific message only for User Creation

### Additional notes:
- You can find the Glific credentials for the org in focus for this story in Keeweb.
- Code changes done in avni-server and rules-server master branch

### Out of scope:
- Configuring the message and schedule rule for the user creation on the UI. To get/test the story working you can insert some sample rules in the DB.

**Comment by mahalakshme** [comment]
@vinayvenu do we have a RWB glific account to try out the above?

**Comment by himeshr** [comment]
@mahalakshme in the User registration message that is sent from Cognito, we use the following template:
```
Your Avni username is {username} and temporary password is {####}.
```
As part of the Glific message, do we need to include temporary password as well.?

Based on the answer to this question, 
- we would end up having the trigger point for Glific Registration Invitation message at different points.
- also, we might not be able to do Glific Registration Invitation message with password for Keycloak IDP organisations

**Comment by mahalakshme** [comment]
@himeshr No we need not add facility to send password

**Comment by himeshr** [comment]
SQLs to create glific system config and messageRule for AvniInvitation:
```sql
INSERT INTO public.message_rule (id, uuid, name, message_rule, schedule_rule, organisation_id, is_voided, entity_type,
        message_template_id, version, created_by_id, last_modified_by_id, created_date_time,
        last_modified_date_time, entity_type_id, receiver_type)
        VALUES (DEFAULT, uuid_generate_v4(), 'Avni Invitation', '//SAMPLE RULE EXAMPLE
        ''use strict'';
        ({params, imports}) => {
        const user = params.entity;
        return {
        parameters: [user.username, ''going to be shared by the Admin.'']
        }
        };', '//SAMPLE RULE EXAMPLE
        ''use strict'';
        ({params, imports}) => ({
        scheduledDateTime: new Date("December 21, 2023 01:00:00")
        });', 191, false, 'User', '333223', 0, 1, 1, now(), now(), -1,
        'User');

        INSERT INTO public.external_system_config (id, organisation_id, uuid, is_voided, version, created_by_id,
        last_modified_by_id, created_date_time, last_modified_date_time, system_name,
        config)
        VALUES (DEFAULT, 191, 'dacc3578-1593-4ad9-8e59-b3ff60116b1a', false, 1, 1, 1, now(),
        now(), 'Glific',
        '{"phone": "<phone>", "baseUrl": "https://api.atecfchat.glific.com", "password": "<password>", "avniSystemUser": "maha@rwbniti"}');
```

**Comment by himeshr** [comment]
Sample bulk users create file which included Existing users: 

[rwb-usersAndCatchments.csv](https://github.com/avniproject/avni-webapp/files/13740112/rwb-usersAndCatchments.csv)

**Comment by himeshr** [comment]
**Note: Code review to be done on avni-server repo with commits prefixed as #1099**

**Comment by AchalaBelokar** [comment]
- [ ] @himeshr What happen when we change the phone number of existing user

**Comment by himeshr** [comment]
> * [ ]  @himeshr What happen when we change the phone number of existing user

As of now, there is no requirements to do any actions when the phone number is changed for an existing user.
