### ISSUE TITLE
Permissions for configuring message rule for users

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1103]
### Acceptance criteria:
- Update description of 'EditUserConfiguration' privilege to 'Create and update users and their subject assignment'
- ~~Insert a new privilege to allow editing message rule configuration for users - 
let name be 'Edit user messaging configuration'
description: 'Edit message rule configured for user creation'
entityType: 'NonTransaction'
type: 'EditUserMessagingConfiguration'~~
- Update description of 'EditOrganisationConfiguration' privilege to reflect the features it controls access to including the new feature to configure message rule on user creation.
- ~~Should be backward compatible - in the sense that existing Administrator groups should have this new privilege enabled and for others disabled.~~
- Make use of 'EditOrganisationConfiguration' privilege in webapp and server while allowing access for UserMessagingConfig actions.

**Comment by himeshr** [comment]
@mahalakshme and @joy, 
I'll be creating a migration for performing the following update as per the requirement specified in the card description:

```sql
UPDATE public.privilege
SET description = 'Create and update users and their subject, task , group or identifier assignments', last_modified_date_time = now()
WHERE name = 'Edit user configuration' and type = 'EditUserConfiguration';

UPDATE public.privilege
SET description = 'Edit organisation configuration like filters, languages, userMessagingConfig, etc.,', last_modified_date_time = now()
WHERE name = 'Edit organisation configuration' and type = 'EditOrganisationConfiguration';
```

Lemme know if the description needs to be changed further

**Comment by mahalakshme** [comment]
@himeshr it looks fine to me.
