### ISSUE TITLE
Getting Data Integrity Violation Exception while saving the form.

### ISSUE THREAD

**Issue by himeshr** [avniproject/avni-webapp#1105]
**Describe the bug**
I'm getting this error, not every time but pretty often. It happens when I try to save two form elements at once or when I create a new form element group and form element together simultaneously. Despite the error, everything seems to be saving correctly.

**Why prioritised**
These kinds of failures are affecting the speed of implementation team impacting the costs.

**To Reproduce**
env: prod, any org

1. Go to Any form
2. create and save two form elements, or a form element group and a form element together at the same time—instead of doing it separately.
3. See error

Getting this error, not every time but pretty often. Not easy to reproduce this issue.

**AC**:
Should save without showing the error.

**Screenshots**
![Image](https://github.com/avniproject/avni-webapp/assets/10369963/383846f2-d3a5-4b82-b6bf-d1e3bcd60dea)

**Comment by mahalakshme** [comment]
@himeshr I was unable to reproduce this issue on prerelease? Can you add 'steps to reproduce'?

**Comment by himeshr** [comment]
> @himeshr I was unable to reproduce this issue on prerelease? Can you add 'steps to reproduce'?

@nupoorkhandelwal please add the steps to reproduce and then remove the WIP prefix from the title of the card.

**Comment by adamsanadi6** [comment]
[Screencast from 20-12-23 11:17:58 AM IST.webm](https://github.com/avniproject/avni-webapp/assets/64148954/9d7b5384-ec2f-4e93-b96e-99b6e7f659b3)
![Screenshot from 2023-12-21 12-44-46](https://github.com/avniproject/avni-webapp/assets/64148954/d79b83a2-393a-469e-9b8a-05b0b7eb0102)

**Comment by adamsanadi6** [comment]
![Screenshot from 2023-12-21 12-44-46](https://github.com/avniproject/avni-webapp/assets/64148954/efe910c9-0de6-473a-a866-8bdf4db6ccb5)

**Comment by adamsanadi6** [comment]
[Screencast from 20-12-23 11:17:58 AM IST.webm](https://github.com/avniproject/avni-webapp/assets/64148954/c248671e-0c68-4ded-a578-77f1ec5fcb04)

**Comment by mahalakshme** [comment]
Steps to reproduce as per Adam:
You can try to save two form elements at once or
create a new form element group and form element inside it then save them at once not separately. This error is not coming every time.

**Comment by 1t5j0y** [comment]
Issue was due to duplicate API calls being triggered from webapp (since the api call was triggered within `render()` and the component was being re-rendered). Depending on the timing of the duplicate call, this issue was occurring intermittently.

#### QA notes:
Check that validations and save works as before.
