### ISSUE TITLE
Clicking on the checkbox the user assigned is getting reset

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-webapp#1106]
When a user is assigned under the assigned to and if we click the check box under the name it is user assigned is automatically removed

steps to reproduce:
1.login to webapp
2.Click on the assignment
3.search for individual or subject type 
4.click on select under assigned to and select the user
5.Click on the check box under the name 

Expected : user assigned shouldnot be remove and actions button should be intractable
Actual : user removed from the assigned to 

https://github.com/avniproject/avni-webapp/assets/127730126/06ee9d77-82c6-4a4b-915e-3b47ba808b3c

**Comment by AchalaBelokar** [comment]
- [ ] I uploaded latest version  on web app .. still I ma facing the same issue.

https://github.com/avniproject/avni-webapp/assets/104890488/799eb672-7542-4a1d-a2f7-530c52de7bdf

**Comment by 1t5j0y** [comment]
@AchalaBelokar did you refresh your browser after deploying the change? I am unable to simulate this on staging
