### ISSUE TITLE
Hex code input type missing

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/avni-webapp#1109]
**Describe the bug**
Earlier, there was a field where we used to enter the hex code of the color, and the color used to stay consistent across multiple cards.
Now the input type is missing.

**To Reproduce**
Go to offline report card and click on the color palette.

**Screenshots**

![Image](https://github.com/avniproject/avni-webapp/assets/94247708/8b272d25-0952-4b4a-b8cd-9584bbb45e55)

### Need:
Will help self-service orgs to be able to set colours for report cards, even without having the knowledge to write rules.

### Technical analysis:
Looks like the issue is from this commit: 1ca782a5

**Comment by himeshr** [comment]
Sample Screen Recording
https://github.com/user-attachments/assets/2b3e59b0-d2d9-4860-865e-c9c4733070f5

**Comment by AchalaBelokar** [comment]
- [ ] If we edit or want to remove the color and have it as default or previous color system automatically take the color code if we added recently. As a user if don’t want to change i have to select or have the backup of previous color And also when we click on the card first it loads the red color and after a sec the selected color is displayed can we fix if we click the corresponding color is displayed .
https://drive.google.com/file/d/1rPVxJrlhwyFA71SakHcZ0lTBLm4xUg3D/view?usp=sharing

**Comment by himeshr** [comment]
> * [ ]  If we edit or want to remove the color and have it as default or previous color system automatically take the color code if we added recently. As a user if don’t want to change i have to select or have the backup of previous color And also when we click on the card first it loads the red color and after a sec the selected color is displayed can we fix if we click the corresponding color is displayed .
>   https://drive.google.com/file/d/1rPVxJrlhwyFA71SakHcZ0lTBLm4xUg3D/view?usp=sharing

@AchalaBelokar, there are 3 issues reported as part of this:
- Red colour shown for report card during load of show/edit screens of old report cards 
- Removing color doesn't replace it with initial / default value
- Inability to reset to previous values

Of the above, i have resolved only the first item, i.e. to not show Red colour in intermittent load state.
The other 2 issues, the ability to reset to previous value on removal of current value or through a button is not fixed, as there is an easy alternative for it, using undo(Cmd+z) option.

Additionally, also fixed issue with display and load of nested cards count value.

**Comment by dinesh2096** [comment]
QA Reference :

https://drive.google.com/file/d/1F3V8_RQSd7nxsxXjB3rhfsEPWCMitE-s/view?usp=drive_link
