### ISSUE TITLE
Voided answer concepts showing up in  longitudinal exports

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-webapp#1110]
**Describe the bug**
Currently coded answer concepts which have been removed from the coded concept still show up in App Designer. Also, these come as columns in the longitudinal exports.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a coded concept with A, B, C and D as answers to coded concept
2. Now, remove A as the answer to the coded concept
3. But when we search for concept A on App designer, It will still show as answer to the coded concept
4. Also, when longitudinal export is downloaded for the form containing above coded concept(with multiselect) as field, the voided A answer will still come as a column

### Fix proposed for the related ticket: https://avni.freshdesk.com/a/tickets/3371
```
delete from concept where id in (68348, 68252,68255,68438,68441,68461,68553,68585);
delete from concept_answer where answer_concept_id in (68348, 68252,68255,68438,68441,68461,68553,68585);

```
- Since the voided answer concepts still need to show in the longitudinal export since the older observations of encounters could have them as answers selected, the issue cant be fixed in longitudinal export functionality
- So we can delete the concepts for them, since they are not used as answers in any of the observations .

### Out of scope:
showing up in App designer will be dealt separately as part of: https://github.com/avniproject/avni-webapp/issues/1113

**Comment by vinayvenu** [comment]
@mahalakshme @nupoorkhandelwal While voided concepts in App Designer should be removed, I am not sure about longitudinal reports because there is a chance of having observations for the voided concept when it was still not voided

**Comment by vinayvenu** [comment]
@mahalakshme pushing this back to "In analysis since we need a discussion to take this forward".

**Comment by mahalakshme** [comment]
@vinayvenu I discussed with @petmongrels  and he mentioned we can go forward with the execution of queries instead of APIs or supporting it as a feature - since API ll not be useful for any other purpose, and we dont support hard-delete from a feature perspective in our product.

**Comment by petmongrels** [comment]
verified.
https://github.com/avniproject/data-fixes/blob/a73b4d91a184bf9104ae64d2a334349655fd1144/yenepoya/delete-unused-concept-answers.sql

**Comment by petmongrels** [comment]
deployed

**Comment by arjunk** [comment]
@vinayvenu This is where the difference of void and retire will come. void = i am deleting. retire = i am not more using it.

**Comment by vinayvenu** [comment]
@arjunk there is an "active" field for exactly this purpose.  Unfortunately we don't really use it anywhere at this point.
