### ISSUE TITLE
User subject assignment and unassignment slow

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1123]
https://avni.freshdesk.com/a/tickets/3263

### Issue:
Assignment and unassignment of individuals to users, taking around 20 secs.

<img width="1503" alt="Screenshot 2024-01-30 at 4 08 38 PM" src="https://github.com/avniproject/avni-webapp/assets/10369963/2c2e635c-0ce5-45db-8422-a6f32c5a3348">

Without understading this, the user tries to click the checkbox to assign repeatedly and faces 'Constraint Violation' issues.

### Analysis:
Looks like as part of [this](https://github.com/avniproject/avni-server/issues/663) card, this slowness issue has got introduced. Before when there was just assigning to groups I don't remember seeing this slowness issue.

### Acceptance criteria:
The assignment and unassignment should take less than one sec ideally. Optimise how muchever possible.

**Comment by petmongrels** [comment]
### QA
- can be tested on pre-release by deploying 7.0 (merged the change to 7.0), we don't have env for 6.1 to test
- post QA need to tag and deploy to prod

**Comment by mahalakshme** [comment]
@achala did you test sync functionality with direct assignment as well?
