### ISSUE TITLE
Dont provide option to set colors for standard report cards since they are hardcoded

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1124]
### AC:
In the webapp, dont provide option to select color when standard report card type is selected

<img width="1512" alt="Screenshot 2024-06-06 at 5 33 24 PM" src="https://github.com/avniproject/avni-webapp/assets/10369963/7a1f4da4-ee48-433c-a924-77845438edf5">

This is to avoid confusion, since standard report cards comes with its own colors set.

**Comment by ombhardwajj** [comment]
Hey @mahalakshme , @vinayvenu  I've fixed this issue and henceforth submitted a PR.
