### ISSUE TITLE
Not able to see the exact status of ETL enable /disable

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-webapp#1125]
**Describe the bug**
when I am login with admin user and check Active analytics data sync for org it not showing anything and also when I open show it is not showing it.

 
**To Reproduce**

1. login as admin user
2. go to the organisation’s  tab
3. see the analytic table
5. See error

**Expected behavior**
Able to see the clear status of analytic 

<img width="466" alt="analytic " src="https://github.com/avniproject/avni-webapp/assets/104890488/225c7c82-0c2a-446c-9fce-a5ce78ec40c2">
example users, environment detail, username against which this issue is happening.

### Analysis:
The issue seems to be that ETL is not running in prerelease-integration machine. Looks like it has stopped running from the time 5th Feb on which prerelease setup for bugbash was done. On trying to restart ETL service it failed:

```
ubuntu@ip-172-1-2-108:/var/log/avni-etl-service$ sudo systemctl status avni-etl-service_appserver.service
× avni-etl-service_appserver.service - Avni ETL server
     Loaded: loaded (/lib/systemd/system/avni-etl-service_appserver.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2024-02-07 11:39:13 UTC; 52s ago
    Process: 1054879 ExecStart=/opt/avni-etl-service/start.sh (code=exited, status=1/FAILURE)
   Main PID: 1054879 (code=exited, status=1/FAILURE)
        CPU: 11.187s

Feb 07 11:39:13 ip-172-1-2-108 start.sh[1054880]:         at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.determineDialect(DialectFa>
Feb 07 11:39:13 ip-172-1-2-108 start.sh[1054880]:         at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.buildDialect(DialectFactor>
Feb 07 11:39:13 ip-172-1-2-108 start.sh[1054880]:         at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvi>
Feb 07 11:39:13 ip-172-1-2-108 start.sh[1054880]:         at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvi>
Feb 07 11:39:13 ip-172-1-2-108 start.sh[1054880]:         at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(Standar>
Feb 07 11:39:13 ip-172-1-2-108 start.sh[1054880]:         at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractService>
Feb 07 11:39:13 ip-172-1-2-108 start.sh[1054880]:         ... 39 common frames omitted
Feb 07 11:39:13 ip-172-1-2-108 systemd[1]: avni-etl-service_appserver.service: Main process exited, code=exited, status=1/FAILURE
Feb 07 11:39:13 ip-172-1-2-108 systemd[1]: avni-etl-service_appserver.service: Failed with result 'exit-code'.
Feb 07 11:39:13 ip-172-1-2-108 systemd[1]: avni-etl-service_appserver.service: Consumed 11.187s CPU time.
```

### Acceptance criteria:
- ETL on prerelease need to be fixed to carry out release-sign off testing
- Make sure the appropriate branch of ETL is deployed on prerelease
- Update readme [here](https://avni.readme.io/docs/setup-avni-pre-release-environment-on-aws-cloud#steps-specific-to-prerelease-env-setup-before-bugbash) if needed to prevent such issue happening again
- Make sure 'Active analytics data sync' column value displays after the fix.

**Comment by AchalaBelokar** [comment]
- [ ] it is reflected but I am changing the active analytics enable disable it is showing me 500 error code.

![Image](https://github.com/avniproject/avni-webapp/assets/104890488/0336e911-1ecb-44d7-8c9a-9591f523d2b7)

**Comment by 1t5j0y** [comment]
Issue seems to be due to DB slowness - the 500 was due to ETL already being enabled for the org.
Working fine after @himeshr upgraded prerelease db instance class. No other fix applied.

@mahalakshme / @vinayvenu noticed one thing that we might want to fix - the ETL `POST /job/status` API (called on the list of orgs webapp screen) checks for the existence of job for orgs while the `GET /job/<orguuid>` (called on the org specific screen) looks at whether there are any scheduled job run records for the org. This discrepancy shows a different status for an org on the list of all orgs (status: enabled) and the org specific screen (status: disabled) and the user ends up in a state where they are trying to enable ETL for an org which already has ETL enabled (but has not run yet).
