### ISSUE TITLE
Verify UI/UX features built with actual scenario

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1127]
### Need:
To make sure what we have built, fulfills the requirement for which we built it.

### Acceptance criteria:
- Create a nested card to display the top section of Profile dashboard as shown in this [slide](https://docs.google.com/presentation/d/16TG0zdI949mCqdXMb2ERUWNj50TDhyoJopOr0Q2LmXI/edit#slide=id.p3) on 
 -- As value for each card, show the (no of teachers observed in that quarter by the logged in user[determined by filledby value])/15) as the value.
 -- Divide the quarter as shown in the image into Jun-Jul, Aug-Sep, Oct-Dec, Jan-March
 -- On clicking the report card, it should take to the list of teachers observed in that quarter
 -- Ignore the nos with yellow background on left side.
- Create a nested report card as shown in [this](https://docs.google.com/presentation/d/16TG0zdI949mCqdXMb2ERUWNj50TDhyoJopOr0Q2LmXI/edit#slide=id.p6) slide for 'Overall Overview' dashboard. Currently they are separate report cards. I think it will be easier to handle if it is the  If value less than 1.5 than make the color red, else green.  Ignore the nos with yellow background on left side.
- In the Subject Summary rule, display 'Last Observed By - Username'
- Add the org name and login credentials for the above in this card, so that the same can be used for client demos.

**Comment by petmongrels** [comment]
One issue noticed with all report cards (not just nested card) is that when one adds to the section from the designer it shows up only after save is done.

**Comment by mahalakshme** [comment]
@petmongrels I ve updated the release to 7.1.0 as discussed in standup today.
