### ISSUE TITLE
[DEA] Multiselect media support

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1133]
### Current status:
- Currently in DEA only one media file(video/file/image) can be added at a time even when the media concept is multiselect.
Video for the issue:
https://github.com/avniproject/avni-webapp/assets/10369963/f7e2baaf-fde9-455e-89af-e1fff72957b9

### Acceptance criteria:
The below should work for Image concept, for video, move it to separate card, if it is difficult(retaining the current functionality). Just added all in the same card, thinking if it is just one day additional effort, then I suggest we can complete it.
- When the media concept is single select, it should work in the way currently it is working.
- when the media concept is multiselect, on clicking upload image/video again, additional files should get added. 
--- when editing a form with a multiselect media concept,
--- I should be able to add an additional image to the existing list of media
--- I should be able to remove one image from the existing list of media
--- I should be able to do both the above together
--- When saving the form, each change mentioned above is handled correctly
--- If I do not save the form, then changes do not persist
--- when creating a form with a multiselect media concept, all the above criteria is fulfilled
- Add the ability to be able to do multiple selection on single click of 'Upload image/video' 
- For viewing the uploaded files, refer the mockups below: The same mockups are applicable for Summary and Recommendations page as well as for viewing observations in DEA. Kindly also refer the design related AC in the violet sticky in the mockup. 
[media_viewing.pdf](https://github.com/avniproject/avni-webapp/files/14770465/media_viewing.pdf)

### Tech reasons:
- Continuing to support carousel for viewing media, is not needed, hence is removed. Also the [library](https://github.com/Ngineer101/react-image-video-lightbox) currently used for carousel is archived.

### Out of scope:
- Dealing with File concept([separate card](https://github.com/avniproject/avni-webapp/issues/1178)). Just make sure the current way of working is retained for file. 
- @mahalakshme Wont support RQG Media addition or display as part of this card, as it needs work on rqg edit page to complete #1137

### Test cases:
- SingleSelect and MultiSelect
- subject registration, program enrolment, program encounter and encounter
- Create and Edit(addition, deleting) flows
- Image and Video concepts
- Upload via mobile and view in DEA
- Upload via DEA and view in mobile

## Old: ignore
----- When multiple files uploaded from mobile, they are not visible in DEA. For them, Additional images uploaded(via DEA/mobile) should be visible, on clicking the right arrow in the carousel that appears when clicking 'View Media'. 
![Image](https://github.com/avniproject/avni-webapp/assets/10369963/5f2040e6-9c27-4995-a75e-2beb79c87c2d)
----- In the Profile tab, in View mode increase the height of carousel to triple that of current one. On clicking right arrow again here as well, users should be able to see consecutive images. And on clicking cross mark in top right currently unable to close the carousel, though it closes in Edit mode. This need to be fixed. 
<img width="1492" alt="Screenshot 2024-03-21 at 12 54 59 PM" src="https://github.com/avniproject/avni-webapp/assets/10369963/38cb1d3e-b9f1-4f4a-af5a-48078000c81c">
----- Remove the 'Open in New tab' option.
----- Carousel need to be applicable only for the media in that concept when clicked on View media. Currently it shows media across all concepts for that subject.
https://github.com/avniproject/avni-webapp/assets/10369963/7cdc3b85-f99b-471f-ae55-4d959ae4d0f4
- For video concept,
----- downloads in carousel when uploaded via DEA, works fine when uploaded via mobile app. This need to be fixed.

**Comment by vinayvenu** [comment]
@mahalakshme 
- There are a lot of issues mentioned here. This should be broken down into multiple cards each with its own acceptance criteria. This will help us focus on the core issues of each, discuss clearly in the card and test well


Suggesting detailed acceptance criteria to ensure testing does not miss flows. Example: 

Where 
- a form is used across subject registration, program enrolment, program encounter and encounter
- a media concept includes image, video and file concepts that are used in forms

- As a user,
  - when editing a form with a multiselect media concept, 
    - I should be able to add an additional image to the existing list of media
    - I should be able to remove one image from the existing list of media
    - I should be able to do both the above together
    - When saving the form, each change mentioned above is handled correctly
    - If I do not save the form, then changes do not persist
  - when creating a form with a multiselect media concept, all the above criteria is fulfilled
  - when creating a form with a singleselect media concept, existing behaviour is retained

### Testing notes
- Testing required for
  - SingleSelect and MultiSelect
  - subject registration, program enrolment, program encounter and encounter
  - Create and Edit flows
  - Image, Video and file concepts

**Comment by mahalakshme** [comment]
@vinayvenu I can add the test cases that you have mentioned and few more, but I mentioned everything in the same card, because everything is somewhat interrelated. Fixing for image would in itself fix for video - for carousel related issues

**Comment by himeshr** [comment]
https://prerelease.avniproject.org/#/app/editSubject?uuid=4efeb844-d49f-42e0-b399-b85597b94fcf&type=curator
Organisation: Artist

https://github.com/avniproject/avni-webapp/assets/72493481/a25f3dc0-4bdd-4f99-9664-1a76fd033665

**Comment by himeshr** [comment]
## Create / edit form test cases for Image and Video type formElements


- Multi-select image allowed
- Show Thumbnails on selecting single image
- Show Thumbnails on selecting multiple image
- Allow preview of images
- Thumbnail refresh on selecting single videos
- Thumbnail refresh on selecting multiple videos
- When the media concept is single select, it should work in the way currently it is working.
- when the media concept is multiselect, on clicking upload image/video again, additional files should get added.
- when editing a form with a multiselect media concept,
--- I should be able to add one or more additional images to the existing list of media
--- I should be able to remove one or more images from the existing list of media
--- I should be able to do both the above together
--- When saving the form, each change mentioned above is handled correctly
--- If I do not save the form, then changes do not persist
- Retain checks on media type
- Retain type and size check on Files(docx, pdf, etc)
- Behaviour is unchanged for Audio and file formElements
- Allow preview of video

**Comment by himeshr** [comment]
## In Observations View sections (Summary, etc..):
- Remove Caraousel
- On click open in new tab
- On click of view-media, open pane and show thumbnails of media (200 * 200 pixels)
- Show hand icon on hover over image, on-click of media open in new tab
- ~Max 3 thumbnails in a row,~ Responsive and fit
- Show in collapsible pane
- On clicking Up-arrow collpase and show just "View Media" Underlined link
- Use same theme color and style as used for other icons and buttons
- Support media elements within QuestionGroup 
- Wont support RQG Media as part of this card, needs work on edit page to complete

### Known behaviour:
- Can't Fix repeated loads of observations summary page, happens due to refreshOfSignedURLs every 110 seconds

https://github.com/avniproject/avni-webapp/assets/72493481/43296499-ff37-4bf0-8316-a5a9b65bce0a

<img width="1840" alt="Screenshot 2024-04-05 at 2 41 00 PM" src="https://github.com/avniproject/avni-webapp/assets/72493481/57bbd0de-a144-4234-8345-cb32e9e59a15">

**Comment by AchalaBelokar** [comment]
- [ ] In the mobile app we can add image one by one means suppose we add one image after adding 1st image then only we can add 2nd image . after click on add button is gray out. 

https://github.com/avniproject/avni-webapp/assets/104890488/e8fc5570-1985-4e71-a65a-d4fcc5cdbb5d



https://github.com/avniproject/avni-webapp/assets/104890488/8635bc76-2719-4e37-824d-8c6ef2ab4198

**Comment by himeshr** [comment]
> * [ ]  In the mobile app we can add image one by one means suppose we add one image after adding 1st image then only we can add 2nd image . after click on add button is gray out.
> 
>  az_recorder_20240430_151610.mp4 
>  Screen.Recording.2024-04-30.at.3.18.40.PM.mov
Yes, we'll need to correct this behaviour.

**Comment by AchalaBelokar** [comment]
- [ ] created a individual which is having the muti select  image is displaying like the requirement but after clicking on one image I am not able to go to next image there is no arrow.
- [ ] After edit the subject type multi select image  is not working
[Screen Recording 2024-04-30 at 8.45.18 PM.mov.zip](https://github.com/avniproject/avni-webapp/files/15167016/Screen.Recording.2024-04-30.at.8.45.18.PM.mov.zip)
- [ ] This is happen with multi-select image In the mobile app we can add image one by one means suppose we add one image after adding 1st image then only we can add 2nd image . after click on add button is gray out.

**Comment by himeshr** [comment]
> * created a individual which is having the muti select  image is displaying like the requirement but after clicking on one image I am not able to go to next image there is no arrow.

- This is expected, we had a discussion, after which, we decided to do away with Caraousel in Summary page for Media elements
- `After edit the subject type multi select image is not working` : Works for me as shown in demo
- Media select behaviour is different in DEA from Client. In DEA, we use single button to add single / mutiple images.

**Comment by himeshr** [comment]
@mahalakshme and @vinayvenu
 How should we handle invalid Media URLs of follwoing types in DEA Create/edit flow:
	- media observation has only uuid values (happens incase client failed to perform successful media upload after syncing entity)
	- media s3 url is invalid,(happens when webapp upload of video wasn't stored correctly?)
	
In the view, flow we show a Placeholder error text stating, SignedUrl not found for the observation value.

**Comment by mahalakshme** [comment]
@himeshr we can show similar red toast message stating `Unable to fetch media.` But the rest of the information like images need to continue to show. Let me know if you think this needs to be moved to a separate card. This message(SignedUrl not found for the observation value.) can also be changed to `Unable to fetch media` if it is not much work, else its okay.

**Comment by himeshr** [comment]
## Sample screenshots

DEA Summary page:
<img width="1840" alt="Screenshot 2024-05-06 at 2 02 12 PM" src="https://github.com/avniproject/avni-webapp/assets/72493481/68f7721f-0901-445e-8904-c9f85579c2f8">

DEA Form Create / Edit page:
<img width="1840" alt="Screenshot 2024-05-06 at 2 02 53 PM" src="https://github.com/avniproject/avni-webapp/assets/72493481/c70cb222-39b8-4d1e-8e8b-f6087cde6dd5">

**Comment by himeshr** [comment]
Only code review commits made since card was moved to "QA Failed" lane.

**Comment by AchalaBelokar** [comment]
- [ ] If Image or video is larger than normal size clear message should be visible but currently this message is showing
<img width="686" alt="error" src="https://github.com/avniproject/avni-webapp/assets/104890488/147e6c91-6f50-4b27-8f25-c11519efac5b">

**Comment by himeshr** [comment]
@AchalaBelokar i have fixed this issue _"If Image or video is larger than normal size clear message should be visible"_
Please resume testing on webapp and Client

**Comment by AchalaBelokar** [comment]
@himeshr tested on web app with max size upload is showed

**Comment by himeshr** [comment]
Staging test screenshot after cherry-pick to 9.0 branch:
<img width="1840" alt="Screenshot 2024-06-03 at 1 43 09 PM" src="https://github.com/avniproject/avni-webapp/assets/72493481/4eea50b1-e327-4125-8c3f-db7c4ad01095">
