### ISSUE TITLE
[DEA] Add support to input values for question group - repeatable and non-repeatable

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1137]
### Need:
Sometimes admins want to edit some data entered by other users. And since admins are using master catchment, using mobile app to do the same via sync will be more time consuming. Hence they prefer to do it via DEA. Currently this is not possible for organisations whose forms use question group(repeatable or non-repeatable) since currently DEA doesn't support input for question group concepts(repeatable or non-repeatable).

### Acceptance criteria:
- Being able to take input for concepts within question group(QG).
- For RQG, Ability to add more groups using + add button.
- For RQG, Ability to remove groups using the - button. 
- For RQG, When the 'Disable addition or removal' is enabled, + and - buttons should not be displayed.
- Being able to edit for all the above scenarios
- In Summary and Recommendations page as well, observations need to display page wise supporting RQG. The UI design part, will already be done as part of [this](https://github.com/avniproject/avni-webapp/issues/759) card. I think we just need to use the same component to display observations here if not done.

### Mockups:
1. In mobile app currently, we are changing the UI based on the data types of the form elements within the question group. Lets say them as Linear type and Box type. Unlike two different ways in mobile app, in DEA we can just have one way - linear type without using the box type considering webapp will be used on a larger display.

_Linear type when coded data type present:_
<img width="446" alt="Screenshot 2024-02-16 at 2 13 29 PM" src="https://github.com/avniproject/avni-webapp/assets/10369963/e162f57a-8be7-46b3-b8ff-b62a3cc14556">

_Box type when coded data type not present:_
<img width="442" alt="Screenshot 2024-02-16 at 2 12 41 PM" src="https://github.com/avniproject/avni-webapp/assets/10369963/57986d80-047c-4ccc-ab4f-7a4bab02dc6f">

2. For RQG, Video and mockups regarding when to enable and disable + and - buttons. Also note that we need to display the question group concept name.
Video link: https://github.com/avniproject/avni-webapp/assets/10369963/adb96697-f886-412b-947e-f98077bc175a
![Image](https://github.com/avniproject/avni-webapp/assets/10369963/61060b02-637d-484b-b746-684b66c4616b)

3. For RQG, When 'manual addition and removal' disabled, + and - icons should not be displayed like in the mobile:
<img width="1193" alt="Screenshot 2024-02-16 at 2 59 17 PM" src="https://github.com/avniproject/avni-webapp/assets/10369963/23736f56-be06-46a5-841a-6542cd9737fb">

4. Also For  question group which is not repeatable, + and - icons should not be displayed like in mobile:
![Image](https://github.com/avniproject/avni-webapp/assets/10369963/4f5b62b1-1af1-4adf-bc1c-beacbbff8b26)

5. Summary and Recommendations page current reality(left) Vs expectation(mobile)
![Image](https://github.com/avniproject/avni-webapp/assets/10369963/e58f8160-0843-48e8-a416-846d5f7cd7c6)

### Out of scope:
- Form element, form element group rules, decision rule and visit schedule rules(currently supported in DEA) need to execute as expected on form elements within RQG and QG
- Supporting subject concept type within RQG

### Suggestions:
- we can potentially move decision and visit schedule rules as a different card 
- subject support - sync concept values - confirm - based on minor/major - validation 
- sync concept value - drop down/radio group - webapp?
- can be supported - DEA complementary to mobile

**Comment by petmongrels** [comment]
- For testing, it may be better to wait for the rules stories to complete as well - since they are not working correctly. I tested by disabling FormElementStatus rules. Without rules working doing QA on existing implementations may be misleading.

**Comment by mahalakshme** [comment]
@petmongrels @AchalaBelokar just mentioning whatever discussed in standup:
- I am creating cards adhering to INVEST principles, such that every card can be independently tested. From that perspective, @AchalaBelokar you can make sure cases around the ACs mentioned, works as expected.  I am also hoping you are aware where what rules are employed. So I don't think testing this card should be a problem.

**Comment by himeshr** [comment]
@petmongrels While working on #1171, i found that, encounter form, RepeatableQuestionGroup support does not work as expected for Goonj DispatchReceipt. 

We'll have to pair on this again, before i can resume the Rules evaluation.
