### ISSUE TITLE
Add support for validFormat in form

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-webapp#114]
As an implementer I should be able to add a validation to a numeric and text form element. E.g. A pincode in India must be 6 digits, aadhar card must be 12 digits. I should get an error message in the app if I fill invalid value in these fields.

#### Acceptance Criteria

- For form elements with concept of type numeric and text, I should be able to add validation regex.

**Comment by garimadosar5** [comment]
QA Notes - 
- Giving this error
![Screen Shot 2019-12-03 at 1.36.21 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/3433db59-6be5-4732-806b-dcf6003e67c8)

**Comment by hithacker** [comment]
@garimadosar5 Fixed this. Now there is a validation that both fields(regex and description key) either have to be filled or both have to be empty.
