### ISSUE TITLE
Hardcoded reporting urls in home page

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#1140]
The reporting urls are right now hardcoded to the Avni cloud website, and this is a problem when Avni is deployed elsewhere. 

### Acceptance criteria
- It should be possible to change the reporting urls through a server configuration so that when the webapp is deployed and configured in an environment, then it shows the corresponding reporting urls
- We now have three reporting urls that can be configured per environment. Some environments only have one reporting environment. Some have none. We should be able to set up the title and url on these reporting urls. Each reporting url that is configured will show up on the login screen

### Tech design (avni-server)
- Sample configuration in application.properties
```
avni.reporting.url[0]=Metabase,https://reporting.avniproject.org
avni.reporting.url[0]=Jasper Reports,https://reporting-jasper.avniproject.org
```
- Url /config that returns
```
{
  "reportingSystems: [
    {
      "name": "Metabase",
      "url": "https://reporting.avniproject.org"
    },
    {
      "name": "Jasper Reports",
      "url": "https://reporting-jasper.avniproject.org"
    },
  ]
}
```

**Comment by vedfordev** [comment]
@vinayvenu  Does it require changes in avni-server code?

**Comment by vedfordev** [comment]
@vinayvenu Created below pull requests please check it.
**avni-server:** https://github.com/avniproject/avni-server/pull/698
**avni-webapp:** https://github.com/avniproject/avni-webapp/pull/1151

**Comment by petmongrels** [comment]
Looks good. Couple of points.

Web app
You can use httpClient.getData instead of fetch
Try to keep all the code within useEffect instead of calling a function and passing a function in that function
Server
Explore how the properties will be over-ridden in a different environment using environment variables like it has it for other properties.
@vedfordev

**Comment by petmongrels** [comment]
one comment on web-app commit @vedfordev

**Comment by vedfordev** [comment]
@petmongrels removed function.

**Comment by petmongrels** [comment]
good to merge now to master

**Comment by vedfordev** [comment]
@petmongrels changed the code suggested by you. Can u please check it and merge it?
