### ISSUE TITLE
Unable to see sync concept if it is not coded concept

### ISSUE THREAD

**Issue by vedfordev** [avniproject/avni-webapp#1145]
**Describe the bug**
we made changes to show sync attribute values which was earlier shows as uuids. but currently for non coded concept it is not showing the value as screenshot

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to goonj organization
2. Open user who has sync attribute
3. See the user

**Expected behaviour**
Handle scenario for both coded and not coded sync attribute value.

**Screenshots**
<img width="1235" alt="Screenshot 2024-02-29 at 11 47 09 AM" src="https://github.com/avniproject/avni-webapp/assets/106894932/152bfbcd-d2f9-41dc-894c-9497f8d5f9f1">

**Comment by mahalakshme** [comment]
already a card is there for this

**Comment by mahalakshme** [comment]
https://github.com/avniproject/avni-webapp/issues/1141

**Comment by vedfordev** [comment]
@himeshr / @vinayvenu  raised pull request please check once.

**Comment by himeshr** [comment]
## Test Cases
- Users without sync concept value config
- Users with coded sync concept value config (APFOdisha Users)
- Users with Text sync concept value config (Goonj users)

**Comment by AchalaBelokar** [comment]
- [ ] Tried with goonj organisation on prerelease the sync attribute concept is not coming there it is visible same in the screen shot

**Comment by vedfordev** [comment]
@AchalaBelokar changes are not approved. Now I approved to staging. Moving card back to qa ready. check in staging.

**Comment by AchalaBelokar** [comment]
- [ ] tested with goonj revamp the value is visible there
- [ ] tested on rwbniti it is working fine there

**Comment by mahalakshme** [comment]
@AchalaBelokar add the testcases related to other concept types that u mentioned already tested.

**Comment by AchalaBelokar** [comment]
- [ ] I tested on prerelease now using the nupoork@goonj  and edit the user with sync value it is showing me only Sync Attribute 1 not showing the exact value of sync attributes 

![Image](https://github.com/avniproject/avni-webapp/assets/104890488/c359c435-5233-41b1-922d-cb1aa75ec69a)

**Comment by mahalakshme** [comment]
@AchalaBelokar you have not yet added the test cases that u mentioned
