### ISSUE TITLE
Ability for admin to create custom filter configuration

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#116]
As an organisation admin, I should be able to create custom filters for all kinds of configuration specified in the [Custom filters on Search and MyDashboard](https://app.zenhub.com/workspaces/avni-5cf8e458bf08585333fd64ac/issues/openchs/openchs-product/1076) epic. 

## Acceptance Criteria
- When opening the [filters](https://staging.openchs.org/#/admin/filters) screen, it contains a  "Name" field and a "Type" dropdown that consists of the following fields
  1. Concept
  2. Registration Date
  3. Enrolment Date
  4. Encounter Date
  5. Name
  6. Age
  7. Gender
  8. Address
- When choosing anything other than "Concept", the save button is enabled. 
- When choosing "Concept", options to enter the concept, subject type and search scope are provided. 
- When choosing concept, only the concept is the mandatory field (existing)
- When choosing concept, only registration and enrolment concepts are shown in the autocomplete (existing)
- Save works in both My Dashboard Filters and Search Filters
- There is a widget selection option based on the field selected. These options will be provided as follows

Date
- Single Date
- Date Range
- Relative Date [Today, Yesterday, Last 24 hours, Last 7 days, Last 30 days, Last 90 days]

Numeric
- Single Value
- Relative Value [Below Low Normal, Above High Normal, Normal, All Abnormal]

Time
- Single Value
- Time Range

Others
- None. Default widget will be used

- Data will be saved as per format provided in the [epic](https://app.zenhub.com/workspaces/avni-5cf8e458bf08585333fd64ac/issues/openchs/openchs-product/1076). 

### Reference (existing screen)
![image.png](https://images.zenhubusercontent.com/5d0b1ec92fff8629577fc2ef/13ed2be8-3f9c-4a8c-a4b4-e995b69ad2bb)

**Comment by garimadosar5** [comment]
> mkk;
