### ISSUE TITLE
Not able to upload on csv on prerelease

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-webapp#1162]
**Describe the bug**
Not able to upload on csv on prerelease
I am tried csv on prerelease and  prod it was working fine on prod but on prerelease it is giving me error
these are the csv we are using

[indiviual.csv](https://github.com/avniproject/avni-webapp/files/14567217/indiviual.csv)
[errors-errors-sample-Subject---Individual.csv](https://github.com/avniproject/avni-webapp/files/14567218/errors-errors-sample-Subject---Individual.csv)

**To Reproduce**

1. Login with dinesh@jss_uat
2. Click on admin
3. upload csv of individual registration 
4. after uploading csv we got the error

**Expected behavior**
We are able the upload the csv

**Comment by mahalakshme** [comment]
@AchalaBelokar in which org in prod u tried? I checked in JSS UAT NEW and archived, these locations are not there.

**Comment by AchalaBelokar** [comment]
- [x] uploaded csv for subject type which is working fine
