### ISSUE TITLE
Should not be able to create a catchment with space

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1168]
### Need:
Currently when we see the values of user's catchment in db or UI, when they are assigned a catchment with name with just    ' '  (space), its difficult to understand whether the user is assigned catchment or not.

![Image](https://github.com/avniproject/avni-webapp/assets/10369963/5408db00-ad01-4c0d-a356-cddea3ff658f)

Video recording for the issue: 

https://github.com/avniproject/avni-webapp/assets/10369963/13fc9711-8f93-455c-bfb1-63bf62d0f3bb

### Acceptance criteria:
Like we show error when catchment name already exists like in below image, similarly show error with text 'Catchment name should contain atleast one non-whitespace character'
<img width="1512" alt="Screenshot 2024-03-20 at 6 40 38 PM" src="https://github.com/avniproject/avni-webapp/assets/10369963/5237909c-5ba8-4d23-9ffd-d11ac60b7085">

**Comment by ombhardwajj** [comment]
Hey @mahalakshme , I've fixed this issue and henceforth submitted a PR.

**Comment by AchalaBelokar** [comment]
- [x] Tried with the only space it is working as expected 

- [x] Tried with space with alphabet 
- [x]  Tried with special char
