### ISSUE TITLE
Added dashboard card need to display in the list

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1169]
### Acceptance criteria:
On clicking Add, the added dashboard card need to appear in the list. Currently the user experience is confusing.

https://github.com/avniproject/avni-webapp/assets/10369963/1960bc8b-a924-4ea4-91c7-d2885dd78ac4

**Comment by petmongrels** [comment]
fixed in a diff card. no commits.

**Comment by AchalaBelokar** [comment]
@Achala for the dashboard card, section, filter etc stories, please also test by syncing to the mobile app and checking the behavior.

**Comment by AchalaBelokar** [comment]
- [ ] tested weather it is appearing or not 
- [ ] also check import bundle
