### ISSUE TITLE
[DEA] Rules execution support for RQG 

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1171]
### As is:
- Already rules server supports RQG 
- So programSummary, subjectSummary, decision rule, messageRule etc., would already work in DEA
- Form element  and group rules executes in webapp itself, since it deals with minimum set of info

### AC:
1. The below rules(mentioned in 4th point) should work when used in form element rule and form element group rule across forms(subject registeration, cancel, program/general encounter, enrolment) with different entities like individual, program, encounter.
2. Also need to work with repeatable question group/non-repeatable based on what is applicable
3. Make sure the below works when childConcept is text concept type
4. Need to check the above cases for below rules(where applicable) and make sure it returns the right value as in mobile app. The idea is if we support for the below, probably others also would work, but making it work if it doesn't is not within the scope of this card. If you identify any, add it as a comment.
      - rules-config: methods like ```questionGroupValueIn{Entity like Registeration, Encounter,..}("child-concept-uuid", "parent-concept-uuid", params.questionGroupIndex)``` followed by ```defined```  - for RQG
    - some of the model functions: 
             ---- ```{entity}.findGroupedObservation(parentConceptNameOrUuid)``` - for QG & RQG
             ---- ```{entity}.getObservationReadableValue(childConceptUuid, parentConceptNameOrUuid)``` - for QG

### Technical details:
 - looks like need to pass questionGroupIndex in params
 - looks like need to map the entity with RQG/QG observations to the model object to be able to call model functions. This was already done for rules-server [here](https://github.com/avniproject/avni-models/issues/43) - to execute glific rules(which accesses value from RQG) - See if such mapping logic can be extracted to separate library

### Analyst notes - Ignore:
- Already rules server supports RQG Moved to rules-server - So programSummary, subjectSummary, decision rule, messageRule etc., would already work in DEA - whenever more needs to be queried from DB
- form element rule is executed in webapp itself - then how for CSV validated?
- When we support RQG via CSV upload - need to add this AC to add in rules-server also
- dot notation in rules-config for easiness, but not all cases can be predicted, so rest in models without dot notation

**Comment by mahalakshme** [comment]
@vinayvenu review this

**Comment by himeshr** [comment]
@mahalakshme and @vinayvenu Please note that there is an important caveat to make use of SubjectSelectFormElements in forms through webapp for Goonj orgs.
We currently be default use AttendanceFormElement implementation for SujectSelectFormElement, this does not work for non Group-Member subjectTypes. Therefore, for Goonj orgs, in the forms that use SubjectSelectFormElements, we would instead have to mark "Search option" flag to true. This "Search option" flag is not used in Avni-client and only used in Webapp, therefore the change would not have any impact for Goonj orgs.

**Comment by himeshr** [comment]
@vinayvenu and @mahalakshme , We have not implemented support in Webapp RulesEvaluationService to handle EntityContext and getCommonParams() as is the case in client.

**Comment by himeshr** [comment]
Sample Distribution Creation from Avni webapp Screen Recording is available [here](https://drive.google.com/file/d/1nWjI7MP8k_Dk49Y3ER3w9wKfT4qXGXnk/view?usp=sharing)

**Comment by himeshr** [comment]
@mahalakshme and @vinayvenu 
Rules Execution on rules server fails for Goonj org during creation of DispatchReceipt.

```
curl 'https://staging.avniproject.org/web/rules' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'content-type: application/json' \
  --data-raw '{"encounterRequestEntity":{"uuid":"4445fa75-942f-473c-8f02-7ba9e983b56a","encounterTypeUUID":"543c3eb6-fc01-4e3a-b3e1-ef50ec6a8896","observations":[{"conceptUUID":"78f9d6cb-356e-45dc-90d5-216185784fe6","value":"2024-04-17T18:30:00.000Z"},{"conceptUUID":"8c101325-b8f1-497e-87a2-f6cde31e0cf3","value":["d4d7519d-8247-464b-a136-c29147aeb34d","9e0f3a28-ca42-45e7-8d62-384d86ce8dd8"]},{"conceptUUID":"132868ab-811a-401e-9fd3-7c87f5512436","value":"DSH-01"},{"conceptUUID":"5dfb2f28-b866-4442-be01-0ed451c6aad9","value":[{"f25402e3-8d6c-4436-ba81-ad7b4f97131e":"6f6eb1de-88c4-4df2-a8ae-997a339a78c5","4d9a9cb8-1c7c-4d86-b7d7-f6a03a1d520b":2,"384789ec-1f69-4407-932c-9451d4e05a51":"Nos","44cd43e1-d2a7-46e4-92f3-1fcf3508f8aa":"DLIH-01","aaede45f-53ca-40dc-a349-feca810810f5":"mnh","71644765-6e55-4b8b-b01a-082e311bfa11":"40f13680-bc05-46ef-8223-e56cf20b8d0a","bf591bee-f3a5-4481-9b01-ab40ca01c8b4":0}]},{"conceptUUID":"e132e4fe-7c7a-4612-b086-426b9f74147b","value":"Remark"}],"encounterDateTime":"2024-04-26T12:01:57+05:30","name":"Dispatch receipt","cancelObservations":[],"individualUUID":"1e6cca73-f44c-4aa9-a57c-0c120a8e60b6"},"rule":{"formUuid":"57bb2d3a-f8a5-4405-8d2c-514456e91533","workFlowType":"Encounter"}}'
```

API response:
```
{
    "status": "failure",
    "error": {
        "message": "Cannot read property 'name' of undefined",
        "stack": "TypeError: Cannot read property 'name' of undefined\n    at Function.fromResource (/opt/rules-server/node_modules/openchs-models/dist/Concept.js:121:36)\n    at Function.constructConceptModel (/opt/rules-server/node_modules/openchs-models/dist/observation/QuestionGroup.js:63:38)\n    at _lodash.default.map (/opt/rules-server/node_modules/openchs-models/dist/observation/QuestionGroup.js:52:43)\n    at arrayMap (/opt/rules-server/node_modules/lodash/lodash.js:639:23)\n    at Function.map (/opt/rules-server/node_modules/lodash/lodash.js:9554:14)\n    at Function.fromObs (/opt/rules-server/node_modules/openchs-models/dist/observation/QuestionGroup.js:47:36)\n    at Concept.getValueWrapperFor (/opt/rules-server/node_modules/openchs-models/dist/Concept.js:247:129)\n    at mapObservation (/opt/rules-server/src/models/observationModel.js:74:56)\n    at /opt/rules-server/src/models/observationModel.js:12:20\n    at Array.map (<anonymous>)"
    },
    "decisions": {
        "enrolmentDecisions": [],
        "encounterDecisions": [],
        "registrationDecisions": [],
        "enrolmentObservations": [],
        "encounterObservations": [],
        "registrationObservations": []
    },
    "visitSchedules": [],
    "checklists": [],
    "summaries": [],
    "summaryObservations": []
}
```
