### ISSUE TITLE
[DEA] Issue with subject form element

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1173]
### Context:
From [this](https://app.zenhub.com/workspaces/avni-product-deprecated-635b73bded85e50018871ae6/issues/gh/avniproject/avni-webapp/474) and [this](https://app.zenhub.com/workspaces/avni-product-deprecated-635b73bded85e50018871ae6/issues/gh/avniproject/avni-webapp/670) cards, support for subject form element was already added in DEA.

### Issue:
env: staging
org: hello
Login username: AchalaB@hello
From [this](https://drive.google.com/file/d/1JVBLktbP2sCTuGKVYm7q3Uvv1u5KNbTi/view?usp=drive_link) video, you can see it breaks when 'Search option' enabled on a form element(with Subject concept type) for a Group subject type 

Also check with the above fix, being able to add a subject as value on Individual subject type will also get sorted. If not, this can be moved to separate card.
![Image](https://github.com/avniproject/avni-webapp/assets/10369963/d4896ca1-91dd-491d-b064-779bdbad5d55)

### Technical analysis:
- Issue seems to be in ```SubjectFormElement.js``` file linked in ```LandingSubjectFormElement.js```.
- The component ```AsyncSelect``` in ```SubjectFormElement.js``` file, is similar to the one used in ```GroupMembershipAddEdit.js``` where logic for adding members to a group resides.

**Comment by AchalaBelokar** [comment]
- [ ] I login with  AchalaB@hello and try to add try to register there it is showing me error Cannot read property level of undefined
- [x] and I tested with AchalaB@rwbmh which is working fine

**Comment by 1t5j0y** [comment]
Issue appears to be because 8.0 is deployed to staging and this is a fix in 9.0

**Comment by AchalaBelokar** [comment]
- [ ] still it is failing

**Comment by 1t5j0y** [comment]
This change is on webapp while the issue Achala is reporting is on client for a specific org.
Verified that change on webapp is working fine:


![Image](https://github.com/avniproject/avni-webapp/assets/54208632/e8285f36-cd2a-481f-ae9e-8ea3729ef70d)
