### ISSUE TITLE
[DEA] File concept issue

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1178]
### Issues:
env: staging, username: maha@apf_bnd_test, individual name: 'abc def'
- Currently in Data Entry app even when multiple files are uploaded from mobile app, you will be able to view only one file
https://drive.google.com/file/d/1Ig_k2W_L3PYUIdAVegg5RCaSkjlQIOA4/view?usp=drive_link

- Also unable to upload multiple files via Data Entry App unlike image concept
https://drive.google.com/file/d/1FH8nlbp5zxobXIUOBf7wBpcYNLvdrwFc/view?usp=drive_link

### AC:
- The above should work for both create, edit  and view flows as applicable
- When multiple files are there display multiple links - View File - for each file for user to click and open in new tab

**Comment by petmongrels** [comment]
- in fileOptions method, the check _.isNil(signedURL) should for empty array list
- not sure whether mediaDataList can be null or it will empty array. pls test once.

**Comment by vedfordev** [comment]
> * in fileOptions method, the check _.isNil(signedURL) should for empty array list
> * not sure whether mediaDataList can be null or it will empty array. pls test once.

changed _.isNill with _.isEmpty and other changes as well

**Comment by dinesh2096** [comment]
- [ ] When we upload the file greater the Kb we have mentioned we getting the error but it is saves as the error file and it is showing blank image.
- [ ] In the file if we upload the image can we have the preview now the behavior is only downloading the image

QA Video : 

[Click here to watch the video](https://drive.google.com/file/d/1sdBBlpkMa3d6px_3DXix-xccJcfHeGbv/view?usp=drive_link)

**Comment by dinesh2096** [comment]
Know issue : 

[Click here to see the issue](https://github.com/avniproject/avni-server/issues/832)
