### ISSUE TITLE
Allow users to change language

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-webapp#118]
### Motivation
As an data entry user I want to be able change the preferred language for the app so I can use the app in my preferred language.

### Acceptance Criteria
- Clicking on settings menu should show an option to choose each of the available languages in the organisation config.
- Clicking on a language radio button from Settings menu should change the language for the entire app. 
- If user do browser refresh our app should still show up in user's preferred language.
- If user logs out and logs in again using the same account then our app should show up in user's preferred language.

### Assumptions
- Existing keys will already be there in api response 

### Visual Design
Slide 10

### Tech Approach
- Call POST /v2/me api to save locale preference.
- Get user's current local pref from redux store
- React library like https://github.com/formatjs/react-intl or https://github.com/i18next/react-i18next can be used for internationalization in react apps.

**Comment by eshwarjoshiPsl** [comment]
1] On successful login

  I]   We will get default language from user info.
  II]  We will get translation data by calling translation API by providing default language.
  III] We will store default language and translation API response data in "Redux store".

2] On clicking on user profile

  I]   We will fetch all language by calling "webOrganizationConfig"  by providing organization ID.
  II]  On language change we will update default language using save API.
  III] On success  we will update default language and translation API data in "Redux store".
  IV] We will reload app global component /redirect current user to home page.

3] On logout

  I] We will destroy the "Redux store" and user will be redirected to login page.

5] We are using "I18n Next library"  to do  translation.

6] Require clarity on below point

  I]  Default language update API.
  II] Is  Avni Model approach require for translation API?
