### ISSUE TITLE
[DEA] Deleting enrolment and encounter

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/avni-webapp#1180]
https://avni.freshdesk.com/a/tickets/4546

**Describe the bug**
When a user tries to void an individual with active encounters, enrolments, and program_encounters, a big error pops up causing the user confusion.

**To Reproduce**

1. Register an individual, enroll it into a program, and try to have encounters planned as well.
2. Try to void the individual
3. You must see a big modal pop like the below screenshot.
![Image](https://github.com/avniproject/avni-webapp/assets/94247708/c2203d4e-16fa-49cf-9cb3-6beeea00629e)
4. Because of the stack trace the user panics and seeks out help from the support team.
A similar kind of error comes when there are active encounters and program_encounters present.

Issue link: https://drive.google.com/file/d/1PgWC0iuG-CUxuPnuJdo6J9uAiDaM2vE_/view?usp=drive_link

### As is:
- In DEA, an individual can't be deleted(voided) without voiding its encounters and program enrolments.
- There is no way to delete enrolment and encounter in mobile. Anyways it does help when a user has done something wrong. So lets keep it in DEA.
- In mobile when we void an individual, its encounters and enrolments are not voided, but feels like thats not correct, and need to be fixed.

### AC:
- Void an individual as well in DEA without voiding its enrolments and encounters like in mobile app and user should not be asked to void them as well
- So when clicking on DELETE on enrolment in DEA should void the enrolment alone without voiding its encounters.
- Allow voiding of enrolment and registration only if the beneficiary is in the sync zone of the user (catchment, attributes, etc) like in other places in DEA

### Analysis notes:
- Unable to find a reason to retain the current behaviour of voiding in DEA: [source card for this behavior](https://app.zenhub.com/workspaces/avni-product-deprecated-635b73bded85e50018871ae6/issues/gh/avniproject/avni-webapp/569)
- if we void all the related entities anyways for the existing data still history will be present and in users mobile data all data might not be present
- Which means need to do as a server BG job
- Even if done above, need to check for voided to make sure, so no advantage of voiding all the related entities.
- should else auto void  all related entities like group/household members, eligibility, etc., - if a individual has 1000 encounters - what 'll happen if user closes the app when it is happening, how long will it take?
- Also the above is simple - cases like same member should not be part of more than one group will come - in such cases voiding and unvoiding might need to deal with complex cases.

**Comment by mahalakshme** [comment]
@vinayvenu review the ```as is``` and ```to be``` above. Will change the headings, just wanted to check with you.

**Comment by Dinesh2019** [comment]
Test

**Comment by dinesh2096** [comment]
Suggestion can we have the error message as given below 

suggested one : Not in this user's catchment
Already existing in the system : notInThisUsersCatchment

**Comment by himeshr** [comment]
@dinesh2096 Getting the correct error now, might have been a missing / overwritten translations issue.
<img width="1840" alt="Screenshot 2024-10-22 at 5 41 26 PM" src="https://github.com/user-attachments/assets/0ba81bf9-dad4-4c4b-92be-a4791c4e5134">
