### ISSUE TITLE
UI is broken on offline dashboard DEA

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-webapp#1181]
**Describe the bug**
While creating a new offline dashboard, at couple of places, UI is broken. Sharing screenshot for the same. 

**To Reproduce**
This can be reproduce on any organisation on production enviorement

**Expected behavior**
UI should be properly displayed. Proper inline labels and overriding of the components.

**Screenshots**

![Image](https://github.com/avniproject/avni-webapp/assets/37863085/d3a4ad16-a5fd-44bb-aa5a-b1b0de091dc3)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Developer Checklist**(Developer fixing the bug should fill this checklist)
- Does the fix require extensive regression testing?
  - [ ] Yes
  - [ ] No
- Are you mentioning the required scenarios that could be affected?
  - [ ] Yes
  - [ ] No

**Comment by AchalaBelokar** [comment]
- [ ] @sachsk This changes is not reflected on staging I deployed latest server and web app still it is not visible

**Comment by sachsk** [comment]
@AchalaBelokar please ask someone from Prod team to merge [this](https://github.com/avniproject/avni-webapp/pull/1287) pull request then deploy app to staging and test
