### ISSUE TITLE
User subject type creation

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1189]
As an implementor, I should be able to associate an encounter or a program to a user.

### Acceptance criteria:
- Implementor should be able to create a subject type of type User
- When no form is selected, in the empty form that will get created, do not have any default form elements like Person
- When associating subject types to encounters or programs, User subject type should also display
- Enable 'Allow empty location' - should be able to disable to User subject type
- Under sync settings - Just display 'Determined based on subject type' - not editable. Sync settings should not be editable
- On saving the form, subjects for each User need to be inserted into db
- name of the user can be inserted as firstName in individual table for now.
- When the number of users exceeds 50, show a warning message after saving stating 'To be able to successfully create this subject type, do bundle upload'
- Should not be able to change the Type of subject type after creation.
- When a user is created, and when subject type User exists as non-voided, then create subject for that user. Similarly for creating users via CSV upload.
- registeration_date in individual table will be same as created_date_time. 

### Acceptance criteria:
- Subject type creation:
- 
    - When org created, create User subject type
    - Enable 'Allow empty location' - unable to disable
    - Under sync settings - Just display 'Determined based on subject type' - not editable
    - Being able to not associate form 
   <img width="960" alt="Screenshot 2024-04-01 at 8 11 53 PM" src="https://github.com/avniproject/avni-product/assets/10369963/0e60a8ab-6128-4317-b6b4-70919b847a34">

- When a user created from Admin tab, create subject for that user in individual table
- When a user created via CSV, create subject for that user in individual table
- Migration for existing organisations

### Technical details:
- subject id in users table - many to many
- different table than user_subject_assignment - so that it doesn't show up in the 'user assignment', etc.,

### Inputs:
- When to create subjects for users:
      - User subject type if predefined in org - need to handle many cases, will affect stability of the app
      - so when Creating user subject type - Synchronous inserting of users 
              - Show an error - exception - when more than a particular no of users(1) exist - no risk, bundle upload - lets build iteratively
              - Bundle upload handle this
      - Separate platform and product epic - usability vs - evaluate independently
      - creating subjects for all users - antithetical - cons: migration(all orgs - uuid), all orgs, backward compatibility
      - My concerns: Not intuitive that need to be solved by bundle upload, registeration_date
                    - bundle upload - we are not exporting users
                    - backward compatibility - can alter the existing API
- Form - associate
      -  associate empty form always - if form mappings dont exist - will affect stability
      - make the the subject type immutable
      - when no form elements associated with form do not display in Register and 'Registeration Details'
      - My concerns: The [meaning](https://app.zenhub.com/workspaces/avni-product-deprecated-635b73bded85e50018871ae6/issues/gh/avniproject/avni-client/657) of immutable is different when it comes to encounter types. Introducing new terminology and meaning not intuitive.

### Out of scope:
- Concepts of subject resgisteration form can be mentioned in CSV

**Comment by petmongrels** [comment]
### Refactoring tasks
- transaction management of endpoints that launch jobs
- Rename bgJobLauncher and BatchConfiguration classes as these are generic names and there other jobs also

**Comment by petmongrels** [comment]
### Functional notes
- When subject type is created the background job is launched so no need to show error message for > 50 users

**Comment by AchalaBelokar** [comment]
- [ ] created user which doesn’t have any image  we need to check that.
- [ ] and there is mandatory filed on first  page are showing wrong on client app.

![Image](https://github.com/avniproject/avni-webapp/assets/104890488/0db637d1-5649-4a6d-b1cb-10f660d3160f)


![Image](https://github.com/avniproject/avni-webapp/assets/104890488/ec648154-f857-4196-93a9-0db62fc06d27)

**Comment by mahalakshme** [comment]
@AchalaBelokar please update the above cases based on the discussion we had 
- icon is not an issue 
- only Edit in app designer is a issue
- mobile app related issues if any exists can be raised in the respective card, and not this card

**Comment by AchalaBelokar** [comment]
- [ ] Edit screen is not showing all the value
