### ISSUE TITLE
not able to see the data in data entry app

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-webapp#1196]
**Describe the bug**
Not able to see the data in data entry app on prerelease 
I login with AchalaB@rwbnitiuat and go to the data entry app
showing this error there was a problem  when loading this page .Please contact administrator 
**To Reproduce**

1.Login with AchalaB@rwbnitiuat
2. Click on data entry app 
3. see the error 
5. See error
<img width="737" alt="d error" src="https://github.com/avniproject/avni-webapp/assets/104890488/72b7b4ae-147d-4de4-ad35-1ce72c441a65">

**Expected behavior**
user should  see the data 

### Analysis:
Looks like prerelease is trying to access prod bucket for icon: - But need to fix for the QA to be able to test.
<img width="1504" alt="Screenshot 2024-04-15 at 4 15 43 PM" src="https://github.com/avniproject/avni-webapp/assets/10369963/91c13dd8-260f-4ab4-96ac-d8ad391c5c8e">

**Comment by mahalakshme** [comment]
@AchalaBelokar was this org imported by bundle import, or was it present already?

**Comment by mahalakshme** [comment]
achala replied already present in prerelease - so not a bundle import issue.

**Comment by 1t5j0y** [comment]
@AchalaBelokar should be fixed after prerelease db was setup again yesterday. Could you retest?
