### ISSUE TITLE
Incorrect snackbar color when profile picture URL incorrect

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1199]
### Steps to reproduce:
- Add a profile picture for an individual
- In the db remove 'https://' from the profile picture
- Open the individual in data entry app.

### AC:
Update the toast color to red thats already used for error scenarios in our code base.

<img width="1512" alt="Screenshot 2024-04-17 at 12 21 17 PM" src="https://github.com/avniproject/avni-webapp/assets/10369963/d88e4d93-c3a9-4dc4-9434-a796bdb74742">

**Comment by ombhardwajj** [comment]
@mahalakshme , I have fixed this issue and created a PR! Please have a look!

**Comment by replyre** [comment]
hello :) 
Is this issue open?

**Comment by vinayvenu** [comment]
@replyre no. There has already been a merge against this issue. It will be closed once QA is done.

**Comment by replyre** [comment]
ok, do let me know if there tasks in which I can help :)
