### ISSUE TITLE
Error on trying to open an individual

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/avni-webapp#1200]
**Describe the bug**
After uploading the profile image from the client, and trying to open the individual from Webapp, it gives an error.

**To Reproduce**

1. Enable the "Allow Profile Picture" toggle on the subject_type's advanced settings.
2. Using the client, register that subject type and upload the profile picture for that type.
3. Try opening that subject on the web app and it should give you the error.

**Expected behavior**
It shouldn't give you an error and the individual with it's profile picture should open up.

Attaching the SS of the error

![Image](https://github.com/avniproject/avni-webapp/assets/94247708/1efbc3ba-d3ca-4041-824d-ad7947deaac6)

Below attached is the SS of the individual with profile picture.

![Image](https://github.com/avniproject/avni-webapp/assets/94247708/af20441c-420a-411b-a2de-bb776b9035ae)

**Comment by mahalakshme** [comment]
I tried the same scenrio mentioned here in prerelease in iph_ctrith_uat but unable to reproduce the issue.
name of individuals - aaa, bbb, ddd. Also when profile image is incorrect the page will not fail - as mentioned in the screenshot it will show error stating - 'url incorrect or unable to load' - this I will check why urls are becoming invalid as part of this ticket: https://avni.freshdesk.com/a/tickets/3784 anyways.

But Mohammed Taqi Afsar need more details regarding how the errror page in this card

**Comment by Gojo-Taqi** [comment]
The details provided on this card are incorrect.
Closing this ticket.
