### ISSUE TITLE
Getting the Error in serving file dignosticCard.html when printing 

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-webapp#1207]
When we click on the printing the report it is displaying the error instead of printing the report card 

env : per-release 
User : nupoork@jscs

Steps to reproduce:
1.Login to Jscs
2.Click on the individual or Lab Facility
3.select the individual 
4.Click on the print diagnostic card 

Expected result : it show open the print report with format
Actual result : it is displaying the error in serving file 

https://github.com/avniproject/avni-webapp/assets/127730126/d3b57eda-a38e-407b-bc65-5d9200568893

**Comment by mahalakshme** [comment]
probably its because the scripts are missing in s3, but need to be fixed for QAs to complete release signoff

**Comment by petmongrels** [comment]
@Dinesh2019 @mahalakshme the extensions are not working as the it is stored in S3 where and on pre-release our db and S3 are not in sync.
