### ISSUE TITLE
App designer should not break on invalid glific configuration

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1208]
https://avni.freshdesk.com/a/tickets/3352

### Steps to reproduce:
- Any org without valid glific configuration
- In `Organisation details` toggle on `Enable Messaging`
- Open a subject type in `App designer`
- We show the oops error page

### Need:
Issue raised by several tickets and people in implementation team. 

### Acceptance criteria:
when the /messageTemplates call fails, do the below on different scenarios,
- In the Show mode, when the /messageTemplates call fails, and when there are no message rules, it should not fail, and the subject type need to show
- In the Edit mode, when the /messageTemplates call fails, and when there are no message rules, show the error message as below along with other usual subject type information on click of 'Add new message rule'
![Image](https://github.com/avniproject/avni-webapp/assets/10369963/79d93b55-1d70-434b-bdd1-6a43a9174704)
- In the Show mode, when there are message rules, show the other subject type info, along with the error message as above.
- In the Edit mode, when there are message rules, show the other subject type info, alone with the error message as above. When user tries to add more message rules by clicking on 'Add new message rule', again show the above error message. It is okay if the error message displays multiple times on the page
- The above needs to work across entity types (program, subject type, encounter type)
- Similar above behaviour for `User Messaging Config` of App designer as well.

### Analysis reason:
The above was decided to be done, instead of handling it when toggling on `Enable Messaging` in `Organisation Details` because of the below reasons:
- The credentials might become invalid at a later point of time, after enabling messaging.
- The implementation engineer might enable it from db

**Comment by mahalakshme** [comment]
username: maha@lahi
env: prerelease
encounter type: [LAHI INTERN ATTENDANCE](https://prerelease.avniproject.org/#/appDesigner/encounterType/1814/show)

fails because of incorrect configuration - ve already added the above case in AC above

Also 2nd AC looks like is not implemented - These things will again come via self-service or some other route that it is not evident.

**Comment by petmongrels** [comment]
@mahalakshme was master server deployed on prerelease to test this?

**Comment by mahalakshme** [comment]
@petmongrels no previously this was part of 10.0. The above is released. I changed it to 10.1, since found the above issues.

If you have done the above, intentionally for some reason, you can let me know.

**Comment by dinesh2096** [comment]
- [ ] When try to save without mandatory fields we are not displayed with any errors 
- [ ] And also we are not getting any error while configurating the message rule 

Reference video : 

[Click here to watch the video](https://drive.google.com/file/d/1k53eDGBr9heieAImUrrTPObyRfK2Y5Zk/view?usp=drive_link)

**Comment by himeshr** [comment]
## Additional fixes done
Fixed broken "On save" click operation User-experience during create / edit of following entityTypes:
- SubjectType
- EncounterType
- Program
- UserMessagingConfig

## Known issues
- We have not introduced UI validation for MessageRules form-section, as its a bigger changes and not part of scope for this card
- MessageRule."Name" not empty validation is not strictly adhered to in DB in some scenarios

**Comment by dinesh2096** [comment]
- [ ] When we add the message rule while creating the subject type the rule is not saved 


[Click here to watch the video](https://drive.google.com/file/d/1peRGVaeelIab-cJroorCpBbEZ2akSVly/view?usp=drive_link)

**Comment by himeshr** [comment]
> * We have not introduced UI validation for MessageRules form-section, as its a bigger changes and not part of scope for this card

@dinesh2096 the error is due to receiverType not having value set during SubjectType creation.
On Discussion with @mahalakshme , we had decided to restrict scope of this card to only avoiding App breakage due to missing/invalid glific config.

To fix this issue, we would need to work on UI validations bit, which has been marked as a know issue and not included in scope.

**Comment by dinesh2096** [comment]
QA Reference video : 

[Click here to watch video](https://drive.google.com/file/d/1Ls6Z_ngsTbP9V7Fb0-G0ftVWYv96Xbm3/view?usp=drive_link)
