### ISSUE TITLE
Search widget

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#121]
### Motivation
Subject search attributes are now configurable through the admin UI (see /#/admin/organisationConfig). However, the existing search API is not configured to use attributes configured through search. This story will add this ability.

Organisation config contains a searchFilters key of the form
```
[
  {
    "titleKey": "Registration_date",
    "type": "RegistrationDate",
    "widget": "RelativeDate",
    "subjectTypeUUID": "9f2af1f9-e150-4f8e-aad3-40bb7eb05aa3",
    "searchScope": "programEncounter"
  },
  {
    "titleKey": "Search All",
    "type": "SearchAll"
  },
  {
    "titleKey": "Age",
    "subjectTypeUUID": "9f2af1f9-e150-4f8e-aad3-40bb7eb05aa3",
    "type": "Age"
  },
  {
    "titleKey": "Name",
    "type": "Name",
    "subjectTypeUUID": "9f2af1f9-e150-4f8e-aad3-40bb7eb05aa3"
  },
  {
    "titleKey": "Standard",
    "type": "Concept",
    "subjectTypeUUID": "9f2af1f9-e150-4f8e-aad3-40bb7eb05aa3",
    "Scope": "programEncounter",
    "conceptUUID": "fda18675-59dc-4a69-82f7-4e137c274073",
    "scopeParameters": {
      "programUUIDs": [
        "215f4795-7d46-4617-95dd-52343f945a0f"
      ],
      "encounterTypeUUIDs": [
        "14e23e16-5db0-4d16-9efe-b206a18010a7"
      ]
    }
  }
]
```

Note: All fields in the array are optional. It is used to configure the search widget. 
The search widget will use the config available to show relevant fields to search. 

### Acceptance Criteria
- Always show filter for choosing subject type.
- Always show filter to include voided subjects. It should be false by default.
- When no search filters are provided, use only an AllSearch filter and a subject type toggle with the label Search All
- The titleKey is used to label the search field
- Search widgets will be of the form:
  - Text (for name and concepts of type text).
  - Date Range (for registration Date, enrolment date, encounter date, program encounter date and concepts of type date). It could also be relative date if the widget type in org config is "RelativeDate".
  - Numeric range (between two numbers) (for age and concepts of type numeric) 
  - Exact Number (for age and concepts of type numeric)
- Search widgets are shown only for the subject type chosen on the UI

### Visual Design
https://drive.google.com/drive/u/1/folders/1rMV5zI9STrzsF9_RibngWTz_H9dziD9u
Page 8
![Search.PNG](https://images.zenhubusercontent.com/5e0f2f610385a430f442c14d/9e48e574-d1b3-40d1-8f95-d2064ea13d5b)
Note: All types are not really provided in the visual design, this must be changed.

**Comment by hithacker** [comment]
Paper sketch

![Search-Wireframe.png](https://images.zenhubusercontent.com/5d0b10e42fff8629577fc2cc/35e6b815-759f-4ae3-826e-eea72c49bcd0)

**Comment by hithacker** [comment]
Section details for non coded, non concept, coded concept filters

Non Coded Concept Filters
![Non-Coded-Concept-Filters.png](https://images.zenhubusercontent.com/5d0b10e42fff8629577fc2cc/c60dec04-d2d7-4d38-80db-6ebf56650739)

Non Concept Filters
![Non-Concept-Filters.png](https://images.zenhubusercontent.com/5d0b10e42fff8629577fc2cc/e7149a75-a19d-4900-a5f4-7465914104e6)

Coded Concept Filters
![Coded-Concept-Filters.png](https://images.zenhubusercontent.com/5d0b10e42fff8629577fc2cc/98263555-740f-4558-b83d-9e930b023452)

**Comment by garimadosar5** [comment]
QA Notes - 
- 'Search' and 'subject type' are too close.
![Screen Shot 2020-08-06 at 8.51.37 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/27a03a04-6ef8-4c98-bd45-49bab91154ef)

- Include Voided button does not come for all the subject type.
![Screen Shot 2020-08-06 at 8.53.53 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/c62cbd2b-7b21-49bb-8483-fb779eb58629)

![Screen Shot 2020-08-06 at 8.54.52 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/f914b5b4-b825-4102-bdb7-44a49f4d5faf)

- When the Text 'Subject type changes colour- 
1. Click on any subject type, it turns blue.
2. Click on the text, again turns grey.

- If there are some search filters defined for client, it does not show in the web.
eg: admin@jnpct/password
- Login into the web admin <- go to data entry app <- on Home page without any search filter, it shows SEARCH RESULT as a heading.
![Screen Shot 2020-08-06 at 9.03.05 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/eb78d3a8-e18a-44f8-8b85-d4f60b3163b3)

**Comment by vindeolal** [comment]
Fixed
