### ISSUE TITLE
Offline Dashboard Filters show voided filters as well

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#1210]
### To reproduce
- On the App Designer, go to Offline Dashboard
- Edit a dashboard (create one if none exist)
- Add filter
- Choose something and save
- Delete the filter

Expected: The filter should be removed
Actual: The filter still shows up on the screen

**Comment by d1vyanshu-kumar** [comment]
@vinayvenu I am working on this issue.
