### ISSUE TITLE
Export location form fields also in sample file

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1211]
### Need:

In several orgs like Goonj, Mobile creche, and APF odisha, use these location properties. And currently it is not user friendly for the users to identify the column names and allowed values.
Related ticket: https://avni.freshdesk.com/a/tickets/2442

### AC:
- In the sample location file to be downloaded, display name of form element(not concept name) part of Location type form as headers
- Only the name of form elements associated with forms mapped to location type, present in the selected location hierarchy need to be displayed in the headers.
- When a form element has coded concept, then mention `Allowed values: A,B,C,D` in the description row
- When a form element has numeric concept, then mention `Allowed values: any number`
- When a form element has text concept, then mention `Allowed values: any text`
-  So sample file for APF odisha UAT would be like [this](https://docs.google.com/spreadsheets/d/1R3l_tRUKZ7_WoZa4QIRctecFqJZoB2jdltyKUPMSD0Q/edit#gid=1280171864) (note the last 4 columns)

### Out of scope:
- When a form element is added as mandatory, then displaying in the 'descriptor row' as mandatory field, since [this](https://github.com/avniproject/avni-webapp/issues/1216) card is out of scope for this release

**Comment by himeshr** [comment]
Handle Dynamic generation of Locations  upload CSV file, for Create only mode, with Single Heirarchy.
Sample Locations upload CSV Files
[sample-locations-APF.csv](https://github.com/avniproject/avni-webapp/files/15456494/sample-locations-APF.csv)
[sample-locations-Goonj.csv](https://github.com/avniproject/avni-webapp/files/15456495/sample-locations-Goonj.csv)
