### ISSUE TITLE
Deleting dashboard section does not delete the section from the Android app

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#1212]
### Reproduce issue
- Go to Offline Dashboard
- Choose a dashboard (create one if not available)
- Delete one section
- Look at the dashboard_section entries for the dashboard

### Expected
- The dashboard_section is voided and last_modified_date_time and last_modified_by is updated

### Actual
- The dashboard_section row is deleted

Due to this, existing Android clients cannot see any changes made on the App Designer

**Comment by prithu7872** [comment]
Sir , the dashboard problem is on the app or the web ?

**Comment by prithu7872** [comment]
Sir please if you can guide me a to the problem

**Comment by vinayvenu** [comment]
@prithu7872 do you have avni-webapp and avni-server set up on your machine? If you do, you can follow the steps mentioned in the card

**Comment by mahalakshme** [comment]
if there are too many changes in 10.0 in the places where the pull requests are done, we can merge it with 9.1.0 for time being. if not we can merge with 10.0 itself based on when it gets reviewed
