### ISSUE TITLE
Upload Locations data

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1213]
### Need:
- Some times headers are itself incorrect and we so far don't do any validation on the headers.
- Edit+create mode allows to 
      - update the existing location by specifying uuid or immediate parent of the location
      - create a new location by mentioning the hierarchy - but only lowermost child can be created. If any of the parents doesn't exist it will throw an error. This can be achieved using create mode as well.
So because of having multiple ways to do a certain thing, and different fields are required based on Edit or create in Edit+create mode, it is difficult for the user to deduce what data need to be entered to achieve what he wants. This results in poor UX according to Don Norman in 'Design of Everyday Things'.
- We are currently allowing to update location's parent via Edit mode via CSV. But it is not correctly handled - lineage and subjects in the location not updated.

### AC:
- Validate the headers(expectation: refer [here](https://github.com/avniproject/avni-product/issues/1531)) for the uploaded mode and selected hierarchy. If any extra column name is present or if any mandatory column is missing, display the error in error column as 'Headers are incorrect. Kindly check the sample file.' 
- For create mode, when a location of lower level is created, all its higher level locations are mandatory. Currently this is not present and could lead to the location getting created under the wrong parent. Say for a location hierarchy, State -> Block -> GP -> 'Village/Hamlet', a user wants to create a GP and in the CSV hasn't mentioned Block and State, then show error stating 'Mention Block and State under which the GP needs to be created.' 
- For Edit name, coordinates, properties mode, only allow to update name, GPS coordinate, location properties based on hierarchy of the location in the sample file
        - So doing the above should also remove the ability(and hence the code) to create a location and update a location's parent
- For edit parent mode, throw an error in the error column stating like 'Location doesn't exist' similar to error shown for UsersAndCatchments. 
         - Here everything similar to done when [updating parent via UI](https://github.com/avniproject/avni-webapp/issues/1217) needs to be handled like updating children location lineage, mapping, marking users for reset sync.
- Also in both edit modes above, location hierarchy comparison need to be case insensitive. Eg: If the hierarchy is 'A, B, C', even if in CSV it is mentioned as 'a, b, c' it should be considered matching locations.
- Even if descriptor row present, edit or create should work 

### Code review checkpoint:
Make sure all the unnecessary code for Edit mode is removed like validation of presence of parent locations, being able to update locations parent, etc.,

### Technical Questions:
How to identify the description row?

**Comment by mahalakshme** [comment]
- GPS coordinates are shown as invalid when not mentioned - but they are not mandatory, 
- The 1st data row gets removed in the error CSV fine
- Location properties when not mentioned shown as invalid - but they should not be mandatory

**Comment by himeshr** [comment]
- GPS Co-ordinates and location properties are lost on Changing parent location
- Lineage and LineageAddressIds are in-correctly set for the migrated location

Steps followed:
1. Create location using upload
<img width="1728" alt="Screenshot 2024-09-20 at 1 10 17 PM" src="https://github.com/user-attachments/assets/30c4e77e-5111-4b88-99ef-a4bfbf9dde8e">

2. Edit location using upload to point to different location hierachy as mentioned in description row : "Hierarchy of parent location that should contain the child location".
Upload successfully changes parent location, but grand-parent is still old one.
<img width="1728" alt="Screenshot 2024-09-20 at 1 14 12 PM" src="https://github.com/user-attachments/assets/44f57e7c-17ea-40e8-bb17-7c6e20f88168">



[editTest4.csv](https://github.com/user-attachments/files/17071783/editTest4.csv)
[CreateTest3.csv](https://github.com/user-attachments/files/17071785/CreateTest3.csv)
[createTest2.csv](https://github.com/user-attachments/files/17071786/createTest2.csv)



Refer screenshots and sample files.

**Comment by 1t5j0y** [comment]
Retaining older GPS coordinates and location properties when not set in edit csv implies we cannot reset these to empty via edit location csv. However, have fixed in line with the QA finding as retaining the older value when not provided seems to be the more intuitive behaviour.

Added an additional condition to prevent updating parent to a parent whose type different from current parent's type.

**Comment by mahalakshme** [comment]
@himeshr @1t5j0y I see from a usecase perspective, new parent can be of different type than the existing parent - esp., in orgs that support multiple hierarchies. Will add it to a subsequent release.
