### ISSUE TITLE
DEA fails if no options provided for Duration

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#1219]
### How to reproduce
- Add a new Duration element in a form. Ensure not to provide Duration options
- Try to fill in the form on the Data Entry Application
- Notice that the form fails

### Expected
The Duration element should not be allowed to be saved on the App Designer

**Comment by himeshr** [comment]
This change seems to also impact FormElements for "Date" dataType Concepts, which is a big regression.
<img width="1048" alt="Screenshot 2024-07-03 at 3 07 24 PM" src="https://github.com/avniproject/avni-webapp/assets/72493481/2030320d-1c8a-4c34-9fc5-72b1e122087b">
<img width="1840" alt="Screenshot 2024-07-03 at 3 07 38 PM" src="https://github.com/avniproject/avni-webapp/assets/72493481/60554ad8-973b-4366-b354-9351809ab251">

**Comment by mahalakshme** [comment]
@shraddha761 kindly check the above issue

**Comment by shraddha761** [comment]
@mahalakshme Did changes and created pr.

**Comment by himeshr** [comment]
Code available in master branch, which is currently 10.0 release, so updating the release for the card to help QA figure out the testing.

**Comment by Dinesh2019** [comment]
The error is not updated and not allowed to save the form.This happen only in duration error. Validated with adding two formelement with same concept and saved it shows the error after removing the duplicate it allows to save the form.

Steps to reproduce: 
1.Add the concept of duration select the duration option
2.Save the form 
3.edit and remove the duration option 
4.save the form which will display the error
5.Now delete the concept 
6.Try to save it

Expected result : Form should saved 
Actual result : error still displays and not allows to save the form 


Refer video : 


https://github.com/user-attachments/assets/9b621435-a48a-4460-a7a3-314c3f4413e9

**Comment by Dinesh2019** [comment]
Main functionality is not behaving as expected 



https://github.com/user-attachments/assets/38cfe2f8-5f5c-4648-a8af-b9cb275e3c94

**Comment by himeshr** [comment]
@Dinesh2019 i tested using latest master code, but couldn't reproduce the issue.
the Code deployed on staging env might have been something else, as the error is consistently shown when duration options is not set for Duration FormElement.

**Comment by Dinesh2019** [comment]
Test Scenario : 

1.Added the concepts and selected the duration option 
2.edit and remove the duration option
3.delete the duration concepts and tested it 
4.Remove the option error will be displayed , try save after deleted the concepts


Refer video for QA References : 


[Click to here to watch](https://drive.google.com/file/d/1zmAeDAMvELwT4Tn5O7sNtczJsW4KpyA2/view?usp=drive_link)
