### ISSUE TITLE
Search results page

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#122]
### Motivation
This story deals with showing of search results based on parameters given in the url.

### Acceptance Criteria
- When search is performed through the search widget, results are available on the search results page
- When nothing is provided as a search criteria, a listing of all results are provided
- On clicking of a result, the subject dashboard of that subject opens up. 
- Search provides options for pagination and sorting (need to update visual design for this)

### Visual Design

https://drive.google.com/drive/u/1/folders/1rMV5zI9STrzsF9_RibngWTz_H9dziD9u
Page 15

**Comment by garimadosar5** [comment]
QA Notes -

**Comment by vindeolal** [comment]
@garimadosar5 this is default behaviour right now in our app designer also, not changing it right now.
