### ISSUE TITLE
[DEA] Images do not work inside repeatable question group

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#1221]
### How to reproduce
- Add a form with an image concept inside a repeatable question group
- Try to save the form from the Data Entry App
- Look at the Subject Dashboard after save. Notice that the images are missing

<img width="1496" alt="Screenshot 2024-05-09 at 10 11 08 AM" src="https://github.com/avniproject/avni-webapp/assets/344222/9b6b4808-b3dd-4c6e-bc0f-eb96a521d20e">

**Comment by himeshr** [comment]
Missed resolving a TODO in code, fixed it.
<img width="1840" alt="Screenshot 2024-05-10 at 1 27 40 PM" src="https://github.com/avniproject/avni-webapp/assets/72493481/112d149e-27d8-44b3-9d36-374a52d6d935">
