### ISSUE TITLE
Facing issue while uploading the matadata zip file on staging

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-webapp#1224]
**Describe the bug**
Facing issue while uploading the matadata zip file on staging
I created a organisation testach  and try to upload the meta zip to that org but it is showing me error
 
[RWB_Niti.zip](https://github.com/avniproject/avni-webapp/files/15260833/RWB_Niti.zip)
[errors-RWB_Niti.csv](https://github.com/avniproject/avni-webapp/files/15260837/errors-RWB_Niti.csv)

**To Reproduce**

1. Login with AchalaB@testach
2. try to upload a bundle 
3. See error

**Comment by petmongrels** [comment]
not reproducible. tried locally as well as on techach in staging. it worked in both places.
