### ISSUE TITLE
Analytics data sync is not showing status.. 

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-webapp#1228]
**Describe the bug**
Analytics data sync is not showing status..
Analytics status should be shown organisation list

**To Reproduce**

1. Login with admin user
2. Click on orgnisation
3. See the list and check the status analytical status

env: prod and prerelease
**Expected behavior**
should be shown status of this
**Test Data**
Give details of example users, environment detail, username against which this issue is happening.

**Screenshots**
<img width="675" alt="status" src="https://github.com/avniproject/avni-webapp/assets/104890488/2f1163d5-a712-44d9-be4e-cd8ff47f7e9a">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Developer Checklist**(Developer fixing the bug should fill this checklist)
- Does the fix require extensive regression testing?
  - [ ] Yes
  - [ ] No
- Are you mentioning the required scenarios that could be affected?
  - [ ] Yes
  - [ ] No

**Comment by himeshr** [comment]
Modified the AWS Load-balancers to route all /etl calls directly to the corresponding Environments Integration-server on HTTPS 443 port, using newly created ${env}-int-target-group Target groups.

**Comment by himeshr** [comment]
## After Fix screenshots:

<img width="1840" alt="Screenshot 2024-05-22 at 12 49 20 PM" src="https://github.com/avniproject/avni-webapp/assets/72493481/fcc5e21d-581d-4b37-8c5d-70ddc0286f84">
<img width="1840" alt="Screenshot 2024-05-22 at 12 49 08 PM" src="https://github.com/avniproject/avni-webapp/assets/72493481/8c725c83-0ec0-4147-adab-7b52749964d0">
<img width="1840" alt="Screenshot 2024-05-22 at 12 48 52 PM" src="https://github.com/avniproject/avni-webapp/assets/72493481/5e610e88-c832-4fb4-8514-d82392f8f307">

**Comment by AchalaBelokar** [comment]
- [ ] tested on prerelease  it is showing the now

**Comment by himeshr** [comment]
No Pending Release deployment tasks as part of this card.
