### ISSUE TITLE
DEA support for the expected concepts within QG

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1229]
### AC:
DEA should work for the below concepts when used in Question Group or Repeatable question group:
subject, coded(single/multiple), text, numeric, notes, image, date with different options (calendar, years, months, etc., checked)

### Test cases:
Make sure to verify the above in the concepts mentioned [here] (https://docs.google.com/spreadsheets/d/1B0q47TvHJnLtromEwywGEyR9sg2zR1t6n6yLhLBrou8/edit#gid=1576193946) other than any other applicable test cases.

**Comment by AchalaBelokar** [comment]
- [ ] checked with all scenario in lahi and goonj
-
