### ISSUE TITLE
Unable to Find Individual in DEA When Searching.

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-webapp#1230]
When searching for an individual in the DEA using name of the individual under any subject type, the individual is not displayed in the search results. However, when performing a search with empty data, the individual is found and displayed in the search results.

Env : Prod
org : cini_uat
user : dinesh@cini_uat

Steps to reproduce :

1.Login to org
2.Click on the DEA in the Webapp
3.Enter the individual name (eg: ABHAY MISRA under the subject type : CRB/BRP)

Expected Result : Individual is not displayed in the DEA
Actual : it should displayed the individual in the DEA after the search

Refer video :

https://github.com/avniproject/avni-webapp/assets/127730126/8423d076-e00d-47ca-bd6b-5c0f27f95a72

Note : this is happening for some account (cini,adsruat) but not happening in apfodishauat

### Analysis:
Based on the [code](https://github.com/avniproject/avni-server/blob/5f2ca33650226181bed0fe77eea8652cbb744a85/avni-server-api/src/main/java/org/avni/server/dao/search/BaseSubjectSearchQueryBuilder.java#L167) we have written this should have worked.

**Comment by mahalakshme** [comment]
@Dinesh2019 you can search for first name or last name separately but not together - check this if it works

**Comment by Dinesh2019** [comment]
@mahalakshme i tried all the combination it is not working as expected

**Comment by mahalakshme** [comment]
@Dinesh2019 okay will prioritise it, yeah I also checked, it should ve worked

**Comment by 1t5j0y** [comment]
@mahalakshme Looks 'as expected' since default search in DEA (without configuring search filters) [only searches within text observations of registration and enrolment](https://github.com/avniproject/avni-server/blob/45fe63c6eeddc5b136c71754266036d683122332/avni-server-api/src/main/java/org/avni/server/dao/search/BaseSubjectSearchQueryBuilder.java#L231) observations (as the label of the search field already indicates).

**Comment by mahalakshme** [comment]
@1t5j0y you are right. misunderstood the expectation from the code. so closing this card

**Comment by mahalakshme** [comment]
@Dinesh2019 u can confirm the above and then close this card.
