### ISSUE TITLE
Bundle uploads with dashboards and report cards broken

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-webapp#1231]
**Describe the bug**
Bundle upload is failing on staging
I am created new org Uchange and upload this bundle to that org
[lfeui.zip](https://github.com/avniproject/avni-webapp/files/15469783/lfeui.zip)
After uploading it is giving me this error
[errors-lfeui.csv](https://github.com/avniproject/avni-webapp/files/15469792/errors-lfeui.csv)

**To Reproduce**

1. Login to AchalaB@uchange
2. upload the bundle 
3. See error

**Expected behavior**
bundle should upload successfully 
**Test Data**
Give details of example users, environment detail, username against which this issue is happening.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Developer Checklist**(Developer fixing the bug should fill this checklist)
- Does the fix require extensive regression testing?
  - [ ] Yes
  - [ ] No
- Are you mentioning the required scenarios that could be affected?
  - [ ] Yes
  - [ ] No

**Comment by 1t5j0y** [comment]
Issue was on staging because avni-server master was incorrectly deployed to staging while 9.0 is being tested there. Deployed avni-server 9.0 again to staging to unblock testing and ensure the issue is not present in 9.0.

**Comment by 1t5j0y** [comment]
Issue in master is due to avniproject/avni-client#1381 still being WIP. Can be rechecked once it is dev complete.
