### ISSUE TITLE
Link self service support to right readme link

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1233]
If you click on the "Support and training" -> ''Self service help articles" it doesn't take to right readme link. It needs to take to [this](https://avni.readme.io/docs/implementers-concept-guide-introduction) link

![Image](https://github.com/avniproject/avni-webapp/assets/10369963/f2e1a7ce-501c-41eb-861d-3e7cb481cabd)

**Comment by Abhi591** [comment]
I've create a PR for the above fix - https://github.com/avniproject/avni-webapp/pull/1234. Please review

**Comment by mahalakshme** [comment]
Thanks @Abhi591 One of our team members will review it asap
