### ISSUE TITLE
Edit Registration

### ISSUE THREAD

**Issue by arjunk** [avniproject/avni-webapp#124]
### Motivation
As an data entry user, I should be able to edit the registration details of subject or void it so that can view the subject with updated details.

### Acceptance Criteria
When on Subject Dashboard - > Profile Tab, 
- Clicking on Edit button on Registration section should show form elements of the registration filled form
- User should be able to update any data and Save the form 
- On Save, Show success message as a toast and not a popup. Success message should be "Registration details saved". Redirect to Subject Profile Dashboard.
- Validations should work during registration form edit. Erroneous fields should be in red and show apt message if configured. Once resolved, user can move to next page and then save the form.
- On Registration section - updated data should be seen. On viewing Registration Form, edited details should be seen.
- User's edited / updated data should be seen in below cases:
  - On browser refresh
  - User re-login
  - For data edited on mobile app then on sync same user or other users of same org should see the updated 
    details for subject.
- User should be able to Void a subject registered.
Registration Details section should show Void button
On Void, 
   - display popup to confirm to void the individual. 
   - Once user selects Yes, Show message:"THE INDIVIDUAL HAS BEEN VOIDED" on all tabs of this subject dashboard
   - Unvoid option should be shown
   - All other details remain as is.
On Unvoid,
   - registration details as were should be displayed.
   - message for voided should no further be shown 

### In scope
Edit Registration form can contain following types of form elements.
Numeric 
Text 
Notes 
Date 
DateTime 
Time 
Duration 
SingleSelect 
MultiSelect 

### Out of scope:
Form elements Image, Id and Video
Storing of location
Rules (visibility filter, calculated fields, decisions)
Ability to choose address of the Subject ( a separate card is there)

### Notes
Use openchs-models for data.
Keep reference data in memory.

### Tasks
Call GET api to fetch saved data

**Comment by Sayali-Dev** [comment]
Updated below in acceptance criteria for feedback for toast received from Arjun for 17/03-18/04 iteration:
- Show success message as a toast and not a popup. Success message should be "Registration details saved"

**Comment by garimadosar5** [comment]
QA Notes. -
- New button (admin@yenepoya)
    1. Household 
    2. Individual  (UI broken)
![Screen Shot 2020-08-07 at 6.17.12 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/605f3aa6-bdc3-416b-9183-a685688db700)
- Random system recommendation.
![Screen Shot 2020-08-07 at 6.24.39 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/fa2ca8c3-b8b6-4c62-8a68-0f468a67beba)
