### ISSUE TITLE
[DEA] Edit registration is not working as expected on web app.

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-webapp#1240]
**Describe the bug**
Edit registration is not working as expected on web app. 
Login with maha@goonj and try to edit the distribution registration details.
it directly goes to summary page.

**To Reproduce**

1. Login with maha@goonj
2. go to data entry app
3. search for distribution
4. click on any registration details
5. try to edit it
6. See error

**Expected behavior**
user is able to see the first page of registration 

**Test Data**
Maha@goonj any distribution subject type

**Screenshots**

https://github.com/avniproject/avni-webapp/assets/104890488/01453b12-881b-43c6-82d4-b67a070a8eca

**Smartphone (please complete the following information):**

**Additional context**

**Developer Checklist**(Developer fixing the bug should fill this checklist)
- Does the fix require extensive regression testing?
  - [ ] Yes
  - [ ] No
- Are you mentioning the required scenarios that could be affected?
  - [ ] Yes
  - [ ] No

**Comment by 1t5j0y** [comment]
@petmongrels shouldn't we disable the logging in prod?

**Comment by mahalakshme** [comment]
@AchalaBelokar reopening this card to retest since this card was closed before the fix was deployed to prerelease/staging

**Comment by AchalaBelokar** [comment]
- [x] tested with maha@goonj it is working fine there
- [ ] also tested on sncu where I tried to edit the child Enrolment it goes directly on summary page.

1. Login with taqim@sncu 
2. search for individual 
3. try to edit enrolment details of that individual 
4. it goes to the summary page

- [x] try to edit that child  encounter details it is working fine

**Comment by AchalaBelokar** [comment]
- [ ] Edit  encounter is failing bcz rule is failing taqim@sncu.

![Image](https://github.com/avniproject/avni-webapp/assets/104890488/9dcb37c9-3abf-45b4-951c-9b13e744651f)

this is happen child followup edit.
