### ISSUE TITLE
After adding the new dashboard new one is not showing until the dashboard is saved

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-webapp#1241]
**Describe the bug**
After adding the new dashboard new one is not showing until the dashboard is saved.
Login with dinesh@mc 
try to add the card on dashboard
after adding it it is not reflected after saving it is shown

**To Reproduce**

1. Login with dinesh@mc
2. click on data entry app
3. click on offline dashboard
4. click on edit 
5. add the card 
6. See error
8. and then save 
9. it is reflecting

**Expected behavior**
After adding the card card name and count should shown
**Test Data**
dinesh@mc

**Screenshots**
[My Movie.mp4.zip](https://github.com/user-attachments/files/15756165/My.Movie.mp4.zip)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Developer Checklist**(Developer fixing the bug should fill this checklist)
- Does the fix require extensive regression testing?
  - [ ] Yes
  - [ ] No
- Are you mentioning the required scenarios that could be affected?
  - [ ] Yes
  - [ ] No

**Comment by mahalakshme** [comment]
@AchalaBelokar this is an existing known issue and is already fixed as part of 10.0. There is another card for this. So closing this card.
