### ISSUE TITLE
[DEA] When a subject is kept in Edit more for like around 5 mins it crashes because it is trying to fetch random things from s3. 

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-webapp#1242]
**Describe the bug**
When a subject is kept in Edit more for like around 5 mins it crashes because it is trying to fetch random things from s3. Even the calls should ve not been made

**To Reproduce**

1. Login with maha@goonj
2. edit the distribution 
3. wait for 5 min
4. see the error on inspect

**Expected behavior**

**Screenshots**
![s3](https://github.com/avniproject/avni-webapp/assets/104890488/335119fa-8e33-45ed-97aa-3f51a227bab5)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Developer Checklist**(Developer fixing the bug should fill this checklist)
- Does the fix require extensive regression testing?
  - [ ] Yes
  - [ ] No
- Are you mentioning the required scenarios that could be affected?
  - [ ] Yes
  - [ ] No

**Comment by mahalakshme** [comment]
@himeshr still too many failing requests are there in prerelease - notes are also considered as media currently and tried to fetch

![Image](https://github.com/avniproject/avni-webapp/assets/10369963/d3621447-0775-4e50-b3e7-da17d5a3ab01)

/rules returning 400 bad request - so decisions not getting shown
![Image](https://github.com/avniproject/avni-webapp/assets/10369963/630024fb-625b-48db-a9e6-6251c479b744)

**Comment by himeshr** [comment]
Issues here:
1. Prerelease will not have prod media content, resulting in media fetch errors
2. Notes is handled as media and tried to fetch
3. rules api call for decisions is failing
4. any eligibilityCheck was failing due to token invalid error and crashing the app //Fixed
5.

**Comment by AchalaBelokar** [comment]
- [ ] I am login with taqim@sncu and search with individual  and try to edit the child followup ...rule is failing there

![Image](https://github.com/avniproject/avni-webapp/assets/104890488/bb6783b7-6e4d-45f9-86fe-368c22705ce5)

**Comment by mahalakshme** [comment]
@AchalaBelokar we didn't address all issues in DEA - the above is out of scope for this release
