### ISSUE TITLE
[DEA] Subject concept form values not displaying in repeatable question group on Edit

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-webapp#1243]
**Describe the bug**
Subject concept form values not displaying in repeatable question group
In the summary it is showing the concept but while editing it isnot showing

**To Reproduce**

1. Go to maha@goonj
2.  go to data entry app
3. edit the distribution subject type
4. summary page look at the Implementation Inventory Id *
5. while editing it is not showing that

**Expected behavior**
that thing should be shown

**Test Data**
maha@goonj
subject type: distribution 

**Screenshots**

https://github.com/avniproject/avni-webapp/assets/104890488/e23a82cd-0da9-444a-8943-92511e207e0c

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Developer Checklist**(Developer fixing the bug should fill this checklist)
- Does the fix require extensive regression testing?
  - [ ] Yes
  - [ ] No
- Are you mentioning the required scenarios that could be affected?
  - [ ] Yes
  - [ ] No

**Comment by himeshr** [comment]
This is working as desinged, please follow related documentation to configure the Subject FormElement for use within RepeatableQuestionGroups, as mentioned [here](https://avni.readme.io/docs/repeatable-question-group)

**Comment by himeshr** [comment]
Please ensure configurations mentioned in this [card's comments](https://github.com/avniproject/avni-webapp/issues/1171) are adhered to, to get the RQG working for Goonj Org.
