### ISSUE TITLE
Spaces in headers and locations needs to be truncated

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1255]
[This](https://drive.google.com/file/d/1P6ZrSXcTbA9r3ishQs5iVU0VJ87UsYJz/view?usp=drive_link) was erroring out because there was a space in the header 'Catchment Name '. And it took long time to figure out the issue.

### AC:
- Trim leading and trailing spaces in headers of Locations and 'Users and Catchments' upload. 
  - As part of [this](https://github.com/avniproject/avni-webapp/issues/1213) card, we show error message stating 'Headers are incorrect. Kindly check the sample file'. But even before validating the headers, trim the trailing and leading spaces. 
  - If after truncating if showing of error message like 'Headers are incorrect. Kindly check the sample file'.  when not correct(If any extra column name is present or if any mandatory column is missing) is not done for Users and Catchments do the same.
- Trim leading and trailing spaces of location names across location types, in location upload(when creating locations) - if not done this is leading to issues when specifying locations for creating catchments since the spaces need to be correctly mentioned

**Comment by Dinesh2019** [comment]
When we upload the file for user and catchment i am getting the error stating that provide location does not exist in the avni but the location is already exist in the system.

Env : staging 
org : Teststatus
user : dinesh@teststatus

steps to reproduce : 

1.Login to the webapp
2.Downloaded the user and catchment sample file 
3.Edit the file according to the location 
4.Upload the file 

Expected result : it should accept and create or it should show Headers are incorrect if the data is invalid
Actual : it shows the Provided Location does not exist in Avni. Please add it or check for spelling mistakes 'Karanataka,tel,sol,dol'


Sample files : 

uploaded file 
[sample-usersAndCatchments (1).csv](https://github.com/user-attachments/files/16469877/sample-usersAndCatchments.1.csv)

error file : 
[errors-sample-usersAndCatchments (1)(1).csv](https://github.com/user-attachments/files/16469886/errors-sample-usersAndCatchments.1.1.csv)

**Comment by petmongrels** [comment]
This is not a bug as the address lineage needs to have space in between.
This fix is only for preceding and trailing space is any cell.

**Comment by Dinesh2019** [comment]
We have changed the header for each header we are getting diff error message 

error file : 

1.

[errors-sample-usersAndCatchments (1) (1).csv](https://github.com/user-attachments/files/16569341/errors-sample-usersAndCatchments.1.1.csv)

2.

[errors-sample-usersAndCatchments (3).csv](https://github.com/user-attachments/files/16569344/errors-sample-usersAndCatchments.3.csv)

**Comment by mahalakshme** [comment]
@petmongrels yeah I also didn't mean the in between spaces in the AC. So all the points in the AC applies.
