### ISSUE TITLE
Offline report card view link is broken

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#1256]
**Describe the bug**
The link to open an offline report card on the App Designer is broken

**To Reproduce**
- Go to the App Designer
- Click on Report cards
- Click on the name of any report card
- Observe the screen failure

**Comment by mahalakshme** [comment]
@vinayvenu in staging ?

**Comment by vinayvenu** [comment]
Yes

**Comment by 1t5j0y** [comment]
Latest deployment of master to staging fixed this.
