### ISSUE TITLE
Disallow changing of form element type

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1257]
### Issue:
During testing or when self-service organisations change the form element configuration(Single to Multi-select, repeatable to non-repeatable) of question type(Coded or QuestionGroup) without knowledge, the app breaks.

### Analysis:
Should not allow to change them since anyways 'app designers' can always create new form elements and migrate the data to it.

### AC: 
- When Type selection(multi/single select) on coded concept changed or when 'question group' concept made from Repeatable to non-repeatable(or vice-versa) show message under Repeatable or Type element(in coded concept) stating 'Cannot modify this directly. To proceed with this change, contact support team if there exists important data for this Question, else delete this question and create a new one and associate it with a different new concept.'

<img width="1174" alt="Screenshot 2024-08-06 at 12 21 58 PM" src="https://github.com/user-attachments/assets/03ad4d31-e77b-4b01-9821-62eeda7d0ee3">

<img width="1213" alt="Screenshot 2024-08-06 at 12 21 19 PM" src="https://github.com/user-attachments/assets/23c02afb-9a21-483b-ad0a-9f27b3d13748">

#### Example mockup for showing error message:

![Image](https://github.com/user-attachments/assets/1c2e4ddb-e325-489a-9eed-5c98c46a0da1)

- The above should happen when editing an already existing/saved form, not when changing the type or repeatable before saving the form for the first time.

### Out of scope:
Introducing new data types that will support switching between types.

### Analysis notes:
- Should we do this as bg job? No, since difficult to migrate client data
-  or just disable, - No, might cause confusion
- Handling in product(without migration) doesn't seem to be a good idea since we need to do at rule execution, displaying in both mobile and web app - many places to handle - so No
- disallow only for prod - No, confusion bcoz inconsistent across orgs
- allow when there is no data - No, if allowed, then need to handle during bundle upload since the destination org, may have data
- so just disallow with proper error message(try with new form element/concept) on the workaround

### Suggestion:
- One thing I see we can do is, store multi-select, single-select, RQG, QG etc., in the same format ie., array or whatever, and use an attribute to determine the logic what to do
- Need not migrate the existing data, instead when we see a object in place of array, treat it accordingly.
- We cant by default have everything as multiselect since it depends on the business use case.
- concrete egs why it was needed to change
- we 'll not scale now

**Comment by vinayvenu** [comment]
If no forms have been filled, we can allow the change.

**Comment by petmongrels** [comment]
### UX Inputs
- in cannot use the same concept twice, name of concept will be required by user to resolve the problem.
- in cannot change the type, we should provide the name of the form element with group name to pin-point the issue

**Comment by mahalakshme** [comment]
@petmongrels in cannot change the type, we should provide the name of the form element with group name - if the error message is going to be near the place where change has happened, pin-pointing might not be needed. Thought so and hence didn't mention the same in the message.

**Comment by 1t5j0y** [comment]
Fixed form validation server side error messages to include more information of the offending elements. Kept webapp error message as-is.

**Comment by dinesh2096** [comment]
- [ ] When we change the non to repeatable then the error in not display under the form element instead it is display at the top of the form the error message is also looks different
- [ ] And also error message still display if we also revert the changes and saved it 
- [ ] Suggestion for repeatable can we align error it looks clumsy with more space and not aligned properly 

Reference video : 

[Click here to watch the video](https://drive.google.com/file/d/1Amt_7GxUTMcjmC5n1ex7WeFCFTxwb_WI/view?usp=drive_link)
