### ISSUE TITLE
Being able to configure subject type filter on 'Last 24 type' cards

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1263]
### AC:
- Similar to https://github.com/avniproject/avni-webapp/issues/1203
- Should work for standard report cards 'Last 24 hour registrations', 'Last 24 hour enrolments', 'Last 24 hour visits'
- Rename the standard report card types in the dropdown to 'Recent registrations', 'Recent enrolments', 'Recent visits'
- For 'Configuration 1', consider the below points:
          1. When any of the 3 recent card types selected, subject type, program and encounter type filters need to display based on what is applicable for the selected subject type 
                  - Initially when the above standard report card types are selected, show 'Subject type' filter alone.
                  - Based on the subject type selected, show any programs if applicable, in the programs filter, and general encounter types in the 'Encounter type' filter.
                  - Based on the program selected, show program encounter types as well, in the 'Encounter type' filter.
                  - Should be able to save without anything selected in 'Subject Type' filter as well.
          2. When recent visits selected, provide a 'relative date' range filter(like in the image below)
                  - Similarly, When recent registrations selected, instead of 'Encounters in last', it needs to be 'Registrations in last'
                  - When recent enrolments selected, instead of 'Encounters in last', it needs to be 'Enrolments in last'
                  - Options are months, weeks and days - not years
                  - Should not be able to save without anything selected in the date range filter
                  - By default show '24 hours'
                  - Similar UI element used in setting numeric abnormal values.
                  - Should be able to set only positive integers, 0 or negative nos should not be allowed
          3. Should be able to select any colour from the colour picker.
- For Configuration 2, nothing needs to be done here since already done.

![Image](https://github.com/avniproject/avni-webapp/assets/10369963/682dd5dc-80a9-4dc7-914e-66feabd365d5)

**Comment by 1t5j0y** [comment]
pending: dev testing on bundle

**Comment by petmongrels** [comment]
1. org.avni.server.web.contract.ValueUnit#toJSONString can use ObjectMapper json serialisation method
2. org.avni.server.service.CardService#buildDurationForRecentTypeCards - since the input is internal to the system it is expected always that the string will not throw exception. If it will throw exception then it should be handled explicitly. If it will not throw exception unless there is a bug, we should let the exception break the system.

**Comment by 1t5j0y** [comment]
Addressed code review comments.

**Comment by AchalaBelokar** [comment]
- [ ] Login with Maha@APF

1. click on offline report card 
2. toggle the button stander report card
3. Encounter in last is not showing in the report card



![Image](https://github.com/user-attachments/assets/ef4f585b-7363-4f80-919a-a484b5b6d642)

**Comment by 1t5j0y** [comment]
@AchalaBelokar please go through AC on this card. The card types have been renamed.
