### ISSUE TITLE
Error on Downloading Bundle - Object Error Displayed

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-webapp#1264]
When attempting to download the bundle for shelter, an object error is displayed, preventing the download from completing successfully.

env : prod 
org : shelter
user : dinesh@shelter

Steps to Reproduce:
1.login to the org 
2.click on the app designer 
3.click on the bundle 
4.Click on the download

expected result : The bundle for shelter should download without any errors.
Actual result : An object error is displayed, and the bundle does not download.

<img width="1710" alt="Screenshot 2024-06-21 at 5 55 35 PM" src="https://github.com/avniproject/avni-webapp/assets/127730126/e823ff9b-b89e-4bf5-bab6-9a4b8098df41">

**Comment by 1t5j0y** [comment]
Issue was due to forms with duplicate names present in shelter prerelease. Voided the duplicate forms. No code fix.
