### ISSUE TITLE
View Subject Profile Dashboard

### ISSUE THREAD

**Issue by arjunk** [avniproject/avni-webapp#127]
### Motivation
As a user I should be viewing subject profile Dashboard 

### Acceptance Criteria
The dash board should display individaul subject profile

### Tech Approach
This should be implemented using Avni Data Models

Also include Navigating between relative dashboards

This should be using Avni Model structure

**Comment by github-harshal-ghisad** [comment]
1. Validate Subject registration and its details

2. Validate Subject relative and its details
