### ISSUE TITLE
Fixes for dashboard cards

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1283]
### Need:
Some of the fixes for dashboard cards were done in 10.0, since there were many changes in it. But implementors are facing many issues because of this. The testing is done in UAT and the bundle is just imported to prod. These issues are leading to retesting on prod and unexpected results. If this leads to manual update of database leading to conflicting UUIDs between UAT and prod, this will also result in issues. So, its better to fix them sooner.

### AC:
So the fixes for below issues need to go as part of 9.1.0:
  - https://github.com/avniproject/avni-webapp/issues/1235
  - https://github.com/avniproject/avni-webapp/issues/1210 - If the pull requests in this card doesn't fix the issue, then fix the issue.
  - https://github.com/avniproject/avni-webapp/issues/1265

**Comment by petmongrels** [comment]
too many merge issues. aborting this card.
