### ISSUE TITLE
Rules and corner secnario is not behave as expected 

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-webapp#1286]
The rule applied in the web app, date functionality, and corner cases does not behave as expected 

env: prod 
org: adjnpctuat
user: dinesh@adjnpctuat

Note: the customer is doing the backfilling data and they have asked if we should not schedule any visit if the scheduled date .register and enrollment date > 31/Aug/2024

2. Steps to reproduce: (scenario if the age is 10 )

1. Login to the app
2. Register the individual with the age of 10 
3. once we have saved the individual the enroll option should be displayed

expected result: The enrollment option should be displayed 
Actual result: enrollment option is hidden 

Reference video : 

https://github.com/user-attachments/assets/4af0cde2-1ecb-4a45-8a1c-291b12837adb

3. Steps to reproduce: (edit enrollment )

1. Login to the app
2. Register the individual with the date as 31 /Aug/2024 
3. enroll on 01/Sep/2024 and the visit will be scheduled on the same date
4. edit the enrollment to 31/Aug/2024

Expected result: visit should be scheduled 
Actual result: The visit is getting scheduled with the backfilling date

Reference video : 

https://github.com/user-attachments/assets/9eda4195-af41-4c4d-8228-5dcb81fe6635

### Analysis:
- Seems similar to [this](https://github.com/avniproject/avni-client/issues/1237) issue fixed in client.

**Comment by mahalakshme** [comment]
@Dinesh2019 for gender autofilling even in mobile app if you select Male, it is filling Female. The form element rule seems to be incorrect.

**Comment by mahalakshme** [comment]
Just commenting here for later reference: Another issue raised: 'Child Followup' again getting scheduled on editing enrolment. 
- Root cause: encounters of enrolment not accessible in DEA
- Solution: Issue might not occur when entering backdated entries since the enrolment date will anyways be before the upload date.  Dinesh will confirm the same with Anjali.
