### ISSUE TITLE
Vaccination Checklist not working properly

### ISSUE THREAD

**Issue by vedfordev** [avniproject/avni-webapp#1288]
**Describe the bug**
**"dependentOn"** flag not working properly.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to ck_uat vaccination checklist
2. search **Albendazole 3** and add ```"dependentOn": "bf5d2cdb-0713-4005-8135-d757e8b68707",```
3. Sync in the mobile app
4. The dependentOn added above is not respected when displaying the Vaccination Checklist.

### Root cause:
- check in backend - dependentOn will be not be updated. ```select * from checklist_item_detail where uuid = 'ea4a2663-4a1f-4a59-b76e-c996a49a35af';```
- It shows in web-app but if you try to shit + command + r , again it remove dependentOn.

**If we are updating via backend :**
1. add dependentOn via backend ```UPDATE public.checklist_item_detail SET dependent_on = 1166, last_modified_date_time = now() WHERE id = 1173;```
2. check the updated value.
3. go to web-app form 
4. do some change ex change **minDaysFromStartDate** and save.
8. again check it removes dependentOn.

Also check is_voided also working weirdly.

### Analysis:
Try to follow the same steps above to reproduce the issue since the issue doesn't occur always.

**Expected behaviour**
1. Vaccination checklist should work properly.
2. Check everything thoroughly 

**Test Data**
[card](https://github.com/avniproject/calcutta-kids/issues/204)

**Comment by 1t5j0y** [comment]
@vedfordev `dependentOn` for 'Albendazole 3' is getting saved correctly if 'Albendazole 2' is present in the json before 'Albendazole 3'. Just mentioning so you are not blocked and have a workaround. Continuing to look at this issue to see if further fix is required.

**Comment by vedfordev** [comment]
@1t5j0y Done with the changes. currently it is working fine but it randomly set the order.

**Comment by 1t5j0y** [comment]
@vedfordev We've put in a fix as part of this card to make the order of items in the JSON irrelevant.
