### ISSUE TITLE
Creating organisation with same name not handled

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-webapp#1289]
### Need:
So far 3 times, this issue has been raised by different people. To make our work process smooth.

**Describe the bug**
Not able to create organisation through super admin on staging  
Login with admin and try to create a organisation 
it is showing communication error

**To Reproduce**

1. Login with admin user
2. Click on  organisation
3. try to create a organisation with the same name as already existing organisation.

https://github.com/user-attachments/assets/e9f29c71-1e57-4ac7-a6e1-df025eb5771a

**Expected behaviour**
- Show error message under the Name field stating 'Organisation with the same name already exists. Please try with a different name.'
- The below common message 'The form is not valid. Please check for errors.' also need to show.
<img width="1504" alt="Screenshot 2024-08-05 at 5 59 25 PM" src="https://github.com/user-attachments/assets/001d5004-3ade-4d21-8215-a0e90be1aa8b">

- The above issue happens for same dbname, schemaname, etc as well - Handle them like the above.
- Handle other additional validations applicable to db_user also - comment on the same.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Developer Checklist**(Developer fixing the bug should fill this checklist)
- Does the fix require extensive regression testing?
  - [ ] Yes
  - [ ] No
- Are you mentioning the required scenarios that could be affected?
  - [ ] Yes
  - [ ] No

**Comment by 1t5j0y** [comment]
@AchalaBelokar please try with another org name. There is already an org with the name 'testbun'

**Comment by mahalakshme** [comment]
since it should 've shown a readable error message ll schedule it in a different release

**Comment by vedfordev** [comment]
Tried with CustomToolbar and other approaches still not working

**Comment by 1t5j0y** [comment]
@vedfordev please share the commit(s) for this issue. Couldn't locate them

**Comment by vedfordev** [comment]
> @vedfordev please share the commit(s) for this issue. Couldn't locate them

@dinesh2096 by mistake moved to review. it is in progress.

**Comment by dinesh2096** [comment]
@mahalakshme  

- [ ] i hope for report and ETL we are using Schema name i think we should not allow the duplicate as well.
- [ ] As we going to handle the case sensitive.
- [ ] If we are going to handle the case sensitive then we have to  handle the user errors as well means if the user created the org as
test and wants to change to Test then wat happen .
- [ ]  Are we going to allow the duplicate org in the organisation group

**Comment by mahalakshme** [comment]
@dinesh2096 moving to hold until I reply

**Comment by mahalakshme** [comment]
@dinesh2096 

- yes for username suffix and schema name as well we should not allow duplicates
- we need not do case insensitive comparison.

**Comment by mahalakshme** [comment]
@vedfordev please find my comment above

**Comment by vedfordev** [comment]
> @vedfordev please find my comment above

@dinesh2096 added constraint and notification.

**Comment by vedfordev** [comment]
@mahalakshme server migration causing issue due to there are many org with usernamesuffix blank and duplicates. 
```sql
SELECT username_suffix,count(id)
FROM public.organisation
group by username_suffix
having count(id) > 1
;
-- 24 with null

SELECT schema_name,count(id)
FROM public.organisation
group by schema_name
having count(id) > 1
;


select *
from organisation
where username_suffix is null
;

```

**Comment by mahalakshme** [comment]
@vedfordev I will move this back to 'In Analysis'. Will get back on this.

**Comment by mahalakshme** [comment]
@vedfordev we need not add unique constraint for username suffix

**Comment by vedfordev** [comment]
> @vedfordev we need not add unique constraint for username suffix

@dinesh2096 please check this and UI Changes are on branch 10.2

@mahalakshme I reverted the migration change in master [Link](https://github.com/avniproject/avni-server/commit/0ec3fe734231a7c44b271a9d25cf8fe9f2e1a933)

**Comment by dinesh2096** [comment]
Still we can able to create the duplicate value for Username and Schema name 

<img width="1710" alt="Image" src="https://github.com/user-attachments/assets/4f60fa68-aa22-4489-ba58-a5c17f09e6d9" />
