### ISSUE TITLE
New Encounter

### ISSUE THREAD

**Issue by arjunk** [avniproject/avni-webapp#129]
### Motivation

As a Avni user, the field service worker will be able to create New encounter using the Avni web app to track the subject any time visit.

Note Prerequisite:
Admin app should have forms configured for type: encounters for Subject Type : Individual
Subject should be registered to Avni
Search Subject and View Subject Dashboard - > General tab: Planned and Completed Visits sections.

### Acceptance Criteria:
1. Given a user is on Subject Profile Dashboard, General tab, then System should allow to click on "New Form" 
2. On New form, user should be able to click on the visit form and fill out and save the details. On save successfully, Show success message as a toast and not a popup. Success message should be "Encounter details saved"
3. While filling up the form, 
Encounter Date field should be set to today by default
User should be able to change the encounter date. It can’t be set in future. It can’t be before enrolment date or registration date.
All the standard form validations should apply
If the api returns an error when saving then keep them on the last page only and don't redirect to the dashboard.
4. On successfully adding details and save, Show toast with message:"Visit details saved" and redirect to Subject General Dashboard - completed visit section. If the api returns an error when saving then keep them on the last page only and don't redirect to the dashboard.

### Visual Design
Please refer slide 44,45

**Comment by Sayali-Dev** [comment]
:

**Comment by Sayali-Dev** [comment]
As cannot update user story into description for now putting it into the comment.

As a Avni user, the field service worker will be able to create New General encounter using the Avni web app to track the subject any time visit.

The process for this should be as follows:

1. Register the Subject if new Subject 
Note: If not new Subject, Search Subject and View Subject Dashboard.

2. Create New Encounter
- To create new encounter:  Under ""General" Section on Subject Dashboard, Create a New visit, fill out the details for the visit and Save.
- Mandatory Fields for Visit Details should be:
Visit name
Visit Date and Time
Action: "Edit Visit"
Visit Type << value can be ""Encounter"", to identify encounters from unplanned visit of a program>>
[[VDs are pending for Create Encounter ]]

3. View the Visit details. 
This can be shown under "Unplanned Visits" on "General" section. 
[[ Finalized VDs pending ]]

Following minimum rules should exist:
- not allow a subject to be registered again
- not allow create a duplicate encounter visit for same subject
Display appropriate suggestive message in case of popup.

Few clarifications on this story summary description as confirmed with Sridhar:
Is "New General" meaning "New Subject" ? Yes
Is "New General Encounter"" a planned or unplanned visit ? Its unplanned visit not on a program.
So Need to update summary to :"New Subject Encounter"
