### ISSUE TITLE
Should be able to delete location type when no locations of that type exist

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1290]
### As is:
Currently when a location type once created in App designer cant be deleted

### Need:
For someone who is new, when they have set the hierarchy incorrectly when newly trying to setup, it becomes irreversible for them and leads to confusion

### AC:
<img width="1508" alt="Screenshot 2024-08-05 at 5 21 08 PM" src="https://github.com/user-attachments/assets/400c82b7-8b5e-4e8e-8119-78948f0acb9d">

- DELETE icon needs to be enabled always.
- When no locations of that type exists, user should be able to delete that location type.
- When locations exist, show error message(toast message in the bottom) stating that 'Locations of this type exists. Delete them to proceed further.'

**Comment by dinesh2096** [comment]
- [ ] When we added the parent type for the location type and try to delete it we are getting a error 

![Image](https://github.com/user-attachments/assets/3015f4fd-e7f1-4e5e-bac5-8e569656b484)

- [ ] And also if we deleted the location type by mistaken if the user want to readd the error is displayed 

![Image](https://github.com/user-attachments/assets/cf28c12a-c71d-4298-a47b-7bcca34c1e98)

**Comment by 1t5j0y** [comment]
Fixed 2nd issue by renaming address level type on deletion so same name can be used again for a new address level type.

Unable to simulate the 1st issue - was able to delete child type when it did not have any children or levels of that type. The error message in the screenshot is not the latest so perhaps there was incorrect version of server deployed while testing.

**Comment by dinesh2096** [comment]
- [ ] Still we are getting the same error 

[Click here to watch video](https://drive.google.com/file/d/15PUSDmOBb6upB7bXL4gzLJFTiifDbHR1/view?usp=drive_link)

**Comment by mahalakshme** [comment]
@1t5j0y good to mention last_modified_by_id also I think, Previously when something via migrations have gone wrong it was with this, able to find a pattern and identified the root cause. Let me know if you think otherwise.

**Comment by 1t5j0y** [comment]
good to have but not necessary for this particular one in my opinion since we are only touching already voided entities. Also, migrations should use last_modified_by_id 1 to differentiate migrations from manual fixes.

Maybe we need `manual_update_history` column for non transactional tables too.

**Comment by mahalakshme** [comment]
yeah agreed

**Comment by dinesh2096** [comment]
QA References : 

[Click here to watch the video](https://drive.google.com/file/d/12RW3DqZ9hfWtV2BMmxOT0AYzWCxHZHFn/view?usp=drive_link)
