### ISSUE TITLE
After uploading the metadata zip file. status showing wrongly on staging

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-webapp#1293]
**Describe the bug**
After uploading the metadata zip file. status showing wrongly
Login with maha@APF the I download the bundle 
upload it shinu org status is confusing the user

**To Reproduce**

1. Login with AchalaB@shinu
2. upload this bundle to that organisation [APF (3).zip](https://github.com/user-attachments/files/16347874/APF.3.zip - downloaded from staging
3. See error
[errors-APF (3).csv](https://github.com/user-attachments/files/16347887/errors-APF.3.csv)
4. Issues noticed above are the below:
  -  creates 2 status rows like in the image below, one with filename, and another with no filename 
  - Also fix any errors in the failure file - looks like regression issues related to dashboard

**Expected behavior**
Error message should be completed or error not the both.

**Screenshots**

https://github.com/user-attachments/assets/f43ca4a8-faf9-4876-bd4c-e2c1767277f1
![Screenshot 2024-07-23 at 4 53 35 PM](https://github.com/user-attachments/assets/3cdfdf1f-fa5f-4fb0-b307-8c5deb1dd1f0)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Developer Checklist**(Developer fixing the bug should fill this checklist)
- Does the fix require extensive regression testing?
  - [ ] Yes
  - [ ] No
- Are you mentioning the required scenarios that could be affected?
  - [ ] Yes
  - [ ] No

**Comment by petmongrels** [comment]
separated this issue in its own card - https://github.com/avniproject/avni-server/issues/769
