### ISSUE TITLE
When a report card with already existing name created show proper error message

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1297]
Need to fix the comments and merge the PR. The contributor is missing.

### Issue:
Create a report card with same name as non-voided existing report card. The below issue happens.
![Image](https://github.com/user-attachments/assets/57a75963-341b-4cb0-b076-4bcb4ccc9e81)

### AC:
Show error message stating 'Report card with same name already exists' in the place where 'Name cannot be empty' is shown in the image below (or) when handling all these issues at server side is easier, then we can just show a common toast error message at the bottom if that will simplify the work across if in any new entities we face this issue.

<img width="902" alt="Screenshot 2024-08-06 at 1 18 15 PM" src="https://github.com/user-attachments/assets/f9be48c7-d2cb-41d5-8d51-cb489301bd86">

**Comment by mahalakshme** [comment]
@Bhushan-Thombre sure you can work on it

**Comment by Bhushan-Thombre** [comment]
@mahalakshme Kindly review the below PR.
https://github.com/avniproject/avni-webapp/pull/1301

**Comment by himeshr** [comment]
@petmongrels Created this draft sql script for fixing the duplicate report_cards
https://github.com/avniproject/data-fixes/blob/main/all/duplicate_report_cards.md

**Comment by dinesh2096** [comment]
- [ ] Need to handle the case sensitive.
- [ ] when we edit the report card to the already existing report the web app displays the error 


[Click here to watch video](https://drive.google.com/file/d/1Aa1dq4Vv9dhcFP2s5MwYTOg1PTiugpWX/view?usp=drive_link)

**Comment by mahalakshme** [comment]
@himeshr @petmongrels In the SQL migration as well as in UI check, should be able to create a new report card, if the report card with the same name was voided before. Will make the AC more explicit next time.  But have mentioned in the issue.

**Comment by himeshr** [comment]
We already rename voided report cards to include suffix voided~id. 
And with the existing unique constraint and case-insensitive check in sever, we should not be able to create cards with same name for an org.
Not adding case-insensitive unique constraint using unique index, as it could fail transactions with updates of multiple report-cards

**Comment by himeshr** [comment]
### SQL command to find already existing report-cards with case-insensitive match within same org.

```sql
select o.name, lower(rc.name), count(*)
from report_card rc
join organisation o on rc.organisation_id = o.id
    where not rc.is_voided
group by 1,2
having count(*) > 1;
```

In prod all report-cards are in decomissioned UAT orgs.

**Comment by dinesh2096** [comment]
**Query :** 

- [ ] if we already created dashboard and if we try to edit it then error is popping up (eg : One card created as dummy and if the want change the name as Dummy then the error is showing as Report card already exists ) if so users want to rename the card then they want to delete and recreate the card 


**QA Reference video :** 



[Click here to watch the video](https://drive.google.com/file/d/16O3flplIkPs5TmEZhRfhcSIzUdO-VSOt/view?usp=drive_link)

**Comment by himeshr** [comment]
Have fixes the case reported here..

> **Query :**
> 
> * [ ]  if we already created dashboard and if we try to edit it then error is popping up (eg : One card created as dummy and if the want change the name as Dummy then the error is showing as Report card already exists ) if so users want to rename the card then they want to delete and recreate the card
> 
> **QA Reference video :**
> 
> [Click here to watch the video](https://drive.google.com/file/d/16O3flplIkPs5TmEZhRfhcSIzUdO-VSOt/view?usp=drive_link)

**Comment by dinesh2096** [comment]
QA References : 

[Click here to watch the video](https://drive.google.com/file/d/1mcdO0CuntnmvMWWEz-6VICu42wwHwHOi/view?usp=drive_link)
