### ISSUE TITLE
Register a subject

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#13]
In scope
--------
From the search screen, the add button must take you to a listing of different subject types. Clicking on appropriate subject type takes you to the registration screen.
Registration screen must contain the following types of form elements.

 - Numeric [done]
 - Text [done]
 - Notes [done]
 - Date [done]
 - DateTime [done]
 - Time [done]
 - Duration [done]
 - SingleSelect [done]
 - MultiSelect [done]

Out of scope
-------------
 - Form elements Image, Id and Video
 - Storing of location
 - Validation (mandatory, range, regex)
 - Implementation hooks (visibility filter, calculated fields, decisions)
 - Ability to choose address of the Subject ( a separate card is there)

Notes
------
 - Use openchs-models for data
 - Keep reference data in memory

Workdone
------

date of registration should be current date by default - [done]
date of birth should have age - [done]
test with multiple subject types - [done (almost)]
multiple form element groups - [done]
add previous button on first page of form - [done]
other field types - [done]
handle non Duration FormElements [done]
fix underline in previous and next [done]
tests for new adapters for operational modules [done]
remove Linebreaks in SubjecrRegister

**Comment by sidsamanvay** [comment]
On hold. Deprioritized.
