### ISSUE TITLE
'Id' concept type search filter not supported on DEA

### ISSUE THREAD

**Issue by 1t5j0y** [avniproject/avni-webapp#1303]
https://avni.freshdesk.com/a/tickets/4364

If a search filter with an 'Id' concept type is configured, DEA load breaks.

Tech details:
'Id' type filters [not mapped](https://github.com/avniproject/avni-webapp/blob/f67cd6e14289d54c22bb11708b0f1cbea10cf632/src/dataEntryApp/views/GlobalSearch/SearchFilterForm.js#L340) or considered while rendering search filters

**Comment by petmongrels** [comment]
support for Id concept data type was missing

**Comment by AchalaBelokar** [comment]
- [ ] I login with AchalaB@iphscd and added search filter with id search filter is not showing on search  screen..

**Comment by 1t5j0y** [comment]
id search filter visible on prerelease.

![Image](https://github.com/user-attachments/assets/0fe6f255-5df5-4b5a-b828-2fff5812f84d)
