### ISSUE TITLE
Add more catgories

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1304]
### AC:
- Add 'Training' and 'Dev' to the category list of 'Prototype, Trial, UAT, Production and Temporary'
- Sort in alphabetical order along with other categories.
- Move these categories to db

**Comment by AchalaBelokar** [comment]
- [ ] sorting is not working there..

![Image](https://github.com/user-attachments/assets/98897873-0583-4701-aa40-1fe802eada25)

**Comment by himeshr** [comment]
After discussion we've decided that the issue found is not a blocker for 9.2 release.

**Comment by AchalaBelokar** [comment]
- [ ] still sorting is not working I deployed latest commit

**Comment by petmongrels** [comment]
There are two places where the sorting is present.
1. In the org list one can sort by category
2. when creating / editing org the dropdown should have sorting

both are fixed now
