### ISSUE TITLE
Analytics status is not showing on prerelease..

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-webapp#1305]
**Describe the bug**
Analysts status is not showing on prerelease.

<img width="1427" alt="Screenshot 2024-08-07 at 8 00 13 PM" src="https://github.com/user-attachments/assets/915316d8-1baf-477c-adcb-358d9ef9e928">

**To Reproduce**

1. Go to  organisation 
2. and check the analytic 
3. Click on '....'
4. Scroll down to '....'
5. See error

**Expected behavior**
status should be shown 
**Test Data**
Give details of example users, environment detail, username against which this issue is happening.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Developer Checklist**(Developer fixing the bug should fill this checklist)
- Does the fix require extensive regression testing?
  - [ ] Yes
  - [ ] No
- Are you mentioning the required scenarios that could be affected?
  - [ ] Yes
  - [ ] No

**Comment by himeshr** [comment]
<img width="1728" alt="Screenshot 2024-08-08 at 11 20 09 AM" src="https://github.com/user-attachments/assets/a21da8f3-e259-43e7-8fe7-5304ee69fcad">

After fix screenshot.

**Comment by himeshr** [comment]
Marking as done as the issue resolution is confirmed with this comment 
https://github.com/avniproject/avni-webapp/issues/1305#issuecomment-2275004620
