### ISSUE TITLE
Error handling by code review

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1306]
### Need:
We see that many error handling scenarios for CSV upload not done. Since there are many combinations of errors that can happen, it is easier to identify them via code review and fix them than by manual testing.

### AC:
- Error scenarios for CSV upload of 'Users and Catchment' and Locations upload need to be handled.
- Errors shown on the error CSV file need to be a human readable message and should not have technical details like null, etc.,
- Any issue covered as part of AC in other cards, need to show error messages as mentioned in the AC of that corresponding card since the error messages were well thought thru'.

### Out of scope:
Error handling in other CSV files

**Comment by mahalakshme** [comment]
Issue in this: https://github.com/avniproject/avni-server/blob/master/avni-server-api/src/test/java/org/avni/server/importer/batch/csv/writer/BulkLocationEditorIntegrationTest.java 

- 'Parent location with full hierarchy' is required - should not be showed as error and should pass - since it is not a mandatory field - only for mandatory field we need to show the error - already an AC as part of a different card

--------------------
Issue in this: https://github.com/avniproject/avni-server/blob/master/avni-server-api/src/test/java/org/avni/server/importer/batch/csv/writer/UserAndCatchmentWriterIntegrationTest.java
Regarding the below:
```
  hasError("Invalid or Empty value specified for mandatory field Track Location"),
 hasError("Invalid or Empty value specified for mandatory field Enable Beneficiary"
```
Track Location and Enable Beneficiary are not mandatory fields. We can show similar error like for other fields

**Comment by mahalakshme** [comment]
@petmongrels added the above comment. Forgot to mention - so this msg

**Comment by petmongrels** [comment]
moved to code review, without handling the comments.
Will take care of them when everyone has provided feedback.

**Comment by petmongrels** [comment]
> Issue in this: https://github.com/avniproject/avni-server/blob/master/avni-server-api/src/test/java/org/avni/server/importer/batch/csv/writer/BulkLocationEditorIntegrationTest.java
> 
> * 'Parent location with full hierarchy' is required - should not be showed as error and should pass - since it is not a mandatory field - only for mandatory field we need to show the error - already an AC as part of a different card

not able to follow which test this is referring to

**Comment by himeshr** [comment]
Testing note:
Basic sanity only required for Locations upload and UserAndCatchment upload.

**Comment by AchalaBelokar** [comment]
@petmongrels pls check this test cases this is written by dinesh some test cases I think already cover which I click right.
- [ ] Can we add the without space scenario in the test case.
- [x] Can we have the scenario with and without mandatory fields.
- [ ] Can we have the validation for location creation what if we have small and upper case scenario for example (bIhAr giving this as input but actual input should be Bihar or Bihar)
- [ ] Can we validate GPS Coordinates with an empty string, with an alpha character.
- [x] Can we have the validation same address with upper case and lower case
- [ ] Can we have the validation for the same gps coordinate but different location and same location with same coordinates
- [ ] Can we have validation to update the high-level hierarchy eg : state,district,block(KA,Ban,test to KA,dek,test)
- [ ] Can we have validation of valid address with invalid GPS coordinates

**Comment by petmongrels** [comment]
3. each case will be a different location, so we cannot add this.
6. we have no such validation in our system
7. Only lowest level rename is supported in one row. this can be achieved by KA,Ban to KA,dek
8. it is already there.

**Comment by mahalakshme** [comment]
@petmongrels 
3. We already did case insensitive location matching - It should work already. Bihar, BIHAR, etc., will be treated the same. Creating different locations caused many issues in RWB so we had done this

**Comment by himeshr** [comment]
Completed sanity testing for:
- User and Catchements bulk upload
- Create locations bulk upload
- Edit locations bulk upload
