### ISSUE TITLE
Make the error message user-friendly

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1314]
### Issue:
When trying to create a location with already existing name, unreadable parts like uuid and isVoided shows up. 

![Image](https://github.com/user-attachments/assets/0284cfdf-e3c4-4b25-bdfd-4c6935848d2b)

### AC:
- Do not show things within the brackets in the above image in the error message
- Also don't show such object text in any error messages or in bundle upload

### Need:
Our website should have a professional look and should be easy to use, already the workflow and navigation of pages are difficult for users.

**Comment by 1t5j0y** [comment]
uuid etc added to aid debugging of bundle upload failures as part of #1293. Needs discussion on handling.

**Comment by AchalaBelokar** [comment]
- [ ] Try to create a location  manual in lahi organisation when create a block under district but district list is undefined.

**Comment by 1t5j0y** [comment]
@AchalaBelokar this was already fixed. Please retest after deploying latest avni-server master branch to staging.
