### ISSUE TITLE
[DEA] Location concept support issue

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1316]
https://avni.freshdesk.com/a/tickets/4364

### Need:
- Seems like when location of lower location type is not known, higher location type will be set for the org in focus.
- To handle the already (incorrectly)set values, independent of the implementation issue.

### Issue:
No support in DEA LocationFormElement for Location type concept with 'highestAddressLevelTypeUUID' set. [Only levels of 'lowestAddressLevelTypeUuids' are accepted](https://github.com/avniproject/avni-webapp/blob/ad0c877fe3b692c6dd3ac9a47747fa8c345b55ce/src/dataEntryApp/components/LocationFormElement.js#L27) and the component [breaks](https://github.com/avniproject/avni-webapp/blob/ad0c877fe3b692c6dd3ac9a47747fa8c345b55ce/src/dataEntryApp/components/LocationFormElement.js#L38) when handling a level of a higher type.

### Steps to reproduce:
org: IPH Sickle cell
search Participant 'Thanya' -> Profile-> Registration-> edit ->  next -> you will get the below error page

![Image](https://github.com/user-attachments/assets/16a6faed-d469-4c43-9ad9-01b3e05995ac)

### Out of scope:
Implementation issue.

**Comment by petmongrels** [comment]
I noticed there is a bug in form element status rule which is not allowing edit of the location field.

**Comment by mahalakshme** [comment]
@petmongrels the above was communicated to the support team by Joy as part of the ticket. They will check with implementation team and resolve it. I informed the impl., team as well.

**Comment by AchalaBelokar** [comment]
- [ ] The value is not appearing in the location field after selection in the location concept
https://drive.google.com/file/d/19iQyM9zhcnZww1JRyfr3uC2B5xFI6JOH/view?usp=sharing

**Comment by petmongrels** [comment]
Registration form is not opening in this org. please test in some org which is correctly setup.

**Comment by dinesh2096** [comment]
Web app is getting is crashed 

[link i used to for deploy the webapp](https://app.circleci.com/pipelines/github/avniproject/avni-webapp?branch=10.1.0)


[Click here to watch the video](https://drive.google.com/file/d/1cj-BvzQDhpWlTPW171OXObfFzfKdMfxQ/view?usp=drive_link)

**Comment by himeshr** [comment]
## Test cases

### DEA, Within form, Location Form element
- Hierarchial mode
- - Single lowerAddressLevelTypes
- - Multiple lowerAddressLevelTypes
- - With HigherAddressLevelType set
- - Without HigherAddressLevelType set

- Regular search mode
- - Single lowerAddressLevelTypes
- - Multiple lowerAddressLevelTypes
- - With HigherAddressLevelType set
- - Without HigherAddressLevelType set

### App designer
- - Create and edit of Location concept with Multiple lowerAddressLevelTypes, old setting should be retained


### Known issue
- Unselect of Location is not supported in webapp
