### ISSUE TITLE
Issue when adding a sync attribute

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1320]
### Issue:
When adding a sync attribute value on UI, it shows [object Object] as the default value. Make it empty. Applicable for text and numeric sync attribute concepts.

![Image](https://github.com/user-attachments/assets/c2c1f031-f05f-41aa-afc7-f33deea8ae2d)

**Comment by dinesh2096** [comment]
When we changes the sync attribute the sync value is not reset only the attribute is getting changed.

Reference video : 

[Click here to watch video](https://drive.google.com/file/d/1iX1Z1ROoS717z_A7pnUhAqCY0JA-WMGz/view?usp=drive_link)

**Comment by 1t5j0y** [comment]
Invalid test case - If sync attribute is updated via query directly in the db, sync value cannot be expected to be automatically updated.

**Comment by dinesh2096** [comment]
QA Reference video : 

[Click here to watch the video](https://drive.google.com/file/d/1FoxAa1PofDRsrZMA8eWkfSui8AjDYOtk/view?usp=drive_link)
