### ISSUE TITLE
File preview failing for multi-select form element in data entry app

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-webapp#1325]
https://avni.freshdesk.com/a/tickets/4456

### about the fix
only supporting one preview right now, as we have made a lot fixes around this in later releases.
changes should not be merged

**Comment by 1t5j0y** [comment]
### QA Notes:
- Fix stops app from breaking
- File preview does not seem to have been modified in later releases so we could merge this
- We should put in a proper product fix to display multiple files in the preview if present

**Comment by petmongrels** [comment]
to be merged by with master

**Comment by mahalakshme** [comment]
@petmongrels I have added the above in release card, so will close this.
