### ISSUE TITLE
Wrong options while creating a new encounter type

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/avni-webapp#1328]
**To Reproduce**

1. Create two subject_types, let's say Person and Anganwadi.
2. Create a program against the Individual subject_type let's say "DNH-ECC".
3. Click on Create "New encounter type" to create a new encounter type, and select Household as the subject_type.
4. The next option is to "Select program", by clicking on the drop-down, among the options that it shows, there are those programs that have been created against a different subject_type as well.

**Expected behavior**
Ideally, depending on the subject_type that was selected while creating a new encounter_type, the options in the program should be filtered.

![Image](https://github.com/user-attachments/assets/a12bac71-f9a8-47e4-9d5e-bbfaeab8b55c)

**Comment by dinesh2096** [comment]
- [ ] We can able to see the program in different subject type while creating the encounter 
- [ ] And also we edit the encounter the edited details is not saved in the encounter.

Reference Video : 

[Click here to watch the video](https://drive.google.com/file/d/1uIpppqXbh6K7QHvKKC9bU58Y_NLFV1B2/view?usp=drive_link)

**Comment by 1t5j0y** [comment]
Issue due to bad form mapping data linking 'Test' program to 'Details' subject type. Issue does not occur when invalid form mappings are deleted.

**Comment by dinesh2096** [comment]
QA Reference : 

[Click here to watch video](https://drive.google.com/file/d/1UNVHZMcyLrihMsbJx1zW39xSux3Xabat/view?usp=drive_link)
