### ISSUE TITLE
New Program Enrolment

### ISSUE THREAD

**Issue by arjunk** [avniproject/avni-webapp#134]
### Motivation
As a Avni App user, I should have the ability to enroll a subject to program/programs.

### Acceptance criteria
Given I am logged  into Avni App, 
- When I navigate to the subject dashboard I should see an option to "Enroll in Program"
- When I click on Enroll in Program and select the program  then I should be shown the form page.
- When I am on the form 
  - fill up the form field details,
  - validations should run on data entered by user And In case of discrepancy, highlight the field in red and show apt error message and disable next until error is resolved
   - and Click Next for multiple pages of the form then on last page I should see "Summary and recommendations" sections with Observations details and I should be able to Save the form.
- On Save, Notification for enrolled successfully in <program name> should be displayed.
This success message notification, show as a toast and not a popup. Success message should be "Enrolment details saved"
- When the details are saved successfully then I should be able to view below sections for the Program enrolled on the Subject Dashboard, Profile tab
  - Program List (includes names of program enrolled), 
  - Summary
  - Enrollment Details 
Note: During enrolment,  - Visits Planned Section should be seen on last page under Summary and recommendations and on Subject Profile Dashboard once Visit schedule rules implemented - 139 Story

### Visual Design
Please refer slides 34, 35, 36, 37 at **Avni_Revised.PPTX** 

**Note:** As discussed with Hiren, GPS coordinates not to be shown even if seen on VDs.

**Comment by Sayali-Dev** [comment]
Updated below in acceptance criteria for feedback - popup should be toast, received from Arjun for 17/03-18/04 iteration:
Show success message as a toast and not a popup. 
Also added, Success message should be "Enrolment details saved"
