### ISSUE TITLE
[Documentation] DEA - remove sync attributes restriction

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1340]

**Comment by 1t5j0y** [comment]
Updated https://avni.readme.io/docs/sync-strategies#handling-on-data-entry-app-dea

**Comment by mahalakshme** [comment]
@1t5j0y 

- The setting doesn't allow us to override all sync settings, but only sync attribute settings. Catchment and assignment will still be respected
- Will be useful to mention that for edit, the old and the new - both settings need to adhere to user sync settings
