### ISSUE TITLE
[Visit Scheduling] Should be able to schedule a visit without conditions

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1345]
### Need:
Currently some condition in visit schedule dragdrop component needs to be mentioned for the rule to get generated. There are workarounds but they are not intuitive.

https://github.com/user-attachments/assets/0d92d4f5-f6c2-4005-8589-5f7a6e6f5eda

### AC:
- Should be able to schedule a visit from the drag-drop component, without any condition mentioned.
- If condition is only half-complete then it is fine to show error like currently done.

**Comment by 1t5j0y** [comment]
The change makes having a condition optional for any declarative rule.

**Comment by dinesh2096** [comment]
QA Reference video : 

[Click here to watch the video](https://drive.google.com/file/d/10yjYl7WBURujfsmLVFhN6f3BzY9nmeLH/view?usp=drive_link)
