### ISSUE TITLE
CSV upload issues of previous release

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1347]
1) 
#### Issue:
As part of a previous [card](https://github.com/avniproject/avni-webapp/issues/1213#issuecomment-2363556616), an extra condition was additionally implemented with respect to updating the parent of a location to be that of the same type as that of the previous one.

#### Analysis:
Especially in organisations with multiple hierarchies, during upload, it is possible to incorrectly upload, and they might want to correct it.

#### AC:
- On Edit of location, type of the new location can be different from that of the previous one. So the above check can be removed.
- And instead add this check: The new location, should be of type, of the immediate parent as configured in the location type. If not then show an error message. Eg: lets say Ahmednagar is the child location name mentioned as part of full hierarchy then the error message need to be "Only parents of location type 'A' is allowed for Ahmednagar."

2) 
#### Issue:
- The descriptor row is not the second row in the Edit Location sample file creating confusion regarding what can be retained and what needs to be removed.
- Same in create location sample file - Message indicating "Mandatory to mention the parent locations to which the location to be created belongs to" is in the placeholder row.

#### AC:
Refer the sample files in [this](https://github.com/avniproject/avni-product/issues/1531) card to know the order and the content - for create and Edit location sample files.

3) 
#### Issue:
In the upload status, read considers descriptor row also as one row, but like header row that needs to be ignored.

I uploaded only one row both times.
![Image](https://github.com/user-attachments/assets/82970282-ceb9-46cb-82db-c77270e81b50)

#### AC:
- In the rows read and completed - dont count the descriptor row
- applies for Locations create, edit, and Users and catchments upload.

**Comment by mahalakshme** [comment]
@himeshr you are right. I got confused with the case in Hasirudala Karnataka - Two children types can have same parent type, but a child type can have only one parent type. So this: "Only parents of location types A and B are allowed for Ahmednagar." is not valid.

**Comment by himeshr** [comment]
We have to spend considerable effort to optimize bulk upload of data, as currently the chunk size is set to 1 to perform proper error handling at every row level, which results in repeated invocation of common actions that should ideally be performed only once for each file upload or at the least once for a large chunk of the uploaded content.

**Comment by 1t5j0y** [comment]
AC for issue 1 not satisfied.
Prod org inslocation.
[errors-sample-locations(4)(1).csv](https://github.com/user-attachments/files/17829586/errors-sample-locations.4.1.csv)
