### ISSUE TITLE
Do not allow users in pre-release and staging environments to login using password=password (including in different cases) from the web app

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-webapp#1348]
- The check should be on the frontend
- Show a nice error message when this happens to the user with details of what they can do.

Simple workarounds are:
- login to the same user from prod and change password (only if these are not customer users)
- login via super admin or org admin and change password

**Comment by petmongrels** [comment]
not reviewed the code, but the message saying password change is required is too short. people will not know what is wrong.

**Comment by dinesh2096** [comment]
The user is not displayed with any error as per the AC 

Reference video : 

[Click here to watch the video](https://drive.google.com/file/d/15sFiUe7pqenwtKuu-L5P9-n3g0dDNFnn/view?usp=drive_link)

**Comment by dinesh2096** [comment]
QA Reference : 

[Click here to watch the video](https://drive.google.com/file/d/1yjSuZa_iM5C_NdXEbeEe0LHVrJKZa6CW/view?usp=drive_link)

**Comment by AchalaBelokar** [comment]
- [ ] I am not able to login with password  is password then I try to change the password with super admin login try to reset password it id showing me error. I am not able to reset the password.

**Comment by himeshr** [comment]
> * [ ]  I am not able to login with password  is password then I try to change the password with super admin login try to reset password it id showing me error. I am not able to reset the password. this is happening on prerelease

@AchalaBelokar , we cannot and should not perform password change in prerelease environment.

Test this card only in Staging environment.

**Comment by dinesh2096** [comment]
@AchalaBelokar closing this card as per the above comments
