### ISSUE TITLE
Edit Program Enrolment

### ISSUE THREAD

**Issue by arjunk** [avniproject/avni-webapp#135]
### Motivation
As a Avni App user, I need the ability to edit the Program Enrollment Details for a subject so as the details can be edited if needed.

### Acceptance criteria
Given I am logged in into Avni webapp,
- When I navigate to the subject dashboard I should see an option to Edit the enrollment details 
- When I click on Edit, 
  - I should be able to edit and update the form values. 
  - In case of discrepancy during edit, validations should run, highlight the field in red and show apt error message and disable next until error is resolved
- on save successfully, 
Show success message as a toast and not a popup.
Success message should be "Enrolment details saved"
- On successfully saving details, then I should find the updated details displayed on Subject Profile Dashboard

### Visual Design
Please refer slides 25

**Comment by Sayali-Dev** [comment]
Updated below in acceptance criteria for feedback - popup should be toast, received from Arjun for 17/03-18/04 iteration:
Show success message as a toast and not a popup.
Also added, Success message should be "Enrolment details saved"
