### ISSUE TITLE
Organisation Status "Live" or "Archived" not showing in the Status in the Avni Web Console

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/avni-webapp#1351]
**Describe the bug**
1. The status of an organisation whether it is Live or Archive should show on the Dashboard on Avni Web Console. status. But currently it is not showing. To see the status, you have to click on SHOW and go to the detail page to see the status.

**Expected behavior**
- Show the status "Live" or "Archived" on the Dashboard it self
- Also dont show addition Status label on clicking SHOW
<img width="336" alt="Screenshot 2024-09-30 at 2 55 23 PM" src="https://github.com/user-attachments/assets/006c0df6-edbd-4355-bf88-9552d49f814a">

**Test Data**
I have Archived Periodshala both UAT and Production environment on Web Console, as we are no longer using them. But I am not able to see the status on the dashboard

**Screenshots**

<img width="1470" alt="Screenshot 2024-09-30 at 11 01 50" src="https://github.com/user-attachments/assets/ae6bf77c-1328-4b0b-ae27-4ecb278bbad7">

**Comment by dinesh2096** [comment]
Getting the server communication error 

Reference video : 

[Click here to watch video](https://drive.google.com/file/d/1nJHx5gkdNdL643Hobsnw7YuLz5KAWKHh/view?usp=drive_link)

**Comment by 1t5j0y** [comment]
Able to change org status without any issues on staging.

**Comment by dinesh2096** [comment]
QA Reference video : 

[Click here to watch video](https://drive.google.com/file/d/1vQVHivGYqbhHD0vdMIbU89FS8uum6or_/view?usp=drive_link)
