### ISSUE TITLE
[For server side release] Not able to download error file from upload screen

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-webapp#1355]
**Describe the bug**
env: prerelease
Not able to download error file from upload screen
when I upload the file with some error .. when I am trying to download that file it is showing me error message
<img width="1394" alt="Screenshot 2024-10-04 at 6 55 36 PM" src="https://github.com/user-attachments/assets/1a7db6ab-dbc3-4794-a997-16c1be3d6443">

**To Reproduce**

1. Login with admin user
2. create csv file for user and catchment which having some error
3. upload that csv 
4. error with csv file is genrated
5. try to download that csv
6. see the error

**Expected behavior**
error file should be downloaded

**Test Data**
[Achalack.csv](https://github.com/user-attachments/files/17259046/Achalack.csv)

**Screenshots**

https://github.com/user-attachments/assets/cb7f3964-a5af-43dd-ab40-27d3fb497a66

**Comment by mahalakshme** [comment]
@AchalaBelokar with what user you are logged in as?

**Comment by mahalakshme** [comment]
@AchalaBelokar and what permissions does the user have?

**Comment by dinesh2096** [comment]
Video Refrences : 


[Click here to watch video](https://drive.google.com/file/d/1suVHG6RtCsHaTru3aWiuJ8C-emKvpx-U/view?usp=drive_link)
