### ISSUE TITLE
Unable to specify the part of the location to which new location needs to be added

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1364]
### Issue:
https://avni.freshdesk.com/a/tickets/4831

![Image](https://github.com/user-attachments/assets/e4982287-9712-4783-a518-e3f001f31bf3)

### AC:
- It should display the locations matching the type selected

**Comment by dinesh2096** [comment]
QA Reference video : 

[Click here to watch video](https://drive.google.com/file/d/1ptpVQedmkVR5OI34CkmD1SaUZsLYN7a9/view?usp=drive_link)

**Comment by mahalakshme** [comment]
- released to prod
- Updated release notes as part of 10.0.4 release
- merged the changes to 10.1.0
- merging to master resulted in merge conflicts, but anyways will get done, when we release 10.1.0
