### ISSUE TITLE
Hide Review button

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1366]
### Need:
Currently the feature developed by C4GT to analyse the metadata uploaded with what has been already uploaded, there are some bigger improvements to be made and issues to be fixed.

### AC:

Hide 'Review' button on webapp in Admin page that displays on clicking Admin -> Upload -> Metadata zip -> Upload a zip file.
![Image](https://github.com/user-attachments/assets/9035ec2a-8eda-4747-9921-9f2762848003)

**Comment by dinesh2096** [comment]
QA Reference : 

[Click here to watch the video](https://drive.google.com/file/d/1npEkjH5u7URm_swDCNnegkLq5VcB-ZpJ/view?usp=drive_link)
