### ISSUE TITLE
[DEA]  Breaking when clicking on any individual

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1367]
env: prod
user: maha@calcutta_kids, maha@cmhlp

### Analysis:
- Rules execution was failing because last week server went out of space and rules-server didn't recover after that
- So redeployed rules-server - but the job is failing

### AC:
Fix the failing job: https://app.circleci.com/pipelines/github/avniproject/rules-server/301/workflows/d83aebbd-d22b-475c-b894-9c39b58d4ec2/jobs/1327

**Comment by himeshr** [comment]
Completed successfully after performing fresh "TriggerPipeline" action on https://app.circleci.com/pipelines/github/avniproject/rules-server?branch=10.0.1.

**Comment by himeshr** [comment]
<img width="1840" alt="Screenshot 2024-11-04 at 3 15 04 PM" src="https://github.com/user-attachments/assets/fbea68ab-379f-4882-bf9e-113fdebfe10f">
Validated that rules-server responds as expected.
