### ISSUE TITLE
Unable to easily change the dashboard section order

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1374]
### Issue:

https://github.com/user-attachments/assets/53360333-2229-4138-9c45-314521a9d688

- On drag and drop of sections - when there are more than 2 sections - not reordered as expected
- Looks like the order deduced for other sections are incorrect - check for report card as well

### AC
- Order of sections and report cards should be able to change by drag and drop
- The same should work as configured in mobile app as well after sync

**Comment by Zek1t0** [comment]
Hello, I’m interested in working on this issue. Could you confirm if it’s still available for someone to take? If you have any specific guidelines or suggestions for tackling this, please let me know. Thank you!

**Comment by mahalakshme** [comment]
@Zek1t0 no this is done.

**Comment by 1t5j0y** [comment]
@adamsanadi6 include this commit in 10.2 branch as well since the branch has been cut

**Comment by dinesh2096** [comment]
QA Reference video : 

[Click here to watch the video](https://drive.google.com/file/d/1HUaslhKcBqyK-F4PvU24jsLEFErsjCzL/view?usp=drive_link)

**Comment by mahalakshme** [comment]
@dinesh2096 agreed during the first attempt also it should work as expected like happening during the second time. 
cc: @adamsanadi6

**Comment by himeshr** [comment]
### Tests to be done:
- Re-ordering of Dashboard Sections
- Re-ordering of Report Cards within a section

**Comment by petmongrels** [comment]
lets write a unit test for this method.

**Comment by dinesh2096** [comment]
- [ ] Tested by shuffle the card for the first attempt and validate in the cilent app
- [ ] Tested by shuffle the card for the multiple time and validate in the cilent app 
- [ ]Added the new card and changed the order and validate in the cilent app
- [ ] Removed the new card and changed the order and validate in the cilent app
