### ISSUE TITLE
Decision rules support to all workflows

### ISSUE THREAD

**Issue by arjunk** [avniproject/avni-webapp#138]
### Motivation
As a Avni user, the system should apply decision rules on form being filled and display system recommendations on the summary page.

### Acceptance Criteria
- At the Summary screen, the details should be displayed based on the decision rules applied for all the following forms/workflows:
  - Registration
  - Encounter
  - Enrollment
  - Program Encounter
  - Cancel
  - Exit
- If there are rule failures then do not show the decision table. Rule failures should be logged to the dev tools > console.
- Test that internationalization is also working for decisions if there are translations present for the decision concepts.

### Visual Design
NA

**Comment by hithacker** [comment]
@Sayali-Dev 
Example:
```
//Decision rule program encounter
"use strict";
({params, imports}) => {
    const programEncounter = params.entity;
    const decisions = params.decisions;
    const complicationsBuilder = new imports.rulesConfig.complicationsBuilder({
        programEncounter: programEncounter,
        complicationsConcept: "Birth status"
    });
    complicationsBuilder
        .addComplication("Baby is over weight")
        .when.valueInEncounter("Birth Weight")
        .is.greaterThanOrEqualTo(8);
    complicationsBuilder
        .addComplication("Baby is under weight")
        .when.valueInEncounter("Birth Weight")
        .is.lessThanOrEqualTo(5);
    complicationsBuilder
        .addComplication("Baby is normal")
        .when.valueInEncounter("Birth Weight")
        .is.lessThan(8)
        .and.when.valueInEncounter("Birth Weight")
        .is.greaterThan(5);
    decisions.encounterDecisions.push(complicationsBuilder.getComplications());
    return decisions;
};
```

**Comment by hithacker** [comment]
Current Estimate: 7

**Comment by garimadosar5** [comment]
QA Notes - 
- In registration, on next shows blank page.
![Screen Shot 2020-10-19 at 9.15.15 AM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/bb7abc1b-0bff-48d0-aefa-594babe21053)

**Comment by garimadosar5** [comment]
QA Checklist - 
- [ ] Registration
- [ ] Program Enrolment
- [ ] Program Enrolment
- [ ] Encounter
- [ ] Cancel
- [ ] Exit
