### ISSUE TITLE
Identifier assignment issues

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1387]
https://avni.freshdesk.com/a/tickets/4978

### Issue:
- After editing an identifier user assignment, shows an error message stating 'Element doesn't exist'. Considering the update was successful, it shouldn't show such error messages and should work fine.
- When a user is not assigned prefix, then 'Identifier prefix is not assigned to the user' error message should get displayed instead of 'Server communication error'

https://drive.google.com/file/d/1EaE6nNYevlRk6xvZOAHxTtHuHA5CIJFg/view?usp=drive_link

**Comment by vedfordev** [comment]
have similar steps as  #1289

**Comment by 1t5j0y** [comment]
Following change in `IdentifierUserAssignmentWebController.getIdentifierUserAssignment` should not be required
```
        identifierUserAssignment.setId(request.getId());
        identifierUserAssignment.setOrganisationId(request.getOrganisationId());
```

**Comment by adamsanadi6** [comment]
@1t5j0y Yes, we don’t need `organisation_id`, but we do need to set the `id`.
Reason: After the PUT method (`web/identifierUserAssignment/`) is triggered, it takes the `id` from the PUT method response and uses it in the subsequent GET method. Without setting the `id`, the next GET request will fail with a 400 Bad Request error because it sends null instead of the expected id.

**Comment by adamsanadi6** [comment]
https://github.com/avniproject/avni-server/commit/c79a79f35c930903815a123c5b9ffb4a55c2453d

Wrongly tagged to a different card.

**Comment by dinesh2096** [comment]
Unable to select the user

Refer screenshot : 

https://github.com/user-attachments/assets/73a8d5a1-193b-452a-b7a2-ca0bb97b89ca

**Comment by 1t5j0y** [comment]
@dinesh2096 have put in a quick fix to address this issue

**Comment by mahalakshme** [comment]
@dinesh2096 also need to check how it will work with user pool identifier source

**Comment by dinesh2096** [comment]
The page is not getting refresh and not coming back to the User assignment page : 

Reference Video : 

[Click here to watch the video](https://drive.google.com/file/d/1aFkn7_1J_jls_EPbh0iFTiJL9QwUiUGS/view?usp=drive_link)

**Comment by dinesh2096** [comment]
Created the bug card related to user assignment but not related to the card 

https://github.com/avniproject/avni-client/issues/1555
