### ISSUE TITLE
[UI] Visit schedule rules support to all workflows

### ISSUE THREAD

**Issue by arjunk** [avniproject/avni-webapp#139]
### Motivation
As an Avni user, I should see all the schedule details on the system and recommendations page based on the inputs at the forms applying the visit schedule rules.

### Acceptance Criteria
At the System and Recommendations page, the schedule details should be displayed based on the rules applied for all the following forms. Schedule details should get saved after the user clicks on the Save button on the System and Recommendations page.

Workflows to be covered:
- Registration
- Encounter
- Enrolment
- Program Encounter
- Cancel
- Exit

### Visual Design
NA

### Tech Tasks
- [x] Call the rule API from on the Systems and Recommendations page.
  - [x] Display the returned results in a table format similar to how it's done on the android app.
- [x] On clicking save, pass the visitSchedules object returned by the API to the save API.

**Comment by hithacker** [comment]
Current Estimate: 5 days

**Comment by garimadosar5** [comment]
QA Notes- 
- admin@yenepoya/password
- Giving this error on NCD followup "System recommendation page". Case - Jayant.
![Screen Shot 2020-10-08 at 8.42.21 AM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/58a42923-20fc-4dba-8492-f7cc45849fc4)

**Comment by hithacker** [comment]
@garimadosar5 Fixed.

**Comment by garimadosar5** [comment]
QA Notes - 
- On cancel form app is showing blank page on system recommendation page.
Case - as as, 
program - pregnancy 
Program encounter  - ANC followup
Case - Ajay Gupta
Encounter - Individual survey
![Screen Shot 2020-10-09 at 1.47.02 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/9086cc78-05bb-4244-9eee-3707b8738acc)
