### ISSUE TITLE
[DEA] Show sort icon

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1392]
https://avni.freshdesk.com/a/tickets/4791

### Context:
- Previously by default we were sorting by name, so showing the icon explicitly was not needed. But now to improve the performance since we have removed the default sorting, need to show sort icon evidently.

### AC:
UX for showing sort icon visibly: Click [here](https://drive.google.com/file/d/10Etl86M03-w4C3ymV2BPBorgJ9kzyqch/view?usp=drive_link)
- up and down arrows should be visible in hollow manner even without the need to hover.
- On click of it, show it as solid arrows like in aws.
- On same fields like before

**Comment by dinesh2096** [comment]
- [ ] As per the AC we should display the arrow even when the user is not doing the hover 

Refer the below image : 

<img width="1707" alt="Image" src="https://github.com/user-attachments/assets/56693b2b-6f7b-40dc-a463-11aacb90eb60" />

**Comment by mahalakshme** [comment]
@dinesh2096 I am able to see the sort icon even without hovering. Though it is different sort icon - this is okay.

**Comment by mahalakshme** [comment]
@AchalaBelokar was it there before as well? The aim is to not add sorting in new columns, just to improve the visibility of its existence on the already supported columns.

If it was existing before in prod, and not there now on prerelease, then agreed - it is an issue - Kindly confirm on the same.

**Comment by dinesh2096** [comment]
@mahalakshme Yes we had the suggestion so that user can also have the sort in address and enrollment so that if the user wants to sort by enrollment we can do it.We have the filter do that but if the user doesn't added that filter this will be useful.

**Comment by mahalakshme** [comment]
@dinesh2096 I suggest you can add feature requests to a separate sheet. If the above feature was not already existing, we need not consider it as part of scope in this card.
