### ISSUE TITLE
Creation of user as superadmin is failing

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1396]
env: staging, 

### Steps to reproduce:
org: yenepoya
- Login as super admin
- Go to Users -> Create - App breaks
- Click on an existing user - App breaks

Because of the above, we will not be able to add an user to a org.

### AC:
Should be able to create or view existing users as superadmin.

**Comment by himeshr** [comment]
## For Yenepoya Org:

Issue was caused due to invalid config for Individual of uuid "" across multiple orgs..
Fix was to remove the invalid syncConceptValue and set sync_registration_concept_1_usable to false
```
UPDATE public.subject_type
SET sync_registration_concept_1 = null , sync_registration_concept_1_usable = false
where
        uuid = 'd22027ff-e019-4d1c-9352-bd740efccc38';
```

**Comment by himeshr** [comment]
On staging env, a large number of orgs have the sync_registration_concept_1 set erroneously.

Refer attached file 
[Fix.txt](https://github.com/user-attachments/files/18161327/Fix.txt)
for more info.

**Comment by mahalakshme** [comment]
@himeshr How did it end up in this scenario?

**Comment by himeshr** [comment]
> > @himeshr How did it end up in this scenario?
> 
> Most likely someone have made an erroneous update without applying db_role or appropriate filter condition.. Staging env orgs are rarely without config issues.
> 
> We can check the same on prerelease and prod environment as well.

Checked in prerelease and Prod, the issue was present for voided SubjectTypes for Calcutta_kids org only, caused due bundle upload of Goonj more than a year ago.

**Comment by himeshr** [comment]
There is no further action required in any environment, so moving to done lane.
