### ISSUE TITLE
Validation of fields in a form

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#14]
### Motivation: 
 As an data entry operator, the system should validate the data being entered in the forms before Save

### Acceptance criteria
 - When a validation fails, field is highlighted in red
 - When a validation fails, user is not allowed to go to the next page and apt message is shown to the user
 - For default fields in forms in application, validations given on [technical details below link1](https://github.com/avniproject/avni-models/blob/ac5e4209b70777f5f1682bb8cd308f7dc37d22ad/src/Individual.ts#L326) should work. eg: default fields: basic registration details: First name, last name, age, gender, date of registration, date of birth.
 - For custom fields configured on forms:
   - All types of fields in the form such as (Numeric, Text, Notes, Coded, Date, DateTime, Time, Duration) should be validated based on the form configurations. 
   - Configuration can be done on forms through admin app (regex and description key ) for any custom validations
Example: Form, text element will have regex configured for validation for allowed characters and validation description key for error to be shown. If regex is not matched then we highlight the field in red and show an error given in the validation description key.
Another example: Numeric concept will have low absolute and high absolute specified. If the value entered by the user is below low absolute then an error message with key numberBelowLowAbsolute  should be shown. If the value entered by the user is above high absolute then an error message with key numberAboveHiAbsolute should be shown.
 - Below Validations are in scope for different field types:
    - Mandatory validation for all types of fields (Numeric, Text, Notes, Coded, Date, DateTime, Time, Duration)
    - Numeric validation
    - Coded unique validation
    - Range validation for absolute min and max
    - Highlighting of values that are beyond the acceptable range
    - Regex validation
    ( Please see link2 in technical details for form elements validations that should work )

### Technical Details: 

**All of this validations code is already there in particular avni model and you are supposed to just reuse it instead of writing all these validations from scratch. Use the validate() method of Individual model and FormElement model to validate the user data and get back the validation results. You only have to implement rendering the validation errors returned by the model and stopping the user from going to next page.**

( as discussed and given by Hiren )
For default fields - like on registration basic details , Validations in code exist here:
https://github.com/avniproject/avni-models/blob/ac5e4209b70777f5f1682bb8cd308f7dc37d22ad/src/Individual.ts#L326

For other validations from form element:
https://github.com/avniproject/avni-models/blob/ca82d057567d1f49f709144f8000693a8063ea28/src/application/FormElement.js#L88

**Comment by garimadosar5** [comment]
QA Notes - 
- height and waist circumference is not showing any error.
![Screen Shot 2020-08-16 at 8.56.55 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/439a79ff-7039-4d64-a81c-e408fbfde81f)

**Comment by vindeolal** [comment]
Rules are not implemented, so the last point is not valid right now.
