### ISSUE TITLE
Form Validation in all workflows

### ISSUE THREAD

**Issue by arjunk** [avniproject/avni-webapp#140]
### Motivation
As a Avni user, I want this rule to be applied so I will not be able to fill a form that contains inconsistent data.

### Acceptance Criteria
- The Avni app should apply the form validation rule when the user is on the last page of the form.
- Display the errors on the last page. 
- Disable the save button if there are validation errors.

The above criteria should be applied for all the following workflows
- Registration
- Encounter
- Enrollment
- Program Encounter
- Edit
- Cancel
- Exit
- Checklist form

### Technical Approach

1. Java API as proxy for routing purpose (Intermediate between client and Node) - API ready
2. Connectivity with JAVA API and Node pending - Need Apache HTTP client for the same.
3. Node server setup - (Node modules require "avni-models")
4. Configuring admin side rules mapping.
5. How to filter the rules based on "form ID". 
6. Client will hit Java API by providing JSON string using avni models.
7. Node will execute the rules.
8. All calls will be synchronous.

**Comment by hithacker** [comment]
@Sayali-Dev 
Examples:
```

//Validation rule on enrolment
("use strict");
({ params, imports }) => {
  const programEnrolment = params.entity;
  const validationResults = [];
  if (_.isEmpty(programEnrolment.individual.getRelatives("mother", true))) {
    validationResults.push(
      imports.common.createValidationError(
        "individualWithoutChildrenCannotBeEnrolledInMotherProgram"
      )
    );
  }
  return validationResults;
};

//Validation rule on registration
("use strict");
({ params, imports }) => {
  const individual = params.entity;
  const validationResults = [];
  if (individual.getAgeInYears() < individual.getObservationValue("Age at Marriage")) {
    validationResults.push(
      imports.common.createValidationError("Age at marriage cannot be greater than current age")
    );
  }
  return validationResults;
};
```

**Comment by hithacker** [comment]
Current Estimate: 4 days
