### ISSUE TITLE
Subject Type is automatically created in the filter

### ISSUE THREAD

**Issue by dinesh2096** [avniproject/avni-webapp#1404]
The "Subject Type" field is being created or added automatically in the filter without user interaction or expected behavior.

Env : Pre-release 
org : apfodisha
user : dineshg@apfodisha

Steps to reproduce : 

1.Click on the app designer 
2.Go to the offline dashboard
3.Click on the dashboard to add the filter with subject type

Expected Result : Filter should not be added as subject type 
Actual : Subject type is added as filter 

Reference video : 

[Click here to watch the video](https://drive.google.com/file/d/1AY4d2dDnEc8zWJC6u_Tr8JHHFYYupsvm/view?usp=drive_link)

**Comment by mahalakshme** [comment]
@dinesh2096 this is expected functionality: checkout this card: https://github.com/avniproject/avni-client/issues/1530

**Comment by dinesh2096** [comment]
@mahalakshme got it closing this card
