### ISSUE TITLE
Enrolment Eligibility Check

### ISSUE THREAD

**Issue by arjunk** [avniproject/avni-webapp#141]
### Motivation
As an Avni app user I want the enrollment eligibility rule to be applied so only the eligible programs will be shown while enrolling. 

### Acceptance Criteria
When Enrolling a individual for a program,the system should only display the applicable programs and hide non applicable programs while enrolling. 

These are to be configured here: Admin - Program form
![image.png](https://images.zenhubusercontent.com/5e257855e33c5efb529a84a9/466bd3fb-3a76-4a6c-a192-4a80293efffb)
### Technical Approach

1. Java API as proxy for routing purpose (Intermediate between client and Node) - API ready
2. Connectivity with JAVA API and Node pending - Need Apache HTTP client for the same.
3. Node server setup - (Node modules require "avni-models")
4. Configuring admin side rules mapping.
5. How to filter the rules based on "form ID". - Need to discuss
6. Client will hit Java API by providing JSON string using avni models.
7. Node will execute the rules.
8. All calls will be synchronous.

**Comment by hithacker** [comment]
Current Estimate: 2 days
