### ISSUE TITLE
Encounter Eligibility Check

### ISSUE THREAD

**Issue by arjunk** [avniproject/avni-webapp#142]
### Motivation
As an Avni app user, I need the system to apply encounter eligibility rules so that I can log the encounter details for the subject.

### Acceptance Criteria
Given encounter rules are configured by the Admin, 
- when the subject enrolled to a program encounters, then the field service user should be able to view forms as per the applied system rules to capture encounter details.
- when the subject encounters, then the field service user should be able to view forms as per the applied system rules to capture encounter details.

This needs to be be configured on admin here:
![image.png](https://images.zenhubusercontent.com/5e257855e33c5efb529a84a9/de4f90e6-7626-41a5-a43e-3daaae4fed2a)

### Technical Approach

1. Java API as proxy for routing purpose (Intermediate between client and Node) - API ready
2. Connectivity with JAVA API and Node pending - Need Apache HTTP client for the same.
3. Node server setup - (Node modules require "avni-models")
4. Configuring admin side rules mapping.
5. How to filter the rules based on "form ID". - Need to discuss
6. Client will hit Java API by providing JSON string using avni models.
7. Node will execute the rules.
8. All calls will be synchronous.

**Comment by hithacker** [comment]
Current Estimate: 2 days
