### ISSUE TITLE
Add a relative

### ISSUE THREAD

**Issue by arjunk** [avniproject/avni-webapp#150]
### Motivation
As a supervisor Avni user, I should be able to add a relative for a subject so that can link and view individuals relatives - father, mother, brother, sister in the software

### Acceptance criteria
To add a relative for a subject, I should do two steps:
1. Find relative
2. Give relationship

1. Find relative:
The form should have the following options to search:
- Name of Relative-Text Field
- Age of Relative-Number
- Village ( Address )
- Other data
On search, select a individual row to be added as relative. Click ok

2. Give relationship:
- Relationship: Drop down list to Select Husband, Wife, Mother, Father, Child,Brother,Sister and Others
- Click Add

After adding relative successfully,  When I see subject profile dashbaord, the relation and relative should be seen with under relatives section:
Relatives name
Relation
Age
Actions: remove and edit

### Visual Design
![Add Relatives.PNG](https://images.zenhubusercontent.com/5e0f2f610385a430f442c14d/9ffae862-707a-4a17-a541-13626c60c992)

![Add Relatives1.PNG](https://images.zenhubusercontent.com/5e0f2f610385a430f442c14d/942eb184-037a-4d59-abc1-444f8f85b6b3)

![Relationship.PNG](https://images.zenhubusercontent.com/5e0f2f610385a430f442c14d/2559cee0-b1ae-43cd-a3be-763ee8ff7481)

**Comment by garimadosar5** [comment]
QA Notes - 
- This button 'Filter result', it is not clear what result we are filtering. it is a relative or a relation.
![Screen Shot 2020-08-06 at 11.26.48 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/7b5eed2f-1f85-466a-9593-4b7de6feb430)
- In the search box, Name should not be mandatory. 
![Screen Shot 2020-08-06 at 11.28.38 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/2c5bf356-0b84-44f1-86fc-9b189bfea182)
- In search non-individual subject type also comes.
![Screen Shot 2020-08-06 at 11.30.31 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/116923b9-ccad-44eb-895e-f6f63661b366)
- From the search page, if directly click on add, it does not give any error but shows a blank page.
![Screen Shot 2020-08-06 at 11.31.22 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/3397c9ca-0e41-4964-b856-5b41212265d5)

**Comment by vindeolal** [comment]
Fixed.

**Comment by garimadosar5** [comment]
QA Comment - 
- I can add the relative for household also. In app for household we have add members.
Case - Desai (admin@yenepoya)
