### ISSUE TITLE
Delete Relative

### ISSUE THREAD

**Issue by arjunk** [avniproject/avni-webapp#151]
### Motivation
As a Avni user I should be able to delete a relative for a subject, The relation can be a father, mother, brother, Sister, others.

### Acceptance criteria
- A subject is always mapped with a relative and relationship. 
- When I see subject profile the relation and relative should be available. But when I delete the relative and relation ship should not be available.

### Visual Design
![Remove Relative.PNG](https://images.zenhubusercontent.com/5e0f2f610385a430f442c14d/b886d83d-16e2-4967-8a14-67f1db12cbf8)

**Comment by garimadosar5** [comment]
QA Notes - 
- Confirmation pop up.
![Screen Shot 2020-08-06 at 11.34.38 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/68806744-a8bf-4b3f-9bd8-a3d33c6cb3a1)
- After removing or adding a relative the page goes back to the program. it should stay in profile, as adding/removing relation is part of profile.
