### ISSUE TITLE
Support view of media elements on Subject Dashboard

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-webapp#159]
### Motivation
As a data entry user I should able to see the uploaded images and videos on subject dashboard.

### Acceptance Criteria
- Show the media elements in observations of registration, subject encounter, program encounter, and program enrolment. Image and videos should be shown as links.
- On clicking the link it should open the media in a lightbox/overlay. 
- On popup, there must be an option to open in a different tab

### Visual Design
- Not available

### Tech Approach
Use GET /media/signedUrl to get signed url to be displayed. 
Use a regular overlay, with something like react-player to render video.

**Comment by 1t5j0y** [comment]
- [ ] Get signed url for media elements. Keep track of signed url expiry and refresh if expired.
- [ ] Load media elements in overlay
- [ ] Provide option to open in new tab

**Comment by 1t5j0y** [comment]
Code improvements:
- [ ] Model includes space in the displayable value for media data types. Displayable value should be explicitly set for each concept datatype.
- [ ] Server sends plain text response while mentioning the response content type as json for the media APIs
