### ISSUE TITLE
Chart for Growth Monitoring

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-webapp#165]
### Motivation
As an avni user, the field service worker should be able to create/plot a Growth Chart so that the provider can monitor the growth of the subject

### Acceptance Criteria
When user clicks on "Growth Chart" on Subject Dashboard then Growth Chart Page will be shown.

Growth Monitoring chart should be plotted for below options:
1. WeightForAge ( default )
2. HeightForAge
3. WeightForHeight

- On click on above options, corresponding growth chart should get plotted. 
- Chart Label and Axes should be As option clicked, 
example: When "WeightForAge" Option clicked, 
chart label:"Weight for Age".
Y axis: Weight in KG
X axis: Age in Years
- For the subject, A line on this chart should be plotted for various age intervals: 6m, 1y, 2y and so on so forth and should be updated as data collected for the subject. 
i.e for example: plot a black line for weight for the age. ( In case of a single data point, only a point will be plotted, Tool tip should exist on hover on the data points of the line. )
This black line needs to be plotted on top of a color graded scheme plotted on chart. 

This chart should plot below color grading scheme. 
Grade 1: mild 
Grade 2: moderate 
Grade 3: severe
Input: Standard values from a json with the data will be used to plot the data << please refer below comment for the information asked and response got >>

- Growth Chart should only be plotted when configured/enabled.
Note: Currently This is for Mother,Child and Newborn implementations.
This should be plottable as per the configured implementations

An appropriate UI Library will need to be integrated to plot the chart. ( #166 )

### Visual Design

![image.png](https://images.zenhubusercontent.com/5e257855e33c5efb529a84a9/9033aa9f-6b13-4ecc-8228-d31139fd27b5)

**Comment by Sayali-Dev** [comment]
As discussed on call on 21/02 : The < and > buttons and Scroll of chart on click on < and > on VD is not required for now.

**Comment by Sayali-Dev** [comment]
As received responses for questions from with Hiren, refer below for plotting color grade :
https://github.com/avniproject/avni-client/blob/cae5caa904c59af3cb683938883a38ef8f372cf4/packages/openchs-android/src/views/program/GrowthChartView.js
