### ISSUE TITLE
[Webapp] Date type concept shows duration also on the client.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/avni-webapp#172]
Implementation - 
Hasiru-Karnataka

- On the web app, it looks like this-
![Screen Shot 2019-12-20 at 3.03.34 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/d535c8f1-ee51-4606-98c1-fd04fdc5dafd)
- On the client, it looks like this -
![Screen Shot 2019-12-20 at 3.02.28 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/05227f47-4789-42b9-b4fe-61b0dfe0976a)

**Comment by hithacker** [comment]
@swapnil106111 This is happening because we are setting up durationOptions as empty in keyValues of the form element even when user has not selected any duration option.

**Comment by swapnil106111** [comment]
@garimadosar5 Fixed.

[Uploading... web172.png ] 

[Uploading... Screenshot_20191223-162443.jpg ]
