### ISSUE TITLE
ID Gen Support

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-webapp#177]
This story will add the ability to have identifier support in the UI designer. 

### How do identifiers work? 
https://avni.readme.io/docs/creating-identifiers

### Acceptance criteria
- There is a new menu entry that can be used to add identifier sources
  - Fields: 
    - Name (string)
    - Batch Generation Size (number)
    - Minimum Balance (number)
    - Min length
    - Max length
    - Prefix
    - Type (userBasedIdentifierGenerator | userPoolBasedIdentifierGenerator) (number)
    - Catchment (reference field that allows to choose existing Catchment)
- There is a new menu entry to add Identifier User Assignments
  - Fields:
    - User (reference field that allows to choose existing User)
    - Identifier Source (reference field that allows to choose existing Identifier Source)
    - Identifier Start (string)
    - Identifier End (string)
- When creating a form element, it is possible to mention that it can be filled in using an identifier generated through an identifier source
  - need to add autocomplete to add identifier source by it's name
- When creating a user, it is possible to add the identifier prefix for that user. 
  - Add idPrefix field 

### Technical details for each acceptance criteria:
- Identifier source UI 
  -  need get api to get all id sources
  -  need get single id source api
  -  need to add reference field to link id source to catchment.
  - it saves data in identifier_source table in the database. Look at https://github.com/avniproject/jss-sickle-cell-screening/blob/master/identifier/dev/idSource.json to see it's metadata file.
- Identifier User Assignment UI
  - need get api to get all uias
  - need get single uia api
  - need to add ref fields to user and identifier source
  - It saves data in identifier_user_assignment table in the database. Look at https://github.com/avniproject/jss-sickle-cell-screening/blob/master/identifier/dev/userIdSource.json to see it's metadata file.
- When creating a form element, it is possible to mention that it can be filled in using an identifier generated through an identifier source
  - need to add autocomplete to add identifier source by it's name
  - add it in keyValues in this format `"keyValues": [{"key": "IdSourceUUID", "value": "12e20f5c-cf7a-42e8-877e-c139c8baa938"}]`. See https://github.com/avniproject/jss-sickle-cell-screening/blob/master/sickleCellScreening/sickleCellScreeningProgramEnrolmentNullForm.json for an example.
- When creating a user, it is possible to add the identifier prefix for that user. 
  - Add idPrefix field
  - Save idPrefix field in use like this `"settings": {"idPrefix": "NT"}`. See https://github.com/avniproject/jss-sickle-cell-screening/blob/master/users/dev-users.json for an example.

**Comment by garimadosar5** [comment]
QA Notes - 
-

**Comment by hithacker** [comment]
@amarkamthe I moved this to QA failed because:
1. In every form element, the identifier source dropdown is coming regardless of concept type. It makes sense to attach an identifier source only to the elements with Id concepts. 
2. The labels for selections in the type field of Identifier Source needs to be proper. Right now it is "  userBasedIdentifierGenerator" but it could be "User Based Generator" or "User Pool Based Generator".

**Comment by garimadosar5** [comment]
QA Notes- 2
- 
 ![Screen Shot 2020-04-27 at 12.17.04 PM.png](https://images.zenhubusercontent.com/5d0Ia151d5af8b352a1b5784b/ee7f4e6f-a0a2-4548-bd39-b212db5a391f)

**Comment by vinayvenu** [comment]
@garimadosar5 can you provide more details? userid, implementation etc?
