### ISSUE TITLE
When the logged in user doesn't have admin privileges then the user is shown access denied page without any logout option

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-webapp#192]
![Screenshot from 2020-01-24 16-49-04.png](https://images.zenhubusercontent.com/5d36cb3109d6d4240f1abe8e/e34d619b-9b99-40cc-87a1-e20e85753efe)

We need to add logout button. 
Connect to redux store and use Auth to singout as we did in UI Designer.

**Comment by swapnil106111** [comment]
![Screenshot from 2020-01-24 16-47-53.png](https://images.zenhubusercontent.com/5d36cb3109d6d4240f1abe8e/dd683b41-f6a5-436f-a4a3-3b60e9c57443)
