### ISSUE TITLE
SuperAdmin screen for organisation and org-admin creation

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-webapp#194]
As a super admin I want to be able to create a new organisation and also be able to add an organisation admin user for the organisation.

### Acceptance Criteria:
- When I login as a super admin I should be able to see only two menu items: 1. Organisations 2. Org Admin Users.
- Should be able to create a new organisation
- Should be able to edit an existing organisation
- Should be able to create a new org admin
  - Should be able to login to admin app using new org admin
- Should be able to edit existing org admin

**Comment by garimadosar5** [comment]
QA Notes - 
- In organisation edit, we should not allow editing db user and media directory.

**Comment by vindeolal** [comment]
@garimadosar5 
1,2,3 Done
4. We had decided not to do that in organisation page for now. @arjunk Do we need this?
5. Parent organisation is for the old implementation, we don't use it for newer implementations.

**Comment by garimadosar5** [comment]
@vindeolal 
- Check for point 3. Not done completely.

**Comment by vindeolal** [comment]
@garimadosar5 
For `JSCS` Username Suffix was not set, therefore it was giving null. You can check now.

**Comment by vindeolal** [comment]
@garimadosar5 added user name on menu bar.
