### ISSUE TITLE
New Subject Registration

### ISSUE THREAD

**Issue by SridharNallaPSL** [avniproject/avni-webapp#196]
### Motivation
As a field service/supervisor user, I need the ability to register a subject/Individual to Avni so that can collect data on the subject further.

### Acceptance Criteria
Given logged in into Avni, 
- When user navigates to Search subject list screen, NEW -> Register Individual option should be available And a wizard should open up to allow fill details for registration.
 - When the details are saved then subject registered successfully message should be displayed and subject should be displayed on subject list table
- Show success message as a toast and not a popup. Success message should be "Registration details saved"
- subject registered and its details should be visible in below cases:
   - On re-login
   - On navigating to other pages and back
   - On browser refresh 
   - And after sync through mobile app, for login into webapp by same user OR by other users of same organization
- When registering next subject then previous subject details should not be visible on forms displayed on registration wizard.

### Visual Design
VD 11[https://app.zenhub.com/files/64591222/3b6ba9ec-0a31-4c02-bac6-d9feb27c28b0/download](https://app.zenhub.com/files/64591222/3b6ba9ec-0a31-4c02-bac6-d9feb27c28b0/download)
**Note**: Label on Screen should be "Register Individual" and not as "Register and Enroll -Mother Program" below  in above VD screen

### Notes
Use openchs-models for data
Keep reference data in memory
As discussed on call with Sridhar, Only Individual can be resgistered for now
### Out of scope
Form elements Image, Id and Video
Storing of location
Validation (mandatory, range, regex)
Implementation hooks (visibility filter, calculated fields, decisions)
Ability to choose address of the Subject ( a separate card is there)

**Comment by Sayali-Dev** [comment]
As discussed with Tarun, Review the details on this story and updated for gaps.

**Comment by Sayali-Dev** [comment]
Updated below in acceptance criteria for feedback for toast received from Arjun for 17/03-18/04 iteration:
- Show success message as a toast and not a popup. Success message should be "Registration details saved"

**Comment by garimadosar5** [comment]
QA Notes. -
- New button (admin@yenepoya)
    1. Household 
    2. Individual  (UI broken)
![Screen Shot 2020-08-07 at 6.17.12 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/605f3aa6-bdc3-416b-9183-a685688db700)
- Random system recommendation.
![Screen Shot 2020-08-07 at 6.24.39 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/fa2ca8c3-b8b6-4c62-8a68-0f468a67beba)
- Observation table- Complete table is not showing.
![Screen Shot 2020-08-07 at 6.29.25 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/0efd4c9a-e1f2-444e-8edb-f6246d20178a)

**Comment by vindeolal** [comment]
Rest except last are fixed. Last point is by design.
