### ISSUE TITLE
Subject registration gaps- Subject Address

### ISSUE THREAD

**Issue by SridharNallaPSL** [avniproject/avni-webapp#198]
### Motivation
- As a supervisor and field service user, I should have the ability to fill up address of subject during its registration to Avni application.

Example: Address can includes:
Ex1. For State, District, Village, drop-down will include Village ( lowest level)
Ex2. For City, Centre, School, address drop-down will include School (lowest level)
Note: Admin app has the provision to configure this. 
Address will be shown in comma separated fashion for same name.
(lineage field of Address_level table gives the values for the Address drop-down)

### Acceptance Criteria
Given on login into Avni, 
- When user is on registration page, then to populate the address of the subject, 
 "Village" should be displayed in drop-down; meaning drop-down values should have lowest level values only, In case of same name in two different States, State1, Village and State 2, Village should be displayed as dropdown values.
Some more examples as given in note on top.
This drop-down should be autocomplete
This drop-down should not allow user to enter any values, user should only be able to select these.
- When User selects Address then can view on top bar on next page onwards and can save subject registration.
- When user does not fill Address, System displays apt prompt such as "Enter Address to proceed".
- Address can be edited after registration. Edited Address should be displayed on the Web app. 
- Once Address is selected by user, 
The field label should be shown as column names
<<lowest level >>: <<lowest level name>> should be displayed in the top bar displaying other subject details
- We do not need to display GPS coordinates at any screen ( currently shown on VD but we need not show on web app.)
- In case of two or more lowest levels, there should be a drop-down for each lowest level.
If user selects one of them, the other should be disabled on UI for selection.
Example: Village and Slum both are lowest levels then to capture Address, Village and Slum both dropdowns will be shown. USer can capture only one of them. Once one of them is captured, other will be disabled on ui for selection, PFB VDs.

### Visual Design
Please refer below:
![AddessDesign.png](https://images.zenhubusercontent.com/5e257855e33c5efb529a84a9/5a20a27a-0f6f-489a-b90e-21bb8435d257)

**Comment by Sayali-Dev** [comment]
[https://app.zenhub.com/files/172675608/8d53cdbc-ee9a-4b47-8da0-f6126692f97b/download](https://app.zenhub.com/files/172675608/8d53cdbc-ee9a-4b47-8da0-f6126692f97b/download)

Please refer to the VDs

Also uploaded on teams and sent to the team
