### ISSUE TITLE
voided concept shows up in coded concept crud as an answer

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-webapp#203]
When adding a new concept of type coded, voided answers also shows up in autocomplete selection that allows adding a new answer. One should not be able to add a voided concept as an answer.

**Comment by garimadosar5** [comment]
@swapnil106111 
- How is this supposed to be? Currently, if I void some concept that is used in some coded concept. Then again when I go to the coded concept, the voided concept is there as an answer.

**Comment by hithacker** [comment]
@garimadosar5 Bug description is lacking in details so it's unclear what is expected. I am adding details which should answer your question.

**Comment by swapnil106111** [comment]
@hithacker @garimadosar5 In simple words, it should not show voided concept as a suggestion in concept answer.

**Comment by garimadosar5** [comment]
#### QA Notes - 
#####Not fixed. 
- Implementation JSS. User - adminjss.
-

**Comment by swapnil106111** [comment]
@garimadosar5 Is it applicable for form element also? If it is there then i need to change it form element also.

**Comment by swapnil106111** [comment]
@garimadosar5 Fixed.

**Comment by swapnil106111** [comment]
@garimadosar5  Fixed.
