### ISSUE TITLE
Case sensitive concept creation

### ISSUE THREAD

**Issue by swapnil106111** [avniproject/avni-webapp#221]
In JNPCT, there are two female concept. FEMALE(numeric) and Female(NA). When you use one of them as an 
 answer in coded concept type, it will return error like "query did not return a unique result: 2; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 2".

API : /web/concept

**Comment by garimadosar5** [comment]
@swapnil106111 
Can we please do the dev box for this?

**Comment by swapnil106111** [comment]
@garimadosar5 Yes.
