### ISSUE TITLE
not showing autocomplete suggestion for concept for special character.

### ISSUE THREAD

**Issue by swapnil106111** [avniproject/avni-webapp#222]
When concept starts + special character, it does not understand by server. Encode such parameter with encodeURIComponent().

Changes in files: 
1. src/adminApp/components/CreateEditFilters.js
2. src/formDesigner/components/AutoSuggestSingleSelection.js
3. src/formDesigner/views/Concepts.js

**Comment by garimadosar5** [comment]
QA Notes - 

- Concepts >> 1-5, A+, 8-10 not searchable in the form.

**Comment by swapnil106111** [comment]
@garimadosar5 which implementation? and Are this 1-5, A+, 8-10 NA datatype concepts?
In the form element, it does not show NA datatype concept.
