### ISSUE TITLE
[Webapp] Messages are hidden behind the feedback option.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/avni-webapp#224]
On the bottom where we have put the feedback option. this hides the popup messages.

![Screen Shot 2020-02-16 at 3.10.41 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/c2349566-144c-4225-8d00-74c9faafbba0)

**Comment by garimadosar5** [comment]
QA Notes - 
- It is hiding the value of dropdown-
![Screen Shot 2020-03-06 at 4.12.17 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/78bb8cbf-f61f-45e6-9a56-e0bc92532198)

**Comment by vinayvenu** [comment]
![image.png](https://images.zenhubusercontent.com/5d0b1ec92fff8629577fc2ef/37df19dd-1b20-4776-bfdf-cebcc17b03e1)

Moved this to a right button instead. Handling the dropdown seemed like taking quite a bit of time.
