### ISSUE TITLE
Catchment locations not being loaded when going to the page from the reference on Users page

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-webapp#234]
![image.png](https://images.zenhubusercontent.com/5d0b10e42fff8629577fc2cc/2397c64b-8403-4117-8939-994e48c6e295)
![image.png](https://images.zenhubusercontent.com/5d0b10e42fff8629577fc2cc/0b15a4d2-72f8-421e-a4bc-126f9065d409)

**Comment by hithacker** [comment]
@garimadosar5 You should be able to check whether this is fixed or not by 7 pm(deployed the fix just now) on staging environment.

**Comment by garimadosar5** [comment]
@hithacker 
This is working. Please deploy this on UAT and production as well.
