### ISSUE TITLE
[DataEntryApp] Subject Registration without System Recommendations

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#238]
As a field service user, when I am on the search subject list page, I need to be able to register a new subject. 

In scope
- Basic Registration wizard with all form element types for any subject type
- Mandatory validation
- Regex validation
- Form element filters
- New Registration
- Edit Registration

Out of scope
- System recommendations
- Scheduling visits

Notes
1. Fetch all reference data - concepts, locations, genders, operational subject types, operational programs etc during initial load
2. Ensure these are not fetched every time using http cache
3. Extract openchs-models into its own npm repository. Use this as a dependency

**Comment by Sayali-Dev** [comment]
As discussed with tarun, Reviewed and updated details on epics and stories for this
