### ISSUE TITLE
[WebApp] Delete Location Bug

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/avni-webapp#24]
Location -> select a location with children -> Click on Edit -> Click on delete -> It gives message "Element Deleted" 
After few seconds it gives the message "Cannot delete this location until all the sub-locations are deleted".

"Element Deleted" message should not come.

**Comment by vinayvenu** [comment]
@garimadosar5 I can't seem to reproduce this issue anymore. Can you please check?
