### ISSUE TITLE
Access Control

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-webapp#247]
https://docs.google.com/document/d/1A0YzWGs34y4luPNV75vDefVKjFQUjMco6iggMPp2R0g/edit#heading=h.c8g944d5w2je

Access control for User, Admin for the avni app, There should be well defined privileges for Admin or a user. 

Separate roles, privileges or authorizations should be defined to control the access.

**Comment by vinayvenu** [comment]
Duplicate
