### ISSUE TITLE
New Program Encounter

### ISSUE THREAD

**Issue by Sayali-Dev** [avniproject/avni-webapp#254]
### Motivation
As an avni user, I need the ability to capture the program visit(planned /unplanned) details 

Note: Prerequisite: forms should be configured on Admin app for visits with form type: "Program encounter".

### Specs
- User should be able to do new program encounter by clicking on new program visit button. Clicking on this button should show a screen which shows all possible types of visits that can be done.
- On the new visit screen user should be able to click on the visit name. On click it should take user to a form for that program encounter.
- From the form page user should be able to fill the data and save the program encounter.
- User should be able to add details through Do Visit on Subject Programs Dashboard alternatively to New Program Visit

### Acceptance
- Program Encounter Date field should be set to today by default
- User should be able to change the program encounter date. It can’t be set in future. It can’t be before program enrolment date or registration date.
- All the standard form validations should apply
- User should be able to save the form.
- On successfully adding details and save, Show toast with message:"Visit details saved" and redirect to Subject Programs Dashboard - completed visit section. If the api returns an error when saving then keep them on the last page only and don't redirect to the dashboard.

### Visual Design
Please refer slides 32, 25, 27, 28

### Tech details
Call /web/programEnrolment/{enrolmentUuid} api to get the details of planned encounters.
Get all possible encounters list from formMappings field of operationalModules stored in redux. Use the form type: "ProgramEncounter", program uuid, subject type uuid to get these. Show these on New Program Visit screen. When user clicks on the link to do the visit then load the form from form api and use the FormWizard component.
On save we convert the ProgramEncounter model instance to json using toResource method and send it to /programEncounters via POST. If it is saved we should get 200 OK. If it is not 200 we show the error message on the last page.

**Comment by garimadosar5** [comment]
**QA Notes -** 
- On program encounter edit, the heading should have program encounter name. (same for the program encounter)
Currently it says - Home / <name of individual> / Program encounter. 
![Screen Shot 2020-08-06 at 10.11.52 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/c6b66a0f-59fd-445c-a127-4890e4793a74)
- for the last question in the image, answers are not showing. (admin@jnpct/password, case - Baby chotu)
![Screen Shot 2020-08-06 at 10.26.33 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/a157655e-7e4e-4fcf-aa94-bb1737116ee4)
- Abnormal values are not showing in RED like in android app.
- User needs to fill Non-mandatory questions also 
- Skips are not working in program encounter

**Comment by vindeolal** [comment]
Right now rules are not implemented. So the last point is not valid.
