### ISSUE TITLE
Edit Program Encounter 

### ISSUE THREAD

**Issue by Sayali-Dev** [avniproject/avni-webapp#256]
### Motivation
As an avni user, I need the ability to edit the completed program visit details.

### Acceptance Criteria
- Able to Edit details for visit on Subject Programs Dashboard - Completed visits section
- User should be able to change the program encounter date. It can’t be set in future. It can’t be before program enrolment date or registration date.
All the standard form validations should apply
User should be able to save the form
- On successfully adding details and save, Show toast with message:"Visit details saved" and redirect to Subject Programs Dashboard - completed visit section.

### Visual Design
Please refer slide 32, 25, 27, 28

### Technical Details:
We need to load the data for the visit from the api and map it to ProgramEncoutner avni model. When saved we call the /api/programEncounters POST api

**Comment by garimadosar5** [comment]
QA Notes - 
- On program encounter edit, the heading should have program encounter name.
Currently it says - Home / <name of individual> / Edit Program encounter. 
![Screen Shot 2020-08-06 at 10.11.52 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/c6b66a0f-59fd-445c-a127-4890e4793a74)
