### ISSUE TITLE
Exit Program Enrollment

### ISSUE THREAD

**Issue by Sayali-Dev** [avniproject/avni-webapp#258]
### Motivation
As an Avni user, I need ability to mark a subjects exit from program enrollment

### Acceptance Criteria
- Exit option should be present on Enrollment section on Subject profile dashboard
- On Exit, form for exit to be displayed and On form;
  - View Exit date by default and Fill details on form. 
  - On Next, Exit dated should be seen on every Next page.  Exit date is editable if required.
  - validations should run on data entered by user And In case of discrepancy during edit, highlight the field in red and show apt error message and disable next until error is resolved
   - View observations filled on last page  and Save
- on save successfully,
Show success message as a toast and not a popup.
Also added, Success message should be "Enrolment details saved"
Redirect to details on the Enrollment section of subject Profile Dashboard and view details
Details will be: 
view "Exited on <date>"  on summary section.
Section for "Exited on:<date>" and table with observations under Enrolment Details section. With Undo Exit and Edit option
- Edit option: Able to edit the captured exit details along with exited date and save and view edited exit details. Validations should work for forms during capturing details.
- Undo Exit option: Able to Undo Exit , popup to check if really want to undo exit and restore to enrolled state shows up. On yes, subject enrollment details reappear.

### Visual design
Please refer 38,39

**Comment by Sayali-Dev** [comment]
Updated below in acceptance criteria for feedback - popup should be toast, received from Arjun for 17/03-18/04 iteration:
Show success message as a toast and not a popup.
Also added, Success message should be "Enrolment details saved"

**Comment by garimadosar5** [comment]
QA Notes - 
- when I click on exit button, this page opens up-
(admin@hasiru)
![Screen Shot 2020-08-16 at 8.00.28 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/dac9c58e-281d-42fd-8b8a-2ee9ef088e2e)

**Comment by garimadosar5** [comment]
QA Notes - 
- exit details are shown in enrolment detail card. (baby shah) - admin@jnpct
- In-app for exit details, we have a different card.
