### ISSUE TITLE
ViewFilter rule support to all workflows

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-webapp#259]
### Motivation
As a Avni user, I need the system to support filter rules so as the filter rules are applied at forms.

### Acceptance Criteria
As a Avni user,When I fill the details at forms,The system should apply all the Filter rules and fulfill the following criteria:
- Display Validation error for the form element(field responses) if any.
  - Form next button to be disabled if validation error is there for any element
- Show or hide the form element
- Skip answers from the answers of form element
- Calculated value from the answers of form element

### Flows
- [x]  Registration
- [x]  Program Enrolment
- [x]  Program Exit
- [x]  Encounter
- [x]  Encounter cancel
- [x]  Program Encounter
- [x]  Progam Encounter cancel

**Comment by hithacker** [comment]
@Sayali-Dev Putting the examples:
```
//ViewFilter/SkipLogic - calculated value
"use strict";
({ params, imports }) => {
  const individual = params.entity;
  const formElement = params.formElement;
  let height = individual.findObservation("Height");
  let weight = individual.findObservation("Weight");
  let value;
  height = height && height.getValue();
  weight = weight && weight.getValue();
  if (Number.isFinite(weight) && Number.isFinite(height)) {
    value = _.ceil((weight / Math.pow(height, 2)) * 10000, 1);
  }
  return new FormElementStatus(formElement.uuid, true, value);
};

//ViewFilter/SkipLogic - hide element
("use strict");
({ params, imports }) => {
  const individual = params.entity;
  const formElement = params.formElement;
  const statusBuilder = new imports.rulesConfig.FormElementStatusBuilder({
    individual,
    formElement,
  });
  statusBuilder
    .show()
    .when.valueInRegistration("Height")
    .is.greaterThan(150)
    .and.when.valueInRegistration("Weight")
    .is.lessThan(20);
  return statusBuilder.build();
};

//ViewFilter/SkipLogic - validation error
("use strict");
({ params, imports }) => {
  const individual = params.entity;
  const formElement = params.formElement;
  let systolic = individual.getObservationValue("Systolic");
  const statusBuilder = new imports.rulesConfig.FormElementStatusBuilder({
    individual,
    formElement,
  });
  if (systolic < 50) {
    statusBuilder.validationError("Systolic BP cannot be less than 50");
  }
  return statusBuilder.build();
};

//ViewFilter/SkipLogic - skip answers
("use strict");
({ params, imports }) => {
  const individual = params.entity;
  const formElement = params.formElement;
  const statusBuilder = new imports.rulesConfig.FormElementStatusBuilder({
    individual,
    formElement,
  });
  statusBuilder.skipAnswers("Away from village");
  return statusBuilder.build();
};
```

**Comment by hithacker** [comment]
Current Estimate: 6 days

**Comment by garimadosar5** [comment]
QA Notes - 
- user1@prebb/password (Staging)
![Screen Shot 2020-09-25 at 3.30.24 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/4513de9c-15f2-4272-a46b-f343c7e6680e)

Individual registration- second FEG is hidden, questions are hidden but a blank page is showing.

**Comment by vindeolal** [comment]
The last point is not reproducible. Checked with Garima as well. This doesn't seem to be a bug because of the rules. We can create a new card with all the steps to reproduce, if it happens again.
