### ISSUE TITLE
Cancel Program Encounter

### ISSUE THREAD

**Issue by Sayali-Dev** [avniproject/avni-webapp#260]
### Motivation
As an Avni user, I need the ability to cancel the planned program visits.

### Acceptance Criteria
- Able to cancel details for planned visit  on Subject Program Dashboard.
- On cancel, cancel form opens, user can enter details 
- User should be able to view cancel date field and add the cancel date. It can’t be set in future. It can’t be before program enrolment date or registration date.
- on save successfully, Show toast with message:"Visit cancelled", captured visit should be shown with status:"Cancelled" under planned visits section 
- Validations for field should work during adding the details for visit cancel.
- Allow Edit Cancel Program Encounters. On edit visit for Cancel program encounter, form should open up and user can update details and save and be redirected to subject program dashboard - completed section. Success message, validations, toast all apply here.

### Visual Design
Please refer VD 25
![Program Encounter.PNG](https://images.zenhubusercontent.com/5e0f2f610385a430f442c14d/e4aed17b-8de7-4ae4-b301-a528450551e6)

**Comment by hithacker** [comment]
@RamyaEdapalapatiPSL Can you please update the status of this card?

**Comment by RamyaEdapalapatiPSL** [comment]
@hithacker,  Development is done. Need to raise PR.

**Comment by garimadosar5** [comment]
QA Notes - 
- Other reason is showing first. (admin@jnpct/password)
- Other reason (text) - skip does not work.
![Screen Shot 2020-08-06 at 11.05.03 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/4479d628-e371-479c-88c2-abd54e133681)

**Comment by vindeolal** [comment]
Fixed

**Comment by garimadosar5** [comment]
- Cannot see the cancelled visit.
