### ISSUE TITLE
Use Access control on Avni Web app

### ISSUE THREAD

**Issue by Sayali-Dev** [avniproject/avni-webapp#279]
### Motivation
As an avni user, the system should be able to use the priveleges to display the actions and content to the user based on configured privileges.

### Acceptance Criteria
1. Avni users of an organisation view actions and data based on the priveleges set for group/s to which they belong.
2. Priveleges should be used while data modification ( edit, cancel, delete etc) The transactional data should use priveleges and run rules.
3. For cases where the user does not have priveleges, the action or entity should not be displayed on the UI by Avni web app - client

**Comment by vinayvenu** [comment]
Duplicate.
