### ISSUE TITLE
App designer changes for group subject types

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#284]
### Acceptance Criteria
- When creating a new subject type, there should be an option to mark the subject as a group subject type. 
- The app designer should have the ability to add rows into the group role table for group subjects.

**Comment by garimadosar5** [comment]
QA Notes - 
![Screen Shot 2020-04-11 at 8.55.59 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/4835c01a-8537-42d4-94f8-461f0d8c4640)
 What are the minimum and the maximum number of members, it is the number of minimum members of that type of role or total member in the group?

- ![Screen Shot 2020-04-11 at 8.55.13 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/1a55254f-3466-4b0e-8478-5ec2d5363844)

I cannot sync the application. User - test@jsscp_cp/password
