### ISSUE TITLE
Filter to hide voided forms in the form listing page

### ISSUE THREAD

**Issue by amarkamthe** [avniproject/avni-webapp#288]

**Comment by garimadosar5** [comment]
QA Notes - 
If a form is voided, in the list of forms it starts showing less than 10 numbers of forms.
![Screen Shot 2020-04-05 at 7.23.55 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/0ef5b29d-3a7a-4572-b372-e0fb838f33ce)
-
