### ISSUE TITLE
App Designer

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-webapp#29]
## Problem
Today doing an Avni implementation is not very intuitive to anyone outside of the product team. The metadata creation is tech heavy. It requires quite a bit of training on how an implementation is to be done and knowledge of json, sql and unix.

## Solution
To fix the metadata problem, we have already started building the admin UI. Most of the metadata creation (users, locations, catchments) is available there, the only last thing being the ability to design programs, forms and the custom logic required for skip logic, calculated fields, visit scheduling and configuration other extension points available through code. 

## In scope

- A UI from which following can be designed
  * Programs
  * Forms with rules
  * Checklists

## Out of scope
- Self service UI for tech organisations to host on existing hosted solutions
      This will require features like Database and reports access for partners, Log access for implementers, Server status available publicly, Ability to export and import data from an organisation, Migration of all existing rules to the new format

- Self service UI for end users
	Self service UI. The current purpose is not to have any organisation coming in and designing things for themselves. This is a good to have, but means that we need to integrate invoicing, emails, build a different kind of authentication, a lot more automation etc. The current objective is to be able to open up implementations to partners only. Opening it up to the general public will depend on how this goes. Partners will be empowered to handle data for their own organisations. 

- Translations from UI [Being done part of a separate epic]

## Challenges
- We might need to move away from hierarchical organisations to single organisations, and encapsulate data within each. 

## User flow
The deployment workflow will be managed through organisations. The implementers would be able to create organisations for QA, UAT and production.  Metadata from one organisation to another will be promoted through an export-import mechanism. 

## Tech choices
- We will replace the uniqueness constraint on uuids on every table, and replace it with a combined constraint on uuid and organisation. 
- We will move javascript logic from the file system, break it down and attach it to where they belong (form elements, program etc). This can be either done in the same table, or in a common different table where all rules are stored. This also means zero imports/dependencies like what 
- We will move away from hierarchical organisations to single organisations. 
- We have not solidified any restrictions we need to provide from test to production. 
- Import/export will reuse existing endpoints, and will be idempotent.

**Comment by vinayvenu** [comment]
Look at how program action buttons - vaccination and growth charts are configured for an impl.

**Comment by hithacker** [comment]
Creating a program should also create operational program in backend.
