### ISSUE TITLE
Add "All Privileges" to Everyone group

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#292]
### Context
When we add new subject types after creating organisation, the Everyone group is not updated. This makes the main purpose of creating an Everyone group redundant. The purpose of the Everyone group was to allow organisations who don't care about groups/privileges to not worry about them.

To fix this issue,  we will create a new privilege - "Everything". This will be used everywhere, and will be part of the sync API, usage of API on the client.
We will also prevent users from adding/removing users from the Everyone group or changing its name. However, we will be able to edit privileges associated with this group.

### Acceptance criteria

- [ ] A new privilege called "All Privileges" is added to the list of privileges. 

- [ ] When the "Everyone" group is created, it has just this one privilege created by default

- [ ] The migration to add privileges to "Everyone" group added as part of the [Model and API privileges](https://app.zenhub.com/workspaces/avni-5cf8e458bf08585333fd64ac/issues/avniproject/avni-server/56) story is removed. 

- [ ] Members of the Everyone group cannot be changed through the webapp. However, the privileges can be changed.

**Comment by 1t5j0y** [comment]
Approach to handle "All Privileges" was changed. Instead of having a new privilege to represent this, a new property to each group to indicate if the group applies all privileges or selected.
