### ISSUE TITLE
Support upload of transactional data from webapp

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#294]
### Acceptance criteria

- [x] In the upload section of the admin app, the upload and download sections will have additional entries

- [x] For each subject, dropdown will have a "<SubjectName> registration" option

- [x] For each program combination that is valid, there will be a "<Program> enrolment" option

- [x] For each program encounter, there will be a "FormName>" option

- [x] For each encounter, there will be a "FormName>" option

- [x] All fields that are relevant for subject registration, program enrolment, encounter or program encounter will be available in the downloaded csv. 

- [x]  The behaviour of the upload will be the same as that we have for locations (status will be shown, error files can be downloaded etc)

### Out of Scope

- Cancel observations and Exit observations. 
- Checklists

#### Test cases - 
- Support upload of all data types [Text <all the languages>, Numeric, Date, datetime etc].
- Download Sample file from the UI. Check Sample format for different encounters.
- Prepare a data set based on the sample file and upload it.
- Upload file should give the error if not able to upload all the data.
- Prepare a sample file without the downloaded template and check the errors.
-

**Comment by vinayvenu** [comment]
https://avni.readme.io/docs/upload-data

**Comment by garimadosar5** [comment]
QA Notes - 
- In the individual template file, put "Age" also as column.
-

**Comment by vinayvenu** [comment]
@garimadosar5 , comments below

We can handle age as a separate feature. We have the ability to put in date of birth right now. 
Sample answers is a different story, not in scope of this one. 
About the missing columns, please take a look now. The forms were switched for a while. It should work now. 
To put in enrolment id, take a look at the sample file for the header name. The enrolment id is the id you put in the enrolment upload.

**Comment by garimadosar5** [comment]
QA Notes - 
- In Documentation, please put the format of columns like "Date", "Address" etc.
