### ISSUE TITLE
[Bug] Form crashes when there is only one page

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-webapp#296]
Form crashes when there is only one page. 

When there is only one group/page in the configured form, if you click on next after the displayed page then we get an error page instead of being taken to the summary page.

**Comment by hithacker** [comment]
@Sayali-Dev @eshwarjoshiPsl We are already aware of this bug but just creating the card to make sure it is tracked on ZenHub.

**Comment by kshpsl** [comment]
stated verification on staging ,
i found after fill details on first page it goes to system & recommendation page but it will not save after select save button.
![Capture1.PNG](https://images.zenhubusercontent.com/5eb27a20e5291a120e9101d6/0f47419a-13cc-4d3d-bc6c-4b30aea16f52)![Capture2.PNG]
(https://images.zenhubusercontent.com/5eb27a20e5291a120e9101d6/15ff496f-b9ab-47df-960d-e5a30b97613f)

**Comment by hithacker** [comment]
@kshpsl Can you share the user that you logged in with?

**Comment by kshpsl** [comment]
@hithacker  User- test@ayu

**Comment by kshpsl** [comment]
Started verification on staging with user test@covid19
so after fill details on form page move to summary page and click on save subject get register. 

![cap1.PNG](https://images.zenhubusercontent.com/5eb27a20e5291a120e9101d6/c6167713-c640-4096-beb8-031a66146489)

and click on save subject get register.

![Cap22.png](https://images.zenhubusercontent.com/5eb27a20e5291a120e9101d6/38d50972-a318-40f7-8550-6de8643951b1)
Look as expected,so mark it pass 
and Moved to deploy ready
