### ISSUE TITLE
Delete entity like subjectype, program and encounter type.

### ISSUE THREAD

**Issue by swapnil106111** [avniproject/avni-webapp#298]
While deleting encounter type:
Ask user to confirm its action.
1. Delete encountertype api-  /web/encounterType/< ID >
2. Handle formmapping voiding at server side.

While deleting program:
Ask user to confirm its action.
1. Delete program api-  /web/program/< ID >
2. Handle formmapping voiding at server side.

While deleting subject type:
Ask user to confirm its action.
1. Delete subjecttype api-  /web/subjectType/< ID >
2. Handle formmapping voiding at server side.

**Comment by swapnil106111** [comment]
@vinayvenu @amarkamthe  Can you look at this story?

**Comment by vinayvenu** [comment]
@swapnil106111 I have pushed in the Java side of the solution.
