### ISSUE TITLE
Create search screen

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#3]
##### QA Comment -
- Refresh is not working on the search page. [fixed]
- ~In which order list is sorted. [separate card exists for sorting]~
- ~Can we have some filter also and on top of that we perform the search? [create a separate card if this suggestion converts to a requirement]~
- Also, mention somewhere what is the list about. [Not clear what needs to be fixed]
- For waterbody, subject type list is not appearing. Username - dhakaneka@ddm. [fixed]
- ~Does not tokenify names (search for "sushma thakur" and "thakur sushma" must give Sushma Thakur) [create a separate card for search imporvement]~
- Enter key does not work to search [it works]

____________________________________________________________________________________________________________

On login, if a user is not an org admin, (s)he will be taken to the search screen. Search screen should have the following. 

1. Logout button
1. One search field (text input) and a search button
1. Search results with the following parameters. 
	a. Name
	b. gender (if individual)
	c. Date of birth (if individual)
	d. Location (full location in the form of A->B->C)
	e. Programs enrolled
1. Search results will always be shown by default without starting search. 
1. Search results will be limited to the catchment of the user. 

Out of scope:
1. Pagination. Separate card exists for search page improvements.
2. Granular filters. ex: Gender, Active Programs.

**Comment by sidsamanvay** [comment]
Bug: Search api returns duplicates row for same Subject.

**Comment by sidsamanvay** [comment]
@garimadosar5, please check the updated QA comments

**Comment by garimadosar5** [comment]
##### QA Notes - 16 Sep

###### Search
- Only 10 individuals are showing in one page and there is no way to go on second page onwards.
- I cannot filter with `Gender`, `Date of Birth` and `Active Program`.

###### Create
- If I go on previous, it removes the current page details.
- Except for Gender, I cannot select any option in any of the single select questions.
- The SAVE button is not working.

**Comment by sidsamanvay** [comment]
@garimadosar5 
Both are out of scope. We dont want field specific filters as of now. Search results' pagination will be done in a followup card.
