### ISSUE TITLE
Listing of forms

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-webapp#30]
![form-list.jpeg](https://images.zenhubusercontent.com/5d0b10e42fff8629577fc2cc/096fc1b0-6eff-422f-acc3-0b4f6c655f8a)

Tasks:
* Listing forms
* API also needs to be changed because current /forms api returns only program related forms and not forms like registration or individual encounters.

**Comment by garimadosar5** [comment]
@hithacker  @swapnil106111 
QA Notes - 
- Program is not showing in the list.
- Search is not working.

**Comment by hithacker** [comment]
@hithacker to fix api to add search and sort

**Comment by hithacker** [comment]
@garimadosar5 
- Program is not showing in the list.
 - Program will not show up for the forms which are not associated to the program. E.g. individual registration, individual encounters, vaccination form.
- Search is not working.
  - Search should work now

Also right now we will not support sorting based on subject and program and also will not support filtering by any field.

**Comment by hithacker** [comment]
@amarkamthe moving this back to deploy ready. add another card for voiding
