### ISSUE TITLE
Move editing of form names to the detail page

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#300]
### Summary
Currently, we create rows on form_mapping with an empty form. This is a problem since form_mapping must have a form. 
There is also a UX issue that this card will fix (edit does not allow ability to edit enrolment, exit, encounter and cancellation forms). 

### Acceptance criteria

- [x] On the Programs page, enrolment form name and Exit form name will not be editable
- [x] On the Programs create and edit page, there will be two mandatory fields to add enrolment form name and exit form name. 
- [x] On the Programs create and edit page, there will be an option to create new form. This new form will be named "Program Name -> Enrolment". 
- [x] The app will not create a default row in form_mapping when creating a program. 
- [x] The same set of changes will be performed on the Encounter Types page as well
- [x] The same set of changes will be performed on the Subject Types page as well 
- [x] When creating a form, form mappings will not be created. The fields to add encounter type, program and subject type will be removed.

**Comment by vinayvenu** [comment]
@garimadosar5 response to your comments on skype. 

App Designer - 
Subject Type - 
- Create New Subject type, “Registration Form Name” UI is broken. - What do you mean by this? 

- When we create new subject type, we do not have option of Group type subject type. - fixed

- When we are creating subject type it asks us if we want to create new subject registration form but it does not open a new form. Now we save and move forward. Now that empty Registration form is attached to that Subject type, but it shows no where that this registration for is empty. 
	Going to a new form is going to be hard, because the user is just trying to create a form. Once created, they can click on the link of the form and directly go to the form and edit it. 


- For any subject type Registration form type shows “Individual Profile (Registration)”. It shows for Household registration and other group registration. - Can you show me where in the UI this is happening? 



Program - 
- Create New Program, “Select Enrolment Form” and “Select Exit form” - UI is broken. - What do you mean by this? 


- On New Program create page “Name”  and “Select Subject Type” are mandatory but mandatory (*)
 sign is not there. - fixed


-  By default Name of Program Enrolment form says “<Program> Encounter”.  for eg: NCD Encounter not NCD Enrolment - fixed



Encounter Type - 
- Create New Encounter type, “Select encounter Form” and “Select Encounter Cancellation form” - UI is broken. - what do you mean by this? 


- On Create page of “Encounter Type” option “Select Program” - Select Option does not come Where the text or Arrow is, the selection option appears little above that. - fixed


- Cancellation form should not be mandatory. - Why? 


- From Encounter type option, I can create only the encounters that are related to program, non program encounter cannot  be created from there. (Is this the flow?) - No. Fixed this. 



Form - 
- I cannot do the add the mapping for a non program encounter, because it ask for Encounter type and I cannot create an encounter type without program.
- “New Form” - Now it asks only for FORM TYPE and NAME. Did we change that? - Yes

**Comment by garimadosar5** [comment]
QA Notes - 
- Create New encounter page UI is broken - 
[Uploading... Screen Shot 2020-04-27 at 1.22.58 PM.png ]

**Comment by vinayvenu** [comment]
Have added https://app.zenhub.com/workspaces/avni-5cf8e458bf08585333fd64ac/issues/avniproject/avni-webapp/319 to take card of the garbled screen

We can track it there now. Please move this card to closure.
