### ISSUE TITLE
Cancel Encounter

### ISSUE THREAD

**Issue by Sayali-Dev** [avniproject/avni-webapp#308]
### Motivation
As an avni user, I need the ability to cancel the planned encounters for a subject.

### Acceptance Criteria
- Able to cancel details for planned visit  on Subject General Dashboard.
- On cancel, cancel form opens, user can enter details 
- User should be able to view cancel date field and add the cancel date. It can’t be set in future. It can’t be before registration date.
- on save successfully, Show toast with message:"Visit cancelled", redirect to General - planned visits section of  Subject dashboard section 
- captured visit should be shown with status:"Cancelled"
- Validations for field should work during adding the details for visit cancel.
- Allow Edit Cancel Encounters. On edit visit for Cancel program encounter, form should open up and user can update details and save and be redirected to subject program dashboard - completed section. Success message, validations, toast all apply here.

**Comment by garimadosar5** [comment]
QA Notes - 
- On cancel new visit is not getting scheduled.  household survey (admin@yenepoya). Case - aa

**Comment by arjunk** [comment]
@hithacker any updates on this card?

**Comment by hithacker** [comment]
Point 1 was not valid as visit scheduling did not exist at the time this story was QAed.
Point 2 was invalid but it was because the story itself provided a wrong visual design to review.
Point 3 has been addressed.
