### ISSUE TITLE
Create a new empty form

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-webapp#31]
### Acceptance Criteria
- Allows user to enter form type, form name, and other details.
- For the form types: ProgramEncounter, ProgramExit, ProgramEnrolment, ProgramEncounterCancellation it should ask the user to select the program name.
- For the form types: Encounter, ProgramEncounter, ProgramEncounterCancellation it should ask the user to select Encounter Type.
- Form name and Subject type are mandatory for all types of form.
- Redirects to form edit page after creating the form.

### Mockup
 ![image.png](https://images.zenhubusercontent.com/5d0b10e42fff8629577fc2cc/f700bbc6-3c4c-4b12-9000-4ec2a06376de)

### Implementation details:
Move Form Type to be the first field of the form.

Add a new field for Subject type.
Subject Type, Encounter Type, and Program dropdowns should get populated from /web/operationalModules API.

Call the POST /forms on click of Create Form with all the details. Generate and send form uuid along with other parameters like form name, subject type, encounter type etc to the API. Once the form is created then navigate the user to form details page. API needs to be modified to take subject type, encounter type, and program name.

**Comment by garimadosar5** [comment]
QA Notes - 

- Why do we have "Name" and "Encounter type" different?

**Comment by hithacker** [comment]
@hithacker I have to see what to do about existing implementations where program name and operational program name are different. Issue Garima is mentioning is happening because of that in mdr
