### ISSUE TITLE
Addition of form element group visibility rules in UI designer

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#314]

**Comment by vindeolal** [comment]
Doc : https://avni.readme.io/docs/writing-rules#from-element-group-rule

**Comment by garimadosar5** [comment]
QA Notes - 
- Under "Details and rules" for form element group there is not enough space as at form level.
![Screen Shot 2020-05-04 at 7.55.53 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/ff264abe-d35f-4e31-aa1a-3420128ea073)
