### ISSUE TITLE
Selecting household and group is confusing

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#316]
This is a UI only change. It is confusing to see household and group as two different switches. It might be useful from a UX standpoint to have these as radio buttons. 

### Acceptance criteria

 - [ ]  On subject type list, create, edit and show screens, a new item called Type will be introduced. The type will have four options - Individual, Group, Household and Other
 - [ ] This type will replace group and household options on the screens
 - [ ] The type will be the first item on the screen. Name will be shown only once type is chosen. 
 - [ ] When the type is Individual, then the name will be shown as Individual, and should not be editable

**Comment by petmongrels** [comment]
Is the individual the right word? "person" is clearer.

From the perspective of least surprise and magic - automatic creation of subject types in the background should be made visible to the user. We can do this via the UI so that they can see that it is getting created. Same for the member role.

Similarly, if we are going by person/individual as a special subject type, we should keep the name, dob fields somehow indicated to the user - as already present.

**Comment by arjunk** [comment]
I agree Person is clearer. 
Group and Individual are counterparts. 
so types on subject type can be the ones as mentioned : Group, Household, Individual, Person.  
Group indicates that it is a "group" and so requires members. The roles will be user defined.  
Household is a special type of group, so requires members plus has system defined roles. 
Individual indicates that its a single entity and so does not have members. 
Person is a special type of Individual. It indicates that its a human which has fields like age/dob and gender. 

Implementers can choose to give whatever names they want to for these subject types. 
"Individual", "Patient", "Student", "Adolescent" can all be names for a subject type of type Person. 
This way the hard coding on name also gets removed from client and server. We just check isPerson. 

One idea around automatic creation  in Household : On creation of new Household, We can create roles and let user choose a subject type of type person from dropdown.

**Comment by vinayvenu** [comment]
@arjunk I was hoping that keeping this just on the UI should suffice for the moment, but you seem to prefer changing the domain model as well. I am closing this story for now. 

We can create an epic instead to properly fix this, and bring up the UI fixes at that point.
