### ISSUE TITLE
Minor UI bugs on UI designer

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#322]
- [x] Concept SUBMIT - It is called Save in most other screens
- [x] Edit My Dashboard filters - Save button can align left
- [x] Search Filters - Save button can align left
- [x] Worklist updation rule - Make save button to bottom, left aligned
- [x] My Dashboard filters - Delete and edit buttons reversed
- [x] Search filters - Delete and edit buttons reversed
- [x] Subject types, encounter types and Programs - Add edit and delete buttons just like we have for the other options
- [x] Create buttons should be similar across App designer. They should be in the format "NEW <ITEM>" (where item is anything like a subject type etc)
- [x] Action buttons should be similar across App designer
- [x] Household and group on subject type view should be a tick or a dash

**Comment by swapnil106111** [comment]
@vinayvenu For the one, which button style I follow. 
Should I remove save symbol from save button ?
For the add subject type button, which style should i follow admin app location style or form listing add form style.

**Comment by vinayvenu** [comment]
@swapnil106111 for the concept submit, we use the same style that we have on SubjectType edit. This is to keep consistency with other screens. Means we should have the symbol as well. 

It might be good to have a Save component that is used across screens to keep consistency.

**Comment by swapnil106111** [comment]
@vinayvenu  Pushed changes on master.
