### ISSUE TITLE
Screens for Relationships

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#325]
See epic for server card. Also see image for columns. 

### Acceptance criteria

- [x] Screens required for list, view, edit and create
- [x] Delete ability required
- [ ] All labels are capitalized case and all buttons are capital case
- [ ] Edit and delete buttons are present in the regular locations
- [ ] The screen shows a message to create a subject type with name Individual if it is not already present. 

#### Columns required on listing page
Actions (edit and delete)
Name
Gender

#### Type of widgets on Create/edit page
Name - text
Gender - Check boxes (multiple allowed)

**Comment by garimadosar5** [comment]
QA Notes - 
- The relationship can be created if the individual subject type is not there.
Organisation - covid21 (admin)
![Screen Shot 2020-05-07 at 2.51.38 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/9c03acb2-47db-4cc8-8790-3aed769a57cc)

**Comment by swapnil106111** [comment]
@garimadosar5 Can you click on new relationship type. In New RelationshipType screen, you will see this message.

**Comment by swapnil106111** [comment]
@garimadosar5 ![Screenshot from 2020-05-07 15-00-23.png](https://images.zenhubusercontent.com/5d36cb3109d6d4240f1abe8e/422010e3-d21d-45b7-ba12-074206548395)

**Comment by swapnil106111** [comment]
@garimadosar5  now you we will see individual subject type error on listing page.
