### ISSUE TITLE
[BUG] Success Message is not seen as toast

### ISSUE THREAD

**Issue by Sayali-Dev** [avniproject/avni-webapp#329]
Steps:
Register a individual and on last page Click Save.

Expected:
On save, on successful registration, success message should be displayed as toast.

Actual Results:
Success message is displayed as a popup.
![image.png](https://images.zenhubusercontent.com/5e257855e33c5efb529a84a9/7d848f79-dc3d-44ee-a990-34af62d7a2b5)

Note: Same is applicable on save of enrolment.

**Comment by hithacker** [comment]
@RamyaEdapalapatiPSL Since you have done this for program encounter, can you do this for registration and enrolment also please?

**Comment by RamyaEdapalapatiPSL** [comment]
@hithacker, yeah, sure. we will do it.
