### ISSUE TITLE
Behaviour of web app after session expiration

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-webapp#33]
1. Login.
2. From any listing open an item. Go back to listing.
3. Leave the tab open till your session expires (depends on the token expiration policy we have in Cognito). This basically simulates use case when people stay logged in, use tabs and work regularly using web app.
4. After the session expiration, try to open an item in the listing.

Expected - The user would be logged out and brought to the login screen.
Actual - It tries to open the item, fails and goes back to listing. No feedback to the user that they need to log in.

**Comment by vinayvenu** [comment]
Duplicate of https://app.zenhub.com/workspaces/avni-5cf8e458bf08585333fd64ac/issues/avniproject/avni-webapp/347
