### ISSUE TITLE
[BUG]  For fields with radio buttons or check-boxes, If you select an option and deselect,  Validation is displayed

### ISSUE THREAD

**Issue by Sayali-Dev** [avniproject/avni-webapp#331]
Steps:
1. On registration form, select an option for a radio button field and deselect
2. On a field with check boxes select and deselect option 

Expected:
On click on Next, the validation for field should be shown.

Actual:
Validation is displayed on select and deselect the checkbox/radio button option, 
eg: Medical history, Addiction
PSB screenshot

**Comment by hithacker** [comment]
@Sayali-Dev I think this is fine. Even on the android app, the behavior is to show the validation if you deselect and the field is mandatory.
