### ISSUE TITLE
Screen for Relationship Types

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#332]
### Acceptance criteria

- [ ] There is a new menu item to manage relationship types
- [ ] The listing screen contains Actions (delete only), Relation and Reverse Relation. Note that there wont be an edit functionality
- [ ] There will be a create option. Server will handle duplicates
- [ ] If there is no "Individual" subject type, then there will be a message on the screen "Please create an Individual subject type to enable this screen"

**Comment by swapnil106111** [comment]
@vinayvenu In relationship type create page, what input should be taken. Can you post a sample json which allowed for this?

**Comment by garimadosar5** [comment]
QA Notes - 
- It allows creating a relationship type with no individual subject type.
Org - Location Test.

**Comment by swapnil106111** [comment]
@garimadosar5 I have tested locally. Please check screenshot.![Screenshot from 2020-05-07 17-30-53.png](https://images.zenhubusercontent.com/5d36cb3109d6d4240f1abe8e/7371d562-76b5-4667-8397-fa95bbfb8c8d)

**Comment by swapnil106111** [comment]
@garimadosar5  checked locally it is showing error.

![Screenshot from 2020-05-07 17-32-37.png](https://images.zenhubusercontent.com/5d36cb3109d6d4240f1abe8e/87aaa93f-0314-494b-b432-7a46c2c16292)

**Comment by swapnil106111** [comment]
@garimadosar5 can you provide org credentials? so I can check on staging.

**Comment by swapnil106111** [comment]
@garimadosar5  now you we will see individual subject type error on listing page.
