### ISSUE TITLE
Create a widget for help text on Avni

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#333]
As part of this story, we will create a mechanism to add help texts to the UI designer. 

### Acceptance criteria

- [x] Have a visual mechanism as provided below
- [x] On click, quick help is shown in a popup. 
- [x] Help text need not have internationalization
- [x] Help text must handle markdown so that we can do things like links for concepts, emphasis etc
- [x] Documentation will be common for data entry, admin and UI designer, but will be separated by keys on the documentation json file
- [x] Create a right menu where long-form help text can be added. 

Sample screenshots
![Screenshot from 2020-03-03 14-01-41.png](https://images.zenhubusercontent.com/5d36cb3109d6d4240f1abe8e/d0c3d95d-7fc0-42c6-913b-192fbbc5febb)

![Screenshot from 2020-03-03 14-01-58.png](https://images.zenhubusercontent.com/5d36cb3109d6d4240f1abe8e/28b73155-6756-456a-824c-98d857f57e14)

**Comment by vinayvenu** [comment]
Notes from Joy - https://www.evernote.com/shard/s466/client/snv?noteGuid=a6bd0ae4-43aa-4f44-a2c4-7aaab3818b30&noteKey=d072e22c5004a4f4&sn=https%3A%2F%2Fwww.evernote.com%2Fshard%2Fs466%2Fsh%2Fa6bd0ae4-43aa-4f44-a2c4-7aaab3818b30%2Fd072e22c5004a4f4&title=App%2Bdesigner%2BUI%2Bissues

**Comment by garimadosar5** [comment]
QA Notes- 
- "Add Role" Text.
 ![Screen Shot 2020-05-09 at 11.59.38 AM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/9d2766ce-c5a2-41fb-b2cb-eefd2ecb8dc5)

- Why there is another circle while clicking on help text.
 ![Screen Shot 2020-05-09 at 11.28.39 AM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/b07a00d6-bd4a-43ad-aa69-48c659894c62)
