### ISSUE TITLE
[Bug] Address not shown correctly on subject details next screen after address filled up

### ISSUE THREAD

**Issue by Sayali-Dev** [avniproject/avni-webapp#334]
Steps to Reproduce:
1. Open form to Register a individual
2. On basic details, select Slum Address with other mandatory basic details and click next and check subject details displayed 

Expected Results:
Selected Address should show up under Subject details on next pages of registration after address value filled up
eg:
The subject details should show Slum : << value selected >> if Slum is selected.
Similarly Village :<< value selected >> if Village is selected

Actual Results:
If Slum is selected, still on next pages subject details show Village: <<slum value filled by user >>
Observed during dry run

**Comment by hithacker** [comment]
@Sayali-Dev This is fixed

**Comment by Sayali-Dev** [comment]
Started verification on staging,

On click on new register -> New form doesn't open:
![image.png](https://images.zenhubusercontent.com/5e257855e33c5efb529a84a9/b80596c9-4800-49a8-9ab2-cead3b3206fb)

**Comment by Sayali-Dev** [comment]
Created another organisation covid19
Created data and verified this bug today on build on staging

For above steps followed, it works
PSB screenshots:
![image.png](https://images.zenhubusercontent.com/5e257855e33c5efb529a84a9/4c25fe96-9b93-429d-9544-a2f8fad63c7f)

Also checked during edit, for another village name when previously slum was filled.
![image.png](https://images.zenhubusercontent.com/5e257855e33c5efb529a84a9/7b9c7d4e-ae01-4d99-800f-e7b303f10ae5)

Looks as Expected. Hence Marking it **PASS**
