### ISSUE TITLE
[Bug] New register form is pre-filled when opened after viewing  edit registration subject page

### ISSUE THREAD

**Issue by Sayali-Dev** [avniproject/avni-webapp#335]
Steps to Reproduce:
Open Edit registration subject page -> Click Back through browser -> Click New : Register Individual or Create :Individual

Expected:
Registration form with no values filled for fields should be displayed.

Actual:
>Registration form displays date of birth prefilled
This date of birth is that of edit subject registration viewed in step 1
 >Village is also pre-filled
> If Next is clicked on this page, Validation is seen for date of birth and Village even if filled.
There is no value specified is seen as validation.

PSB screenshot:
![image.png](https://images.zenhubusercontent.com/5e257855e33c5efb529a84a9/17b4a9ad-4457-4d27-8d30-8cd668ea65ea)

Note:
This also happens in below scenario:
Register form opened from New remains pre-filled, when opened when you are  Subject dashboard.

**Comment by hithacker** [comment]
@Sayali-Dev This is session storage related bug. Right now we will disable the session storage completely so this should be fixed. We will relook at the need to have session storage at all in the next release and then we will pick this up if it's still relevant.
