### ISSUE TITLE
Concept Create/Edit page

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-webapp#34]
![image.png](https://images.zenhubusercontent.com/5d0b10e42fff8629577fc2cc/2b23f138-5e9b-4ec2-aed6-88fc7b17e172)

Tasks:
* On choice of datatype, show different ui for each type. 
  * Common fields are name(string(255)) and dataType.
  * Numeric - Show form fields for Low Absolute(number), High Absolute(number), Low Normal(number), High Normal(number), Unit(string)
   * Text
   * Notes
   * Coded - Show an autocomplete field for Answers. It should call API on typing to get matching concepts. Also functionality to quickly add new concept to be used as an answer.  
   * NA
   * Date
   * DateTime
   * Time
   * Duration
   * Image
   * Id
   * Video
* Finally when all the details are filled user will click on Save button which will call POST /concepts API.

API will expect below format: 
- For Coded concept
```
  {
    "name": "Block",
    "uuid": "87e1989a-c690-4385-b3da-e6e1bacc8f85",
    "dataType": "Coded",
    "answers": [
      {
        "name": "Sagbara",
        "uuid": "833d9b73-1743-424e-8b0e-0de05b69ca4a"
      },
      {
        "name": "Nandod",
        "uuid": "8f7befa1-2cc5-4189-9f67-1fd1953ab720"
      },
      {
        "name": "Tilakwada",
        "uuid": "236c7984-4176-45e3-819b-992a39e2a3a4"
      }
    ]
  }

```

**Comment by hithacker** [comment]
There are some API issues that needs to be handled for this story:
- API change required for validating already existing concept
    - Make dataType optional in /search/concept?name=&dataType=NA
- If the new answer already exists and is of type other than NA then we need to show validation error.
  - Make dataType optional in /search/concept?name=&dataType=NA
- When editing if the answer is deleted then the API is not deleting the answer

**Comment by garimadosar5** [comment]
![image.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/a29ce08d-581f-4066-9160-b8dd3065c720)

**Comment by swapnil106111** [comment]
@garimadosar5 Ready for QA.

**Comment by hithacker** [comment]
@swapnil106111 ![image.png](https://images.zenhubusercontent.com/5d0b10e42fff8629577fc2cc/94ec8414-9ba9-4d25-b1f0-729fcf606fe7)
