### ISSUE TITLE
[Bug] After enrolling into one program, cannot enroll into another program immediately. 

### ISSUE THREAD

**Issue by Sayali-Dev** [avniproject/avni-webapp#341]
On enrolling into one program and then after save again enrolling into another program, Success message is shown but individual is not enrolled to program

**Comment by Sayali-Dev** [comment]
Verified it on current build on staging. Individual gets enrolled to two programs one after the other.

However found out that if no program is selected in dropdown, then still page opens up and nothing happens after reaching the last page and  save.

**Comment by hithacker** [comment]
> Verified it on current build on staging. Individual gets enrolled to two programs one after the other.
> 
> However found out that if no program is selected in dropdown, then still page opens up and nothing happens after reaching the last page and save.

@RashmiDavandePsl Can you please fix this?

**Comment by RashmiDavandePsl** [comment]
@hithacker : 
Hello Hiren, 
Added validation code and raised PR for the same.
Thanks

**Comment by hithacker** [comment]
@RashmiDavandePsl Can you please record a small video of how this behaves on your local machine and share here?

**Comment by RashmiDavandePsl** [comment]
Hello @Sayali-Dev and @hithacker , can you please take a look into this video. 
[https://persistentsystems-my.sharepoint.com/personal/rashmi_davande_persistent_co_in/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Frashmi%5Fdavande%5Fpersistent%5Fco%5Fin%2FDocuments%2FShareVideo&ct=1589351308726&or=OWA-NT&cid=d58156c4-41a2-ede9-8bc5-68ec1144adfb&originalPath=aHR0cHM6Ly9wZXJzaXN0ZW50c3lzdGVtcy1teS5zaGFyZXBvaW50LmNvbS86ZjovZy9wZXJzb25hbC9yYXNobWlfZGF2YW5kZV9wZXJzaXN0ZW50X2NvX2luL0VpWEh5R3N2a1ZwQ2xnbDFKMXdXbXpVQjhIdlVlWmIzMm1vYXJkMEdLQ2dYMVE_cnRpbWU9N2ZPVTJRYjMxMGc](Video Link)

**Comment by RashmiDavandePsl** [comment]
Hello @Sayali-Dev and @hithacker , can you please take a look into this video link.

https://persistentsystems-my.sharepoint.com/personal/rashmi_davande_persistent_co_in/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Frashmi%5Fdavande%5Fpersistent%5Fco%5Fin%2FDocuments%2FShareVideo&ct=1589351308726&or=OWA-NT&cid=d58156c4-41a2-ede9-8bc5-68ec1144adfb&originalPath=aHR0cHM6Ly9wZXJzaXN0ZW50c3lzdGVtcy1teS5zaGFyZXBvaW50LmNvbS86ZjovZy9wZXJzb25hbC9yYXNobWlfZGF2YW5kZV9wZXJzaXN0ZW50X2NvX2luL0VpWEh5R3N2a1ZwQ2xnbDFKMXdXbXpVQjhIdlVlWmIzMm1vYXJkMEdLQ2dYMVE_cnRpbWU9N2ZPVTJRYjMxMGc

**Comment by Sayali-Dev** [comment]
@RashmiDavandePsl, Thanks for video. Checked it. Now message is seen for the error, however, 
The error message should be shown as an error toast not a popup. Please could you fix that ?

**Comment by RashmiDavandePsl** [comment]
Hello @Sayali-Dev, Can you please check the other video for the same. I have implemented the functionality as per our discussion. Thanks

https://persistentsystems-my.sharepoint.com/personal/rashmi_davande_persistent_co_in/_layouts/15/onedrive.aspx?ct=1589351308726&or=OWA%2DNT&cid=d58156c4%2D41a2%2Dede9%2D8bc5%2D68ec1144adfb&originalPath=aHR0cHM6Ly9wZXJzaXN0ZW50c3lzdGVtcy1teS5zaGFyZXBvaW50LmNvbS86ZjovZy9wZXJzb25hbC9yYXNobWlfZGF2YW5kZV9wZXJzaXN0ZW50X2NvX2luL0VpWEh5R3N2a1ZwQ2xnbDFKMXdXbXpVQjhIdlVlWmIzMm1vYXJkMEdLQ2dYMVE%5FcnRpbWU9N2ZPVTJRYjMxMGc&id=%2Fpersonal%2Frashmi%5Fdavande%5Fpersistent%5Fco%5Fin%2FDocuments%2FShareVideo%2Fscreen%2Dcapture%20%283%29%2Ewebm&parent=%2Fpersonal%2Frashmi%5Fdavande%5Fpersistent%5Fco%5Fin%2FDocuments%2FShareVideo

**Comment by Sayali-Dev** [comment]
Hi Rashmi, Checked the fix in the video. this looks as expected now. Thanks.
