### ISSUE TITLE
On Save form - Server error received Concept with uuid 'null' not found

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#348]
This is an error that came about during bug bash. See details here - https://docs.google.com/spreadsheets/d/1ycRyvs12VwhN2zmeiSMGam5861x87a22P_DUPxt1g1o/edit#gid=831593043

Screenshot - https://drive.google.com/open?id=1CG9G7U35aNmrFkO3tcV_YwwnHEKKcO7x

Steps to reproduce,
Create a new form -> create first FE with some concept -> now add another FE (don't fill anything) -> delete the empty FE -> try to save the form.  It gives same error.

Happens because deleted FE does not get cleared from the state and get passed to server.

**Comment by arjunk** [comment]
@swapnil106111 is this defect fixed so soon?

**Comment by swapnil106111** [comment]
@arjunk it is fixed.
