### ISSUE TITLE
UI bugs

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#349]
See [bugbash sheet](https://docs.google.com/spreadsheets/d/1ycRyvs12VwhN2zmeiSMGam5861x87a22P_DUPxt1g1o/edit#gid=831593043) for more details

- [x] Add new Location: Location name is centered instead of left justified
- [x] Delete Location (from catchment description) has no confirmation (delete is too close to save so it may be accidentally pressed)

**Comment by swapnil106111** [comment]
same changes for delete button in location types.

**Comment by garimadosar5** [comment]
QA Notes- 
 - Delete Location option does not show any confirmation box.
