### ISSUE TITLE
List concepts

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-webapp#35]
![image.png](https://images.zenhubusercontent.com/5d0b10e42fff8629577fc2cc/afd39e0f-3e10-4079-b4d8-3bdfec746def)

API for search is /search/concept?name={value}

## Tech:
* UI component for listing can be https://material-table.com/#/

**Comment by swapnil106111** [comment]
1. Showing list of Concepts using material table.
2. Delete concepts.
3. Search concepts.

**Comment by hithacker** [comment]
@garimadosar5 

1. Done.

**Comment by garimadosar5** [comment]
QA Notes 2 - 
- Void a concept on the first page -> Concept is voided and showing on first page -> Now go to next page -> Again that concept shows up (concept is voided)
For eg : Dadra Silvari - Organisation 7.
- Concept - Tagritola (Organisation 7). This concept is voided. But not showing in the list. But shows up when I search it from the search box.

**Comment by swapnil106111** [comment]
@garimadosar5 I tried above mentioned behaviour for IHMP implementation, it is working.

**Comment by swapnil106111** [comment]
@garimadosar5 I checked above behaviour on staging, it is working as expected. Can you please retest the same? If it is not working then we will take a call and discuss.

**Comment by hithacker** [comment]
@swapnil106111 Garima showed me how to reproduce this today. I am working on the fix.

**Comment by hithacker** [comment]
https://github.com/OpenCHS/openchs-server/commit/84c89c4fa67148e0ddd6dc4b642436a3726808a3 fixes this. It will be deployed to staging once CircleCI build is fixed(failing due to other reasons).
