### ISSUE TITLE
[BUG] Form  can be saved  with Date Duration field having invalid date

### ISSUE THREAD

**Issue by Sayali-Dev** [avniproject/avni-webapp#355]
Steps:
Open a registration form or any other from with field like: Date of House tax paid.
Enter invalid date and Save the form

- [ ] User entered date of birth: 03/24/4444 OR 04/--/---- is accepted, no validations shown after next even on previous and next
Expected:
Validation should be shown

Actual:
Form gets saved with value invalid date
PSB screenshot
DateOfHouseTaxPaid_CanhaveInvalidDate_InvlaidDateSeenOnLastPage_FormcanbeSaved
![DateOfHouseTaxPaid_CanhaveInvalidDate_InvlaidDateSeenOnLastPage_FormcanbeSaved.png](https://images.zenhubusercontent.com/5e257855e33c5efb529a84a9/690f78d0-bf46-4fd2-bac8-dc9c487bde74)

**Comment by RamyaEdapalapatiPSL** [comment]
@Sayali-Dev , PR for invalid date/datetime/time/duration changes are raised yesterday only. please test and verity them once PR was approved.

**Comment by garimadosar5** [comment]
QA Notes - 
- DOB and encounter dates can be filled invalid date.
