### ISSUE TITLE
[Improvement]: User entered date of birth: 03/24/4444 OR 04/--/---- is accepted, no validations shown after next even on previous and next

### ISSUE THREAD

**Issue by Sayali-Dev** [avniproject/avni-webapp#357]
Steps:

1. Enter date of birth 03/24/4444
2. Check if validation is shown and registration form can be saved
3. Click Next, Previous and Next and again check if validation is seen.
Similarly repeat above step and enter date of birth 04/--/---- and check validation if thrown

Expected:
Registration cannot be saved, 
Validation should show up on 2 and 3, 4 step above
Validation for date of birth and registration should be added

Actual:
Registration is saved, no validation exists on both steps above for steps 2 and 3
Also Date of Birth can be entered as 04/--/---- and Its displayed as NaN. for step 4.

**Comment by RamyaEdapalapatiPSL** [comment]
@Sayali-Dev , PR for invalid date/datetime/time/duration changes are raised yesterday only. please test and verity them once PR was approved.

**Comment by garimadosar5** [comment]
QA Notes - 
- From DOB, it does not calculate age.
![Screen Shot 2020-10-09 at 5.23.38 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/0e814d4c-4fa3-49f8-b0e4-775605e1a774)

**Comment by garimadosar5** [comment]
Covered in #355
