### ISSUE TITLE
Form Details Page - Ability to add and remove questions/groups

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-webapp#36]
![image.png](https://images.zenhubusercontent.com/5d0b10e42fff8629577fc2cc/a676ec52-306d-44f3-8ce1-fff6352d4120)

Tasks:
* Add Create New Group button - 1
   * Will be located outside group section
   * Should add a new group section below an existing group
* Add Create New Question button - 1
  * Will be inside group 
  * Should add new question below last question
* Expand/Collapse for groups and questions - 0.5

**Comment by vinayvenu** [comment]
need to add other options such as regex (validFormat), durationOptions in this screen.

**Comment by hithacker** [comment]
- Give a popup for creating a new concept when creating form
    - New answer is just inline. answer types are NA

**Comment by hithacker** [comment]
Questions should be draggable for reordering

**Comment by hithacker** [comment]
When user enter concept name we should search for existing concepts and display suggestions. If user wants to create a new concept we should provide a button "Create Concept". Create concept should be inline. When adding answer for concept if new answer is being created show a popup to enter text.

**Comment by hithacker** [comment]
There should be a tab for rules in each question.

**Comment by garimadosar5** [comment]
@hithacker I am able to create a new form. for eg: If I am creating a form under Phulwari Implementation. It say `Program Phulwari not found`.

**Comment by hithacker** [comment]
@amarkamthe Please take a look at Garima's comments.

**Comment by amarkamthe** [comment]
@garimadosar5 : Not able to create a new form  - Do you face same issue with other implementation as well? I have tested this with IHMP implementation and this works.

**Comment by hithacker** [comment]
@amarkamthe to fix element name in two places issue.

**Comment by amarkamthe** [comment]
Changed the textfield to label in the form element expansion summary part so as to avoid confusion of NAME field at two places.

**Comment by garimadosar5** [comment]
QA Notes - 
-

**Comment by hithacker** [comment]
@garimadosar5 the second scenario only happens when you write concept name that do not exist right?

**Comment by swapnil106111** [comment]
@garimadosar5 Showing proper error messages on UI after form save action.
