### ISSUE TITLE
Dragging a form element from one form group to another removes it from the original group but doesn't put it in the new group

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#363]
Dragging a form element from one form group to another removes it from the original group but doesn't put it in the new group

Bugbash issue - https://docs.google.com/spreadsheets/d/1ycRyvs12VwhN2zmeiSMGam5861x87a22P_DUPxt1g1o/edit#gid=831593043

Screenshot - https://drive.google.com/open?id=1o5FT7N3Xa_JlF6a6BvPxAslenfc658x3

**Comment by swapnil106111** [comment]
It is working when you drag element from one group to other group. But not working when destination index in other group element is 0.
