### ISSUE TITLE
During New individual registration ,Number of family members field take only specific value.  

### ISSUE THREAD

**Issue by kshpsl** [avniproject/avni-webapp#367]
steps:
click on New 
select individual registration
fill details on form page 1
click next

Expected Result : user can enter value

Actual Result    : field take only specific value
                            e.g 9,10,19,20,29,39,40.....and so on
 ![capture 1.PNG](https://images.zenhubusercontent.com/5eb27a20e5291a120e9101d6/a460c1ee-9777-42f3-bfe6-ec08005498e2)

**Comment by RamyaEdapalapatiPSL** [comment]
@kshpsl, There is regex configured for that field in app designer forms. Hence it is giving validation message as per regex.
