### ISSUE TITLE
Handling inactive and voided items on the App designer

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#372]
### Acceptance criteria
All below acceptance criteria is meant for the following **items**
- Subject Types
- Programs
- Encounter Types
- Concepts

Each of these are referred to as items in the acceptance criteria below. 

- [x] Voided items will not be shown on the App designer. All voided entries are considered deleted (currently available in forms and concepts)
- [x] There will be an option to inactivate an item
- [x] The inactivate option will be shown as an icon along with edit/delete
- [x] Retired options will be shown in grey, with an inactive icon
- [x] Options can be unretired by clicking the inactive icon to make them active
- [x] Active/inactive options will be available as a switch on the edit pages

**Comment by swapnil106111** [comment]
@vinayvenu api to activate and inactivate entity.

**Comment by swapnil106111** [comment]
@vinayvenu for concept listing, get api should return voided false concepts.

**Comment by swapnil106111** [comment]
Active is property of entity so can we add it as switch in edit screen as we are seeing in subject type?

**Comment by vinayvenu** [comment]
@swapnil106111 to inactivate an entity, send a post request with all existing fields, and mark active as false.

**Comment by swapnil106111** [comment]
Remove active button from listing page.
Removed checkbox from form listing page to include voided forms.

**Comment by garimadosar5** [comment]
QA Notes - 
- If a concept is inactive I can use this concept again in another form. 
Case - admin@testbe (Concept - Occupation)

**Comment by vindeolal** [comment]
1. Inactive concept can't be used in any forms. Also you can inactive a concept only if it is not used in any form.
2. It shows the alert. Probably you would have checked the option to prevent the dialogs.
![image.png](https://images.zenhubusercontent.com/5d0b116e2fff8629577fc2d4/5bce9c4a-43e1-4190-922a-33898872e9e9)
