### ISSUE TITLE
New screen in admin app to delete the data

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-webapp#386]
- [x] Menu item name "Organisation Details".
- [x] It'll have org details like "organisation name" ~and "created on"~
- [x] There will a button "Delete all data".

Pressing delete button opens up a modal that has message : "This will remove all transactional data such as subjects, program enrolments and encounters entered through the Field App. Do you want to continue?"

This screen also has a checkbox "Also delete metadata created through the system (This will only delete everything except users, catchments and locations)".

When this checkbox is also selected and user presses ok, All the tx and metadata will get deleted.

**Comment by garimadosar5** [comment]
QA Notes - 
- What all details will be there in Organisation Detail Menu item?
-

**Comment by vindeolal** [comment]
@garimadosar5 
1. In the future, we'll have more organization information like what plan organization is using and stuff like that.
2. All option deletes the metadata. except user, location, locationType and catchment. Also we don't delete gender and default group "Everyone" which we create while creating an organisation.
