### ISSUE TITLE
Dynamic pages UI issues

### ISSUE THREAD

**Issue by Sayali-Dev** [avniproject/avni-webapp#387]
10. For dynamic pages:
- On dynamic pages of form, label gets crossed with below lines, please see below screenshot:
![image.png](https://images.zenhubusercontent.com/5e257855e33c5efb529a84a9/45571ce6-25a9-4867-958b-b9eab29e35f3)

**Comment by garimadosar5** [comment]
QA Notes - 
- Next button has a black line.
![Screen Shot 2020-08-06 at 10.09.49 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/49c451ef-f2fd-41f4-9407-68fede133b37)
