### ISSUE TITLE
New screen for managing video playlist

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-webapp#388]

**Comment by garimadosar5** [comment]
QA Notes - 
- Duration does not take decimals. (like 2:30 secs.)
-

**Comment by vindeolal** [comment]
@garimadosar5 
1. added (in seconds) in the label.
2. The path for the video playlist is correct. the path in the picture is for media upload done by the user.
3. I'm able to play the video if it is placed in the correct path. (i.e. under /OpneCHS/movies). You might have to create movies folder under OpenCHS.
