### ISSUE TITLE
CRUD for encounter type

### ISSUE THREAD

**Issue by amarkamthe** [avniproject/avni-webapp#39]
UI:
Using react admin. Fields  - Name.

API:
New api needs to be created which will create encounter type and operational encounter type.

**Comment by hithacker** [comment]
This is on hold since API is not ready

**Comment by garimadosar5** [comment]
![Screen Shot 2019-09-20 at 12.08.13 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/cfc684ce-0818-4af8-a3d7-897474cda9b2)

It gives server communication error on saving a new encounter type.

**Comment by hithacker** [comment]
@garimadosar5 It will not work for encounters from organisation 1. I will disable edit and delete for them.

**Comment by hithacker** [comment]
@garimadosar5 moving this to qa ready as it's working now for orgs other than 1. We are showing org id column now so it's clear which entities belongs to core and can't be edited or deleted.
