### ISSUE TITLE
Bugs on the app designer

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-webapp#395]
- [x] Forms should be sorted by date. Add a new column last modified in the form table.

- [x] Add documentation link for concept datatype on the form create/edit page.

- [x] Change audit displays to make it more human-readable across the app (admin and app designer) Example: Created by admin@bborg on 12/3/2020 at 12:00 am

- [x] When you click 'select from library' the focus should be in the concept name field so I can start typing right away .

- [x] In concept show page and form element concept answer show be displayed as per the order defined.

**Comment by garimadosar5** [comment]
**QA Notes-**  
- Created and modified users name are shown differently
![Screen Shot 2020-05-26 at 4.14.49 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/25db3fec-6f09-495b-b24c-984d894c570b)

"Modified by" is the right way because there can be more than one admin users.
