### ISSUE TITLE
CRUD for subject type

### ISSUE THREAD

**Issue by amarkamthe** [avniproject/avni-webapp#40]
UI:
using react admin. Field - Name

API:
Needs to be created which creates subject type and operational subject type.

**Comment by hithacker** [comment]
This is on hold since API is not ready

**Comment by garimadosar5** [comment]
QA Comments - @swapnil106111  @hithacker 

- It is giving server communication error on edit, delete and creation of Subject type.

**Comment by hithacker** [comment]
@garimadosar5 It will not work for org 1. Will disable edit and delete for org 1 here also. But creation should have worked. I will check.

**Comment by hithacker** [comment]
@garimadosar5 moving this to qa ready as it's working now for orgs other than 1. We are showing org id column now so it's clear which entities belongs to core and can't be edited or deleted.
