### ISSUE TITLE
[Webapp] when a location is deleted it does not delete from client.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/avni-webapp#404]
Steps - 
1. Create 3 levels of location BLOCK, PHC and Village.
2. Check in the app. (it shows all the locations)
3. Now delete the location VILLAGE and delete location types also.
4. It keeps showing in the client. (delete data and check.)

**Comment by vindeolal** [comment]
Staging APK : https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-e78b-2020-06-08-16-05-15.apk
