### ISSUE TITLE
Readonly app release blockers

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-webapp#408]
Dev:
- [x] app sometimes crashes on the subject dashboard - **DONE**
- [x] app crashes if user settings are null - **DONE**
- [x] app shows write functionality if the read-only setting is not set on the user - **DONE**
- [x] app shows name column on search dashboard as Household number - **DONE**
- [x] Login page alignment issues. https://user-images.githubusercontent.com/100277/84374170-402c2f80-abfb-11ea-9b76-f7564f425728.png - **DONE**
- [x] Columns coming in the wrong order on Yenepoya staging. - **DONE**
- [x] Home page list of all the individual, Sorting option on columns does not work. Some duplicate rows start showing up duplicated if you sort multiple times. - **DONE**
- [x] Pagination and sorting is buggy on completed visits page when there are more than 5 visits e.g. https://staging.avniproject.org/#/app/subject/completedProgramEncounters?uuid=7160381f-2736-49d1-bc3a-d5e745ac8ddb. User admin@setco-trial
- [x] Pregnancy program also shows as MOTHER when click on profile. eg - CK implementation, case - Shital Chaudhary - **DONE**
- [x] Search does not work if I search by middle name, last name or surname - **DONE**
- [x] Shows static label Village on subject dashboard regardless of address level type - **DONE**
- [x] Translations 
        - HOME
        - RESET
        - DASHBOARD (at top)
        - ROWS PER PAGE
        - Relatives is translated as - रिश्तेदारों (Keep it as रिश्तेदार)
        - “No Scheduled Visit” should be कोई नियोजित विजिट नहीं 
        - “No complete visit” should be कोई पूर्ण विजिट नहीं 
- [x] Add a box for Data Entry app on org admin home page - **DONE**
- [x] On General tab of the subject dashboard -> Cancelled encounter shows up as a planned encounter with tag Due or Overdue. It should show tag canceled and not "due or overdue"
- [x] User settings menu get partially hidden behind the table on the home page
- [x] Translations missing for the search table columns on the home page - **DONE**

**Comment by garimadosar5** [comment]
QA Notes - 
- Home page list, first column says "Household number". It should be "Name".
-

**Comment by garimadosar5** [comment]
**QA Notes** - 
- There is no filter to search for Specific visits and program or Subject type.
