### ISSUE TITLE
Checklist Schedule Builder

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-webapp#42]
### Mockup

Checklist Builder

- Checklist Form `<dropdown that allows to choose form of type ChecklistItem>`

Items (Option to add items)
Item (Option to remove item)
 - Concept `<autocomplete with NA concepts>`
 - After how many days of birth should it be scheduled? `<number>`

 - Can this item expire? `<yes|no>`
 - Expires after how many days from birth date? `<number>`

 - Do this item depend on any other item? `<yes|no>`
 - Dependent On `<autocomplete or dropdown with items defined previously>`
 - Minimum Gap From Dependent (days) `<number> //show only when this item depends on other item`

![IMG_20200110_124312.jpg](https://images.zenhubusercontent.com/5d36cb3109d6d4240f1abe8e/cc6b5fad-8c46-4e22-96c6-0ac7de8e6013)

### Implementation Details

You need to call POST /checklistDetail api to save the checklist.

**Comment by vinayvenu** [comment]
We will play https://app.zenhub.com/workspaces/avni-5cf8e458bf08585333fd64ac/issues/avniproject/avni-webapp/323 right now in favour of this one.
