### ISSUE TITLE
Cannot upload the metadata zip bundle to an organisation which doesn't have media directory

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-webapp#426]
**Describe the bug**
For an organisation, media directory is optional when creating it. But for such uploading, the metadata zip doesn't work and gives an error that media directory is missing.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to app designer and download implementation bundle with locations
2. Create a new organisation without a media directory
3. Go to admin, upload. Try uploading the zip file by choosing metadata zip
4. See the error below

![image](https://user-images.githubusercontent.com/105867/85541524-b2f2cd00-b635-11ea-826e-4a9152a9cec4.png)

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- Does the fix require extensive regression testing?
  - [ ] Yes
  - [ ] No
- Are you mentioning the required scenarios that could be affected?
  - [ ] Yes
  - [ ] No

**Comment by vindeolal** [comment]
Now media directory is mandatory while creating a new organisation.
