### ISSUE TITLE
Cannot add media directory for an existing organisation

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-webapp#427]
**Describe the bug**
The media directory is not editable even if it is empty.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an organisation without media dir. Save
2. Try editing, the media dir is uneditable.

**Expected behavior**
Media dir  should be editable if empty

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- Does the fix require extensive regression testing?
  - [ ] Yes
  - [ ] No
- Are you mentioning the required scenarios that could be affected?
  - [ ] Yes
  - [ ] No

**Comment by vindeolal** [comment]
Now media directory is mandatory while creating a new organisation.
