### ISSUE TITLE
Upgrade Material UI to latest version so the issues with UI are fixed

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-webapp#438]
### Motivation
Upgrade Material UI to latest version so the issues with UI are fixed

### Tech Approach
When we try to upgrade to latest version of material-ui. Problem is mainly that in the generated js bundle the rendered output shows random styling. 
This could be due to multiple versions of material ui.
We have multiple versions of material-ui mainly being used by react-admin and the second being used by rest of the main application. There could also be small components using material-ui different version that we should remove if not required. We can check in yarn.lock file as to how many versions of material-ui are there. 
Even after removing other versions of material-ui, we will still have two different versions of material UI - one required by react-admin and one by rest of the application.
We have to explore why the prefix option("avnijss") we had used earlier to differentiate between different versions of mui is not working. May be they have changed the API that we need to use. If we can find this out and this solves the problem then well and good otherwise we have to think about getting rid of react-admin itself. Getting rid of react-admin may not really be that big an effort since we have our own admin components that we are using in app designer anyways. And the apis are also there.

**Comment by vinayvenu** [comment]
Too old. Closing.
