### ISSUE TITLE
Pagination is broken in the upload page.

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-webapp#458]
Upload page just shows recent 5 entries and you can't click on next to see more entries. Nex/previous button does not work.

**Comment by garimadosar5** [comment]
QA Notes - 
- In the SS, there are 6 rows but on one page it is showing only 5 and I cannot move to next page.
- everywhere else we show the dropdown to select the number of rows. 5,10,15 (like this).
![Screen Shot 2020-09-11 at 9.11.19 AM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/f26704bd-001d-4e26-83e2-6e5db175d029) 

(admin@yenepoya/password)

**Comment by vindeolal** [comment]
@garimadosar5 
1. Pagination is working
2. Not required for job status tables.
