### ISSUE TITLE
Form details page - Ability to choose concepts and add rules for a question

### ISSUE THREAD

**Issue by amarkamthe** [avniproject/avni-webapp#46]
![image.png](https://images.zenhubusercontent.com/5d0b10e42fff8629577fc2cc/962e7fe7-ad49-4f02-9c7a-3e0aa8d34de2)

* Two tabs inside question - 3
  * Question details
    * Search for concept
      * On selection it will show UI depending on data type. Similar to current design.
  * Settings
    * UI to add a rule related to a form element

**Comment by hithacker** [comment]
@amarkamthe 
We will have to give user an option to use existing concept or create a new concept. I could find similar UI in SurveyCTO to take inspiration from:
![image.png](https://images.zenhubusercontent.com/5d0b10e42fff8629577fc2cc/5454c1c0-bbf6-4ee9-ba43-90663802d55c)

We need some thing similar.
