### ISSUE TITLE
Remove Share feedback and Introduce Freshchat

### ISSUE THREAD

**Issue by arjunk** [avniproject/avni-webapp#461]
### Motivation
The share feedback option hasn't been used much. We can remove it. Also to increase the engagement and adoption we will add freshchat widget

### Acceptance Criteria
- Remove the share feedback widget from all screens
- Introduce the freshchat widget on the home page. 

### Tech Approach
https://www.npmjs.com/package/react-freshchat
Token : 774f28b3-1a88-426b-a3f8-42308714f820

**Comment by garimadosar5** [comment]
QA Notes - 
- It takes 2-3 secs to load freshchat icon after web page.

**Comment by vindeolal** [comment]
@garimadosar5 there will be some delay, script takes some time to load. But I have moved it to the place when apps loads, so it will be bit faster.
