### ISSUE TITLE
DEA returning wrong search results

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-webapp#466]
**Describe the bug**
Search in Data Entry app for Sewa Rural returns wrong results.

**To Reproduce**
1. Login as sewa rural user adminsr and go to Data Entry App.
2. Click on Search button in top menu bar.
3. On search screen enter 10 as value of Standard filter and hit Search. 
4. Open some results. You can see that value of standard is not 10 in any visits.

**Expected behavior**
It should return only the students for which the value of the answer standard is 10 in one of the visits.

**Test Data**
adminsr, app.avniproject.org

**Screenshots**
![image](https://user-images.githubusercontent.com/100277/91538321-4cd83e00-e935-11ea-96ce-a5d9bab5a8fb.png)
![image](https://user-images.githubusercontent.com/100277/91538205-1ac6dc00-e935-11ea-84c2-549ec61d185a.png)

**Developer Checklist**
Developer fixing the bug should fill this checklist.

- Does the fix require extensive regression testing?
  - [ ] Yes
  - [ ] No
- Are you mentioning the required scenarios that could be affected?
  - [ ] Yes
  - [ ] No

**Comment by vindeolal** [comment]
Moving this on hold
