### ISSUE TITLE
View filter rule to hide first Form element group in genral encounter disables the rest of the form 

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-webapp#469]
**Describe the bug**
View filter rule to hide for first Form element group in general encounter disables the rest of the form 

**To Reproduce**

1. Add a skip logic to hide the first form element group of a general encounter
2. Check the form in the app, the remaining form gets disabled

**Expected behavior**

**Test Data**
Give details of example users, environment detail, username against which this issue is happening.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Developer Checklist**
Developer fixing the bug should fill this checklist.

- Does the fix require extensive regression testing?
  - [ ] Yes
  - [x] No
- Are you mentioning the required scenarios that could be affected?
  - [ ] Yes
  - [x] No

**Comment by vindeolal** [comment]
https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-f56d5-2020-09-10-11-19-36.apk
