### ISSUE TITLE
Ability to add/remove/edit members to a group

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-webapp#476]
As a user, I should be able to add/remove/edit members to a group.

Acceptance Criterias:
- When I click on add member button on the group dashboard, it should show a search screen and from there I should be able to add an existing member. When the maximum number for the role is reached, it should not allow to add a new member of that role and show an error.
- When I click on edit member button, there should be a screen that allows to change the role or relationship of that member.
- When I click on remove member button, app should ask for confirmation and then remove the member.

**Comment by 1t5j0y** [comment]
- [ ] Group Subject - Dashboard - UI changes to display and perform add member, edit member and remove member operations
- [ ] Search screen integrate for add member flow
- [ ] Edit Member screen UI
- [ ] Integrate APIs for adding, editing, deleting membership
