### ISSUE TITLE
Ability to create concept inline when creating a form element

### ISSUE THREAD

**Issue by amarkamthe** [avniproject/avni-webapp#48]
As an org admin, I want to be able to create a concept inline when creating a form element.

Mockups:

The flow when you are adding a new element and want to choose an existing concept for it:
![image.png](https://images.zenhubusercontent.com/5d0b10e42fff8629577fc2cc/e7be5591-301a-4f13-a029-d2d15f64c633)

The flow when you are adding a new element and want to create a new concept for it:
![image.png](https://images.zenhubusercontent.com/5d0b10e42fff8629577fc2cc/4e70d5d6-0e1c-425d-96e2-3c4c272b0d44)

The key idea behind these mockups is that we are telling the user explicitly that you have to choose or create a concept when you create a new element. Another main idea is to have a separate box for the concept in the element so it's obvious as to what the concept fields are and what the element fields are once the concept is created or chosen.

**Test Scenarios** - 
- Create a new question with the new concept.
- Create a new question with an existing concept.
- Create a new coded type question with the existing concept for question and new coded answer.
- Create a new question with the new concept but that concept already exist in the system (it should give an error).
- Create a new concept and use this with existing coded answers.

**Comment by garimadosar5** [comment]
QA Notes - 
- If same concept is available in the system but the data type is different it says "concept is already exist" and does not allow to create a new one.

![Screen Shot 2020-05-01 at 5.57.55 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/c2ebe694-8e68-47d7-96e6-e584465f58d7)

**Comment by hithacker** [comment]
@swapnil106111 When we add a new question it shows like this:
![image](https://user-images.githubusercontent.com/100277/80805863-bc802b80-8bd6-11ea-8279-e17aa0e5c275.png)
There should be a header in concept box saying "Concept". Otherwise, it's not clear as to what it is that they need to select from the library or create new.

**Comment by hithacker** [comment]
Also after one choose a concept it shows like this
![image](https://user-images.githubusercontent.com/100277/80805985-14b72d80-8bd7-11ea-934f-d86e520fe37b.png)
Here it's confusing what I need to do to set the concept. Do I need to press back? Do I need to save form? There is no need of back button here. We can give Save and Cancel buttons.

**Comment by hithacker** [comment]
After I add a new concept and save it shows like this:
![image](https://user-images.githubusercontent.com/100277/80806177-9018df00-8bd7-11ea-80de-7c526155fba9.png)
If we add the static header "Concept" to the concept box that remains in all states(nothing selected, choose new, create), we should rename the label on concept name field as just Name)

**Comment by vinayvenu** [comment]
@hithacker the back button is necessary to change my choice. Suppose I chose "Create New Concept", and then change my mind, I cannot easily do so. Maybe we can name that button appropriately. What would you suggest?

**Comment by hithacker** [comment]
> @hithacker the back button is necessary to change my choice. Suppose I chose "Create New Concept", and then change my mind, I cannot easily do so. Maybe we can name that button appropriately. What would you suggest?

We can add Save and Cancel buttons as I said. Save will select the concept and show the state where a concept is selected. Cancel will take you back to the previous state where you can choose or create.

**Comment by vinayvenu** [comment]
@hithacker ok. The Cancel button makes sense.

**Comment by hithacker** [comment]
Paper sketch of what I meant:
![image](https://user-images.githubusercontent.com/100277/80935268-74852280-8de9-11ea-8179-fc01e28dce29.png)

**Comment by swapnil106111** [comment]
@garimadosar5 It must give an error if there is concept already exist. Can you please check same behaviour in new concept screen in concept?

**Comment by hithacker** [comment]
@vinayvenu @swapnil106111 Is there any reason why we are not putting choose button as well when one is selecting existing concept? Adding choose button along with cancel will make the UI consistent. Clicking on choose button will choose the concept and show it in the same state that we get when we create a new concept.
