### ISSUE TITLE
Ability to save system recommendations

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-webapp#487]
### Motivation
As an Avni user, I should be able to save the decisions given by the system.

### Acceptance Criteria
Save the system recommendations displayed after the user clicks the Save button in any of the forms.
- This should happen for the following forms:
  - Registration
  - Encounter
  - Encounter Cancel
  - Enrollment
  - Enrollment Exit
  - Program Encounter
  - Program Encounter Cancel
- If there are rule failures then do not show the decision table but let the user save the form without decisions. Rule failures should be logged to the dev tools > console.

**Comment by arjunk** [comment]
Part of the story we should also ensure that decision is shown in obs
display control
