### ISSUE TITLE
Misc bugs in Data Entry App - Part 1

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-webapp#488]
- Rules referring to zscore are not working because anthropometricReference var in avni-health-modules is empty. **Fixed**.
- In program encounter flow, the model object is not complete. It does not include individual in programEnrolment and also does not have all program enrolment fields so the view filter rules referring to individual are failing. **Fixed**.
- In Encounter flow, model object is not complete. It does not include individual details. So the view filter rules referring to individual are failing. **Fixed**.

**Comment by nupoorkhandelwal** [comment]
1. Nutritional status is not getting calculated, if page is refreshed (@Statging yenepoya)>>

![Screenshot from 2020-10-26 12-39-30.png](https://images.zenhubusercontent.com/5d1469c9b0b5db61870d0f5c/c277237e-d4f3-4663-8ced-5286cafa2b24)

**Comment by vindeolal** [comment]
@nupoorkhandelwal this issue is fixed.
