### ISSUE TITLE
Misc bugs in Data Entry App - Part 2

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-webapp#491]
- App crashes when you go to edit profile for the first time after you have loaded the app or have refreshed the browser. Getting error Cannot read property 'subjectType' of undefined on edit profile. Priority: High. **Fixed**
- When we edit profile, it's not showing gender and DOB fields. Priority: High **Fixed**
- We are allowing to do visits for exited programs also. Priority: Medium. **Fixed**.

**Comment by garimadosar5** [comment]
QA Notes - 
- Cannot edit a household type subject. (staging@yenepoya/password). case - Adarsh Bhavan, Desai etc.
- After exit, if I cancel ANC 2 visit, it scheduled new visit ANC 3. It should not schedule any visit.

**Comment by vindeolal** [comment]
@garimadosar5 
- Fixed the issue.
- We have the same behavior in the mobile app also. Right now in the field app, after a subject exists from a program we just don't allow them to perform unplanned visits. We can control this using the rules by checking the scheduled visit only when the subject is enrolled in the program.
