### ISSUE TITLE
Miscellaneous bugs in Admin and App designer apps

### ISSUE THREAD

**Issue by arjunk** [avniproject/avni-webapp#492]
0. Relationship does not allow to edit. says Individual subject type is required. even though there is a subject type of type Individual, named Person. Looks like it is checking on subject type name rather than subject type type. **FIXED**
1. No way to change the parent of an already saved location **[Admin Application: Locations screen]**  **FIXED**
2. Location search should be ‘anywhere in location name' search, currently, its 'location name starts with' search **[Admin Application: Locations screen]**  **FIXED**
3. Location -> Part of (Location) - The list is not sorted. Its difficult to find in a big list **[Admin Application: Location screen]**  **FIXED**
4. On click of concept from concept answer its a noop. should take to that concept **[App Designer Application: Logically concept answer screen but actually concept screen.]**  **FIXED**
5. No option to delete/void user group **[Admin Application]**  **FIXED**

~ 6. Dropdowns in different places have different UI/UX. At some places, we are using the dropdown and at other places autocomplete control even though they are functionally similar fields **[Data Entry, Admin, App Designer]**
7. At many places, the toast shows in black colour and with text 'Element created'. Rather it should say what specific element is created. E.g. Location created **[Admin Application]** ~
Moved these two to #499

**Comment by garimadosar5** [comment]
**QA Notes -** 
User Group - 
![Screen Shot 2020-11-05 at 7.52.11 AM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/c312f27e-507f-4485-a68f-5d63ab928daf)
Name of the user group is not visible completely.
