### ISSUE TITLE
[Data Entry App] Support for Legacy ViewFilter rules

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-webapp#498]
### Motivation
As an Avni implementer, I should be able to use legacy rules in my implementation.

### Acceptance Criteria
- When any form element or element group is filled, the legacy view filter rules attached to it should get executed if they exist. If there is a new rule existing for the form element(not mentioning group because we did not have legacy rules for groups), it should take precedence over the legacy rule.

### Tech Tasks
- Fetch the bundle whenever the app loads. Declare rulesConfig global variable in a singleton module. Make the API call to get the bundle for that org and eval the bundle and assign the result to the global rulesConfig var. To fetch the rule bundle use the API call GET /ruleDependency/search/lastModified?lastModifiedDateTime={oldestDate}. 
- Import rule files and initialize so RuleRegistry is populated with core module rules. Importing it in the main file of the server should do it.
- Add logic for initializing and merging rules and eval the rule. Similar to RuleService on avni-client.
- Add RuleService that gets a legacy rule handler for a form from RuleRegistry.
- Add code to do if-else to know whether to run legacy rule or new rule and eval the rule.

**Comment by garimadosar5** [comment]
QA Notes - 
- In CK, you cannot enrol a woman in mother program until unless a child is linked to her profile. But in DEA this is not happening.

**Comment by hithacker** [comment]
> QA Notes -
> 
> * In CK, you cannot enrol a woman in mother program until unless a child is linked to her profile. But in DEA this is not happening.

This is because of Validation rule that we don't support.

**Comment by arjunk** [comment]
@hithacker @garimadosar5 so what's the plan for this card?

**Comment by hithacker** [comment]
I moved this to Deploy ready after discussion with Garima. 
Point 1 was not valid because of not having to do with the scope of this story.
Point 2 was a corner case behavior (new style group rule in legacy implementation) that will not happen in a real-world scenario.
