### ISSUE TITLE
1 - Add rules tab with basic rule for form elements

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#505]
As an app designer, when I go to the rules tab, I have an option to build a rule. 

Different options to build the rule are available [here](https://docs.google.com/spreadsheets/d/1Y7jXM6Hsv6QIg_MnIK-9L568XaX7JOsN3CWg6xe_8pg/edit#gid=0)

### Scope

- Form element rule only
- Single rule (no conjunctions)
- Allow visibility, select answers and options
- Support only values in RHS

### Acceptance criteria
- When I go to a form element-> Rule, I have an option to graphically create a rule. 
- When such a rule is created, it can be converted to javascript to be saved to server

### Out of scope
- Use of "scope" in RHS
- Compound rules

**Comment by garimadosar5** [comment]
Test cases - 
https://docs.google.com/spreadsheets/d/1WL6F2f2wfhvlitb5WEjDop7nKqXDknhHTPfT3q1ylEY/edit#gid=784916143
