### ISSUE TITLE
5 - Ability to add multiple rules to form a compound rule

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#506]
I should be able to add multiple simple rules where they are all evaluated with an AND or an OR as defined by me to form a compound rule

See rule json in epic

We need modifications in the UI and change to the rule-json to rule conversion to support this.

**Comment by garimadosar5** [comment]
**QA Notes -** 
- If I want to edit the Action, it is not showing the options. 
SS - ![Screen Shot 2022-02-15 at 1.31.25 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/763eb202-bea0-4366-913f-ec4ed0600840)

**Comment by vindeolal** [comment]
- You can clear the action now.
