### ISSUE TITLE
1 - Start using uuids in rules

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#514]
Context for this story is provided in the epic https://app.zenhub.com/workspaces/avni-5cf8e458bf08585333fd64ac/issues/avniproject/avni-product/1139

### Acceptance criteria
- When rules are evaluated, they should respect uuid as well as name. (Android app)
- When rules are evaluated, they should respect uuid as well as name. (rules-server)
- When rules are evaluated, they should respect uuid as well as name. (rules-config)

**Comment by vindeolal** [comment]
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-4388c-2022-02-14-15-28-49.apk
