### ISSUE TITLE
Operational Program Name not displayed consistently

### ISSUE THREAD

**Issue by 1t5j0y** [avniproject/avni-webapp#522]
Org: Calcutta Kids

1. Search and Subject Dashboard
We are not consistently displaying program name from operational program name or program name in search and individual dashboard. In the programs column for subjects, it shows Mother as the program name for person enrolled in Pregnancy program

2. Enrol
When I enrol someone into mother program, it schedules a visit of type "Mother Home visit" with visit name "Child older than 6 months". When doing the encounter it shows encounter type name in the breadcrumb bar instead of visit name.

3. CK org - When I enrol someone into mother program, it schedules a visit of type "Mother Home visit". On doing do visit it shows loading screen forever. By refreshing the page it loads it.

4. CK org - Edit Visit in CK for Mother program - When I enrol someone into mother program, it schedules a visit of type "Mother Home visit". After finishing this visit it goes to completed visits section. On doing edit visit it shows loading screen forever. By refreshing the page it loads it.

**Comment by 1t5j0y** [comment]
For issue1, `search/v2` API (and in turn web_search_function) is returning the program name against the operationalProgramName field.

**Comment by hithacker** [comment]
@1t5j0y If Issue 1 is a small fix inside that routine, we can fix that first. avniproject/avni-server#220 does not have that high a priority so let's not wait for it.
