### ISSUE TITLE
Visit scheduling after program encounter not working

### ISSUE THREAD

**Issue by 1t5j0y** [avniproject/avni-webapp#524]
Org: Calcutta Kids

Visit scheduling is working for enrolment but for other program encounter visit scheduling is not working.
Case - dfrt hg (Program - Child program and Visit - Child GMP and Child Home visit)
Case 2 - abc xyz

Just to add more context: After one fills the home visit form, it's supposed to schedule another home visit but that's not happening.﻿

**Comment by 1t5j0y** [comment]
Might be already fixed.

**Comment by hithacker** [comment]
@garimadosar5 Can you check if this is fixed? The bugs we had fixed in legcy rules server side story may have fixed this also.
