### ISSUE TITLE
Age is not auto-calculated after entering DOB

### ISSUE THREAD

**Issue by 1t5j0y** [avniproject/avni-webapp#526]
**Describe the bug**
Age doesn't get autocalculated after entering DOB

**To Reproduce**

1. Register a subject
2. Enter date of birth
3. Age field remains empty

**Expected behavior**
Age should get auto calculated based on the DOB provided.

**Comment by 1t5j0y** [comment]
Issue was because date was being set as empty string by default which the component wasn't handling as a valid initial state.

**Comment by 1t5j0y** [comment]
Dev box discussion: Don't set date of birth to current date.

**Comment by garimadosar5** [comment]
**QA Notes -** 
- Age can be filled anything.
![Screen Shot 2020-11-25 at 1.04.14 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/47399f98-a504-412d-bd38-346d801c5074)

**Comment by 1t5j0y** [comment]
Unable to simulate this issue. DOB field is always shown with mask. Garima also confirmed it happened just once. Moving it back to QA.
