### ISSUE TITLE
[DEA] The unit is not displayed along with fields.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/avni-webapp#533]
- In case of the numeric field we provide unit in some concepts but in the web form, these units are not showing up.
SS - 
![Screen Shot 2020-11-30 at 11.52.59 AM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/a6558d19-5397-4d26-a83e-1a61d10932af)

**Comment by 1t5j0y** [comment]
Adding display of low and high range as well to be consistent with the field app.
