### ISSUE TITLE
[DEA] Small P3 issues in data entry app

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/avni-webapp#536]
**Profile and Breadcrumb**
- [x] Age unit in profile bar when filling the form shows up in 3 letters (like 3yrs), We have enough space. We can show 'years'
![Screen Shot 2020-12-02 at 4.10.09 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/0d21c5a9-778f-49e4-935a-05f7d1a5c4f4)
- [x] For the non person subject type registration name says "first_name Undefined" because last name is undefined Same for age and gender. link - https://files.gitter.im/5d821246d73408ce4fcb56d8/H8AG/image.png
- [x] Breadcrumb is lost when one starts exit enrolment. It shows Home->Enrol instead of Home->Subject->Enrol
- [x] breadcrumb in the enrolment flow does not show the option to go to the subject dashboard as it does in program encounter flow

**Form and Form fields**
- [x] Certain input fields show grey in colour e.g. numeric and text whereas certain input fields show in Black e.g. Date. Similarly certain labels are grey in colour e.g. for coded type whereas certain labels are black in colour e.g. numeric. This all should be consistent
- [ ] When inputting value / when in focus in coded type question e.g. Floor (org - CK), it highlights in blue but does not do any such highlighting for other datatypes. The others should also be highlighted similarly
- [x] Boundaries between different form elements is not clear when there is validation error. The error message seems to be displayed on the next element.
- [ ] ~There should be more gap between input control of previous element and label of next element~ Same as prev
https://drive.google.com/drive/folders/1GEEr2qsk8B6pCEDLrWABvKfrb5flmTbt
- [x] On the first page while entering DOB, its not clear that i can either enter DOB or Age. Is it a single component? Expected behaviour: Reduce space between the two components similar to what is done in Android.
- [x] On click of save of the Registration form, there seem like a pause before transitioning to subject dashboard
 Same for all save buttons.
 In code, there is hard coded 2.5 secs timer. We have to remove that.
- [ ] ? If it is a non-editable field should we show the input control. e.g LMP EDD. EDD shows underline and calendar button. User will never be using them. so what's the point of showing it
![Screen Shot 2020-12-02 at 4.19.05 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/4faaff6a-aefc-4840-8bff-56569441dccc)

**S&R**
- [x] On S&R page different boxes are showing in a different style. one is grey, others are not. This is should be consistent and clean. Expected behaviour: Display Scheduled visits with grey background similar to Decisions. Leave observations with white background.
https://drive.google.com/file/d/1ieyBivkxzN4HUoWZnJ7S4kHw5-WH60-T/view?usp=sharing

**Misc**
- [ ] On New program visit, only the visit name is clickable. This will slow down the user. The whole bar should be clickable. Also when there are a lot of elements, we will have to separate one bar from another either by alternate colour or giving space between bars
https://drive.google.com/file/d/1Ne6o0WdTdLS0xHXUlOU7ij-6vvTJXlX5/view?usp=sharing
- [x] Register subject -> Subject Type selection Dropdown remains on screen even after making a selection
- [x] Position of primary action is different at different places. For e.g. in form, the next button is second, whereas in Enrolment modal, the enrol button is first
![Screen Shot 2020-12-02 at 4.04.58 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/ee982b7a-fad6-4ef4-81dc-2799bc2a7f76)
![Screen Shot 2020-12-02 at 4.05.05 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/d6f77890-fa3a-487e-98fb-e7df2c677691)
![Screen Shot 2020-12-02 at 4.05.22 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/caece87a-55d1-46c5-872d-8c6806110c98)
- [x] General encounter, cancelled visits shows in the scheduled visit list. E.g. Yeneoya > Sachi Family
<img src="https://images.zenhubusercontent.com/5d0b10e42fff8629577fc2cc/a5903c34-69c9-4027-ba9f-8fccb25f3db8" alt="drawing" width="400"/>

**Comment by 1t5j0y** [comment]
I would suggest moving the following points to separate cards are they will require more work:
1. When inputting value / when in focus in coded type question e.g. Floor (org - CK), it highlights in blue but does not do any such highlighting for other datatypes. The others should also be highlighted similarly
2. On New program visit, only the visit name is clickable. This will slow down the user. The whole bar should be clickable. Also when there are a lot of elements, we will have to separate one bar from another either by alternate colour or giving space between bars

**Comment by garimadosar5** [comment]
QA Notes - 
Point - "Position of primary action is different at different places. For e.g. in form, the next button is second, whereas in Enrolment modal, the enrol button is first", is not done at all the places.
![Screen Shot 2020-12-09 at 8.27.52 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/05915f06-28e8-4f73-821b-a2c45e785e88)

![Screen Shot 2020-12-09 at 8.28.07 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/d1c5b4d9-bf23-469e-9632-d0b6930ffbfd)

**Comment by 1t5j0y** [comment]
Fixed mentioned issues.
