### ISSUE TITLE
[DEA] Visit scheduling is not working for JSSCP.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/avni-webapp#545]
- The visit is not getting scheduled after program encounter. (ANC clinic visit.) Case - Aagar Gond
-  BMI is not getting auto-calculated. check in Pregnancy Program

**Comment by vindeolal** [comment]
- View Filter rule for BMI was missing, added that now auto-calculate is working.
- Call to the rule server is failing, that's why visit is not getting scheduled.
