### ISSUE TITLE
Add storybook to avni-webapp

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#555]
Development of components is easier when you can test them in isolation. Storybooks provide an easy way to do that. 

Acceptance criteria
--------------------

- Integrate storybook (https://storybook.js.org/) into avni-webapp
- Write two sample storybook components as example.

**Comment by vinayvenu** [comment]
Some guidelines
1. Write storybooks along with the component itself with a name <component>.storybook.js
2. Develop from the smallest components. Makes it easier to build bigger stories
3. When writing one storybook, take another random component and write a storybook for it. 
4. Name them "<AppName>/<directory>/<component> for consistency.

**Comment by 1t5j0y** [comment]
Got it working locally and can see the components for which storybooks have been written. Moving to closed.
