### ISSUE TITLE
Add new "Phone Number" concept datatype

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#563]
## Story
As a form designer, when I create a form, I get the option to create a new datatype - Phone Number. While creating, I have the option to mark it as verifiable. 

## Acceptance criteria
- When creating a form, there is an option to create a form element of type "Phone Number"
- When choosing a concept of type Phone Number, there is an option to "Switch on Verification". 
- Details are stored in the concept table. "verification" is stored in keyValues of concept.

**Comment by 1t5j0y** [comment]
- [ ] Concept creation
- [ ] Inline concept creation
- [ ] Form designer
