### ISSUE TITLE
Ability to void entities from DEA

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-webapp#569]
We provide an option to void the subject. A similar option should be available to void program enrolment, program encounters, and general encounters. Right now we'll only give the option to void the other entities so the user will not be able to unvoid it once it's voided.

**Acceptance criteria**
- We should void an entity only when all its children voided. So for voiding a subject user must first void all the encounters and program enrolments. Similarly for program enrolment user must first void all the program encounters.
- We'll continue to show the voided subjects from the search as we do right now.
- Other voided entities(enrolment, encounters, and program encounters) will not be shown to the user.

**Tech tasks**
- Server APIs to void encounter, program encounter, and enrolment.
- Using these APIs on DEA to perform the appropriate action.

**Comment by garimadosar5** [comment]
QA Notes - 
- What is subject 29 here? this error message comes when you try to void an individual.
![Screen Shot 2021-01-29 at 1.36.12 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/3b2d372e-46a4-4f25-b05d-3dffcc5a475d)

**Comment by vindeolal** [comment]
Fixed the error message.
