### ISSUE TITLE
[AppDesigner] - Offline Dashboard customizations

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#570]
In order to perform customizations on the field-user app, we need to be able to add these customizations to the custom dashboard configuration. Specifically

1. Icon for a report card
2. Option to define standard report cards
3. Option to set up dashboards on a group basis

### Acceptance criteria
- New field - "Icon" - on Report Card to choose icon on a report card. 
- New option to create standard report cards. The standard report cards will be available in standard_report_card_type table. We will eventually add more items to this list. The query will not be available for standard report cards.   
- New tab to edit list of dashboards available. You can mark dashboards as available to group, and mark one of them as primary.

**Comment by garimadosar5** [comment]
QA Notes - 
- I cannot see the option to set up a dashboard on group basis.
![Screen Shot 2021-02-26 at 6.42.52 AM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/8b8d531d-9b68-458d-b60a-ded263dedceb)
