### ISSUE TITLE
[DEA] Scheduling a general encounter from registration is not working. 

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-webapp#575]
**Describe the bug**/**To Reproduce**
Try registering subject type "Monthly Reporting" in Chetna-Sneha org on DEA. Ideally the general encounter should get scheduled (as in the app).But the visit is not getting scheduled on staging & prod as well.

**Comment by vindeolal** [comment]
@nupoorkhandelwal 
Can' reproduce the issue, it is scheduling the visit on staging and prod. Please provide more details.
