### ISSUE TITLE
Add icon to Subject Type

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#576]
As an implementer, when I create a subject type on the dashboard, I have the option to choose an icon to describe the subject type visually. 

### Acceptance criteria
- When creating or editing a subject type, there is an option to upload an icon for the subject type
- When there is an icon selected, it shows up on the screen
- When saved, the icon is saved on s3

**Comment by garimadosar5** [comment]
**Qa Notes -** 
- I cannot go back to default icon from UI/

**Comment by vindeolal** [comment]
- Added ability to delete the uploaded icon so that it fallbacks to default icons.
