### ISSUE TITLE
[DEA] List broadcasts

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#580]
This story will add the ability to list and view news broadcasts on the data entry app. 

### Acceptance criteria
- There is a new option called News on the top of the screen, which takes you to the list of news broadcasts (https://preview.uxpin.com/79845a6c0a33074286a4a933ca1ac6cc074aae04#/pages/136090555/simulate/sitemap?mode=i)
- On clicking on one of the broadcasts, it takes you to read the broadcast (https://preview.uxpin.com/79845a6c0a33074286a4a933ca1ac6cc074aae04#/pages/136090557/simulate/sitemap?mode=i)
On clicking back, it takes you back to the listing

**Comment by garimadosar5** [comment]
QA Notes - 
- Formatting is not right.
![Screen Shot 2021-04-08 at 11.38.43 AM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/c1b96c06-d8d4-4652-b3e7-51c9fad4c81d)

- There is no way from the news page to come back to the home page of the Data entry app.

**Comment by vindeolal** [comment]
@garimadosar5 
- UI is fixed.
- We can click on the browser back button to move back or we can click on avni icon that will open the first page of DEA.
