### ISSUE TITLE
[Web admin][Bug] Catchment is not showing while creating user.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/avni-webapp#587]
**Describe the bug**
While creating users, some catchments are not showing. this is reported for two implementations - 
1. JSSCP - Catchment - Shivtarai is not showing in the catchment list on Create user page.  
2. Chetna Sneha - Master catchment is not showing in the catchment list on Create user page. 

**To Reproduce**
Check for Chetna Sneha(Master Catchment) and JSSCP implementation  (Catchment -Shivtarai)

**Expected behavior**
It should show the complete list of catchments.

**Test Data**
Give details of example users, environment detail, username against which this issue is happening.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Developer Checklist**(Developer fixing the bug should fill this checklist)
- Does the fix require extensive regression testing?
  - [ ] Yes
  - [ ] No
- Are you mentioning the required scenarios that could be affected?
  - [ ] Yes
  - [ ] No

**Comment by vindeolal** [comment]
- Shivtarai Catchment is voided, so it showing on the listing page when you search it but not on the user page. Now voided catchment will not show on the listing page as well.
- You can now see the master catchment as well.
