### ISSUE TITLE
Allow empty locations for subjects

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#593]
It is possible that the location of a subject is unknown at the time of registration. As part of this story, we will allow registering subjects without a location. 

In order to make this happen, the subject must be marked as "Allows empty location". Sync will not happen for the subject without locations. Once it is marked to a location, it must start syncing to the location.

**Comment by garimadosar5** [comment]
QA Notes - 
- What will happen if the data entry is done by the Web data entry app. It is syncing to the server.
