### ISSUE TITLE
first entry of location upload gets skip/fail

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-webapp#598]
**Describe the bug**
During each location file/csv upload for first time, the first entry is skipped. Though the remaining items get upload.
And if the same file is uploaded again, the entry gets uploaded successfully.

**To Reproduce**
[RWB MH Manavlok - locations.csv](https://github.com/avniproject/avni-webapp/files/6351899/RWB.MH.Manavlok.-.locations.csv)

Tying uploading the attached file to RWB UAT org. The first entry is skipped. And if the same file is uploaded again, it will upload successfully.

**Comment by vindeolal** [comment]
I was not able to reproduce the bug completely. This was happening because the user context was not set properly, have fixed it in this commit https://github.com/avniproject/avni-server/commit/2556b2c41d215626574ab61e86289e367a0ef452.
