### ISSUE TITLE
Numeric concepts do not allow decimal values

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#615]
Freshdesk Ticket - https://avni.freshdesk.com/a/tickets/1274

Example: In app.avniproject.org, go to JSSCP programme, data entry app. 

Pick any child in Phulwari programme and try to enter weight on the Growth Monitoring Visit. App does not allow entering decimals.

**Comment by garimadosar5** [comment]
QA Notes- 
- There should an option to select if decimal is needed in the numeric concept.
For example - we do not need decimal in adhar or phone number, BP etc.

**Comment by vindeolal** [comment]
@garimadosar5 We can do this by specifying the regex validation in that form element. It is already there.
