### ISSUE TITLE
Release feedbacks

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-webapp#637]
- Fix the UI of the longitudinal export. When the report type is changed, the date filter shakes up and down.
- Add report type column to the longitudinal report.
- Action buttons(modify search and ok) on the relationship page should be floating, so that user don't have to scroll down for selecting the relative.

**Comment by garimadosar5** [comment]
QA Notes - 
![Screenshot (10).png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/6bc15feb-1a65-4736-a270-d938d907d90a)

Please fix this table UI.

**Comment by vindeolal** [comment]
@garimadosar5 
- UI is fixed
- Report type column is added in the job status table and not in the CSV file.
