### ISSUE TITLE
[DEA] Ability to upload and download a file

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-webapp#648]
If the file concept is used in any form as a user I should be able to upload the file. File MIME type and file max size as configured for a form element should be respected while uploading the file to s3. Display the file name once the user selects a file in the form. The user should also be able to download the file from s3.

**Comment by garimadosar5** [comment]
QA Notes - 
- I could upload csv, jpeg etc as files.
https://staging.avniproject.org/#/app/subject?uuid=a93e4a96-30ad-474f-946e-3f5538c3a3ad

**Comment by vindeolal** [comment]
You can upload any file even zip if you have not selected what file type you want to upload.
