### ISSUE TITLE
Identifier assignment screen doesn't display more than 20 users

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-webapp#651]
If an organization has more than 20 users, then the identifier assignment screen does not display all the users. Only the top 20 users are visible.

**Comment by garimadosar5** [comment]
QA Notes - 
- While assigning user the ids, do not show super admin's ids.
![Screenshot from 2021-09-03 10-23-48.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/28ddd822-7d59-4dee-9979-979301c59942)

**Comment by vindeolal** [comment]
Fixed
