### ISSUE TITLE
[DEA] Search issue

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/avni-webapp#659]
**Describe the bug**
In case of text type search, if the user types text with the space then it shows the cases with the last word in it.

**To Reproduce**
1. Go to DEA of JSSCP (for eg)
2. Go to search page.
3. select subject type Phulwari
4. search for name Mani Bai.
5. It will give you all the phulwari where 'Bai' is in the name.

**Expected behavior**
It should return the search result that consist of both Mani and Bai in the name.

**Test Data**
Give details of example users, environment detail, username against which this issue is happening.

**Screenshots**
![Screen Shot 2021-09-28 at 3.26.16 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/8c0fba4f-b10b-46c6-8039-903d5f6048fb)

![Screen Shot 2021-09-28 at 3.26.29 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/bfbeadd6-cf95-4884-bcda-49292a15cbc3)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Developer Checklist**(Developer fixing the bug should fill this checklist)
- Does the fix require extensive regression testing?
  - [ ] Yes
  - [ ] No
- Are you mentioning the required scenarios that could be affected?
  - [ ] Yes
  - [ ] No

**Comment by vinayvenu** [comment]
Some performance enhancements have also been made as part of this fix.
