### ISSUE TITLE
Getting error while registration the subject

### ISSUE THREAD

**Issue by sachsk** [avniproject/avni-webapp#666]
**Describe the bug**
When we are skipping the first FEG of the subject registration form. then getting error while registration of that subject from DEA.

**To Reproduce**
1. Create a subject registration form add one FEG and skip that FEG. 
2. Register that subject from DEA
3. On the last screen see the error

**Expected behavior**
We should be able to register the subject 

**Test Data**
Rise_uat ->>organisation registration 

**Developer Checklist**(Developer fixing the bug should fill this checklist)
- Does the fix require extensive regression testing?
  - [ ] Yes
  - [x] No
- Are you mentioning the required scenarios that could be affected?
  - [ ] Yes
  - [x] No

**Comment by vindeolal** [comment]
@sachsk this is fixed, can you test this out on Staging?
