### ISSUE TITLE
Support Attendance UI for existing subject form element

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-webapp#670]
**App designer**
- On the app designer for subject type concept provide the option of attendance which will be stored as key values in the form element.

**DEA**
- If attendance is enabled on any subject form element then show the new UI. which will be a switch button with the name of each member.
- User can turn on the switch to mark any member present.

**Comment by vindeolal** [comment]
There are two key-values added "Display all group members" when enabled it'll display all the members of the group and rules value will not work in this case. "Search option" This will display the default search screen on webapp, this has no effect on mobile app.
Right now at a time only one key-value is respected.

**Comment by garimadosar5** [comment]
**QA Notes -** 
UI -
![Screen Shot 2021-11-18 at 8.04.20 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/3cc52d43-0e03-40ad-ac58-f10c4ab51384)
