### ISSUE TITLE
getAllUnique('name') is not working

### ISSUE THREAD

**Issue by sachsk** [avniproject/avni-webapp#689]
**Describe the bug**
getting an error when we use the getAllUnique('name') in visit scheduling. and visits are not scheduling .

**To Reproduce**
1. Use the getAllUnique('name') in visit scheduling.
see the error on server log

**Expected behavior**
It should schedule visit

**Test Data**
impl: ywnxtkef
Uname: sachink@ywnxtkef
Password :saman@123

**Developer Checklist**(Developer fixing the bug should fill this checklist)
- Does the fix require extensive regression testing?
  - [ ] Yes
  - [ ] No
- Are you mentioning the required scenarios that could be affected?
  - [ ] Yes
  - [ ] No

**Comment by vindeolal** [comment]
Bug description: encounters are not passed to the rules-server during registration flow and rule execution fails as `individual.encounters` is undefined.
This is fixed now in both servers on staging.

**Comment by sachsk** [comment]
@vindeolal  @garimadosar5 Now it working fine.

**Comment by vindeolal** [comment]
@sachsk can you please move the card to the next lane if QA is done.
