### ISSUE TITLE
Custom fields on the search result

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-webapp#699]
### Context
Avni web app has the capability to search by many fields, but the results do not show any of these fields. As part of this story, we will be providing an option to configure fields to be shown on the results page. 

### Solution
- Results page can be configured through App Designer
- Only registration fields can be shown on the results page

### Acceptance criteria
- On App Designer, there is a new section for Results Fields
~- A note will be provided on the App designer that the "Results" fields will be available only on the "Data Entry App", and not on the "Field App".~
- Results Fields will have ability to remove existing default fields, and add new fields
- Fields can be ordered within the App Designer
- For new fields, there will be an option to choose from all observations in Registration form as well as concepts provided as decision concepts
- Fields will be shown based on this design on the results screen

**Comment by vindeolal** [comment]
moving it back to ready till we get the approval.

**Comment by garimadosar5** [comment]
**QA Notes -** 
- Subject type concept is showing like this.
![Screen Shot 2022-01-28 at 11.00.37 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/6c46d753-a33b-4bba-b210-7aab196c54e2)

User -garimad@qa

**Comment by vindeolal** [comment]
You can't use subject concept now. Only numeric, text coded and I'd will be shown
