### ISSUE TITLE
Longitudinal export date field is always on UTC format

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-webapp#701]
**Context**
Right now all the time is saved in UTC in the Avni DB, and we export the same date time when the user downloads the reports from longitudinal export. Sometimes due to differences in timezone(UTC and IST(+5.30)) the date might lag by one day. This kind of creates confusion.

**Solution**
The browser will send the timeZone and all the date time-related fields will get converted to the passed timeZone.

**Acceptance criteria**
All the date-time relates fields like encounter_date_time, last_modified_date_time, or any date-time concept should get exported to the local timezone.

**Comment by garimadosar5** [comment]
Make dates YYYY:MM:DD HH:MM:SS.

**Comment by vindeolal** [comment]
Time zone information is required and right now we are not doing this. If there is any comment from the client then we'll change this later
