### ISSUE TITLE
Catchment only allows adding locations at the same level.

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-webapp#711]
Right now one can only add locations at the same level to a catchment. We should not have such a check and should allow adding any location to a catchment.

## Acceptance criteria
- Any location can be added to the catchment.
- Sync should work fine and data should get synced for all children of the selected locations.

**Comment by garimadosar5** [comment]
QA Notes - 
- when diff level of locations are assigned, how it will sync in the app.
Org - Yenepoya Staging.
User staging@yenepoya
Catchment - Diff level (One Surveillance Unit and one Gram panchayat)
In App only Surveillance Unit is showing 
Refer SS - 
![Screen Shot 2022-01-28 at 11.37.18 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/6bf98220-cdaf-4416-b023-29b053c782a5)
![Screen Shot 2022-01-28 at 11.37.12 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/5297a99a-9953-429d-b9d2-67e4d901ff79)

**Comment by vindeolal** [comment]
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-243b-2022-02-01-14-31-27.apk
