### ISSUE TITLE
Form element group invisible on Safari

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#724]
https://avni.freshdesk.com/a/tickets/1577

**Comment by garimadosar5** [comment]
**QA Notes -** 
- For registration form, first FEG is not showing.
![Screen Shot 2022-03-01 at 5.51.42 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/024d32fe-fd4a-4748-92e1-6611023779ad)

**Comment by vinayvenu** [comment]
@garimadosar5 Can you please check now?
