### ISSUE TITLE
Display encounter/program name directly

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-webapp#743]
In the case of a single Program/Encounter display the option directly instead of moving to a new screen.

### Places

- [x]  When enrolling into a program
- [x]  When creating a new General Encounter
- [x]  When creating a Program Encounter

DIrectly show option on the button if there is just one option available. 

### Tech Notes
- Currently, we get the values when we go to the new screen. It has to happen earlier if we need to know this information ahead of time

**Comment by vinayvenu** [comment]
This is complete.
