### ISSUE TITLE
Visit scheduling rule designer doesn't allow/show general encounters as option in the encounter type for the visit to be scheduled from program visits

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-webapp#744]
![Screenshot from 2022-05-01 11-34-59.png](https://images.zenhubusercontent.com/5d1469c9b0b5db61870d0f5c/9d24956f-7109-4ef2-a099-26a0e6e525d9)

This is a screenshot from JSSCP UAT, there are general encounters- eg. Verbal autopsy which is not coming in the drop down.

**Comment by petmongrels** [comment]
it was found to be working already.
