### ISSUE TITLE
Sync attributes to set via users & catchments csv upload is not working

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-webapp#751]
We tried uploading the attached csv on RWB UAT, but it dint work-
![image.png](https://images.zenhubusercontent.com/5d1469c9b0b5db61870d0f5c/3bbf67cc-2a4b-467d-8ba3-7071cb8624c4)

**Comment by vinayvenu** [comment]
Fixed as part of avni-server #382. Closing this issue.
