### ISSUE TITLE
[DEA] - Inline display of observations with that of mobile app

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-webapp#759]
### Need:
Currently the DEA only supports question group when it is not repeatable. It breaks whenever it has to render a form with repeatable question group elements. And for lengthy forms it is difficult to differentiate the observations captured in different pages.

### Acceptance criteria:
- Ability to display observations captured in repeated group form elements in any form/entity - encounter, cancel forms etc.,.
- Differentiate the observations captured in different pages, by displaying the name of the 'form_element_group' with grey background, like done in mobile app
![Image](https://github.com/avniproject/avni-webapp/assets/10369963/bdb0b52f-483c-44b1-9cd2-9ebc8bf8ddb0)

#### Showing:
Current status of DEA with question group which is not repeatable:
<img width="1512" alt="Screenshot 2024-02-13 at 6 03 39 PM" src="https://github.com/avniproject/avni-webapp/assets/10369963/a73c441d-23d7-4646-81be-849175f2c1ff">

Make it something similar to how it is in client as shown in the below image regarding the below 3 things:
-  line dividing different question group sets.
- 'Materials dispatched' displays twice because one is page name and the other is concept name 
- alignment - names of concepts within question group is left indented to the name of the question group concept name.

<img width="439" alt="Screenshot 2024-02-13 at 6 13 11 PM" src="https://github.com/avniproject/avni-webapp/assets/10369963/48996d8e-74ac-4644-b387-74eda7f69c80">

**Comment by himeshr** [comment]
Sample screenshot for Goonj Distribution Subject DEA screen with Repeatable(Inventory Details) and Single(Activity Details) QuestionGroups.
<img width="1840" alt="Screenshot 2024-03-25 at 4 21 22 PM" src="https://github.com/avniproject/avni-webapp/assets/72493481/12ab2823-7ce8-4b4d-9eda-43ca40ae6ea7">

**Comment by himeshr** [comment]
http://localhost:6010/#/app/subject?uuid=df56a62a-e7bf-461d-ac6f-0a6134bc65c6
<img width="1840" alt="Screenshot 2024-03-25 at 5 22 34 PM" src="https://github.com/avniproject/avni-webapp/assets/72493481/ddfe80d3-4cfd-484b-aae6-0092ca52b4d8">
