### ISSUE TITLE
Task assignment

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#769]
### Acceptance criteria
- As an admin, when I go to the task assignment page, I see a list of tasks
- I can filter tasks by type, metadata, dates and assigned person
- In the Actions popup, there will be a mechanism to select all in the list so that the relevant action can be performed. This will work only for upto 1000 tasks (which will be auto selected). 
- I can change assignment by clicking on the Action button
- I can have multiple people in the assignment section, in which case, tasks are equally assigned to all selected users
- I can change status by clicking on the Action button
- Pagination is available on the tasks list with a default page size of 25
- By default, only unassigned tasks are shown
- Columns on the page are - Metadata fields (eg: Phone Number, State, Source), Assigned to, Status, Created, Completed

### Notes
- Based on task type, metadata should show up on filter fields dynamically

**Listing page**
![Untitled Page.png](https://images.zenhubusercontent.com/5d0b1ec92fff8629577fc2ef/c1dc257b-9573-4a0f-831b-c1324533d309)

**Bulk action Popup**
![Bulk Action.png](https://images.zenhubusercontent.com/5d0b1ec92fff8629577fc2ef/b045169b-2382-45cc-af09-d2c9e1c9c6b0)

### Not in scope
- Changing page size
- Individual view and modification

**Comment by petmongrels** [comment]
@vindeolal I am putting this on hold and working on RN upgrade :-)
I have done some work on the server side with TaskWebController on this story.
