### ISSUE TITLE
Do not show voided questions in the rule designer

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#784]
![image_2022_08_04T07_39_35_602Z.png](https://images.zenhubusercontent.com/5d0b1ec92fff8629577fc2ef/f3b2e961-fce6-402e-8d13-083e3b5e67c3)

**Comment by vinayvenu** [comment]
https://github.com/avniproject/avni-webapp/commit/b194094e72db2ad7ba6f9c3422e9055bbc41af09

**Comment by shivamragnar** [comment]
Updated!
