### ISSUE TITLE
Incorrect entry getting deleted on webapp

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#794]
Issue:
------
- For a subjectTypes which have 
    - more than one "EncounterType" with Scheduling rule configured (To be able to create planned visits)
    - more than one Encounter(of different encounter types) shown in the SubjectDashboard under "Planned visits" section
- If user clicks on Delete action for any encounter  in the "Planned visits" section, then we always delete the last encounter  listed in the "Planned visits" section

Root cause:
------------
    This issue was caused due to all Encounters in Planned Visits sharing a common entity for implementing the Delete action. This would result in the data retaining the last encounters details on invoking the Delete action, which resulted in trigger of Delete API for the Last encounter everytime.

Steps to reproduce:
--------------------

1. For any subjectType, create 3 different Encounter types with some dummy field.
2. In the "Visit Schedule rule" section of each of the Encounter forms, include modified version of rule config specified in [this](https://avni.readme.io/docs/writing-rules#visit-schedule-object) reference document to ensure a PlannedVisit is created on creation of a CompletedVisit.
3. Create Visits for each of the 3 different Encounter types, resulting in 3 entries for each EncounterType in the PlannedVisits section of SubjectDashboard in DEA.
4. Delete any PlannedVisit other than the last one, which would cause the last PlannedVisit to always be deleted.
5. Post fix: On deletion of any PlannedVisit, the corresponding Encounter will be deleted as required by the user.

Below specified video gives a glimpse of occurance of the issue:
-----------------------------------------------------------------
https://drive.google.com/file/d/1V28YnVRyGu1I_uLMUFWiC3l9T1cvjqFN/view?usp=sharing

**Comment by AchalaBelokar** [comment]
![Screenshot 2022-09-15 at 3.07.27 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/a420t06b5-5032-46c6-9837-eb40ab6b4006)
not able to delete the visit
