### ISSUE TITLE
Don't allow to void location type before voiding it's children

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-webapp#8]
Don't allow to void location type before voiding it's children.

https://docs.google.com/spreadsheets/d/1cVy2Lz1_A9f8RP3HhNUfvbCkrgMjA4k4nUy6Figx5NI/edit#gid=2134823698&range=D13

##### QA Comment - 
• It does not allow to delete the location but at first it gives the message that element deleted and after some seconds it gives the error message that "location cannot be deleted......".
It should give the error message as user click on the delete button.

**Comment by sidsamanvay** [comment]
Part of this issue we fixed location type resource page not location.
