### ISSUE TITLE
Unable to set group role to concept of type GroupAffiliation in form

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#803]
Images to understand the bug:

![concept.png](https://images.zenhubusercontent.com/62ff301d2acde40fdafa4566/ce7ac0cf-8f55-4263-adbf-9baf52b06975)

Group role drop down doesn't list any options though there are roles set in the selected group subject type.
![Screenshot from 2022-09-13 22-17-20.png](https://images.zenhubusercontent.com/62ff301d2acde40fdafa4566/fd09ea05-b060-4f44-9406-57ecbbb92cc3)

The issue is present in prod as well as shown above.

**Comment by petmongrels** [comment]
fixed and pushed on 3.34 branch

**Comment by petmongrels** [comment]
fixed on master
