### ISSUE TITLE
Default rule in App Designer is incorrect

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#804]
Because of this, there is a rule failure that happens when we add a single space in the rule. 

To reproduce: 
Try editing a rule, add a space and then save. Go to app and try going through the form. 

![Screenshot from 2022-09-13 23-56-02.png](https://images.zenhubusercontent.com/62ff301d2acde40fdafa4566/13dbdea4-48ec-425b-9fc1-94dd5234b1ef)

![Screenshot from 2022-09-14 00-00-21.png](https://images.zenhubusercontent.com/62ff301d2acde40fdafa4566/2ac17168-b17a-4c07-82c6-a98f8b0c38e7)

**Comment by vinayvenu** [comment]
This was already fixed by Sachin. Moving.

**Comment by AchalaBelokar** [comment]
In web applications it is showing values are not equal.
![Screenshot 2022-11-03 at 3.08.57 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/dfa33fd7-0be9-4d6e-aaef-8fd606479661)

**Comment by vinayvenu** [comment]
The existing rule in the organisation was wrong. The code does not fix existing rules. Moving this back to QA ready.

**Comment by AchalaBelokar** [comment]
what is the exact requirement of PNC visit? it is not clear yet
