### ISSUE TITLE
Not able to generate visits on staging 

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-webapp#808]
When we are trying to shedule visit on staging error msg come something went wrong .

Steps to reproduce
1. take any form click on the rules.
2. Click on visit scheduling
3. after filling in all the details of visit scheduling   
4. click on the save button
not able to save that rule.![Screenshot 2022-09-15 at 2.56.26 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/400e8745-1b11-4c0b-8e22-d82b48d28396)

**Comment by vinayvenu** [comment]
working now.
