### ISSUE TITLE
Add documentation link for Application Menu

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#810]
There is no documentation link for the Application Menu. 

- Needs to be pointed to https://avni.readme.io/docs/application-menu
- Consistent naming (Call it Application Menu everywhere)

**Comment by himeshr** [comment]
We have made changes in webapp to show documentation link as seen in attached screenshot.![Screenshot 2022-09-28 at 10.45.00 AM.png](https://images.zenhubusercontent.com/6261483184a61f6d60f9114a/c4307a8a-56c4-40a3-a7a3-8aa119f5a992)
