### ISSUE TITLE
Save rules for messages

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#813]
### Story
As an implementer, I need to configure rules to send a message to a user based on a trigger. 

### Acceptance criteria
- There is an option to create both schedule and message rules for the following triggers
  - Save of a subject
  - Save of an enrolment
  - Save of an encounter
  - Save of a program encounter
- Multiple rules can be created per trigger
- Each rule is associated with a template id (templates are available with Glific API)
- The default message_rule will return an empty rule and the default schedule_rule will return current_time
- When editing rules, all existing rules (those that match the entity_type and entity_type_id) should be shown
- An empty rule will be saved even if there are no parameters (this will be required for templates that do not have a parameter). 
- Rules can be deleted
- Each rule will have a name, that defaults to the message_template's label
- Message templates will be fetched on demand from Glific and shown on the screen

### Rule structure
```
//Schedule Rule
'use strict';
({params, imports}) => {
   return {
    date: '2022-01-01'
   }
};
```

```
//Message Rule
'use strict';
({params, imports}) => {
   return {
      params: ["firstParam", "secondParam"]
  }
};
```

### Not in scope
- Rules UI

**Comment by vinayvenu** [comment]
Mandatory validations are not done. 
Error scenarios need to be specified.

**Comment by petmongrels** [comment]
We should remove @Transactional from the service layer and it should be controlled by the controller or spring batch job or any other entry point (User Service, MessageRuleService).
