### ISSUE TITLE
List all messaging groups

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#815]
### Story
As an admin, I need to be able to see a list of groups to whom I can send a broadcast message

### Details
- We will now have a Broadcasts feature, which includes News broadcasts and Whatsapp broadcasts
- There will be a main menu that says "Broadcasts" (replaces the existing "News broadcasts")
- There is a left menu that provides the following options
  - Groups (listing of groups)
  - Send a message to a group
  - News broadcasts (the complete feature)

Tech tasks
- Menu changes on UI
- Show groups on UI (based on Glific API)

API:
https://api.glific.com/#6e923aa7-7ae5-4f8b-b445-94b12faf94fe

For **postman collection and mockups** refer the epic card.

**Comment by petmongrels** [comment]
glific doesn't provide total count, hence implemented as progressive pagination

**Comment by AchalaBelokar** [comment]
- [ ] When I am trying to add new group with same group name present in the list. The group is not created but it is not showing any validation error. and also not showing the duplicate name in the list.

- [ ] After creating a group I need to refresh the site then only the created group is appearing .

**Comment by petmongrels** [comment]
@vinayvenu 
2. What do we want to do? Refreshing groups further slows down the user experience. 
1. Creating a group with the same name is a bug that we have to check if we can fix without causing further slowness in the UI.
@AchalaBelokar

**Comment by petmongrels** [comment]
avni server and web app. second time in code review so check commits on 25th

**Comment by mahalakshme** [comment]
@petmongrels I feel useCallback is useful only when used with React.memo or useEffect. How does it help, when used alone? Not sure if I am missing something. I googled about it, but it was never used alone.

Also since memoizing also requires space and uses some performance, I feel onSaveClick(even if used with React.memo) should not be memoized, since editing contact group with same name and description next to next, I feel will be rare.

**Comment by petmongrels** [comment]
@mahalakshme 
There are two issues here - optimising the re-rendering of a child component and re-definition of functions in the render. useCallback takes care of second part not the first. In this case there are four state items so the useCallback will ensure that function is not redefined on all four state changes.
- onNameEdit -> it will never be redefined
- onSaveClick -> it will not be redefined when error and displayProgress state changes

https://www.w3schools.com/react/react_usecallback.asp

Good to know about useMemo which we can use also to avoid re-render elsewhere.

**Comment by AchalaBelokar** [comment]
- [ ] why we are showing error code

**Comment by AchalaBelokar** [comment]
- [ ] tested only positive test cases
