### ISSUE TITLE
Send messages with static parameters to group

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#816]
### Story
As an admin, I need to be able to send a Whatsapp message to a group

### Acceptance criteria
- Assuming that I have a list of groups available in Glific, I should be able to choose a group and send a message to that group. 
- First I choose a message template. If it requires a rule, then I should be able to choose a rule that matches the entity_type of members of that message template. 
- I should be able to create a new rule if none exist. This is important because many messages require constant values to be sent. A new rule will be created in this scenario
- If there are no parameters, we don't necessarily need a rule. 
- Messages are added to the message_queue and sent (existing functionality)

Tech tasks
- Ability to choose rule for a template. This will be a user selection based on rules available for the message_template chosen. 
- Ability to create a new rule if none exist (mostly copy of existing functionality)
- Add message to the queue

### API:
https://api.glific.com/#cf2ad1f3-1089-4b96-bb49-532f4877b7a7 - use 'params' key to mention parameters of the template.

For **postman collection, mockups and db schema structure** refer the epic card.

### In scope:
- static or no parameters

**Comment by AchalaBelokar** [comment]
- [ ] what happened when 1  phone number is present in different group.I got 2 msg. It is valid  or not.
