### ISSUE TITLE
[Bug] Locations not showing up in catchments page

### ISSUE THREAD

**Issue by arjunk** [avniproject/avni-webapp#82]
Steps to reproduce
1. Go to user with catchment
2. Click on catchment
3. Shows only a progress bar and the locations don't show up

![image.png](https://images.zenhubusercontent.com/5ce7c98fd8501ed6b9d2d1f8/4a56193d-7c19-4460-88cd-b57a1eb02c2d)

**Comment by vinayvenu** [comment]
@garimadosar5 this is probably because of the authentication bug we had. Can you please verify if this is still the case?
