### ISSUE TITLE
Impl with two different hierarchy skips creating same name locations

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-webapp#826]
In Implementation APF, where there are locations with same name in different hierarchies, the csv upload skips creating the other location in the hierarchy and maps the child locations to the one which is already created , though that exists in the different location hierarchy.

https://docs.google.com/spreadsheets/d/1AbpfaKJQyghlNz_AWJLv2ChzS26NrzgVjlHgY0XnPJg/edit?usp=sharing

**Comment by petmongrels** [comment]
for my reference - https://docs.google.com/spreadsheets/d/1rbtCiSiasZkaCvAWGqzem7LJcO-BvRyoH9oovsscszE/edit#gid=1722096294

**Comment by AchalaBelokar** [comment]
Organization name: Achala test2 on staging
![Screenshot 2022-11-08 at 3.32.44 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/361f9f9c-762b-4dda-8402-a7bfce07ff46)

after uploading the location Mumbai block is missing.
![Screenshot 2022-11-08 at 3.33.54 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/ca1f072c-00e0-4678-8203-7f867a413508)[](url)

**Comment by AchalaBelokar** [comment]
these are the csv.[https://docs.google.com/spreadsheets/d/1xgsuFW7cJ7KSvysxrCh-ODXGGWNS85bX8wRPuYsEyJc/edit#gid=0https://docs.google.com/spreadsheets/d/1xgsuFW7cJ7KSvysxrCh-ODXGGWNS85bX8wRPuYsEyJc/edit#gid=0](url)

**Comment by vinayvenu** [comment]
@petmongrels I am not sure of the history behind this card. Was anything done to fix this?

**Comment by petmongrels** [comment]
no.....it was not reproducible

**Comment by vinayvenu** [comment]
Closing as not reproducible
