### ISSUE TITLE
Adding middle name without a regex fails the app designer

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#828]
Adding a middle name without a regex fails the app designer. 

Looks like even with valid regex - unable to save the subject whose middle name satisfies the regex. - doesn't show any error just unable to save.

Also readme for middle name is missing - Hence add it.

**Comment by petmongrels** [comment]
@vinayvenu 
only could reproduce failing of app designer.
regex check is working in data entry app.
also couldn't find the readme link for subject type in readme
