### ISSUE TITLE
[Admin app] [bulkupload] Show sample downloadable csv files

### ISSUE THREAD

**Issue by ghost** [avniproject/avni-webapp#83]
Show 2 sample downloadable csv files for the following types in dashboard:
- locations
- users-and-catchments

##### Acceptance Criteria- 
1. It should allow the user to choose the type of CSV file i.e. location or user & catchment.
2. By clicking on the download button, the CSV file should be downloaded with the required format and sample data.

**Comment by garimadosar5** [comment]
QA Notes - 
- When we download the CSV and open it in excel, it gives the mobile number as a scientific number. If we can do something that would be good. Users might get confused with that. (Not very important right now)

**Comment by sidsamanvay** [comment]
I think it is possible to mark phone number to text.
Move it to QA failed once rest of this issue is done.

@sidsamanvay @garimadosar5

**Comment by sidsamanvay** [comment]
> QA Notes 1

done

@sidsamanvay , @garimadosar5
