### ISSUE TITLE
statusBuilder.showAnswers isn't working on webapp

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-webapp#830]
**Sample code** -
**statusBuilder.showAnswers**("Signed Copy of Labour Card","Birth Certificate of Child","Discharge certificate/Letter of Proof from Midwife","Bank Passbook");

In implementation PoWER UAT on prod, there is a program encounter "Claims Documentation", which has a multi select concept "Documents", the above sample rule should hide the remaining answers of the concept but it isn't doing it.

**Comment by vinayvenu** [comment]
This was never built - 

Pending story - https://app.zenhub.com/workspaces/avni-5cf8e458bf08585333fd64ac/issues/avniproject/avni-webapp/497
