### ISSUE TITLE
Bulk assignment of subjects

### ISSUE THREAD

**Issue by arjunk** [avniproject/avni-webapp#839]
### Motivation
We should provide ability to bulk assign subjects to one or more users. 

### Acceptance Criteria
In the current mechanism, we cannot do bulk assignment/unassignment to users. In order to achieve this. 

1. User chooses a list of subjects based on a criteria
2. Bulk actions include
  - Unassign user (Choose a user to unassign)
  - Assign a user (Choose a user to assign)
Doing this will help in bulk assigning users for new students, and unassigning users when they go out of the program. 

### Acceptance criteria
- There are checkboxes on the left-most part of the screen, with an option to select all (similar to the task assignment)
- Actions button visible on the screen
- Options are "Assign User" and "Unassign User", with single selection on both
- Done button to complete the action

### Tech Approach
- Assignment API needs to change
- New UI (similar to the task design mechanism)

**Comment by AchalaBelokar** [comment]
- [ ] The total count of subject  Achala is 16 in client where in web app it is showing 17 one subject is missing.

**Comment by AchalaBelokar** [comment]
- [x] Tested assigned and unassigned in web applications.

- [ x] also check on client assigned subject is appearing or not.

**Comment by sachsk** [comment]
@AchalaBelokar  This was not an issue. 
the individual was in a different location I have changed it now to your catchment address.
