### ISSUE TITLE
[Admin app] [bulkupload] dashboard new screen

### ISSUE THREAD

**Issue by ghost** [avniproject/avni-webapp#84]
As an admin, I should be able to import data from a csv file.
I should be able to import locations/users this way.
Once, upload is initiated, there should be table of contents describing the status of each upload.
See all upload statuses initiated in my organisation.
I should know all the failures happened during import.

Add 2 upload types:
- locations
- users and catchments

##### Acceptance Criteria - 
1. When I upload a file It should show the status/Progress of the file upload.
2. The entry of the file upload should be there in the status table.
3. By clicking on the sync button, it should show the current status of the upload.

**Comment by garimadosar5** [comment]
QA Notes - 
- When I am uploading the data, it is not updating the status table on the same page. Also users are not reflecting on User's Page.

**Comment by sidsamanvay** [comment]
> When I am uploading the data, it is not updating the status table on the same page.

This is left intentionally. The user can press the refresh button next to user profile icon

> Also, users are not reflecting on the User's Page.

This should not happen. Please provide the scenario.

> It seems the status table on the upload page is the same for all the implementations. i.e. showing the same content in the table for all the implementations.

It is bug. Mark it as QA failed. will pick it up.

@garimadosar5 @sidsamanvay
