### ISSUE TITLE
Enabling Immutable encounter feature for DEA.

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/avni-webapp#840]
Immutable should work for:

- [x] Scheduled programEncounter
- [x] Unplanned programEncounter
- [x] Scheduled generalEncounter
- [x] Unplanned generalEncounter

### Acceptance criteria
When an encounter type is marked as immutable, then creating a new encounter of that type should prefill all data from the last filled encounter of the same type for that subject.

**Comment by petmongrels** [comment]
@sachsk 
Instead of loading all the encounters from the server and then filtering on the client, we should load only the encounter in which we are interested. For a large number of encounters, this will create performance issues both on the server and client.

**Comment by sachsk** [comment]
Done now we are only loading the latest encounter.

**Comment by petmongrels** [comment]
checked with sachin, latestEncounter.content[0].observations) works for first encounter also. haven't functionally verified.

**Comment by AchalaBelokar** [comment]
- [ ] On staging web app is not responding after saving with  individual  .

**Comment by AchalaBelokar** [comment]
- [ ] tested on sakhi app on staging. Immutable encounter not saving any data of previous encounter . 
userid : AchalaB@sakhi
Individual  name: Kranti Kranti

**Comment by sachsk** [comment]
The server was not deployed on staging. now its deployed

**Comment by vinayvenu** [comment]
Going to the first non-filled page is not done as part of this story. This will be done as part of https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-webapp/902

**Comment by AchalaBelokar** [comment]
- [ ] After saving all the data in encounter .when I am filling another encounter  it will show me blank page 1st
