### ISSUE TITLE
Getting error on bundle upload.

### ISSUE THREAD

**Issue by sachsk** [avniproject/avni-webapp#844]
I am trying to upload a bundle for adolescence from UAT to Prod but getting some errors.
Attaching the error file and bundle.
[https://app.zenhub.com/files/172675608/c7b72e1b-181a-43cd-ac21-ce01ddbc613c/download](https://app.zenhub.com/files/172675608/c7b72e1b-181a-43cd-ac21-ce01ddbc613c/download)

Error : https://docs.google.com/spreadsheets/d/1qHBvbVCH-TGowiiTzBMVgoEwrKmPzfYIQye1gXTP760/edit?usp=sharing

**Comment by vinayvenu** [comment]
Incorrect zip file being uploaded. The error contains __MACOSX directory, which does not come in a regular zip file. Closing this issue.
