### ISSUE TITLE
Escape error messages when creating rules

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#847]
### To reproduce
- Try adding a new error message on a form element with a value in quotes. eg: "Bad message"
- Rule is of the form. Notice the error message being pushed. 
```
'use strict';
({params, imports}) => {
  ...
  
  const condition11 = new imports.rulesConfig.RuleCondition({individual, formElement}).when.valueInRegistration("58bd429a-23af-4545-9df6-929cae2cb980").equals("test").matches();
  
  if(condition11 ){
    validationErrors.push(""Values are not equal"");  
}
 
 ...
}
```

**Comment by shivamragnar** [comment]
This will convert the incoming Single or Double quotes into Single quotes. This keeps the code not give errors and keep the highlighted part in the message as well.

**Comment by vinayvenu** [comment]
package.json change to avni-webapp pushed.
