### ISSUE TITLE
Showing all settings parameters in Users page

### ISSUE THREAD

**Issue by arjunk** [avniproject/avni-webapp#85]
Following settings are shown currently : Language, Track Location
Following settings are missing and to be shown : Hide Exit, Hide Enrol, Hide Register, Hide Unplanned, date Picker Mode, show Beneficiary Mode

Acceptance Criteria
1. The above mentioned missing settings are to be shown in Admin Users page of webapp
2. Each setting should have its own relevant dropdown, radio button, etc. 
3. In the language setting, only those languages selected in Organisation config should be shown. 
4. The title of the language setting should be Preferred Language

**Comment by garimadosar5** [comment]
QA Notes - 
- In Date picker no default value is showing.
