### ISSUE TITLE
Error when assigning status

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#854]
To reproduce
Perform the actions shown on the video on staging on the power test organisation where task assignment is set up. 

https://images.zenhubusercontent.com/172675608/63a40d8a-9c05-4c31-ad3a-60e0118e6bb1/assigning_task_status.mov

**Comment by petmongrels** [comment]
@mahalakshme I cannot find the commit for this.

**Comment by mahalakshme** [comment]
@petmongrels the commit is in avni-server codebase.
