### ISSUE TITLE
View members of a messaging group

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#857]
Acceptance criteria
- I should be able to see all members of a collection
- For the search of subjects show the search in the data entry app(to be able to search by multiple fields), and for users it can be the same one as in user groups.

Glific API
List members of a group: https://api.glific.com/#d89ca85a-8fc1-40ab-a45b-ea05650c06ba - add id or any other key to the users object of GraphQL request as needed.

For postman collection and mockups refer the epic card.

**Comment by petmongrels** [comment]
There is no search capability in Glific within a group. Hence that feature is not developed in Avni also.

**Comment by AchalaBelokar** [comment]
- [ ] After searching we can add only one member at a time but I think we can add more than one member

**Comment by petmongrels** [comment]
Yes, that is correct. We have a separate story for adding multiple members. @AchalaBelokar
