### ISSUE TITLE
Task assignment screen - Dropdown for status is empty

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#859]
https://images.zenhubusercontent.com/172675608/691453b8-c509-4ace-8e8e-62920bbb6f5a/status_options_not_available.mov

To reproduce
Staging - Power UAT organisation

See video. The options are dependent on the filters selected, not the tasks selected. 

Expected behaviour. 
- When there is only one task type among the tasks selected (look at the selected tasks, not the filters), show the options for that task type
- When there are multiple task types, show the Task Status dropdown disabled

**Comment by petmongrels** [comment]
@vinayvenu we have to think more. what if there are two task selected of the same task type?
