### ISSUE TITLE
[avni-webapp] Make locations list alphabetically sorted.

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-webapp#871]
https://avni.freshdesk.com/a/tickets/2333

![err24.png](https://images.zenhubusercontent.com/5d1469c9b0b5db61870d0f5c/ae13147c-a98a-4b52-b54a-514836e2ff0f)

**Comment by petmongrels** [comment]
@nupoorkhandelwal @vinayvenu - Sorting is done but the list down doesn't have pagination. Not sure whether they will need that also.
