### ISSUE TITLE
[avni-webapp] clicking on a catchment shows an error page

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-webapp#872]
Freshdesk https://avni.freshdesk.com/a/tickets/2320

To Reproduce
1. Go to Catchments screen
2. Click on a Catchment
3. Click on the "Catchments" menu item
4. Click on another catchment

**Expected** 
App should go to catchment

**Actual**
App throws an error

PS: Refreshing the page fixes the issue. 

![Screenshot 2023-01-10 at 5.16.08 PM.png](https://images.zenhubusercontent.com/5d1469c9b0b5db61870d0f5c/c07b85b5-a130-4c4d-9847-78f1e1c4c550)

**Comment by vinayvenu** [comment]
Not reproducible. Will confirm and close.

**Comment by 1t5j0y** [comment]
Unable to simulate on local, staging or prod.
