### ISSUE TITLE
Visibility of features on avni-webapp (Admin)

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#879]
### Acceptance criteria
- Use privileges provided [here](https://docs.google.com/spreadsheets/d/1y_3tArAeMlDCBPVdv2z-tX9xItMkLySWAedOOkGbQEA/edit#gid=0)

- If edit privilege is provided, the edit and delete buttons are shown
- Superadmin/admin/orgadmin privileges are unchanged. They have all acces

### Tech tasks
- /me may need to be modified

### Not in scope
- Handle 403-Forbidden responses

----------
- [X] Language 
- [ ] Location types
- [ ] Location
- [ ] Catchments 
- [ ] users
- [ ] User group
- [ ] upload
- [ ] Identifier sources
- [ ] Identifier assignment 
- [ ] org details
- [ ] Phone verification

**Comment by sachsk** [comment]
Moving back to Ready as the requirement is not clear.

**Comment by AchalaBelokar** [comment]
1. Currently I am administrator user but I am able to see the data in data entry app and also create a data there.

**Comment by petmongrels** [comment]
not a blocker for now
