### ISSUE TITLE
Remove enabling approvals at an organisation level

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#884]
### Context
Approvals are always enabled per form, and not at the organisation level. As a result, we do not need this feature in the organisation config settings

### Acceptance criteria
- The Organisation Settings page does not have the "Enable Approvals" option anymore
- The table organisation_settings does not have enableApproval option anymore

### Tech tasks
- Remove option from UI
- Remove all usages of this key from avni-server

**Comment by petmongrels** [comment]
changes in webapp and server
