### ISSUE TITLE
Add Enable Approval feature when adding/editing Form Mapping

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#885]
The enable approval flag on the form mapping currently is populated by the server based on the value of the organisation config. With this story, we will add this flag to the Form Mapping screen.

### Acceptance criteria
- Save and view form mapping with enable approval flag
- The current mechanism where form mappings take the value for ```enableApproval``` from the value of ```OrganisationConfig.enableApprovalWorkflow``` will be removed.

**Comment by petmongrels** [comment]
todo: delete enableWorkflow from OrganisationConfig in database

**Comment by petmongrels** [comment]
We had discussed that we will manage the enable approval flag on Encounter Type and Program screen and save it on Form Mapping. There is no one-to-one correlation between Encounter Type and Form Mapping - for each encounter type there could be multiple Form Mapping for different programs (It is possible that the same is true for Programs as well).

But there is no screen for Form Mapping edit/create. It is maintained via the Form Settings screen as a list over there. But from the discussion, I remember that people don't know about the Form Settings screen.

If we save the enable approval on Encounter Type or Program then we cannot achieve multiple form mapping per encounter type scenario.

I am putting this story on hold.

**Comment by vinayvenu** [comment]
@petmongrels Checked with implementer folks, they are aware of the Form Mapping section and actively use it as well. 

I am thinking we don't make this overly complicated, and add it to the Form Mapping section in the Form Settings alone.
