### ISSUE TITLE
Visibility of features on avni-webapp (base screen)

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#887]
### Acceptance criteria
- Use privileges provided [here](https://docs.google.com/spreadsheets/d/1y_3tArAeMlDCBPVdv2z-tX9xItMkLySWAedOOkGbQEA/edit#gid=0)
- This affects visibility of the cards Documentation, Assignment, News Broadcasts, Translations and Reports only
- Other cards will be always shown
- Only view privileges are required to decide if something needs to be shown
- Add privileges missed out when we did this before

**Comment by 1t5j0y** [comment]
Moving back for now since none of the new privileges deal with News Broadcasts, Translations or Reports

**Comment by vinayvenu** [comment]
media app

**Comment by vinayvenu** [comment]
Documentation - documentation edit
Task assignment - task edit
Subject assignment - user edit
Translations - edit only
News Broadcasts - edit news
Whatsapp broadcasts - whatsapp-web
Reports - reports

**Comment by AchalaBelokar** [comment]
1. Visibility  feature is not working properly when I am disable the toggle for the analytics still it is allow me to download the message

**Comment by AchalaBelokar** [comment]
- [ ] when media and reports are present in one org I disable the analytics still I am able to create a report. on prerelease rwbnitiuat

**Comment by AchalaBelokar** [comment]
1. what happen when user wants only media viewer access not report access .for that reason we need a separate toggle for report and  media viewer.

**Comment by vinayvenu** [comment]
@AchalaBelokar Media reports are just like analytic data access, and does not need a new permission (because most of what we are doing here is data based access, not functionality based access). 

In case this changes in the future, we will add another one for granular media access.
