### ISSUE TITLE
[Calcutta kids ] App designer unable to load registration  form gives error

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-webapp#894]
Go to App designer -> Subject Type -> Click on Calcutta Kids registration form. Form doesnt load. Server returns 500.

The changes for fix are made in avni-server. The reason for failure was because of existence of answers for concepts which are not of Coded type in db. Fix was deployed to prerelease for testing.

Created a card in Impl & Support board, to cleanup the db - https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/calcutta-kids/50

**Comment by AchalaBelokar** [comment]
![Screenshot 2023-02-06 at 5.27.54 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/e14fd075-a3f9-4d01-b127-bca1e63a17b6)
giving me this error

**Comment by mahalakshme** [comment]
@AchalaBelokar the above is a different issue. Have created a separate card for it - https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-webapp/896
