### ISSUE TITLE
[avni-webapp] programEnrolment.findObservationInEntireEnrolment() not working 

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-webapp#898]
https://avni.freshdesk.com/a/tickets/2413

In JSSCP Pregnancy program, the below program summary rule is not working  and is showing the current date --

const lmp = programEnrolment.findObservationInEntireEnrolment('Last menstrual period');
   console.log('lmp',lmp);
   if(lmp){
    var lmpDate = imports.moment(lmp).toDate();
    console.log('lmpDate',lmpDate);
    summaries.push({name: 'Last menstrual period', value: lmpDate});
   }

Console of the above is - 
 'lmp', { that: {} }
 'lmpDate', Fri Feb 10 2023 00:00:00 GMT+0530 (IST) (this is today's date)

**Comment by mahalakshme** [comment]
no code to review - ticket fix under review

**Comment by vinayvenu** [comment]
Closing ticket. It looks like this is resolved.
