### ISSUE TITLE
Immutable encounter - move to the right page

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#902]
### Acceptance criteria
- Similar to the Android client, When an immutable encounter is being edited on the webapp, the app should move to the first non-filled page

Reference - https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-client/674

**Comment by petmongrels** [comment]
We are not supposed to use .that on model
documentation has now been created in readme for this.

**Comment by sachsk** [comment]
Removed instances of .that
