### ISSUE TITLE
Add Carousel based image browsing capability

### ISSUE THREAD

**Issue by rudresh** [avniproject/avni-webapp#906]
Add Carousel based image browsing capability. 
- Research the appropriate library
- Implement the library
- Give download option

#### Acceptance Criteria:
- Clicking on any image in the listing page opens up the image for viewing in carousel. 
- There are options to navigate forward and backward through images.
- On the carousel I've option to select the image.

**Comment by petmongrels** [comment]
Is there any commit for this card? I cannot find it in web-app or avni-media

**Comment by AchalaBelokar** [comment]
- [ ] This msg is showing to me

![Screenshot 2023-04-21 at 10.06.25 AM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/e0f7a5aa-5dda-453f-b1c4-6296c14aa936)

**Comment by brajesh-lab** [comment]
The error comes when the browser is idle and the auth token becomes invalid. I'm now checking those cases and redirecting the user to the home page for login.
