### ISSUE TITLE
Add UI to see the Job status and download the zip file

### ISSUE THREAD

**Issue by rudresh** [avniproject/avni-webapp#908]
Add UI to see the Job status and Download the zip file
- Job Status listing and managment page
- Available zip files listing, download and management page

**Comment by petmongrels** [comment]
cannot find the commits, are commits done with the story number?

**Comment by petmongrels** [comment]
(ignoring the use of tailwind for now)
getFileSizeText and folderStructure methods in MediaViewerService can be factored better and should have unit tests.
