### ISSUE TITLE
Add support for keyValues in form elements

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-webapp#91]
### Acceptance Criteria:
- In Form element for concept type Date and DateTime show a label "Date Picker Mode" and allow user to choose one of the three radio buttons: 'calendar' | 'spinner' | 'default'.
- In Form element for concept type Numeric, Text, Date and DateTime show a checkbox named "ReadOnly" and allow user to tick it.
- In Form element for concept type Date show a label named Duration Options and show checkboxes with options  "years", "months", "days", "weeks", "hours". If user selects date picker mode then do not show duration options or vice versa.
- In Form element for concept type Duration show a label named Duration Options and show checkboxes with options  "years", "months", "days", "weeks", "hours".
- In Form element for concept type Coded show label named Excluded Answers and show multi select input in which they can type values of excluded answers. Values can be any text that user enters.
- In Form element for concept type Image show Max Height, Max Width, Image Quality options where user can enter any number >= 0 in Max Height and Max Width. Image Quality should be a drop down with options 0 and 1. In the UI we should set the placeholder for max height field as 960 and max width field as 1280. Set default value of image quality as high.
- In Form element for concept type Video show Video Quality drop down with options high and low. Also show text input for Duration limit(seconds) allowing any number > 0. In the UI we should set the placeholder value for duration limit field as 60. Set default value of video quality as high.

### Implementation details:
Set keyValues attribute on FormElement. 
Format of keyValues is as following:
```
"keyValues": [
    {
      "key": "key",
      "value": value
    }
  ]
```
- keyValues for datePickerMode if selected should be:
```
"keyValues": [
    {
      "key": "datePickerMode",
      "value": "calendar" or "spinner" or "default"
    }
  ]
```
- keyValues for editable if selected should be:
```
"keyValues": [
    {
      "key": "editable",
      "value": true or false
    }
  ]
```
- keyValues for durationOptions if selected should be:
```
"keyValues": [
    {
      "key": "durationOptions",
      "value": array with one or more values from "years", "months", "days", "weeks", "hours"
    }
  ]
```
- keyValues for ExcludedAnswers if selected should be:
```
"keyValues": [
    {
      "key": "ExcludedAnswers",
      "value": array with whatever values user entered
    }
  ]
```
- keyValues for maxHeight:
```{"key": "maxHeight", "value": number>=0}```
- keyValues for maxWidth
```{"key": "maxWidth", "value": number>=0}```
- keyValues for imageQuality
```{"key": "imageQuality", "value": 0 or 1}```
- keyValues for videoQuality
```{"key": "videoQuality", "value": "low" or "high"}```
- keyValues for durationLimitInSecs
```{"key": "durationLimitInSecs", "value": number>=0}```

**Comment by hithacker** [comment]
@swapnil106111 to add placeholders for default values in image and video. Also add read-only field instead of editable.

**Comment by nupoorkhandelwal** [comment]
** For datePickerMode** app is crashing when calendar mode is selected.

**Comment by swapnil106111** [comment]
@nupoorkhandelwal Take a latest pull of webapp and test.

**Comment by hithacker** [comment]
@nupoorkhandelwal Placeholders are there for image and video both. In the UI theme that we are using it shows up only when you click on the field. See the image
![image.png](https://images.zenhubusercontent.com/5d0b10e42fff8629577fc2cc/f122021a-6503-4f3f-9be3-5f159712f65f)

**Comment by nupoorkhandelwal** [comment]
**For a date concept once Date Picker mode is selected, it is not allowing to switch to mode duration options**

**Comment by swapnil106111** [comment]
@nupoorkhandelwal I think, you dont have current changes. Please take a pull and check.
