### ISSUE TITLE
View messages to a user

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#918]
### Story

As an admin, I should be able to see the messages sent to a user so that I can decide to send a message to that user.

### Acceptance criteria

- A new menu item - "Users" is present in the Whatsapp messages home screen
- On clicking, the User Search widget is available to the user. This is the same widget currently available when adding users to groups
- On clicking Search on the User Search widget, the user is presented with a User Listing, out of which they can choose one user (screen 10)
- When choosing a user, the user is taken to the "Subject" screen that contains scheduled and sent messages to that user (similar to screen 7). The message widgets are the same as what is available on the Data Entry Application.

UI mockups - https://docs.google.com/document/d/1GtlITrqW5hXHjHI9PHWkBi07OiWP1ZN8ycRsRzgz9-o/edit?usp=sharing

**Comment by mahalakshme** [comment]
@1t5j0y  I feel on selecting a user from search, url should have user id in url path param like in groups, so that on refresh, new messages if any can be seen.

**Comment by AchalaBelokar** [comment]
- [ ] I send an msg through the user. but it is not showing directly. I need to go back to user and click on that user then it is reflecting.

**Comment by AchalaBelokar** [comment]
- [ ] I send an msg through the user. but it is not showing directly. I need to go back to user and click on that user then it is reflecting.

**Comment by AchalaBelokar** [comment]
- [ ] I send an msg through the user. but it is not showing directly. I need to go back to user and click on that user then it is reflecting.

**Comment by AchalaBelokar** [comment]
![Screenshot 2023-03-23 at 9.56.35 AM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/f81a11f9-d83f-4176-b44b-d8946419c5cc)

**Comment by AchalaBelokar** [comment]
![Screenshot 2023-03-23 at 9.56.35 AM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/f81a11f9-d83f-4176-b44b-d8946419c5cc)

**Comment by mahalakshme** [comment]
Himesh fixed it.
