### ISSUE TITLE
Ability to define form mappings 

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-webapp#92]
As an implementer I want to be able to associate the same form with multiple encounter types, subjects and programs. E.g. I may want to use the same cancellation form for multiple encounter types. Or I may want to use the same form for a common type of visit in different programs/subjects.

### Implementation details:
Put a mappings section on the form settings page.
It will look something like below:

Settings
—
Form Type : ProgramEncounter
Form Name

Mappings
——
Subject Type | Program Name | Encounter Type | actions
Individual       | Child                 | Annual Visit         | delete
Individual.      | Child                 | Quarterly             | delete
Individual       | Mother             | Annual                  | delete

### Acceptance Criteria:
- Should be able to add new form mapping. 
- Should be able to edit/delete existing form mapping.
- There should be no mappings for ChecklistItem form type.
- Deleting the form mapping should void it.
- Changing the form type should result in existing form mappings being voided and new row with empty selections to be there.
- We should allow user to save settings only when there is at least one form mapping. This do not apply to CheckListItem form type as it do not have any form mappings.
- On changing form type ask for confirmation showing a message: "Are you sure you want to change form type? It may result in your form not showing up in client application so please do it only if you aware of the consequences.". Apply the change only if user confirms.
- On editing existing form mapping ask for confirmation showing a message: "Are you sure you want to change existing mapping? It may result in your form not showing up in client application so please do it only if you aware of the consequences.". Apply the change only if user confirms.

##### TEST CASES - 
Ayu Implementation - 

1. Add the same Registration form for `Individual` and `Location` subject type.
  It should show for both the Subject type in the app.  - **PASS**

2. Add the same form (Test Form 123) for two different encounters (Birth Registration and Annual Survey) of the same subject type.
It should show as a two different encounter in the app. - **PASS**

3. Mapping One encounter type (Annual Survey) in different forms (Test Form 123 and sdfs1).
It should not allow this. - **FAILED**
**Current Behaviour **- 
It shows the same name encounter more than once and both the time same form is showing.
**Dev notes** -
For now we will rely on implementer knowing that this is not desirable. We will cover this in https://app.zenhub.com/workspaces/avni-5cf8e458bf08585333fd64ac/issues/openchs/openchs-product/1092

4. Create a form with type Program Encounter Cancellation, Mapped this to a program encounter
i) Birth Registration
In the app if the encounter is scheduled the cancellation form shows up on clicking cancel.  - **PASS**

**Comment by hithacker** [comment]
@amarkamthe Add your estimate

**Comment by garimadosar5** [comment]
QA Notes -

1. Encounter <-  Birth registration form is crashing
