### ISSUE TITLE
Create thumbnails when an image is uploaded to S3 bucket

### ISSUE THREAD

**Issue by rudresh** [avniproject/avni-webapp#923]
Currently, images uploaded from the mobile app get stored in the AWS S3 bucket in its original size. In order to show the images listing in the media-viewer application we need thumbnails of those images. 

To achieve this create thumbnail from the image as soon as it is uploaded in the bucket. 

### Proposed design approach 
https://docs.google.com/document/d/1pNoDOC2XfcZLvQWvJumLu4tstunQ5R0V-FLAfkub-n0/edit#

**Comment by vinayvenu** [comment]
code in avni-media repo.

**Comment by rudresh** [comment]
Code in anvi-media repo. The Pull Request for this is https://github.com/avniproject/avni-media/pull/1

**Comment by vinayvenu** [comment]
1. avni-media is for much more than these two scripts. We can move these (including README) into a scripts directory. 
2. It will be useful to clarify what each script does through better naming. 
3. Remove .DS_Store. 
4. See commit formats from other repositories. 
5. The project convention is to commit first and handle comments etc through pull requests
6. Have a script through which we can deploy this on AWS using aws-cli. This will make deployment to multiple environments easier. 
7. Add .nvmrc file wherever there is a package.json
8. The existing S3 structure is something like this. ```{bucket}/{organisationName}/{image}.[png|jpg]```. We want the thumbnail to be of the format
```{bucket}/{organisationName}/thumbnails/{image}.[png|jpg]```

**Comment by vinayvenu** [comment]
Not yet deployed to Staging
