### ISSUE TITLE
Create thumbnails for existing images

### ISSUE THREAD

**Issue by rudresh** [avniproject/avni-webapp#924]
Currently, images uploaded from the mobile app are stored in the AWS S3 under respective organisations' bucket. In order to show the images listing in the media-viewer application we need thumbnails of these existing images. 

### Task
- Create a script that generated the thumbnail from the existing images.
- If need be, we can run it nightly as well to create thumbnails for images which got missed in [#923](https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-webapp/923) 

### Proposed design approach 
https://docs.google.com/document/d/1pNoDOC2XfcZLvQWvJumLu4tstunQ5R0V-FLAfkub-n0/edit#

**Comment by rudresh** [comment]
Code in avni-media repo. The Pull Request for this is https://github.com/avniproject/avni-media/pull/1

**Comment by vinayvenu** [comment]
Not yet deployed to Staging

**Comment by AchalaBelokar** [comment]
- [ ] After editing the image it is showing the older and newer one

**Comment by AchalaBelokar** [comment]
- [ ] After editing the image it is showing the older and newer one

**Comment by rudresh** [comment]
@vinayvenu The behaviour @AchalaBelokar explained in this issue is related to avni-webapp. Could you take a look please.

**Comment by vinayvenu** [comment]
@AchalaBelokar This behavior is related to avni-etl and has been fixed. Please verify
