### ISSUE TITLE
Standardize messages tab across the 4 different places on the webapp

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#928]
- [x] Standardize the messages tab across users, groups and subjects
- [x] Remove unnecessary fields such as ids etc
- [x] Standardize the button titles (Open vs Send Message)
- [x] Standardize column headers (Inserted Time vs Sent Date) and data (date vs datetime)

**Comment by mahalakshme** [comment]
body, inserted at are technical terms. I suggest changing to non-technical terms like Message, Sent At.

**Comment by himeshr** [comment]
Made changes in text and translations to make the column headers more user-friendly
