### ISSUE TITLE
Fix Search, Sort and Pagination in Users and Subjects tabs of Whatsapp screen

### ISSUE THREAD

**Issue by himeshr** [avniproject/avni-webapp#930]
Fix Search, Sort and Pagination in Users and Subjects tabs of Whatsapp screen
- [x] GROUP Sent and Scheduled messages screen display size
- [x] Search User
- [x] Search Subject

Not doing the below as the search funtionality is supposed to be used to its full potential to narrow down and select required users.
- Sort User
- Sort Subject
- Paginate the User list
- Paginate the Subject list

**Comment by mahalakshme** [comment]
Other endpoint used by searchUserById also is impacted by changing userEndpoint in webapp

**Comment by himeshr** [comment]
Handled the following review comments 
- [X] Other endpoint used by searchUserById also is impacted by changing userEndpoint in webapp.
- [X] There is already a /user/search/find api call which can be reused instead of new api endpoint and repo method in server.
