### ISSUE TITLE
Deleting multiple contacts from group is throwing 500

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#934]

**Comment by sachsk** [comment]
In deleteContactIds glific expects array of string or int but our code was passing
``"[907895, 1099715, 1108283]"``  as a contact ids so the format was incorrect due to this deleting multiple contact was not working.

Fix 
now we are passing contact ids like this ``[
        907895,
        1099715,
        1108283
      ]``

**Comment by AchalaBelokar** [comment]
![Screenshot 2023-03-24 at 11.53.27 AM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/d465de87-a74b-4353-8ac1-b2e92aec8e56)
Moving this card. I think deployment is remaining

**Comment by AchalaBelokar** [comment]
![Screenshot 2023-03-24 at 11.53.27 AM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/d465de87-a74b-4353-8ac1-b2e92aec8e56)
Moving this card. I think deployment is remaining

**Comment by Dinesh2019** [comment]
While trying to test ticket i am getting the following error in the staging environment
Step to reproduce:
1. Login to Glific account.
2.Click on the Broadcast.
3,Click on the whatsAPP

![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/b7b81d05-d003-484b-8495-ab99dc3dcad8)

**Comment by sachsk** [comment]
@Dinesh2019 now its working fine.
