### ISSUE TITLE
User experience issues

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#935]
- After a subject added we are not showing any toast message, to show the subject/user added to group.
- When a subject cant be added because of incorrect phone no or internal server error and when the subject list is long we are not scrolling to top, or telling at bottom to check errors. Need to check how we handle in other areas of webapp and handle similarly. Hence the user of the app, doesn't know what happened unless they scroll to top.

**Comment by Dinesh2019** [comment]
The bug is fixed and works as expected 
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/99a3bd41-21d9-46af-a8de-56815d6a3ea8)
