### ISSUE TITLE
Add Dashboard filters

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#936]
### Story
As an implementer, I need to be able to add filters to a Dashboard so that they can be used on avni-client to filter based on user requirements

### Acceptance criteria
- When choosing an offline dashboard, there is new section to provide filters. 
- The new offline dashboard looks like the image below (with "MyDashboard Filters" replaced with "Filters"
- The functionality of this new section is similar to the MyDashboard Filters in terms of what can be added
- The filters will be saved in the database and available for sync

![image.png](https://images.zenhubusercontent.com/5d0b1ec92fff8629577fc2ef/d05f235d-0494-45c6-abca-0afc7b251e42)

### Dev tasks
-

**Comment by 1t5j0y** [comment]
Please include regression test of My Dashboard Filters and Search Filters in testing scope.

**Comment by AchalaBelokar** [comment]
- [ ] I added filter and after clicking on save button I got this error.
![Screenshot 2023-04-20 at 3.40.05 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/a3fe6617-730f-474d-9907-17e256b2ae9a)

**Comment by 1t5j0y** [comment]
This is a data issue with the section in this specific dashboard. You can continue testing elsewhere while I figure out what the issue is here.

**Comment by 1t5j0y** [comment]
Data issue was due to dupe card_id, dashboard_section_id rows in dashboard_section_card_mapping table in Iph, goonj and goonj revamp orgs.

Cleaned up with:
```
delete
from dashboard_section_card_mapping
where id in
      (select id
       from (select id,
                    rank() over (partition by card_id order by id desc) rnk
             from dashboard_section_card_mapping
             where card_id in (
                 -- Duplicate uuids query
                 select duplicate_uuids.card_id
                 from (select card_id, count(*)
                       from dashboard_section_card_mapping
                       group by card_id, dashboard_section_id
                       having count(*) > 1) duplicate_uuids)) id_of_duplicate_uuids
       where rnk > 1);
```
