### ISSUE TITLE
In Immutable encounter if form has FEG with all skipped question and if we do new visits then form is showing that blank FEG.

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-webapp#939]
When we created user and enrolled in Masai School program.When we do the planned visit it is directly moved to interview with blank page instead it should display the summary.

Test Sample :
Username : Test Immutable.
1.Create a user and enroll in Masai School program.
2.Click on the planned visit and then click Do.
Expected result:
Summary details or follow up page should displayed.
Actual : Interview page is displayed with blank details.

![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/2dfd6e10-e102-4a74-9114-915b5bd42f79)

**Comment by sachsk** [comment]
@Dinesh2019  if you found any bug on the Webapp please create bug card under the avni-webapp repository

**Comment by Dinesh2019** [comment]
Retested the bug looks fine 
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/33d82901-1548-415c-8d84-aabf993ad97e)
