### ISSUE TITLE
Use signed S3 URL in media viewer application

### ISSUE THREAD

**Issue by rudresh** [avniproject/avni-webapp#945]
Media Viewer application is currently using the exact S3 URL stored in the database. As the S3 bucket is not public, the images are not displayed correctly. 

### Task
- In the ETL API, update the S3 URL to signed URL for both the images and the thumbnails.

**Comment by petmongrels** [comment]
The logic for parsing the S3 Url should ideally be a plain Java object and not in repository. Also please add a unit test for the logic.

**Comment by petmongrels** [comment]
Maybe related to other cards but:
- orgID is number so I am not sure why it is used as String
- Maybe the SQL injection is unlikely for schemaName but please use prepared statement parameter for that as well

**Comment by rudresh** [comment]
@petmongrels We have made the updates per your suggestion.

**Comment by vinayvenu** [comment]
@rudresh Moving this to Code Review Ready

**Comment by petmongrels** [comment]
ContextHolderUtil is still not thread safe. We cannot hold request specific state in a component or a static class. There is a standard approach to do this in Java/Spring. It is difficult to write it down here......but the state should be in the methods.

MediaTableRepository
- repository having dependency on the service should not be the case. service should have dependency on the repository has it is a higher layer. There should be no class called RepositoryService :-)

CognitoAuthServiceImpl
- COGNITO_URL should be externalised

Utils
- minor,. it need not be service.
