### ISSUE TITLE
[DEA] Disable Forgot password for Keycloak

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#948]
### Story
We currently are not planning to build Reset password functionality for Keycloak because we are not clear how SMS integration would work. It is important to remove the Forgot Password option in this scenario because it can otherwise lead to incorrect UX

### Acceptance criteria
- On the landing page, when Keycloak is selected, the Forgot Password option is not shown

**Comment by himeshr** [comment]
https://images.zenhubusercontent.com/172675608/25a4ba08-4135-4f9a-b342-6cf1ae842f5a/screen_recording_2023_04_10_at_3_20_01_pm.mov
