### ISSUE TITLE
Scheduled Date must be usable on the task assignment screen

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#966]
Ticket: https://avni.freshdesk.com/a/tickets/2616

### Story
As an admin who assigns tasks to people, I need to be able to see and filter by the scheduled date so that I can perform my work effectively. 

### Acceptance criteria
- A new filter "Scheduled Date" is added to the filters section on the right
- A new field "Scheduled Date" is added to the results section on the left
- The Schedule Date filter works exactly like the Created filter
- scheduled_on is mandatory on the database and the API

### Analysis notes (personal: do not read):
- Scheduled Date is shown, and can be rescheduled on avni-client
- created date column can be retained along with scheduledOn date column in webapp - for reporting purposes(to understand why a task didn't display earlier or get assigned) it might help. We need not make changes in avni-client for this since it is not relevant for users. the name of the column can be renamed to something like synced_to_date. 

### Testing notes
- Check if this fixes the ticket. The intention on the ticket is to show the time the call happened on the screen. This story achieves that purpose, and is sufficient for a root-cause fix for the issue. No changes required for Power Integration code, avni-client or any other component.

**Comment by vinayvenu** [comment]
Add scheduledOn to the task assignment screen

**Comment by 1t5j0y** [comment]
@mahalakshme is the linked freshdesk ticket correct? The ticket talks about tasks being created with the appropriate created time whereas this issue is about a new scheduled date filter.
