### ISSUE TITLE
User settings shows uuids instead of names as sync attributes

### ISSUE THREAD

**Issue by arjunk** [avniproject/avni-webapp#968]
### How to reproduce
- Go to App Designer
- Create a subject type
- In Registration Form of the subject, add a coded concept
- In the subject type's Advanced Settings -> Sync Concept, add the coded concept from the registration form
- Add a user. In sync settings, set the value of the coded concept to some valid answer of the coded concept
- View the user. Notice that the uuid of the attribute is shown, and not the name. 

It is important to show the name so that it is easier for users to understand the concept that has been set up. 

See attached image

Check the attached image. On the show page of a user (e.g. https://app.avniproject.org/#/admin/user/6690/show) , It is showing uuids of the concepts in the 'Sync settings for Subject Type: Individual' section instead of their current display values. This is not intuitive. We should fix this by displaying the display value e.g. 'Yes' and not '8ebbf088-f292-483e-9084-7de919ce67b7'

![image.png](https://images.zenhubusercontent.com/5ce7c98fd8501ed6b9d2d1f8/eda6ab75-8b6a-43d4-8f08-3a5a84127c69)

**Comment by mahalakshme** [comment]
@vedfordev

**Comment by vinayvenu** [comment]
@mahalakshme no, they have not been fully addressed yet.

**Comment by vedfordev** [comment]
@vinayvenu removed catch statement

**Comment by himeshr** [comment]
Changed to 7.0.0 release as changes are in Master branch and this is not a critical fix which needs to be QAed and released in 6.0.0.
