### ISSUE TITLE
Ability to sort on Task Assignment screen

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#971]
https://avni.freshdesk.com/a/tickets/2676

The task assignment screen can have a lot of records, and it will be useful to be able to sort these records by the fields available on the table.

**Comment by 1t5j0y** [comment]
Enabled sort for the fixed fields for task.

**Comment by mahalakshme** [comment]
@vinayvenu u ve moved this in "In code review" 5 days ago. Is code review done? Do one thing at a time no.
