### ISSUE TITLE
Clearer age display for children

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#979]
When we deal with growth of children, accuracy of the age is important. Between 1 and 6 years, it will be useful to show the age in years and months (eg: "1 year 2 months" instead of "1 year" as shown now). 

### Acceptance criteria
1. The following logic is used to show the age
Under 1 week  - Age in Unit 'days'
Under 1 year - Age in Unit 'weeks'
Under 2 years - Age in Unit 'months'
Under 6 years - Age in Unit 'years' and 'months'
After 6 years - Age in Unit 'years'

eg: 
```
    0 days
    2 days
    6 days
    1 week (week format starts here)
    12 months
    16 months 
    5 years 11 months (last value with months)
    6 years
    7 years
```

2. The change in logic is shown on the Search results, Subject Dashboard and Dashboard search results

**Comment by mahalakshme** [comment]
I thought of doing the same initially, but since we dont have individual model object in webapp, looked like it cant be done. Let me know if you think there is a way to do it.

**Comment by 1t5j0y** [comment]
Moving the logic to a utility method in models and refer to it from Individual model and DEA should work I think

**Comment by mahalakshme** [comment]
@1t5j0y addressed your comments

**Comment by mahalakshme** [comment]
Because of the changes made above: https://github.com/orgs/avniproject/projects/2/views/1?pane=issue&itemId=30667533 - this card again needs to be tested. And also need to test in other places wherever anything related to age is displayed.

**Comment by AchalaBelokar** [comment]
![Image](https://github.com/avniproject/avni-webapp/assets/104890488/a31ce57b-fd10-4dc4-8dcb-155d35a6e969)

here is not showing the age according  to the requirement

**Comment by mahalakshme** [comment]
@AchalaBelokar until less than 2 years need to show in months. 
Have fixed displaying age with correct units in  edit registration details flow.

**Comment by mahalakshme** [comment]
review this commit alone: 8fcde6db83d9aa781c20b4ea4cf73f88891125b0, rest reviewed

**Comment by AchalaBelokar** [comment]
@mahalakshme I think in reg page we are not able to see week we only see the year that.. I am thinking this is not scope of this card
