### ISSUE TITLE
Visibility of features on avni-webapp (App Designer)

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#984]
### Acceptance criteria
- Use privileges provided [here](https://docs.google.com/spreadsheets/d/1y_3tArAeMlDCBPVdv2z-tX9xItMkLySWAedOOkGbQEA/edit#gid=0)
- If view privilege is provided, then the menu item is shown
- If edit privilege is provided, the edit and delete buttons are shown
- Superadmin/admin/orgadmin privileges are unchanged. They have all acces

### Tech tasks
- /me may need to be modified

### Not in scope
- Handle 403-Forbidden responses

**Comment by petmongrels** [comment]
We will need to figure out how to handle concept UI. We can put something like if the user has privilege to do SubjectTypeEdit, ProgramEdit, EncounterEdit then allow the user to manage concepts - but we use concepts in other places too. Not handling this as part of this story.

**Comment by petmongrels** [comment]
DashboardEdit privilege used for search filters edit, search results fields.

**Comment by AchalaBelokar** [comment]
- edit concept is not working .. if I disable the toggle still I am able to edit the concept.
- I disable the toggle for edit from still new form button is showing but I am not able to create from. but new form should not be present there

**Comment by himeshr** [comment]
Test and develop on organisation other than one with orgId 1.

**Comment by ashusvnath** [comment]
@AchalaBelokar : A new form can only be created if the types are visible in the form type option of the new form dialog. Hence, this privilege is NA, will need to remove it from UI.

**Comment by AchalaBelokar** [comment]
- concept is used in subject type, encounter type  we are not handling it here

**Comment by AchalaBelokar** [comment]
- edit form concept is not working

**Comment by ashusvnath** [comment]
Both `EditForm` and `EditRelation` have been removed from `avni-models` based on post-standup discussions in the past. Will need direction from @petmongrels and @vinayvenu about how to proceed.
