### ISSUE TITLE
Show new privileges on the Permissions screen

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#985]
### Acceptance criteria
- All privileges are available on the Privileges tab inside the User Groups of Admin section of the web application
- Existing grouping remains. A new group for metadata privileges is created. It will be called "Metadata". 

### Tasks
- FIgure out what to do with the EntityType

**Comment by 1t5j0y** [comment]
A common EntityType (NonTransaction) is now being used to group all non transactional privileges to aid grouping on the server and selection of privileges on the UI.
