### ISSUE TITLE
Unable to load Household / GroupSubject screen

### ISSUE THREAD

**Issue by himeshr** [avniproject/avni-webapp#990]
Unable to load Household / GroupSubject screen.

Error stack-trace:
TypeError: n.getAgeInYears is not a function
    at eg (GroupSubjectMemberCardView.js:89:57)
    at Ji (react-dom.production.min.js:3667:1)
    at bs (react-dom.production.min.js:6635:1)

![Image](https://user-images.githubusercontent.com/72493481/249768735-4f767739-02bd-4693-89a4-1b936ecad0af.png)

**Comment by petmongrels** [comment]
I tested in APF Odhisha. I am able to open the household subject.
