### ISSUE TITLE
DEA - Error while loading search results - AgeUtil is undefined

### ISSUE THREAD

**Issue by 1t5j0y** [avniproject/avni-webapp#992]
Env: Prerelease
Org: Muktipath
Steps:
Load DEA.
Select 'Reporting User' subject type
Click on search

![Image](https://github.com/avniproject/avni-webapp/assets/54208632/5072cfa2-9f6b-45c2-b86e-4a3ac8a78d4c)

Initial Analysis:
Webapp 3.39 is referring to openchs-models 1.30.34 which is in avni-models 3.39 branch but this branch doesn't seem to have the AgeUtils file.

**Comment by himeshr** [comment]
Reverted the commits in avni-webapp belonging to #979 from 3.39 branch as that card is scheduled for 4.0 release and not 3.40.

**Comment by himeshr** [comment]
DEA for mukti path 'Reporting User' subject type open up now..

https://github.com/avniproject/avni-webapp/assets/72493481/57327e7e-ace5-41d0-8f3e-b615265829c7
