### ISSUE TITLE
Remove org admin switch when creating user

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#996]
### Acceptance criteria
- The "Make this user an administrator ..." switch is removed from the Users screen
- The "Role" column is removed from the User listing screen
- API will still accept the role flag, but valid values will be only user and admin
- Migrate all org-admin values in the database to "user" (need to check if this is possible)

We will eventually replace this with the groups that a user has access to.

**Comment by petmongrels** [comment]
removing preauthorise from server and all users will have access based on their privileges.
1. for 'user', 'org admin' there is session check and rest is controlled by privilege check
2. for 'admin' only endpoints putting a check for isAdmin via accessControlService
3. for avni-client tx data endpoints, adding check now for now for super admin to use them

**Comment by petmongrels** [comment]
instead of creating new privilege for these, using org config privilege - news, msg91config.
for privacy reasons applied edituserconfig privilege for viewing other users.
