### ISSUE TITLE
Assign groups when creating user on the Admin screen

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#997]
### Acceptance criteria
- [x] When creating or editing a user, there is an option to choose the groups that the user will be part of
- [x] Saving a user will automatically add users to the marked groups
- [x] Removing a group from a user will automatically remove the user from the unmarked groups
- [x] Users will by default be assigned to Everyone group during User creation even if he's not assigned to it by AdminUser on the admin-app
- [x] The Everyone group will be visible on this screen and is assignable and removable, but users will always be part of this group even if user attempts to remove it. This is due to inability to hide it in ReactAdmin code.
- [x] Show chips for view of Groups
- [x] User listing will have a new column "User Groups", which will show all group memberships of the user
- [x] Add translations for webapp for userGroups

**Comment by himeshr** [comment]
### Sample screen-recording:
https://github.com/avniproject/avni-webapp/assets/72493481/cc015f1f-ed0a-4923-ace8-2905b460c661

**Comment by vinayvenu** [comment]
- why do we need the ability to edit groups in a `GET` call? - https://github.com/avniproject/avni-server/commit/5372018dca134cb3dda040b17a8582bf94878ea8#diff-f357fe8b806428375f455d3f2bb1aa9bb5958f14b0d75d69ba8d6cba96487fe7R76
- Same method - add `@Transactional`
- Need tests for https://github.com/avniproject/avni-server/commit/1c4f64c0de99cf510a7c7f7c8e87c697a83752a3#diff-a4390843da6f3affc6198f4edc9696db0e2b95e40dd06815ae6c4cd8505935f2R61
- Prefer passing objects instead of Ids of objects - https://github.com/avniproject/avni-server/commit/9d314edab30bfa83d3336b9a869e7019af46e576

**Comment by himeshr** [comment]
@vinayvenu Added unit tests and abosrbed all code-review comments

**Comment by AchalaBelokar** [comment]
1. User group is showing  me mandatory  option but when I am not fill anything it is allow me to save.

**Comment by AchalaBelokar** [comment]
https://docs.google.com/spreadsheets/d/1WRWHgQojYkGtaRAf7dXrj0K_hk9x1vHlBNOq2IstXmY/edit#gid=0 test cases

**Comment by himeshr** [comment]
Everyone group is removed from the UserGroups select, during create.
During edit, it'll be shown, and user can remove it, but, the group will be retained no matter what action user does,
UserGroups is no longer mandatory during edit or create.

**Comment by AchalaBelokar** [comment]
- I am not able to create a user

https://github.com/avniproject/avni-webapp/assets/104890488/38306d93-a2c4-49bc-859e-dea42379a6c5
