### ISSUE TITLE
Not able create user from super admin for some organisation 

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-webapp#999]
**Describe the bug**
Not able create user from super admin
org name swach pune here it is not working
where Deepak Foundation - Adolescent Anaemia tracking
also not able to reset password.. swach pune org

**To Reproduce**

1. Login as super admin
2. Select any organisation
3. try to create new user
4. See the error Server communication error

https://github.com/avniproject/avni-webapp/assets/104890488/b1a743f5-90d7-4854-8ad1-57fe3c370309

**Expected behavior**
super admin should  able to create  user from any organisation

**Comment by vinayvenu** [comment]
Needs to be verified on staging

**Comment by vinayvenu** [comment]
Working fine now. Probably done through some other card. Moving to QA Ready.

**Comment by 1t5j0y** [comment]
Tested against 10 orgs in staging and not able to simulate this.
